// Code generated by scripts/fetch-v1/gen-constants.py from
// spec/fetch-v1/constants.json (sha256:bf19d75118f2d10a1aac28e7e4e44022d59d36d7bbea2f9c7b0c327dcc5a73fc). DO NOT EDIT.

export const SCHEMA_VERSION = 1 as const;
export const ABI_GENERATION = 1 as const;

export const ENV_BASES_NAME = "CHTYPES_ARTIFACTS_URL" as const;
export const BASE_SEPARATOR = "," as const;
export const FIXTURES_REPO_SUFFIX = "/sdk-fetch-fixtures" as const;
export const DEFAULT_BASES = ["https://registry.wavehouse.dev/chtypes/v1"] as const;
export const ALLOWED_SCHEMES = ["https", "http", "file"] as const;

export const ENV_CACHE_NAME = "CHTYPES_CACHE" as const;
export const ENV_TOKEN_NAME = "CHTYPES_DOWNLOAD_TOKEN" as const;
export const ENV_TRUSTED_KEYS_NAME = "CHTYPES_TRUSTED_KEYS" as const;
export const ENV_ALLOW_UNSIGNED_NAME = "CHTYPES_ALLOW_UNSIGNED" as const;
export const ENV_AUTOFETCH_NAME = "CHTYPES_AUTOFETCH" as const;
export const ENV_TARGET_NAME = "CHTYPES_TARGET" as const;
export const ENV_RETIRED = ["CHTYPES_REGISTRY"] as const;

export const SPELLING_REGEX = "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(\\.(0|[1-9][0-9]*)(\\.(0|[1-9][0-9]*))?)?$" as const;
export const SPELLING_REFUSE_HINT_REGEX = "^v|-(lts|stable)$" as const;

export const PLATFORMS = [
  { key: "linux-amd64", os: "linux", architecture: "amd64" },
  { key: "linux-arm64", os: "linux", architecture: "arm64" },
  { key: "darwin-arm64", os: "darwin", architecture: "arm64" },
] as const;

export const MEDIA_TYPE_INDEX = "application/vnd.oci.image.index.v1+json" as const;
export const MEDIA_TYPE_MANIFEST = "application/vnd.oci.image.manifest.v1+json" as const;
export const MEDIA_TYPE_EMPTY_CONFIG = "application/vnd.oci.empty.v1+json" as const;
export const MEDIA_TYPE_CONFIG = "application/vnd.wavehouse.chtypes.config.v1+json" as const;
export const MEDIA_TYPE_LAYER = "application/vnd.oci.image.layer.v1.tar+zstd" as const;
export const MEDIA_TYPE_BUNDLE = "application/vnd.dev.sigstore.bundle.v0.3+json" as const;
export const ARTIFACT_TYPE = "application/vnd.wavehouse.chtypes.artifact.v1" as const;
export const GOLDENS_ARTIFACT_TYPE = "application/vnd.wavehouse.chtypes.goldens.v1" as const;
export const FIXTURES_ARTIFACT_TYPE = "application/vnd.wavehouse.chtypes.sdk-fetch-fixtures.v1" as const;
export const CHANNEL_ARTIFACT_TYPE = "application/vnd.wavehouse.chtypes.channel.v1" as const;

export const DSSE_PAYLOAD_TYPE = "application/vnd.in-toto+json" as const;
export const DSSE_MAX_SIGNATURES = 4 as const;

export const STATEMENT_TYPE = "https://in-toto.io/Statement/v1" as const;

export const PREDICATE_TYPE_ARTIFACT = "https://artifacts.wavehouse.dev/spec/artifact/v1" as const;
export const PREDICATE_TYPE_GOLDENS = "https://artifacts.wavehouse.dev/spec/goldens/v1" as const;
export const PREDICATE_TYPE_FIXTURES = "https://artifacts.wavehouse.dev/spec/sdk-fetch-fixtures/v1" as const;
export const PREDICATE_TYPE_CHANNEL = "https://artifacts.wavehouse.dev/spec/channel/v1" as const;

export const KEYID_ALGORITHM = "sha256-first16hex" as const;
export const RELEASE_KEYS = [
  { keyid: "deb275922dbff76e", ed25519Hex: "fdb5f06a8d4c9918d049a5f1748fa2e3b3238c3f2000986d5bb9e31beff778fc" },
] as const;

// Fixture-only keys. A conformance case trusts one only by explicitly naming
// it; trustedByDefault is always false and never consulted for real trust.
export const TEST_KEYS = [
  { keyid: "6c3468e4ec653ac0", ed25519Hex: "b9b314491f92f6c4b93fc69f932164739a619965ed79dbbcea7a4ae2da611ce2", trustedByDefault: false },
] as const;

export const RETRY_ATTEMPTS = 5 as const;
export const RETRY_FIRST_WAIT_S = 4.0 as const;
export const RETRY_MULTIPLIER = 2.0 as const;
export const RETRY_STATUSES = [408, 429, 500, 502, 503, 504];
export const RETRY_AFTER_STATUSES = [429, 503];
export const RETRY_AFTER_OVER_BUDGET = "refuse" as const;
export const DIGEST_404_POLICY = "next_base_then_retry_on_last" as const;
export const TAG_404_POLICY = "next_base_then_unpublished" as const;

export const CONNECT_TIMEOUT_S = 30.0 as const;
export const IDLE_READ_TIMEOUT_S = 60.0 as const;

export const MANIFEST_MAX_BYTES = 4194304 as const;
export const BUNDLE_MAX_BYTES = 1048576 as const;
export const TAGS_LIST_MAX_BYTES = 8388608 as const;
export const LAYOUT_INDEX_MAX_BYTES = 8388608 as const;
export const MAX_REFERRERS = 16 as const;
export const MAX_REDIRECTS = 5 as const;
export const MAX_UNPACKED_BYTES = 4294967296 as const;
export const ZSTD_WINDOW_LOG_MAX = 27 as const;

// biome-ignore lint/suspicious/noTemplateCurlyInString: a shell path template, not JS
export const CACHE_ROOT_TEMPLATE = "${XDG_CACHE_HOME:-$HOME/.cache}/chtypes/v1" as const;
export const SYSTEM_CACHE_DIRS = ["/usr/local/share/chtypes/v1", "/opt/chtypes/v1"] as const;
export const CACHE_UNPACKED_DIR = "unpacked/sha256" as const;
export const CACHE_VERIFIED_RECORD = "verified.json" as const;
export const CACHE_ANNOTATION_PREFIX = "dev.wavehouse.chtypes." as const;

export const LOCK_SCHEMA = 3 as const;
export const LOCK_DEFAULT_FILE = "chtypes.lock" as const;

export const AUTOFETCH_UNPUBLISHED_MEMO_S = 300.0 as const;

// docs/guides/fetch-v1.md §8: the six v0 codes carry v0's own real, measured
// mapping (ts/src/cli.ts EXIT / errorToExitCode; Go, Python and Rust agree);
// the four new v1-only codes are assigned here, not inherited.
export const ERROR_EXIT_CODES: Readonly<Record<string, number>> = {
  "CHTYPES_ARTIFACT_MISSING": 1,
  "CHTYPES_ARTIFACT_UNTRUSTED": 1,
  "CHTYPES_ARTIFACT_CORRUPT": 1,
  "CHTYPES_ARTIFACT_PINNED": 1,
  "CHTYPES_ARTIFACT_UNPUBLISHED": 4,
  "CHTYPES_SOURCE_UNREACHABLE": 3,
  "CHTYPES_SOURCE_UNAUTHORIZED": 5,
  "CHTYPES_SOURCE_FORBIDDEN": 6,
  "CHTYPES_SOURCE_INCOMPATIBLE": 7,
  "CHTYPES_ARTIFACT_INCOMPATIBLE": 8,
};
