/* GENERATED by scripts/abi-v1/gen.py --major 2 from spec/abi-v2/abi.json (CHS_ABI_FINGERPRINT sha256:4129dccc3f4e698dedb0e99cae413f5240085f633c5a1244e2c55bf7a7bb6c3a) — DO NOT EDIT */
/*
 * The ABI description as DATA: every described symbol's name, its parameter and return
 * shape, and the chs_status enum, both directions. See this emitter's module docstring
 * (scripts/abi-v1/emit/ts.py) for why this file carries no ffi-rs declare() calls: those
 * live in the hand-written ts/src/abi2/raw.ts, which is driven entirely by this data and
 * therefore never hand-spells a chs_* name of its own.
 *
 * SYMBOL.<NAME> is the canonical way hand code refers to a described function by name
 * without ever writing the literal `chs_` prefix itself: `rawCall(raw, SYMBOL.BUF_FREE, ...)`.
 * CAMEL_NAMES maps the same chs_* name to the key ts/src/abi2/raw.ts's define() table uses.
 */

export type ParamKind = 'scalar' | 'enum' | 'bytes_in' | 'handle' | 'out_handle' | 'out_error' | 'out_scalar';
export type ReturnKind = 'status' | 'void' | 'scalar' | 'enum' | 'handle';

export interface ParamSpec {
  readonly name: string;
  readonly kind: ParamKind;
  readonly type: string | null;
  readonly nullable: boolean;
  readonly content: string | null;
}

export interface ReturnSpec {
  readonly kind: ReturnKind;
  readonly type: string | null;
  readonly owned: boolean;
  readonly nullable: boolean;
  readonly content: string | null;
  readonly borrows: string | null;
  readonly constant: string | null;
}

export interface FunctionSpec {
  readonly cls: 'handshake' | 'tombstone' | 'api' | 'tooling';
  readonly thread: string;
  readonly params: readonly ParamSpec[];
  readonly returns: ReturnSpec;
  readonly mayReturn: readonly string[];
}

/** Every described function's shape, keyed by its chs_* name. */
export const FUNCTION_SPECS: Readonly<Record<string, FunctionSpec>> = {
  "chs_abi_revision": {
    "cls": "tombstone",
    "mayReturn": [],
    "params": [],
    "returns": {
      "borrows": null,
      "constant": "CHS_ABI_REVISION_TOMBSTONE",
      "content": null,
      "kind": "scalar",
      "nullable": false,
      "owned": false,
      "type": "int"
    },
    "thread": "any"
  },
  "chs_abi_version": {
    "cls": "handshake",
    "mayReturn": [],
    "params": [],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "scalar",
      "nullable": false,
      "owned": false,
      "type": "int32"
    },
    "thread": "any"
  },
  "chs_back_quote": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": "name",
        "kind": "bytes_in",
        "name": "name",
        "nullable": false,
        "type": null
      },
      {
        "content": "sql",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "any"
  },
  "chs_back_quote_if_needed": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": "name",
        "kind": "bytes_in",
        "name": "name",
        "nullable": false,
        "type": null
      },
      {
        "content": "sql",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "any"
  },
  "chs_block_create": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_REJECTED",
      "CHS_DECLINED",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "schema",
        "nullable": false,
        "type": "chs_schema"
      },
      {
        "content": null,
        "kind": "enum",
        "name": "format",
        "nullable": false,
        "type": "chs_format"
      },
      {
        "content": "bytes",
        "kind": "bytes_in",
        "name": "body",
        "nullable": false,
        "type": null
      },
      {
        "content": "json_object_string_values",
        "kind": "bytes_in",
        "name": "settings",
        "nullable": false,
        "type": null
      },
      {
        "content": "json_array_names",
        "kind": "bytes_in",
        "name": "columns",
        "nullable": false,
        "type": null
      },
      {
        "content": null,
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_block"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "shared"
  },
  "chs_block_free": {
    "cls": "api",
    "mayReturn": [],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "block",
        "nullable": true,
        "type": "chs_block"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "void",
      "nullable": false,
      "owned": false,
      "type": null
    },
    "thread": "handle_serial"
  },
  "chs_buf_data": {
    "cls": "api",
    "mayReturn": [],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "buf",
        "nullable": false,
        "type": "chs_buf"
      }
    ],
    "returns": {
      "borrows": "buf",
      "constant": null,
      "content": null,
      "kind": "scalar",
      "nullable": false,
      "owned": false,
      "type": "u8ptr_const"
    },
    "thread": "shared"
  },
  "chs_buf_free": {
    "cls": "api",
    "mayReturn": [],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "buf",
        "nullable": true,
        "type": "chs_buf"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "void",
      "nullable": false,
      "owned": false,
      "type": null
    },
    "thread": "handle_serial"
  },
  "chs_buf_len": {
    "cls": "api",
    "mayReturn": [],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "buf",
        "nullable": false,
        "type": "chs_buf"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "scalar",
      "nullable": false,
      "owned": false,
      "type": "size"
    },
    "thread": "shared"
  },
  "chs_build_info": {
    "cls": "handshake",
    "mayReturn": [],
    "params": [],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "scalar",
      "nullable": false,
      "owned": false,
      "type": "cstr_static"
    },
    "thread": "any"
  },
  "chs_clickhouse_version": {
    "cls": "handshake",
    "mayReturn": [],
    "params": [],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "scalar",
      "nullable": false,
      "owned": false,
      "type": "cstr_static"
    },
    "thread": "any"
  },
  "chs_discover_columns": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_REJECTED",
      "CHS_DECLINED",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": "bytes",
        "kind": "bytes_in",
        "name": "rows",
        "nullable": false,
        "type": null
      },
      {
        "content": "document:discovery",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "any"
  },
  "chs_discover_query": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": "sql",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "any"
  },
  "chs_error_ch_code": {
    "cls": "api",
    "mayReturn": [],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "error",
        "nullable": false,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "scalar",
      "nullable": false,
      "owned": false,
      "type": "int32"
    },
    "thread": "shared"
  },
  "chs_error_ch_name": {
    "cls": "api",
    "mayReturn": [],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "error",
        "nullable": false,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": "ascii",
      "kind": "handle",
      "nullable": true,
      "owned": true,
      "type": "chs_buf"
    },
    "thread": "shared"
  },
  "chs_error_codes": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": "document:error_code_table",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "any"
  },
  "chs_error_column": {
    "cls": "api",
    "mayReturn": [],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "error",
        "nullable": false,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": "name",
      "kind": "handle",
      "nullable": true,
      "owned": true,
      "type": "chs_buf"
    },
    "thread": "shared"
  },
  "chs_error_free": {
    "cls": "api",
    "mayReturn": [],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "error",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "void",
      "nullable": false,
      "owned": false,
      "type": null
    },
    "thread": "handle_serial"
  },
  "chs_error_message": {
    "cls": "api",
    "mayReturn": [],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "error",
        "nullable": false,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": "message",
      "kind": "handle",
      "nullable": true,
      "owned": true,
      "type": "chs_buf"
    },
    "thread": "shared"
  },
  "chs_error_status": {
    "cls": "api",
    "mayReturn": [],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "error",
        "nullable": false,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "enum",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "shared"
  },
  "chs_filter_create": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_REJECTED",
      "CHS_DECLINED",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "schema",
        "nullable": false,
        "type": "chs_schema"
      },
      {
        "content": "sql",
        "kind": "bytes_in",
        "name": "expr",
        "nullable": false,
        "type": null
      },
      {
        "content": "json_object_string_values",
        "kind": "bytes_in",
        "name": "query_params",
        "nullable": false,
        "type": null
      },
      {
        "content": "json_object_string_values",
        "kind": "bytes_in",
        "name": "settings",
        "nullable": false,
        "type": null
      },
      {
        "content": null,
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_filter"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "shared"
  },
  "chs_filter_eval_block": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_REJECTED",
      "CHS_DECLINED",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "filter",
        "nullable": false,
        "type": "chs_filter"
      },
      {
        "content": null,
        "kind": "handle",
        "name": "block",
        "nullable": false,
        "type": "chs_block"
      },
      {
        "content": "document:filter_result",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "shared"
  },
  "chs_filter_eval_body": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_REJECTED",
      "CHS_DECLINED",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "filter",
        "nullable": false,
        "type": "chs_filter"
      },
      {
        "content": null,
        "kind": "enum",
        "name": "format",
        "nullable": false,
        "type": "chs_format"
      },
      {
        "content": "bytes",
        "kind": "bytes_in",
        "name": "body",
        "nullable": false,
        "type": null
      },
      {
        "content": "json_object_string_values",
        "kind": "bytes_in",
        "name": "settings",
        "nullable": false,
        "type": null
      },
      {
        "content": "document:filter_result",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "shared"
  },
  "chs_filter_free": {
    "cls": "api",
    "mayReturn": [],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "filter",
        "nullable": true,
        "type": "chs_filter"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "void",
      "nullable": false,
      "owned": false,
      "type": null
    },
    "thread": "handle_serial"
  },
  "chs_function_flags": {
    "cls": "tooling",
    "mayReturn": [
      "CHS_OK",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": "ascii",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "process_serial"
  },
  "chs_initialize": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_REJECTED",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": "timezone",
        "kind": "bytes_in",
        "name": "timezone",
        "nullable": false,
        "type": null
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "process_once"
  },
  "chs_live_handles": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": "document:live_handles",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "any"
  },
  "chs_preview_batch": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_REJECTED",
      "CHS_DECLINED",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "schema",
        "nullable": false,
        "type": "chs_schema"
      },
      {
        "content": null,
        "kind": "enum",
        "name": "format",
        "nullable": false,
        "type": "chs_format"
      },
      {
        "content": "bytes",
        "kind": "bytes_in",
        "name": "body",
        "nullable": false,
        "type": null
      },
      {
        "content": "json_object_string_values",
        "kind": "bytes_in",
        "name": "settings",
        "nullable": false,
        "type": null
      },
      {
        "content": "json_array_names",
        "kind": "bytes_in",
        "name": "columns",
        "nullable": false,
        "type": null
      },
      {
        "content": null,
        "kind": "handle",
        "name": "filter",
        "nullable": true,
        "type": "chs_filter"
      },
      {
        "content": null,
        "kind": "scalar",
        "name": "export_format",
        "nullable": false,
        "type": "int32"
      },
      {
        "content": null,
        "kind": "scalar",
        "name": "doc_flags",
        "nullable": false,
        "type": "uint32"
      },
      {
        "content": "document:batch",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": "bytes",
        "kind": "out_handle",
        "name": "out_export",
        "nullable": true,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "shared"
  },
  "chs_preview_row": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_REJECTED",
      "CHS_DECLINED",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "schema",
        "nullable": false,
        "type": "chs_schema"
      },
      {
        "content": null,
        "kind": "enum",
        "name": "format",
        "nullable": false,
        "type": "chs_format"
      },
      {
        "content": "bytes",
        "kind": "bytes_in",
        "name": "body",
        "nullable": false,
        "type": null
      },
      {
        "content": "json_object_string_values",
        "kind": "bytes_in",
        "name": "settings",
        "nullable": false,
        "type": null
      },
      {
        "content": "json_array_names",
        "kind": "bytes_in",
        "name": "columns",
        "nullable": false,
        "type": null
      },
      {
        "content": "document:row",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "shared"
  },
  "chs_quote_string": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": "bytes",
        "kind": "bytes_in",
        "name": "text",
        "nullable": false,
        "type": null
      },
      {
        "content": "sql",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "any"
  },
  "chs_reference_type": {
    "cls": "tooling",
    "mayReturn": [
      "CHS_OK",
      "CHS_REJECTED",
      "CHS_DECLINED",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": "sql",
        "kind": "bytes_in",
        "name": "type_expr",
        "nullable": false,
        "type": null
      },
      {
        "content": "sql",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "process_serial"
  },
  "chs_registered_families": {
    "cls": "tooling",
    "mayReturn": [
      "CHS_OK",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": "ascii",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "process_serial"
  },
  "chs_schema_create": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_REJECTED",
      "CHS_DECLINED",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "server",
        "nullable": true,
        "type": "chs_server"
      },
      {
        "content": "sql",
        "kind": "bytes_in",
        "name": "create_table",
        "nullable": false,
        "type": null
      },
      {
        "content": "json_object_string_values",
        "kind": "bytes_in",
        "name": "settings",
        "nullable": false,
        "type": null
      },
      {
        "content": "input:schema_options",
        "kind": "bytes_in",
        "name": "options",
        "nullable": false,
        "type": null
      },
      {
        "content": null,
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_schema"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "shared"
  },
  "chs_schema_describe": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "schema",
        "nullable": false,
        "type": "chs_schema"
      },
      {
        "content": "document:schema_description",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "shared"
  },
  "chs_schema_free": {
    "cls": "api",
    "mayReturn": [],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "schema",
        "nullable": true,
        "type": "chs_schema"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "void",
      "nullable": false,
      "owned": false,
      "type": null
    },
    "thread": "handle_serial"
  },
  "chs_server_create": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_REJECTED",
      "CHS_DECLINED",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": "input:server_profile",
        "kind": "bytes_in",
        "name": "profile",
        "nullable": false,
        "type": null
      },
      {
        "content": "input:server_options",
        "kind": "bytes_in",
        "name": "options",
        "nullable": false,
        "type": null
      },
      {
        "content": null,
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_server"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "any"
  },
  "chs_server_free": {
    "cls": "api",
    "mayReturn": [],
    "params": [
      {
        "content": null,
        "kind": "handle",
        "name": "server",
        "nullable": true,
        "type": "chs_server"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "void",
      "nullable": false,
      "owned": false,
      "type": null
    },
    "thread": "handle_serial"
  },
  "chs_set_defaults": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_REJECTED",
      "CHS_DECLINED",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": "json_object_string_values",
        "kind": "bytes_in",
        "name": "settings",
        "nullable": false,
        "type": null
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "process_serial"
  },
  "chs_shutdown": {
    "cls": "api",
    "mayReturn": [],
    "params": [],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "void",
      "nullable": false,
      "owned": false,
      "type": null
    },
    "thread": "process_serial"
  },
  "chs_type_validate": {
    "cls": "api",
    "mayReturn": [
      "CHS_OK",
      "CHS_REJECTED",
      "CHS_DECLINED",
      "CHS_INVALID_ARGUMENT",
      "CHS_INTERNAL"
    ],
    "params": [
      {
        "content": "sql",
        "kind": "bytes_in",
        "name": "type_expr",
        "nullable": false,
        "type": null
      },
      {
        "content": "sql",
        "kind": "out_handle",
        "name": "out",
        "nullable": false,
        "type": "chs_buf"
      },
      {
        "content": null,
        "kind": "out_error",
        "name": "err",
        "nullable": true,
        "type": "chs_error"
      }
    ],
    "returns": {
      "borrows": null,
      "constant": null,
      "content": null,
      "kind": "status",
      "nullable": false,
      "owned": false,
      "type": "chs_status"
    },
    "thread": "any"
  }
} as const;

/** chs_* name -> the key ts/src/abi2/raw.ts's ffi-rs define() table uses for it. */
export const CAMEL_NAMES: Readonly<Record<string, string>> = {
  "chs_abi_revision": "abiRevision",
  "chs_abi_version": "abiVersion",
  "chs_back_quote": "backQuote",
  "chs_back_quote_if_needed": "backQuoteIfNeeded",
  "chs_block_create": "blockCreate",
  "chs_block_free": "blockFree",
  "chs_buf_data": "bufData",
  "chs_buf_free": "bufFree",
  "chs_buf_len": "bufLen",
  "chs_build_info": "buildInfo",
  "chs_clickhouse_version": "clickhouseVersion",
  "chs_discover_columns": "discoverColumns",
  "chs_discover_query": "discoverQuery",
  "chs_error_ch_code": "errorChCode",
  "chs_error_ch_name": "errorChName",
  "chs_error_codes": "errorCodes",
  "chs_error_column": "errorColumn",
  "chs_error_free": "errorFree",
  "chs_error_message": "errorMessage",
  "chs_error_status": "errorStatus",
  "chs_filter_create": "filterCreate",
  "chs_filter_eval_block": "filterEvalBlock",
  "chs_filter_eval_body": "filterEvalBody",
  "chs_filter_free": "filterFree",
  "chs_function_flags": "functionFlags",
  "chs_initialize": "initialize",
  "chs_live_handles": "liveHandles",
  "chs_preview_batch": "previewBatch",
  "chs_preview_row": "previewRow",
  "chs_quote_string": "quoteString",
  "chs_reference_type": "referenceType",
  "chs_registered_families": "registeredFamilies",
  "chs_schema_create": "schemaCreate",
  "chs_schema_describe": "schemaDescribe",
  "chs_schema_free": "schemaFree",
  "chs_server_create": "serverCreate",
  "chs_server_free": "serverFree",
  "chs_set_defaults": "setDefaults",
  "chs_shutdown": "shutdown",
  "chs_type_validate": "typeValidate"
} as const;

/**
 * Every described chs_* name, reachable WITHOUT spelling it: hand code writes
 * `SYMBOL.BUF_FREE`, never the string `"chs_buf_free"`. Generated so the one place that
 * spells a chs_* name is this file, machine-checked against spec/abi-v2/abi.json.
 *
 * Deliberately NOT typed `Record<string, string>`: each key's value is its own string
 * LITERAL type, so a known key (`SYMBOL.BUF_FREE`) is never widened to `string | undefined`
 * by `noUncheckedIndexedAccess` the way an index signature would be. Nothing here is ever
 * looked up with a variable key — `CAMEL_NAMES` and `FUNCTION_SPECS` are, and keep their
 * `Record` types for that reason.
 */
export const SYMBOL = {
  "ABI_REVISION": "chs_abi_revision",
  "ABI_VERSION": "chs_abi_version",
  "BACK_QUOTE": "chs_back_quote",
  "BACK_QUOTE_IF_NEEDED": "chs_back_quote_if_needed",
  "BLOCK_CREATE": "chs_block_create",
  "BLOCK_FREE": "chs_block_free",
  "BUF_DATA": "chs_buf_data",
  "BUF_FREE": "chs_buf_free",
  "BUF_LEN": "chs_buf_len",
  "BUILD_INFO": "chs_build_info",
  "CLICKHOUSE_VERSION": "chs_clickhouse_version",
  "DISCOVER_COLUMNS": "chs_discover_columns",
  "DISCOVER_QUERY": "chs_discover_query",
  "ERROR_CH_CODE": "chs_error_ch_code",
  "ERROR_CH_NAME": "chs_error_ch_name",
  "ERROR_CODES": "chs_error_codes",
  "ERROR_COLUMN": "chs_error_column",
  "ERROR_FREE": "chs_error_free",
  "ERROR_MESSAGE": "chs_error_message",
  "ERROR_STATUS": "chs_error_status",
  "FILTER_CREATE": "chs_filter_create",
  "FILTER_EVAL_BLOCK": "chs_filter_eval_block",
  "FILTER_EVAL_BODY": "chs_filter_eval_body",
  "FILTER_FREE": "chs_filter_free",
  "FUNCTION_FLAGS": "chs_function_flags",
  "INITIALIZE": "chs_initialize",
  "LIVE_HANDLES": "chs_live_handles",
  "PREVIEW_BATCH": "chs_preview_batch",
  "PREVIEW_ROW": "chs_preview_row",
  "QUOTE_STRING": "chs_quote_string",
  "REFERENCE_TYPE": "chs_reference_type",
  "REGISTERED_FAMILIES": "chs_registered_families",
  "SCHEMA_CREATE": "chs_schema_create",
  "SCHEMA_DESCRIBE": "chs_schema_describe",
  "SCHEMA_FREE": "chs_schema_free",
  "SERVER_CREATE": "chs_server_create",
  "SERVER_FREE": "chs_server_free",
  "SET_DEFAULTS": "chs_set_defaults",
  "SHUTDOWN": "chs_shutdown",
  "TYPE_VALIDATE": "chs_type_validate"
} as const;

export interface HandleInfo {
  readonly free: string;
  readonly holds: readonly string[];
  readonly className: string;
}

/** Every described handle kind: its free function (a SYMBOL.* value) and what it holds. */
export const HANDLE_INFO: Readonly<Record<string, HandleInfo>> = {
  "chs_block": {
    "className": "Block",
    "free": "chs_block_free",
    "holds": [
      "chs_schema"
    ]
  },
  "chs_buf": {
    "className": "Buf",
    "free": "chs_buf_free",
    "holds": []
  },
  "chs_error": {
    "className": "Error",
    "free": "chs_error_free",
    "holds": []
  },
  "chs_filter": {
    "className": "Filter",
    "free": "chs_filter_free",
    "holds": [
      "chs_schema"
    ]
  },
  "chs_schema": {
    "className": "Schema",
    "free": "chs_schema_free",
    "holds": [
      "chs_server"
    ]
  },
  "chs_server": {
    "className": "Server",
    "free": "chs_server_free",
    "holds": []
  }
} as const;

/** chs_status, both directions (the wire int32 and its C name). */
export const STATUS_NAMES: Readonly<Record<number, string>> = {
  "0": "CHS_OK",
  "1": "CHS_REJECTED",
  "2": "CHS_DECLINED",
  "3": "CHS_INVALID_ARGUMENT",
  "4": "CHS_INTERNAL"
} as const;
export const STATUS_VALUES: Readonly<Record<string, number>> = {
  "CHS_DECLINED": 2,
  "CHS_INTERNAL": 4,
  "CHS_INVALID_ARGUMENT": 3,
  "CHS_OK": 0,
  "CHS_REJECTED": 1
} as const;

/** Every exported symbol, sorted — the loader's step 6 resolve-all sweep. */
export const DESCRIBED_SYMBOLS: readonly string[] = [
  "chs_abi_revision",
  "chs_abi_version",
  "chs_back_quote",
  "chs_back_quote_if_needed",
  "chs_block_create",
  "chs_block_free",
  "chs_buf_data",
  "chs_buf_free",
  "chs_buf_len",
  "chs_build_info",
  "chs_clickhouse_version",
  "chs_discover_columns",
  "chs_discover_query",
  "chs_error_ch_code",
  "chs_error_ch_name",
  "chs_error_codes",
  "chs_error_column",
  "chs_error_free",
  "chs_error_message",
  "chs_error_status",
  "chs_filter_create",
  "chs_filter_eval_block",
  "chs_filter_eval_body",
  "chs_filter_free",
  "chs_function_flags",
  "chs_initialize",
  "chs_live_handles",
  "chs_preview_batch",
  "chs_preview_row",
  "chs_quote_string",
  "chs_reference_type",
  "chs_registered_families",
  "chs_schema_create",
  "chs_schema_describe",
  "chs_schema_free",
  "chs_server_create",
  "chs_server_free",
  "chs_set_defaults",
  "chs_shutdown",
  "chs_type_validate"
];

/**
 * The buf handle's own chs_* name (D2/D3's universal owned-output type), named so hand
 * code can compare `ParamSpec.type`/`ReturnSpec.type` against it without ever spelling
 * the literal itself (a literal would read as a hand-written chs_ reference to
 * scripts/abi-v1/check-no-hand-decls.py once this file's own `define(`-adjacent code also
 * names it — see ts/src/abi2/raw.ts's module comment).
 */
export const BUF_HANDLE: 'chs_buf' = 'chs_buf';

/**
 * This binding's own compiled-in ABI identity (D1.1/§1.7's "one computation, copied
 * everywhere else" — never recomputed, byte-compared against a loaded library's
 * chs_build_info().abi_fingerprint at loader step 4).
 */
export const ABI_VERSION = 2;
export const ABI_FINGERPRINT = "sha256:4129dccc3f4e698dedb0e99cae413f5240085f633c5a1244e2c55bf7a7bb6c3a";
/**
 * The description's stability: "unstable" while this generation is being designed, so
 * ABI_FINGERPRINT moves with every change, and "locked" after (spec/abi-v2/docs.md, rule
 * r6). A dev SDK refuses any other fingerprint with the dev message.
 */
export const ABI_STABILITY: string = "unstable";

export interface CrossCheckField {
  readonly buildInfo: string;
  readonly predicate: string;
  readonly compare: 'bytes' | 'int';
}

/** spec/abi-v2/sdk.json's cross_check table: loader step 5's nine fields. */
export const CROSS_CHECK: readonly CrossCheckField[] = [
  {
    "buildInfo": "abi",
    "compare": "int",
    "predicate": "abi"
  },
  {
    "buildInfo": "abi_fingerprint",
    "compare": "bytes",
    "predicate": "abi_fingerprint"
  },
  {
    "buildInfo": "clickhouse_version",
    "compare": "bytes",
    "predicate": "clickhouse_version"
  },
  {
    "buildInfo": "channel",
    "compare": "bytes",
    "predicate": "channel"
  },
  {
    "buildInfo": "build",
    "compare": "bytes",
    "predicate": "build"
  },
  {
    "buildInfo": "os",
    "compare": "bytes",
    "predicate": "os"
  },
  {
    "buildInfo": "arch",
    "compare": "bytes",
    "predicate": "arch"
  },
  {
    "buildInfo": "core_commit",
    "compare": "bytes",
    "predicate": "core_commit"
  },
  {
    "buildInfo": "inputs_sha256",
    "compare": "bytes",
    "predicate": "inputs_sha256"
  }
];
