/* GENERATED by scripts/abi-v1/gen.py --major 2 from spec/abi-v2/abi.json (CHS_ABI_FINGERPRINT sha256:d60a681ea0e249ab9e2c83b50640ad9cef040261ddf61805106c93e2c68774e4) — DO NOT EDIT */
/*
 * spec/abi-v2/sdk.json's two error tables, as code: a CALL's chs_status -> one of
 * SchemaError/UnsupportedError/UsageError/InternalError (errors.status), and a LOADER
 * refusal's reason -> artifact_incompatible or artifact_corrupt (loader.refusals). Both
 * read spec/abi-v2/sdk.json; regenerate rather than hand-editing either table.
 */

import {
  type CallErrorFields,
  type ChtypesError,
  InternalError,
  SchemaError,
  UnsupportedError,
  UsageError,
} from './errors.js';

/**
 * A call's raw chs_status value -> the mapped error instance (spec/abi-v2/sdk.json's
 * errors.status table). A caller checks for the OK value before ever calling this. A
 * status outside the closed set (impossible under a matching fingerprint; see
 * spec/abi-v2/docs.md's chs_status section) maps to InternalError, naming the raw
 * value, exactly like every other binding's generated table.
 */
export function errorForStatus(status: number, fields: CallErrorFields): ChtypesError {
  switch (status) {
    case 1: // CHS_REJECTED
      return new SchemaError(fields);
    case 2: // CHS_DECLINED
      return new UnsupportedError(fields);
    case 3: // CHS_INVALID_ARGUMENT
      return new UsageError(fields);
    case 4: // CHS_INTERNAL
      return new InternalError(fields);
    default:
      return new InternalError({
        ...fields,
        messageBytes: Buffer.from(
          `chtypes: call status unknown(${status}) is outside the closed set: ${fields.messageBytes.toString('utf8')}`,
          'utf8',
        ),
      });
  }
}

export type LoaderErrorClass = 'artifact_incompatible' | 'artifact_corrupt';

/**
 * A loader refusal reason (spec/abi-v2/sdk.json's loader.refusals vocabulary, a
 * `missing_symbol:<name>` or `build_info_mismatch:<field>` reason included, via its
 * prefix before the first ':') -> which artifact error class the C ABI contract §Loading
 * error map says it is.
 */
export function loaderErrorClassFor(reason: string): LoaderErrorClass {
  const prefix = reason.split(':', 1)[0];
  switch (prefix) {
    case 'glibc_floor':
      return 'artifact_incompatible';
    case 'no_glibc':
      return 'artifact_incompatible';
    case 'predicate_malformed':
      return 'artifact_incompatible';
    case 'dlopen':
      return 'artifact_incompatible';
    case 'not_v1':
      return 'artifact_incompatible';
    case 'abi_version':
      return 'artifact_incompatible';
    case 'build_info_malformed':
      return 'artifact_corrupt';
    case 'fingerprint':
      return 'artifact_incompatible';
    case 'missing_symbol':
      return 'artifact_incompatible';
    case 'build_info_mismatch':
      return 'artifact_corrupt';
    default:
      throw new Error(`chtypes abi2: no sdk.json loader refusal class for reason ${reason}`);
  }
}
