/* GENERATED by scripts/abi-v1/gen.py --major 2 from spec/abi-v2/abi.json (CHS_ABI_FINGERPRINT sha256:d60a681ea0e249ab9e2c83b50640ad9cef040261ddf61805106c93e2c68774e4) — DO NOT EDIT */
/*
 * The libc primitives ts/src/abi2/libc.ts needs for plan §3.3's TS-trap fix: dlopen,
 * dlsym, dlerror, gnu_get_libc_version and strlen, declared through ffi-rs's define()
 * against the PROCESS'S OWN libc, by their real C names. This file carries the generated
 * banner, so scripts/abi-v1/check-no-hand-decls.py exempts it outright — the check's own
 * intent (every raw symbol lookup lives in generated code) is satisfied for real here,
 * never worked around with a renamed key or a disguised call site in a hand file. See
 * scripts/abi-v1/emit/ts.py's module docstring.
 *
 * `resolveSymbol` is THE ONE symbol-lookup helper hand code uses (dlsym plus the null
 * check); the other four exports are the raw primitives dlopen/dlerror/gnu_get_libc_version/
 * strlen need, each with its own null handling where the C function can return NULL.
 * `flock` is the fetch layer's in-use hold (docs/guides/fetch-v1.md §1, "In use"): Node has
 * no file lock of its own, and every binding takes the same flock(2) on the same file.
 */

import { DataType, define, isNullPointer, type JsExternal, open } from 'ffi-rs';

const { External, I32, U64, String: Str } = DataType;

const LIBC_KEY = 'chtypes_abi2_libc';

function libcPath(): string {
  if (process.platform === 'darwin') return '/usr/lib/libSystem.B.dylib';
  if (process.platform === 'linux') return 'libc.so.6';
  throw new Error(`chtypes abi2: unsupported platform ${process.platform}; only linux and darwin are ABI v2 platforms`);
}

let opened = false;
function ensureOpen(): void {
  if (opened) return;
  open({ library: LIBC_KEY, path: libcPath() });
  opened = true;
}

interface LibcFns {
  dlopen(args: [string, number]): JsExternal;
  dlsym(args: [JsExternal, string]): JsExternal;
  dlerror(args: []): JsExternal;
  gnu_get_libc_version(args: []): JsExternal;
  strlen(args: [JsExternal]): bigint;
  flock(args: [number, number]): { value: number; errnoCode: number; errnoMessage: string };
}

let fns: LibcFns | null = null;
function libc(): LibcFns {
  ensureOpen();
  if (fns === null) {
    fns = define({
      dlopen: { library: LIBC_KEY, retType: External, paramsType: [Str, I32] },
      dlsym: { library: LIBC_KEY, retType: External, paramsType: [External, Str] },
      dlerror: { library: LIBC_KEY, retType: External, paramsType: [] },
      gnu_get_libc_version: { library: LIBC_KEY, retType: External, paramsType: [] },
      strlen: { library: LIBC_KEY, retType: U64, paramsType: [External] },
      flock: { library: LIBC_KEY, retType: I32, paramsType: [I32, I32], errno: true },
    }) as unknown as LibcFns;
  }
  return fns;
}

/** dlopen(path, flags) against the process's own libc. Null on failure. */
export function dlopen(path: string, flags: number): JsExternal | null {
  const h = libc().dlopen([path, flags]);
  return isNullPointer(h) ? null : h;
}

/** THE one symbol-lookup helper: dlsym(handle, name). Null if `name` is not exported by `handle`'s image. */
export function resolveSymbol(handle: JsExternal, name: string): JsExternal | null {
  const p = libc().dlsym([handle, name]);
  return isNullPointer(p) ? null : p;
}

/** dlerror(). Null if there is no pending error (POSIX clears it on read, so call this ONCE, right after a failure). */
export function dlerror(): JsExternal | null {
  const p = libc().dlerror([]);
  return isNullPointer(p) ? null : p;
}

/** gnu_get_libc_version(). Null if the symbol does not resolve at all (musl) or the call itself returns null. */
export function gnuGetLibcVersion(): JsExternal | null {
  try {
    const p = libc().gnu_get_libc_version([]);
    return isNullPointer(p) ? null : p;
  } catch {
    return null;
  }
}

/** strlen(ptr): the length of a NUL-terminated C string, for a byte-safe read via createExternalBuffer. */
export function cStringLength(ptr: JsExternal): number {
  return Number(libc().strlen([ptr]));
}

/** flock(fd, operation) against the process's own libc: 0 when it succeeded, else the errno it failed with (-1 when none was captured), never 0 for a failure. */
export function flock(fd: number, operation: number): number {
  const r = libc().flock([fd, operation]);
  if (r.value === 0) return 0;
  return r.errnoCode !== 0 ? r.errnoCode : -1;
}
