//! The v1 fetch layer: OCI distribution plus zstd (docs/guides/fetch-v1.md,
//! plan §1), narrowed by this 2.0.0-dev SDK to the ABI v2 dev channel
//! ([`channel`]; spec/abi-v2/docs.md, rules r5 and r6). This module is **not** re-exported from the crate root — it is
//! wired in behind `#[cfg(feature = "fetch-v1")]` and built/tested on its
//! own (`cargo test --features fetch-v1 --test ocifetch_conformance`).
//!
//! The seam (plan §1.3) is [`ensure`], [`resolve_installed`],
//! [`list_installed`], [`verify_installed`] and [`fetch_signed`], returning
//! [`Resolved`], with [`resolve::resolve`] and [`prune::prune`] beside it for
//! the CLI, and [`hold::hold`], which the registry takes on every build it
//! opens or fetches. Nothing outside this module calls anything else here.
//!
//! Every submodule is `pub` **within this private module only** — `mod
//! ocifetch;` in `lib.rs` keeps all of it unreachable from a consumer of the
//! `chtypes` crate. The visibility exists so `tests/ocifetch_conformance.rs`
//! can exercise it directly: that file recompiles this module tree under
//! its own crate root with `#[path = "../src/ocifetch/mod.rs"] mod
//! ocifetch;`, since an *integration* test (unlike a `#[cfg(test)]` unit
//! test) links the library as an ordinary external crate and cannot see a
//! private `mod` declared in `lib.rs` any other way.
//!
//! `dead_code` is off for this whole subtree, deliberately: `lib.rs` wires
//! in exactly `#[cfg(feature = "fetch-v1")] mod ocifetch;` and nothing else
//! (the switch lane does the rest, plan §2.4), so nothing in this crate's
//! own build calls the seam functions yet — only the conformance test does,
//! in its own separate compilation via the `#[path]` trick above, which
//! rustc's dead-code analysis of *this* crate cannot see. Every other lint
//! (unused imports, unused variables, …) stays on.

#![allow(dead_code)]

// Generated by scripts/fetch-v1/gen-constants.py: skip rustfmt on it rather
// than reformat it, the standard approach for generated code. rustfmt
// follows the `mod` declaration, so this also covers
// tests/ocifetch_conformance.rs's `#[path]` recompilation of this same file.
#[rustfmt::skip]
pub mod constants;
// Generated by scripts/abi-v1/gen.py --major 2 (scripts/abi-v1/emit/rust_fetch.py):
// the ABI fingerprint this crate speaks, which names the dev channel's alias tags.
pub mod abi_fingerprint;
// The fetch contract this build speaks: the ABI v2 dev channel (channel.rs).
pub mod channel;
pub mod dsse;
pub mod ensure;
pub mod error;
pub mod faults;
pub mod goldens;
// The in-use signal (public issue #494): the shared flock a registry holds on
// every build it opens or fetches, and the exclusive one a prune takes.
pub mod hold;
pub mod http;
pub mod layout;
pub mod lock;
pub mod oci;
// `chtypes prune` (public issue #494).
pub mod prune;
pub mod referrers;
// `chtypes resolve` (public issue #493).
pub mod resolve;
pub mod retired;
pub mod tags;
pub mod unpack;
pub mod url;

// Deliberately no top-level `pub use` of the seam here: nothing in this
// crate's own build calls it yet (see the module doc above), and a `pub
// use` nothing uses is itself `unused_imports` — a real lint, left on.
// `tests/ocifetch_conformance.rs` imports straight from `ocifetch::ensure`.
