/* GENERATED by scripts/abi-v1/gen.py --major 2 from spec/abi-v2/abi.json (CHS_ABI_FINGERPRINT sha256:28c7445ce6b5c6d0ae33177fd60eb7b3b5654a966c842b8d812aea622824dc72) — DO NOT EDIT */
/*
 * chtypes.h: the chtypes C ABI, generation 2.
 *
 * This header is generated from `spec/abi-v2/abi.json` by `scripts/abi-v1/gen.py --major 2`. Edit
 * the description and regenerate; never edit this file. `docs/reference/abi-v2.md` is the normative
 * reference, and the rules generation 2 is written under (r1 to r7) are in it.
 *
 * Stability. Generation 2 is UNSTABLE: its description is still being designed, so
 * `CHS_ABI_FINGERPRINT` moves with every change until the description is locked. Nothing built from
 * an unstable description is a release. Only pre-release SDKs (`2.0.0-dev.N`) speak it, each pinned
 * to one fingerprint, and they fetch only from the staging dev channel. ABI v1
 * (`include/chtypes.h`) is frozen and unaffected.
 *
 * Identity. `CHS_ABI_VERSION` is the generation and `CHS_ABI_FINGERPRINT` is sha256 over the
 * canonical form of the description. A loader opens a library with `RTLD_NOW | RTLD_LOCAL`, calls
 * only the handshake set (`chs_abi_version`, `chs_build_info`, `chs_clickhouse_version`) before its
 * checks pass, and refuses any library whose generation or fingerprint differs from the ones it was
 * compiled with. Nothing degrades: every described symbol is mandatory.
 *
 * Ownership. Every input string, statement, document and body is counted bytes, `(const uint8_t *p,
 * size_t n)`: length 0 is none and the pointer may then be NULL, and a NULL pointer with a nonzero
 * length is `CHS_INVALID_ARGUMENT`. Every output is an owned, opaque `chs_buf`, read with
 * `chs_buf_data` and `chs_buf_len` and released with `chs_buf_free`. Bytes pass through unmodified,
 * NUL and invalid UTF-8 included: a column name may contain either (measured on live servers), so
 * no name, statement or message is ever a C string. The only static strings are the handshake's.
 * Handles are opaque, reference-counted and tagged with their kind and the image that made them;
 * every entry point checks both, a child holds a strong reference to what it needs, and each free
 * drops only the caller's reference, so any free order is safe and freeing NULL does nothing.
 *
 * Errors. A fallible call returns a `chs_status` and, through an optional last `chs_error **err`,
 * an owned error carrying the status, ClickHouse's own code and name, the message and the column.
 * The status alone carries the verdict, so `err` may be NULL.
 *
 * Threads. Every function has a thread class, listed in the reference. A handle is immutable once
 * made, so every call that only reads handles is `shared`: any number of threads may call it at
 * once, on the same handles too. The one thing a caller must never overlap with a call is a free of
 * a handle that call uses. Process setup (`chs_initialize`, then `chs_set_defaults`) runs before
 * the traffic it configures.
 *
 * Time zones. A library image has one zone of its own, set once by `chs_initialize`: the image
 * zone. A schema has a home zone, its server's `timezone` (`chs_server_create`), or else the image
 * zone. The schema's types bind its home zone, as a server's table binds the server's zone after a
 * restart, and so do the functions its DEFAULT, MATERIALIZED, ALIAS and CHECK expressions apply to
 * its columns, its PARTITION BY expressions, and a Date-valued TTL under a merge. Each call runs in
 * a zone too, the first of these that is set: the call's own `session_timezone` (a key in its
 * settings, which ClickHouse applies through its own query context); the `session_timezone` in the
 * schema's own settings; the one in its server's `settings`; the one set by `chs_set_defaults`; its
 * server's `timezone`; the image zone. An empty `session_timezone` at any of these means the
 * server's zone, the last two. The call's zone governs parsing and rendering a zone-less `DateTime`
 * or `DateTime64`, export, a DEFAULT literal's fold, `toDateTimeOrZero` and a filter's literals. A
 * `Date` partition id is the civil date in every zone. Every zone name is validated by ClickHouse's
 * own `DateLUT`, which reads the library host's time zone database, on every platform. On darwin
 * the file system is case-insensitive, so `DateLUT` there accepts a spelling such as `utc` that a
 * Linux server refuses; that difference is documented, not patched.
 *
 * Settings. Every settings input is a JSON object whose values are JSON strings, and a binding
 * never rewrites one. A call's settings are layered, highest first: the call's own `settings`; the
 * schema's own (`chs_schema_create`); its server's `settings` (`chs_server_create`); the defaults
 * set by `chs_set_defaults`; the build's own. A filter's WHERE takes the same layers, lowest first:
 * the build's own, `chs_set_defaults`, the server profile, the schema's own, and the filter's own
 * (`chs_filter_create`), with `session_timezone` at every layer staying on the zone path (Time
 * zones, above). One exception: a type gate in the schema's own settings binds the CREATE only, and
 * a WHERE's CAST validates under the session layers, every layer but the schema's own. Each setting
 * that reaches a WHERE is honored (applied to it), passed through (accepted and ignored), or
 * declined (`chs_filter_create` says how). A server resource limit (an `execution`-tier setting,
 * e.g. a small `max_columns_to_read`) can make the server refuse a query the library answers; that
 * is resource policy, not row access, and the library does not model it. A server's settings are
 * the ones its profile applies to every query, and they never change how a schema compiles. No call
 * reads a server's version or its changed settings itself: that discovery is a recorded gap in this
 * generation, so a caller that wants a server's settings passes them explicitly, in a server
 * profile, through `chs_set_defaults` or in each call's settings.
 *
 * Documents. Every output document is valid JSON that a stock parser reads: every ClickHouse
 * rendering (a stored value, an input value, an engine's row) is a JSON string, a number written
 * bare is within plus or minus 2^53 (anything larger is a string), and there is never a bare `inf`,
 * `-inf` or `nan`. Every column entry of a row carries `null`, the library's verdict that the
 * stored value is NULL, poisoned cells included.
 *
 * Byte strings in JSON. Every data-derived string a JSON document carries is a byte string: a
 * column name, a value's rendering, a type (an Enum label or a named Tuple element comes from the
 * caller's DDL), SQL text, and a message (ClickHouse's messages quote input bytes). One rule
 * carries them all, names included, in every output document and in the input column list. The
 * member `F` is a JSON string when the bytes are valid UTF-8, a NUL written as the escape `\u0000`
 * as RFC 8259 allows. Otherwise the member `F_b64` holds the raw bytes in standard base64, padded.
 * The two are never both present, and a member that names an entry (a column name) is always
 * present in one of its two forms. So every document is valid UTF-8 JSON that a strict parser
 * reads, and no byte is lost or replaced. Where a list or a map would hold a bare data-derived
 * string, it holds an object instead, so the rule applies to that object's members: a list of names
 * is a list of `{name}` or `{name_b64}` objects, and an engine's row is a list of cells. Each
 * document lists its data-derived fields (`byte_fields` in the reference); a binding decodes each
 * one to bytes and never assumes UTF-8. A server accepts every kind of name (measured on every
 * supported line). The byte-returning accessors (`chs_error_message`, `chs_error_column`,
 * `chs_error_ch_name`) and the export bytes are raw buffers, not JSON, and are not affected.
 *
 * String values. Every entry that reports a stored value (a row's `cols`, `computed`, an engine
 * row's cells, `storage_transforms`) carries `stored` or `stored_b64`, which is always ClickHouse's
 * rendering of the value. For a scalar `String` or `FixedString` value, including one inside
 * `Nullable` or `LowCardinality`, the entry also carries `value_b64`, the value's raw bytes in
 * standard base64, whenever the value is not NULL, whether or not the bytes are valid UTF-8. A
 * value nested in another type (`Array(String)`, `Map`, `Tuple`, and the like) carries no
 * `value_b64`: that is a recorded gap in this generation, and its rendering is the only form.
 *
 * Input values. A JSON input (`settings`, `query_params`, an input document) cannot carry a value
 * that is not valid UTF-8 in this generation. The workaround is to inline the value in the SQL as
 * `unhex('<hex>')`, built from hex digits only, which keeps it injection-safe because hex digits
 * cannot break out of the quoted literal. A later version would add an object form, `{"<key>":
 * {"b64": ...}}`, never a `<key>_b64` member, which could collide with a real key.
 *
 * Input documents. A counted input whose content is `input:<name>` is a JSON object that the
 * library validates against the document of that name (rule r1). A key the document does not define
 * is `CHS_INVALID_ARGUMENT`, naming the key, and so is a document that is not a JSON object or a
 * member of the wrong JSON type. Length 0 is `{}`, and a repeated member keeps its last value. The
 * library never ignores a key, so a caller that sets an option a build does not implement is told
 * so instead of silently getting the old behavior.
 *
 * Teardown. `chs_shutdown` stops what `chs_initialize` started. A loader never unloads a library:
 * unloading or initializing an image again in one process is unsupported.
 */
#ifndef CHTYPES_V2_H
#define CHTYPES_V2_H

#ifdef CHTYPES_H
#error "include/chtypes.h (ABI v1) and include/v2/chtypes.h (ABI v2) declare the same chs_* names: include one per translation unit"
#endif

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Every chs_* entry point is exported with default visibility; the library exports nothing else. */
#ifndef CHS_API
#define CHS_API __attribute__((visibility("default")))
#endif

/* ------------------------------------------------------------------------------------- identity */

/*
 * The ABI generation: what chs_abi_version() returns. A loader refuses a library whose answer
 * differs.
 */
#define CHS_ABI_VERSION 2

/*
 * `sha256:` and 64 lowercase hex digits: sha256 over the RFC 8785 canonical form of
 * spec/abi-v2/abi.json. chs_build_info()'s `abi_fingerprint` is this macro, copied; a loader
 * compares the two byte for byte and refuses any difference.
 */
#define CHS_ABI_FINGERPRINT "sha256:28c7445ce6b5c6d0ae33177fd60eb7b3b5654a966c842b8d812aea622824dc72"

/*
 * UNSTABLE: spec/abi-v2/abi.json declares `stability` "unstable". Generation 2 is still being
 * designed, so CHS_ABI_FINGERPRINT moves with every change to the description until the lock. A
 * library and a binding work together only when both were built from the same fingerprint; nothing
 * built from an unstable description is a release.
 */

/* ------------------------------------------------------------------------------- thread classes */

/*
 * Every function below names its thread class: what a caller may run at the same time as it.
 *
 * - any: reads no caller handle: safe from any thread, concurrently with any call.
 * - shared: reads one or more caller handles and never changes them: safe concurrently with any
 *   call, on the same handles too, except a free of one of those handles.
 * - handle_serial: a free: releases the caller's reference, so it must not overlap any other call
 *   that uses the same handle.
 * - process_once: process setup, once per image: the first call sets process state, and a repeat
 *   with the same arguments is a no-op that is safe at any time.
 * - process_serial: process-level: must not overlap any other call into the same library image.
 */

/* ------------------------------------------------------------------------- byte strings in JSON */

/*
 * Every data-derived string a JSON document carries (a column name, a value's rendering, a type,
 * SQL text, a message) is a byte string, so one rule carries them all. The member F is a JSON
 * string when the bytes are valid UTF-8 (a NUL written as the JSON escape for U+0000), and
 * otherwise the member F_b64 holds the raw bytes in standard base64 with padding. Never both; a
 * member that names an entry (a column name) is always present in one of its two forms. Every
 * document is therefore valid UTF-8 JSON. Where a list or a map would hold a bare data-derived
 * string, it holds an object instead, so the rule applies to its members. An entry that reports a
 * stored value carries `value_b64`, the raw bytes of a scalar String or FixedString value, beside
 * its rendering. A byte-returning accessor such as chs_error_column returns the raw bytes instead.
 *
 * The data-derived fields, by document:
 *
 * - schema_description: columns[].name, columns[].type, columns[].default_expression,
 *   server.filter_declined_settings[].name, replicated.zookeeper_path, replicated.replica_name.
 * - row: err, verdict_err, partition_id, unknown_fields[].name, unsupported_settings[].name,
 *   cols[].name, cols[].type, cols[].base, cols[].input, cols[].stored, cols[].ref,
 *   cols[].ref_type, cols[].wire, computed[].name, computed[].stored, transformed[].column,
 *   transformed[].input, transformed[].stored.
 * - batch: err, export_declined, rows[].err, rows[].verdict_err, rows[].partition_id,
 *   rows[].unknown_fields[].name, rows[].unsupported_settings[].name, rows[].cols[].name,
 *   rows[].cols[].type, rows[].cols[].base, rows[].cols[].input, rows[].cols[].stored,
 *   rows[].cols[].ref, rows[].cols[].ref_type, rows[].cols[].wire, rows[].computed[].name,
 *   rows[].computed[].stored, rows[].transformed[].column, rows[].transformed[].input,
 *   rows[].transformed[].stored, engine_rows[][].name, engine_rows[][].stored,
 *   storage_transforms[].column, storage_transforms[].stored, at_merge[].column, at_merge[].stored,
 *   transformed[].column, transformed[].input, transformed[].stored, unsupported_settings[].name,
 *   framing.header.names[].name.
 * - filter_result: err, unsupported_settings[].name, errors[].err.
 * - discovery: columns[].name, columns[].type, columns[].default_kind,
 *   columns[].default_expression, columns[].declaration, columns_sql.
 */

/* ------------------------------------------------------------------------------ input documents */

/*
 * An input whose content is an input document is a JSON object the library validates (rule r1): a
 * key the document does not define is CHS_INVALID_ARGUMENT, naming the key, and so is a document
 * that is not a JSON object or a member of the wrong JSON type. Length 0 is `{}`. An options
 * document is the one a growable function takes the inputs it gains in.
 */

/*
 * input:server_profile: A server's profile, `{"timezone": "<zone>", "settings": {"<name>":
 * "<value>"}, "macros": {"<name>": "<value>"}}`. Every member is optional, so `{}` describes a
 * server with nothing known about it. The profile holds server facts only, in the shape a server's
 * own tables report them, so a caller can fill it from the server it describes; library knobs go in
 * `chs_server_create`'s options instead.
 *
 * - `timezone`: the server's own zone, the zone its tables bind. An empty string, or no member,
 *   means the image zone. The name is validated by ClickHouse's own `DateLUT`, which reads the
 *   library host's time zone database.
 * - `settings`: the settings the server's profile applies to every query, each value a JSON string,
 *   never rewritten. The library accepts exactly what the server's own SET check accepts.
 *   `session_timezone` here is the default session zone of the server's user.
 * - `macros`: the server's macros, as its `system.macros` lists them (`macro`, `substitution`).
 *   Absent, they are unknown; present, even as `{}`, they are the complete set (see
 *   `chs_server_create`). A macro name that ClickHouse's own macro reader refuses (for example
 *   `a.b`) is refused with `CHS_INVALID_ARGUMENT` naming it.
 *
 * An input document of fixed purpose. Its members, as JSON Schema:
 *
 * ```json
 * {
 *   "type": "object",
 *   "additionalProperties": false,
 *   "properties": {
 *     "timezone": {"type": "string"},
 *     "settings": {"type": "object", "additionalProperties": {"type": "string"}},
 *     "macros": {
 *       "type": "object",
 *       "propertyNames": {"minLength": 1},
 *       "additionalProperties": {"type": "string"}
 *     }
 *   }
 * }
 * ```
 */

/*
 * input:server_options: The options of `chs_server_create` (rule r1). It defines no member yet, so
 * `{}` (or length 0) is the only valid document, and any key is `CHS_INVALID_ARGUMENT`, naming the
 * key. A library knob that is not a server fact lands here, as a new member.
 *
 * An options document (rule r1). Its members, as JSON Schema:
 *
 * ```json
 * {"type": "object", "additionalProperties": false}
 * ```
 */

/*
 * input:schema_options: The options of `chs_schema_create` (rule r1). It defines no member yet, so
 * `{}` (or length 0) is the only valid document, and any key is `CHS_INVALID_ARGUMENT`, naming the
 * key. A choice about how one statement is compiled lands here, as a new member: for example,
 * compiling a server's own `create_table_query`, read back from the server, rather than a caller's
 * CREATE.
 *
 * An options document (rule r1). Its members, as JSON Schema:
 *
 * ```json
 * {"type": "object", "additionalProperties": false}
 * ```
 */

/* -------------------------------------------------------------------------------------- handles */

/*
 * chs_buf: An owned, immutable byte buffer: every output of the library. Read it with
 * `chs_buf_data` and `chs_buf_len`; the bytes are exactly what the library produced, with no
 * terminator and no encoding promise beyond what the producing parameter's content says.
 *
 * Freed with chs_buf_free.
 */
typedef struct chs_buf chs_buf;

/*
 * chs_error: The error a fallible call reports when its status is not `CHS_OK`: the status,
 * ClickHouse's own error code and name, a message and the column concerned. Created only by the
 * library, through a call's `err` out-parameter.
 *
 * Freed with chs_error_free.
 */
typedef struct chs_error chs_error;

/*
 * chs_server: One ClickHouse server, as a profile describes it: its `timezone`, the settings its
 * profile applies to every query, and its `<macros>`. Immutable once created, so any number of
 * threads may use it at once. A schema created on it holds a counted reference to it, so the caller
 * may free the server whenever it likes.
 *
 * Freed with chs_server_free.
 */
typedef struct chs_server chs_server;

/*
 * chs_schema: A compiled table: the columns, engine, keys, TTL, settings and constraints of exactly
 * one `CREATE TABLE` statement, on the server it was created on, if any. Immutable once created, so
 * any number of threads may use it at once.
 *
 * Freed with chs_schema_free. Holds a reference to its chs_server, so any free order is safe.
 */
typedef struct chs_schema chs_schema;

/*
 * chs_filter: A compiled boolean SQL expression over a schema's columns, with its query parameters
 * bound. It holds a counted reference to its schema, so the schema stays alive for as long as the
 * filter does, whatever order the caller frees them in.
 *
 * Freed with chs_filter_free. Holds a reference to its chs_schema, so any free order is safe.
 */
typedef struct chs_filter chs_filter;

/*
 * chs_block: A body parsed once under a schema, for evaluating many filters without parsing again.
 * Like a filter, it holds a counted reference to its schema.
 *
 * Freed with chs_block_free. Holds a reference to its chs_schema, so any free order is safe.
 */
typedef struct chs_block chs_block;

/* ---------------------------------------------------------------------------------------- enums */

/*
 * chs_status: The verdict of every fallible call, in five values whose numbering is frozen.
 *
 * - `CHS_OK`: the call succeeded and its outputs are set.
 * - `CHS_REJECTED`: ClickHouse's own refusal, with its own code, name and message, which a server
 *   would also give.
 * - `CHS_DECLINED`: this build will not answer; a server might accept. Never scored as agreement.
 * - `CHS_INVALID_ARGUMENT`: caller misuse, such as a NULL pointer with a nonzero length, a
 *   wrong-kind, freed or cross-library handle, or a NULL required out-parameter.
 * - `CHS_INTERNAL`: a guarded exception inside the library, which is a library bug.
 *
 * The set is closed within this generation: any new condition maps onto one of these five. A
 * binding maps each status to one error class (`spec/abi-v2/sdk.json`), and treats a value outside
 * the set as an internal error naming it, whose status is that value's `unknown(n)` (rule r3).
 *
 * Closed and frozen: no value is added within this generation, and none is renumbered or removed.
 */
typedef int32_t chs_status;
#define CHS_OK               0
#define CHS_REJECTED         1
#define CHS_DECLINED         2
#define CHS_INVALID_ARGUMENT 3
#define CHS_INTERNAL         4

/*
 * chs_format: The input and export formats, numbered as they have been since the first release; the
 * numbers are frozen and a binding passes the integer. `ch_name` is ClickHouse's own name for the
 * format, which is how `chs_build_info` lists the formats a build supports. Being in this enum
 * never proves a build supports a format: the build says so in its `capabilities`.
 *
 * Frozen: no value is renumbered or removed.
 */
typedef int32_t chs_format;
#define CHS_JSON_EACH_ROW                                0  /* ch_name: JSONEachRow */
#define CHS_CSV                                          1  /* ch_name: CSV */
#define CHS_TSV                                          2  /* ch_name: TSV */
#define CHS_VALUES                                       3  /* ch_name: Values */
#define CHS_JSON_COMPACT_EACH_ROW                        4  /* ch_name: JSONCompactEachRow */
#define CHS_ROW_BINARY                                   5  /* ch_name: RowBinary */
#define CHS_ROW_BINARY_WITH_DEFAULTS                     6  /* ch_name: RowBinaryWithDefaults */
#define CHS_ROW_BINARY_WITH_NAMES_AND_TYPES_AND_DEFAULTS 7  /* ch_name: RowBinaryWithNamesAndTypesAndDefaults */
#define CHS_NATIVE                                       8  /* ch_name: Native */
#define CHS_BUFFERS                                      9  /* ch_name: Buffers */
#define CHS_CSV_WITH_NAMES                               10 /* ch_name: CSVWithNames */
#define CHS_TSV_WITH_NAMES                               11 /* ch_name: TSVWithNames */

/* ------------------------------------------------------------------------------------ constants */

/*
 * CHS_ABI_REVISION_TOMBSTONE: What `chs_abi_revision` always returns: 1001, outside every revision
 * a released v0 binding speaks.
 */
#define CHS_ABI_REVISION_TOMBSTONE 1001

/*
 * CHS_EXPORT_NONE: The `export_format` of a batch preview that exports nothing.
 */
#define CHS_EXPORT_NONE (-1)

/*
 * CHS_DOC_VALUES: A `doc_flags` bit: the per-row documents carry each column's stored value and
 * provenance.
 */
#define CHS_DOC_VALUES 1u

/*
 * CHS_DOC_TRANSFORMS: A `doc_flags` bit: the per-row documents carry the transformations the
 * library detected.
 */
#define CHS_DOC_TRANSFORMS 2u

/*
 * CHS_DOC_DEFAULTS: A `doc_flags` bit: the per-row documents carry the values the library computed
 * from DEFAULT and MATERIALIZED expressions.
 */
#define CHS_DOC_DEFAULTS 4u

/*
 * CHS_DOC_ALL: Every `doc_flags` bit. A bit outside it is refused.
 */
#define CHS_DOC_ALL 7u

/* ------------------------------------------------------------------------------------ functions */

/*
 * chs_abi_version: The ABI generation this library implements: always 2 for this header. A loader
 * resolves and calls it right after opening the library. A library without the symbol is not a
 * chtypes ABI artifact of generation 1 or later, and any other value is refused, naming both
 * values. An absent handshake symbol other than this one is refused as `missing_symbol:<name>`
 * instead, at whichever step first resolves it — only this symbol's absence means the library is
 * not such an artifact at all.
 *
 * Class: handshake. Thread: any.
 */
CHS_API int32_t chs_abi_version(void);

/*
 * chs_build_info: What this library is, as static, NUL-terminated, ASCII-only JSON in the image's
 * read-only data: never NULL, never freed, the same bytes on every call, and callable straight
 * after opening the library. Its fields are listed under `build_info` in the reference, and
 * `abi_fingerprint` is `CHS_ABI_FINGERPRINT` as the library was built, copied, never recomputed.
 *
 * `capabilities` is read from the build itself, never from a version number: `input_formats` and
 * `export_formats` by ClickHouse's own format names from the build's FormatFactory, `doc_flags` as
 * the document groups it honors, and `features`, an open list of build-level features, where a new
 * feature is a new value and never a new field. `default_generators` in `features` means the
 * library fills admitted generator DEFAULTs and the caller inserts the library's output
 * (`default_generated` under `value_src`).
 *
 * A loader parses it (ASCII only, duplicate keys refused, `schema` equal to 1, every required field
 * of its type), refuses when `abi_fingerprint` differs from its own compiled-in
 * `CHS_ABI_FINGERPRINT` byte for byte, and then compares the fields listed in
 * `spec/abi-v2/sdk.json` (`cross_check`) with the verified signed statement it fetched the library
 * under, refusing on the first mismatch and naming the field. That comparison is mandatory. The
 * file's own size, digest and glibc floor are not in it, because the file cannot carry facts
 * measured on itself; they are in the signed statement.
 *
 * Class: handshake. Thread: any.
 */
CHS_API const char *chs_build_info(void);

/*
 * chs_clickhouse_version: The ClickHouse release this library was built from, spelled as every v0
 * library spelled it (for example `26.8.15.10-lts`): static, never freed. It keeps its v0 signature
 * and spelling so a v0 binding reaches its own refusal. A binding of generation 1 or later reads
 * `clickhouse_version` from `chs_build_info` instead.
 *
 * Class: handshake. Thread: any.
 */
CHS_API const char *chs_clickhouse_version(void);

/*
 * chs_abi_revision: The v0 tombstone. It always returns `CHS_ABI_REVISION_TOMBSTONE` (1001). It
 * must never be removed, and its name must never be given another meaning.
 *
 * A sweep of every released binding (every minor from 0.1 to 0.5, in all four languages; [the CI
 * run](https://github.com/Wave-RF/chtypes/actions/runs/36939764841)) measured why: each one calls
 * this symbol whenever it exists and refuses cleanly, naming both numbers, when it returns a
 * revision other than its own, but treats a MISSING symbol as "revision 0, predates the probe" and
 * goes on to call `chs_init`. So this tombstone is what turns every v0 binding away before it can
 * reach any other symbol, and `gen.py --check` refuses a description that reuses a v0 name without
 * it. A binding of generation 1 or later never calls it; the loader resolves it only to prove it is
 * present.
 *
 * Class: tombstone. Thread: any. Always returns CHS_ABI_REVISION_TOMBSTONE (1001).
 */
CHS_API int chs_abi_revision(void);

/*
 * chs_buf_data: The buffer's bytes. The pointer may be NULL when `chs_buf_len` is 0, and a binding
 * never dereferences it then. A NULL, freed, wrong-kind or cross-library buffer gives NULL.
 *
 * Class: api. Thread: shared. The pointer is borrowed from `buf` and valid until it is freed; copy
 * before freeing.
 *
 * - `buf`: required.
 */
CHS_API const uint8_t *chs_buf_data(const chs_buf *buf);

/*
 * chs_buf_len: The buffer's length in bytes. A NULL, freed, wrong-kind or cross-library buffer
 * gives 0.
 *
 * Class: api. Thread: shared.
 *
 * - `buf`: required.
 */
CHS_API size_t chs_buf_len(const chs_buf *buf);

/*
 * chs_buf_free: Releases the caller's reference to a buffer. Freeing NULL does nothing.
 *
 * Class: api. Thread: handle_serial.
 *
 * - `buf`: may be NULL.
 */
CHS_API void chs_buf_free(chs_buf *buf);

/*
 * chs_error_status: The error's status, never `CHS_OK` for an error a call set. A NULL, freed,
 * wrong-kind or cross-library error gives `CHS_INVALID_ARGUMENT`.
 *
 * Class: api. Thread: shared.
 *
 * - `error`: required.
 */
CHS_API chs_status chs_error_status(const chs_error *error);

/*
 * chs_error_ch_code: ClickHouse's own error code, nonzero only when the status is `CHS_REJECTED`,
 * and 0 otherwise or for an invalid error.
 *
 * Class: api. Thread: shared.
 *
 * - `error`: required.
 */
CHS_API int32_t chs_error_ch_code(const chs_error *error);

/*
 * chs_error_ch_name: A new buffer holding the name this build's vendored error table gives the
 * code, the name a server prints after the code; empty when the build has none or the status is not
 * `CHS_REJECTED`. Like the other two text accessors, it returns NULL only for a NULL or invalid
 * error.
 *
 * Class: api. Thread: shared. Returns a new chs_buf the caller owns and frees with chs_buf_free;
 * its content is guaranteed ASCII; NULL only for a NULL or invalid argument.
 *
 * - `error`: required.
 */
CHS_API chs_buf *chs_error_ch_name(const chs_error *error);

/*
 * chs_error_message: A new buffer holding the message: ClickHouse's own text, verbatim, for
 * `CHS_REJECTED`, and the library's explanation otherwise. A message may quote input bytes, so it
 * is a byte string, not text.
 *
 * Class: api. Thread: shared. Returns a new chs_buf the caller owns and frees with chs_buf_free;
 * its content is a ClickHouse message: may quote input bytes, so may carry any byte; NULL only for
 * a NULL or invalid argument.
 *
 * - `error`: required.
 */
CHS_API chs_buf *chs_error_message(const chs_error *error);

/*
 * chs_error_column: A new buffer holding the name of the column the error concerns, as raw bytes,
 * empty when there is none. A column name is a byte string: NUL and invalid UTF-8 are legal in a
 * name.
 *
 * Class: api. Thread: shared. Returns a new chs_buf the caller owns and frees with chs_buf_free;
 * its content is a ClickHouse column name: NUL and invalid UTF-8 are legal, so never assume UTF-8;
 * NULL only for a NULL or invalid argument.
 *
 * - `error`: required.
 */
CHS_API chs_buf *chs_error_column(const chs_error *error);

/*
 * chs_error_free: Releases the caller's reference to an error. Freeing NULL does nothing.
 *
 * Class: api. Thread: handle_serial.
 *
 * - `error`: may be NULL.
 */
CHS_API void chs_error_free(chs_error *error);

/*
 * chs_live_handles: A JSON document counting the live handles of each kind this image has made,
 * taken before the document's own buffer exists. A test abandons handles, lets its runtime collect
 * them and then asserts every count is zero, which is how all four bindings prove their finalizers
 * release everything.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `out`: receives the JSON document `live_handles`, owned by the caller, freed with chs_buf_free;
 *   required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_live_handles(chs_buf **out, chs_error **err);

/*
 * chs_error_codes: ClickHouse's own error-code table for this build, as a JSON array of `{"code",
 * "name"}` in ascending code order: a passthrough over the vendored table, never a copy. The table
 * belongs to the build, and one number can name different errors on two ClickHouse lines, so a
 * caller that needs several lines asks each library. The name is v0's, with the v1 call shape; the
 * tombstone keeps every v0 binding from reaching it.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `out`: receives the JSON document `error_code_table`, owned by the caller, freed with
 *   chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_error_codes(chs_buf **out, chs_error **err);

/*
 * chs_registered_families: Every type family in this build's own type registry, one per line. A
 * tooling export for the artifact producer's build gates: no binding wraps it, and a loader
 * resolves it only for presence.
 *
 * Class: tooling. Thread: process_serial. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT,
 * CHS_INTERNAL.
 *
 * - `out`: receives guaranteed ASCII, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_registered_families(chs_buf **out, chs_error **err);

/*
 * chs_function_flags: A tab-separated audit of every registered function's volatility flags, one
 * function per line, read off this build's own registry. A tooling export for the artifact
 * producer's build gates, which derive the statelessness evidence from it; no binding wraps it.
 *
 * Class: tooling. Thread: process_serial. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT,
 * CHS_INTERNAL.
 *
 * - `out`: receives guaranteed ASCII, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_function_flags(chs_buf **out, chs_error **err);

/*
 * chs_reference_type: The widened reference type this build pairs with a type expression. A tooling
 * export; no binding wraps it.
 *
 * Class: tooling. Thread: process_serial. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `type_expr`, `type_expr_len`: SQL text (a statement, an expression, a type, a quoted name or
 *   literal): may carry any byte; length 0 is none, and the pointer may then be NULL.
 * - `out`: receives SQL text (a statement, an expression, a type, a quoted name or literal): may
 *   carry any byte, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_reference_type(
    const uint8_t *type_expr,
    size_t type_expr_len,
    chs_buf **out,
    chs_error **err);

/*
 * chs_initialize: Sets this image's server zone, once per process: the zone every compiled type
 * binds, and the zone a call without its own `session_timezone` runs in. `timezone` is counted
 * bytes, and length 0 means `UTC`. The name is validated by ClickHouse's own `DateLUT`, so a name
 * it cannot load is `CHS_REJECTED` with `DateLUT`'s own code and message. A second call with the
 * same spelling is a no-op that answers `CHS_OK`; a different spelling is `CHS_INVALID_ARGUMENT`,
 * naming both. The spelling is compared byte for byte and never canonicalized, because it is
 * observable: `timezoneOf` over a column reports the image zone exactly as spelled.
 *
 * The zone is process state, not a per-call parameter, because ClickHouse's own MergeTree code
 * reads the server zone directly (`DateLUT::serverTimezoneInstance`). A per-call zone is the
 * `session_timezone` setting instead. A loader calls this once, after the handshake checks and
 * before any other call; the list of type families the build must refuse is embedded when the
 * library is built, so nothing else is passed in.
 *
 * Class: api. Thread: process_once. Returns one of: CHS_OK, CHS_REJECTED, CHS_INVALID_ARGUMENT,
 * CHS_INTERNAL.
 *
 * - `timezone`, `timezone_len`: a time zone name, validated by ClickHouse's own DateLUT; length 0
 *   means UTC; length 0 is none, and the pointer may then be NULL.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_initialize(const uint8_t *timezone, size_t timezone_len, chs_error **err);

/*
 * chs_set_defaults: Seeds the settings every later call starts from, as a JSON object whose values
 * are JSON strings (a binding never rewrites a value, a boolean included). Each successful call
 * replaces the previous defaults whole. A setting name the server would refuse is refused here,
 * with ClickHouse's own code and message, and nothing is committed. `session_timezone` here is the
 * default zone for later calls; it does not change the image zone that compiled types bind.
 *
 * Setup only. The defaults are immutable once this image has created its first `chs_schema` (a
 * filter or a block needs one): from then on the call changes nothing and answers
 * `CHS_INVALID_ARGUMENT`. No call ever reads defaults that change under it, so no binding needs a
 * lock around them.
 *
 * Class: api. Thread: process_serial. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `settings`, `settings_len`: a JSON object whose values are JSON strings (settings, query
 *   parameters); length 0 is none, and the pointer may then be NULL.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_set_defaults(const uint8_t *settings, size_t settings_len, chs_error **err);

/*
 * chs_shutdown: Stops what `chs_initialize` started (its background threads) and joins them. It is
 * idempotent and safe before `chs_initialize`. After it, no call is valid except `chs_shutdown`
 * again. Unloading the library, or initializing it again in the same process, is unsupported: a
 * loader never unloads a library.
 *
 * Class: api. Thread: process_serial.
 */
CHS_API void chs_shutdown(void);

/*
 * chs_type_validate: Parses one type expression with ClickHouse's own parser and returns its
 * canonical spelling, or ClickHouse's own refusal.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `type_expr`, `type_expr_len`: SQL text (a statement, an expression, a type, a quoted name or
 *   literal): may carry any byte; length 0 is none, and the pointer may then be NULL.
 * - `out`: receives SQL text (a statement, an expression, a type, a quoted name or literal): may
 *   carry any byte, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_type_validate(
    const uint8_t *type_expr,
    size_t type_expr_len,
    chs_buf **out,
    chs_error **err);

/*
 * chs_back_quote: A name quoted the way ClickHouse's own `backQuote` quotes it: always quoted,
 * every special byte escaped. A passthrough over the vendored function, and named after it; the
 * name is a byte string.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `name`, `name_len`: a ClickHouse column name: NUL and invalid UTF-8 are legal, so never assume
 *   UTF-8; length 0 is none, and the pointer may then be NULL.
 * - `out`: receives SQL text (a statement, an expression, a type, a quoted name or literal): may
 *   carry any byte, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_back_quote(
    const uint8_t *name,
    size_t name_len,
    chs_buf **out,
    chs_error **err);

/*
 * chs_back_quote_if_needed: A name quoted only where this build's own `backQuoteIfNeed` says it
 * must be. Which names stay bare is a property of the ClickHouse release, so a caller that needs
 * one answer for several releases asks each library.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `name`, `name_len`: a ClickHouse column name: NUL and invalid UTF-8 are legal, so never assume
 *   UTF-8; length 0 is none, and the pointer may then be NULL.
 * - `out`: receives SQL text (a statement, an expression, a type, a quoted name or literal): may
 *   carry any byte, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_back_quote_if_needed(
    const uint8_t *name,
    size_t name_len,
    chs_buf **out,
    chs_error **err);

/*
 * chs_quote_string: A byte string spelled as a ClickHouse string literal by the vendored
 * `quoteString`. The input may contain NUL; the answer escapes it.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `text`, `text_len`: arbitrary bytes: a body, a string value, an export; length 0 is none, and
 *   the pointer may then be NULL.
 * - `out`: receives SQL text (a statement, an expression, a type, a quoted name or literal): may
 *   carry any byte, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_quote_string(
    const uint8_t *text,
    size_t text_len,
    chs_buf **out,
    chs_error **err);

/*
 * chs_server_create: Describes one ClickHouse server, from a profile document
 * (`input:server_profile`): its `timezone`, judged by ClickHouse's own `DateLUT`; its `settings`,
 * judged by the server's own SET check; and its `macros`, read by ClickHouse's own `Macros`
 * configuration reader, as a server reads `<macros>`. Every member is optional, and a member the
 * profile omits is not described: the image zone applies, there is no server settings layer, and
 * the server's macros are unknown. `options` (`input:server_options`) defines no member yet.
 *
 * Everything is validated here, once, and the server never changes after it. A key the profile or
 * the options document does not define is `CHS_INVALID_ARGUMENT`, naming the key, and so is a
 * document that is not a JSON object, a member of the wrong JSON type, a NUL in the zone, an empty
 * macro name, a NUL in a macro's name or value, or a macro set that ClickHouse's own reader does
 * not read back exactly as given (a `.` in a name is one). A zone `DateLUT` cannot load is
 * `CHS_REJECTED` with `DateLUT`'s own code and message (36, BAD_ARGUMENTS). A setting the server's
 * SET check refuses is `CHS_REJECTED` with the server's own code and message: 115 (UNKNOWN_SETTING)
 * for a name the server does not know, a library knob such as a `chtypes_*` setting included,
 * because a server's profile holds ClickHouse settings only. Nothing is created on any refusal.
 *
 * `CHS_DECLINED` is reserved: a build that will not describe a profile declines it, which is never
 * a wrong answer. The one decline foreseen is a setting outside the set that shapes an input, at a
 * value other than its default, once that set is generated from the vendored source.
 *
 * The macros are the server's whole `system.macros` when `macros` is present, even as `{}`: a macro
 * a Replicated engine's arguments name that the set lacks is then the server's own refusal
 * (`CHS_REJECTED`, 139, NO_ELEMENTS_IN_CONFIG). When `macros` is absent the server's macros are
 * unknown, and a schema whose engine reads one is declined, as it is without a server. A build that
 * validates a profile's macros but does not yet apply them declines such a schema in both cases.
 *
 * A setting this build's filters do not honor in a WHERE is no decline here: the call computes the
 * server's `filter_declined_settings` (`schema_description`) and succeeds, and so does
 * `chs_schema_create` on the server, because a profile never changes a schema compile.
 *
 * The call reads no defaults and leaves `chs_set_defaults`' latch open. Like every call that is not
 * the handshake, it is valid only after `chs_initialize`.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL. Growable (rule r1): an input it gains is a new member of its
 * options document, `options`.
 *
 * - `profile`, `profile_len`: the input document `server_profile`; length 0 is `{}`, and the
 *   pointer may then be NULL.
 * - `options`, `options_len`: the input document `server_options`; length 0 is `{}`, and the
 *   pointer may then be NULL.
 * - `out`: receives a new chs_server, owned by the caller, freed with chs_server_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_server_create(
    const uint8_t *profile,
    size_t profile_len,
    const uint8_t *options,
    size_t options_len,
    chs_server **out,
    chs_error **err);

/*
 * chs_server_free: Releases the caller's reference to a server. Schemas created on it keep it
 * alive. Freeing NULL does nothing.
 *
 * Class: api. Thread: handle_serial.
 *
 * - `server`: may be NULL.
 */
CHS_API void chs_server_free(chs_server *server);

/*
 * chs_schema_create: Compiles exactly one `CREATE TABLE` statement (columns, engine, keys, TTL,
 * settings and constraints) with ClickHouse's own parser and the checks a server's CREATE runs, on
 * `server`, under a profile of settings given as a JSON object of string values. A trailing
 * semicolon is allowed. A second statement is refused the way ClickHouse's own parser refuses one
 * in a single query (`CHS_REJECTED`, with its code and message), and a statement of any other kind
 * is `CHS_INVALID_ARGUMENT`.
 *
 * `server` is the server the table is on (`chs_server_create`), or NULL. On a server, the schema's
 * home zone is the server's `timezone`: its zone-less `DateTime` and `DateTime64` columns bind it,
 * as a restarted server binds its own, and every call on the schema that names no
 * `session_timezone` runs in it. The server's `settings` layer under the schema's own, and a
 * Replicated engine's ZooKeeper path and replica name expand the server's `macros`. With `server`
 * NULL the schema is on the image's own server, exactly as before servers existed: the image zone,
 * no server settings layer, and macros unknown. A freed server, a handle of another kind or a
 * server from another library image is `CHS_INVALID_ARGUMENT`. The schema holds a counted reference
 * to its server, so the caller may free the server at any time.
 *
 * `timezone()` (and its alias `timeZone()`) in a DEFAULT, MATERIALIZED or CHECK expression is
 * admitted on a schema created on a server whose profile names a `timezone`. On a server schema,
 * `timezone()` answers the server's zone when no session zone is in force; a session zone that
 * would change the answer is declined (named in `unsupported_settings`). That applies equally to a
 * profile whose `settings` carry `session_timezone`. On a schema with no server, or a server whose
 * profile names no `timezone`, it stays refused as a server constant. `serverTimezone()` is refused
 * on every schema.
 *
 * `options` (`input:schema_options`) defines no member yet, so any key in it is
 * `CHS_INVALID_ARGUMENT`, naming the key.
 *
 * A build that does not yet compile on a server declines a non-NULL `server`, and a schema whose
 * compile needs its server's zone is declined on a host thread that already runs a ClickHouse query
 * of its own. Each is `CHS_DECLINED`, which is never a wrong answer.
 *
 * The result is immutable: nothing changes a schema after this call, so it replaces v0's
 * column-list compile and its engine, TTL and partition-key setters, and any number of threads may
 * use it at once. Its types bind its home zone, never the `session_timezone` in its settings, which
 * is the zone of this call and of the later calls on the schema that name none of their own.
 *
 * Class: api. Thread: shared. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL. Growable (rule r1): an input it gains is a new member of its
 * options document, `options`.
 *
 * - `server`: may be NULL.
 * - `create_table`, `create_table_len`: SQL text (a statement, an expression, a type, a quoted name
 *   or literal): may carry any byte; length 0 is none, and the pointer may then be NULL.
 * - `settings`, `settings_len`: a JSON object whose values are JSON strings (settings, query
 *   parameters); length 0 is none, and the pointer may then be NULL.
 * - `options`, `options_len`: the input document `schema_options`; length 0 is `{}`, and the
 *   pointer may then be NULL.
 * - `out`: receives a new chs_schema, owned by the caller, freed with chs_schema_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_schema_create(
    const chs_server *server,
    const uint8_t *create_table,
    size_t create_table_len,
    const uint8_t *settings,
    size_t settings_len,
    const uint8_t *options,
    size_t options_len,
    chs_schema **out,
    chs_error **err);

/*
 * chs_schema_free: Releases the caller's reference to a schema. Filters and blocks made from it
 * keep it alive. Freeing NULL does nothing.
 *
 * Class: api. Thread: handle_serial.
 *
 * - `schema`: may be NULL.
 */
CHS_API void chs_schema_free(chs_schema *schema);

/*
 * chs_schema_describe: A JSON document describing the schema's columns, owned by the caller; it
 * replaces v0's borrowed column accessors.
 *
 * Class: api. Thread: shared. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `schema`: required.
 * - `out`: receives the JSON document `schema_description`, owned by the caller, freed with
 *   chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_schema_describe(const chs_schema *schema, chs_buf **out, chs_error **err);

/*
 * chs_preview_row: Validates and coerces one row of `body` under the schema, as a server's INSERT
 * would, and returns the row's document. `columns` is the INSERT column list, a JSON array of name
 * objects (`{name}` or `{name_b64}`), and empty for none. `session_timezone` in `settings` is this
 * call's zone.
 *
 * An INSERT whose input block has no column at all (every insertable column EPHEMERAL, and no
 * column list) is declined: a server answers it (code 90, EMPTY_LIST_OF_COLUMNS_PASSED) from a
 * statement inside its INSERT interpreter that the library cannot call, and a decline is never a
 * wrong answer.
 *
 * Class: api. Thread: shared. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `schema`: required.
 * - `body`, `body_len`: arbitrary bytes: a body, a string value, an export; length 0 is none, and
 *   the pointer may then be NULL.
 * - `settings`, `settings_len`: a JSON object whose values are JSON strings (settings, query
 *   parameters); length 0 is none, and the pointer may then be NULL.
 * - `columns`, `columns_len`: a JSON array of column names, each an object carrying the name as
 *   byte_strings says; length 0 is none, and the pointer may then be NULL.
 * - `out`: receives the JSON document `row`, owned by the caller, freed with chs_buf_free;
 *   required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_preview_row(
    const chs_schema *schema,
    chs_format format,
    const uint8_t *body,
    size_t body_len,
    const uint8_t *settings,
    size_t settings_len,
    const uint8_t *columns,
    size_t columns_len,
    chs_buf **out,
    chs_error **err);

/*
 * chs_preview_batch: Validates and coerces a whole body, which may hold many rows, and returns the
 * batch document, with the same declines as `chs_preview_row`. Row separation and the server's
 * error allowance are ClickHouse's own, and the document's `unconsumed` and `framing` say what the
 * reader skipped and how it framed the body. `filter`, when given, is evaluated over each stored
 * row in the same parse. When that filter's WHERE would read a setting this build's filters do not
 * honor, from the `chs_set_defaults`, schema or filter layer, the name joins the batch document's
 * top-level `unsupported_settings` and the batch is `unsupported` by `batch_outcome`'s step 2:
 * every row `unsupported`, filter rows `d`, and no export. The same call without the filter is
 * unchanged. `export_format` is `CHS_EXPORT_NONE` or a `chs_format` the build can write; with an
 * export, `out_export` receives the accepted rows serialized once, and it may be NULL when no
 * export is asked for. `doc_flags` chooses which groups the per-row documents carry.
 *
 * Class: api. Thread: shared. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `schema`: required.
 * - `body`, `body_len`: arbitrary bytes: a body, a string value, an export; length 0 is none, and
 *   the pointer may then be NULL.
 * - `settings`, `settings_len`: a JSON object whose values are JSON strings (settings, query
 *   parameters); length 0 is none, and the pointer may then be NULL.
 * - `columns`, `columns_len`: a JSON array of column names, each an object carrying the name as
 *   byte_strings says; length 0 is none, and the pointer may then be NULL.
 * - `filter`: may be NULL.
 * - `out`: receives the JSON document `batch`, owned by the caller, freed with chs_buf_free;
 *   required.
 * - `out_export`: receives arbitrary bytes: a body, a string value, an export, owned by the caller,
 *   freed with chs_buf_free; may be NULL when that output is not wanted.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_preview_batch(
    const chs_schema *schema,
    chs_format format,
    const uint8_t *body,
    size_t body_len,
    const uint8_t *settings,
    size_t settings_len,
    const uint8_t *columns,
    size_t columns_len,
    const chs_filter *filter,
    int32_t export_format,
    uint32_t doc_flags,
    chs_buf **out,
    chs_buf **out_export,
    chs_error **err);

/*
 * chs_filter_create: Compiles a boolean SQL expression over the schema's columns, binding its query
 * parameters (a JSON object of string values) by ClickHouse's own substitution, so a value is never
 * SQL text. `settings` is the profile the expression is compiled under, so `session_timezone` there
 * is the zone of its literals. Non-deterministic expressions are declined.
 *
 * The WHERE's settings are layered, lowest first: the build's own, `chs_set_defaults`, the schema's
 * server profile, the schema's own settings, and then this call's `settings`; `session_timezone` at
 * every layer stays on the zone path. A type gate in the schema's own settings binds the CREATE
 * only, so a WHERE's CAST validates under the session layers, every layer but the schema's own.
 *
 * On a schema whose server lists any `filter_declined_settings` (`chs_schema_describe`), the call
 * is `CHS_DECLINED` with ch_code 0. It is checked after the argument checks and before the
 * expression is parsed, because `dialect` can change the parse, and the message names the settings
 * in the list's order: `chs_filter_create: this schema's server profile sets <a>, <b>, which this
 * build's filters do not honor in a WHERE (listed in chs_schema_describe's
 * server.filter_declined_settings); declined rather than answered`. The server and the schema were
 * created all the same: a profile never changes a schema compile.
 *
 * A key of this call's own `settings` other than `session_timezone` is never `CHS_DECLINED` here. A
 * key in this build's honor set is applied to the WHERE; a key passed through is accepted and
 * ignored; and a key this build's filters do not honor is reported at evaluation, as a declined
 * setting from the `chs_set_defaults` or schema layer is (`filter_result`'s `unsupported_settings`,
 * and `chs_preview_batch`'s). Every key still meets the server's own SET check first, so a name the
 * server does not know is `CHS_REJECTED` with ch_code 115.
 *
 * A filter under a per-call `session_timezone` answers as the artifact producer has measured
 * against live servers, including how the zone in an evaluation's settings combines with the zone
 * the filter was compiled under. Until a path is measured to match a server it declines, which is
 * never a wrong answer. The filter holds a counted reference to the schema.
 *
 * Class: api. Thread: shared. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `schema`: required.
 * - `expr`, `expr_len`: SQL text (a statement, an expression, a type, a quoted name or literal):
 *   may carry any byte; length 0 is none, and the pointer may then be NULL.
 * - `query_params`, `query_params_len`: a JSON object whose values are JSON strings (settings,
 *   query parameters); length 0 is none, and the pointer may then be NULL.
 * - `settings`, `settings_len`: a JSON object whose values are JSON strings (settings, query
 *   parameters); length 0 is none, and the pointer may then be NULL.
 * - `out`: receives a new chs_filter, owned by the caller, freed with chs_filter_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_filter_create(
    const chs_schema *schema,
    const uint8_t *expr,
    size_t expr_len,
    const uint8_t *query_params,
    size_t query_params_len,
    const uint8_t *settings,
    size_t settings_len,
    chs_filter **out,
    chs_error **err);

/*
 * chs_filter_free: Releases the caller's reference to a filter. Freeing NULL does nothing.
 *
 * Class: api. Thread: handle_serial.
 *
 * - `filter`: may be NULL.
 */
CHS_API void chs_filter_free(chs_filter *filter);

/*
 * chs_filter_eval_body: Evaluates the filter over every row of a body, returning one verdict per
 * row. `settings` governs parsing the body, and `session_timezone` there is this call's zone. When
 * a server would not accept an INSERT of the body, because `chs_preview_batch`'s verdict over the
 * same body and settings, with no filter, is not `accepted`, every verdict is `d` and the outcome
 * mirrors that verdict (`filter_outcome`).
 *
 * Class: api. Thread: shared. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `filter`: required.
 * - `body`, `body_len`: arbitrary bytes: a body, a string value, an export; length 0 is none, and
 *   the pointer may then be NULL.
 * - `settings`, `settings_len`: a JSON object whose values are JSON strings (settings, query
 *   parameters); length 0 is none, and the pointer may then be NULL.
 * - `out`: receives the JSON document `filter_result`, owned by the caller, freed with
 *   chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_filter_eval_body(
    const chs_filter *filter,
    chs_format format,
    const uint8_t *body,
    size_t body_len,
    const uint8_t *settings,
    size_t settings_len,
    chs_buf **out,
    chs_error **err);

/*
 * chs_block_create: Parses a body once under the schema, for evaluating many filters over it.
 * `settings` governs the parse, `session_timezone` there included, and `columns` is read as
 * `chs_preview_row` reads it. The block holds a counted reference to the schema. It also records
 * `chs_preview_batch`'s verdict over the same body, settings and columns, with no filter, which
 * `chs_filter_eval_block` answers by.
 *
 * Class: api. Thread: shared. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `schema`: required.
 * - `body`, `body_len`: arbitrary bytes: a body, a string value, an export; length 0 is none, and
 *   the pointer may then be NULL.
 * - `settings`, `settings_len`: a JSON object whose values are JSON strings (settings, query
 *   parameters); length 0 is none, and the pointer may then be NULL.
 * - `columns`, `columns_len`: a JSON array of column names, each an object carrying the name as
 *   byte_strings says; length 0 is none, and the pointer may then be NULL.
 * - `out`: receives a new chs_block, owned by the caller, freed with chs_block_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_block_create(
    const chs_schema *schema,
    chs_format format,
    const uint8_t *body,
    size_t body_len,
    const uint8_t *settings,
    size_t settings_len,
    const uint8_t *columns,
    size_t columns_len,
    chs_block **out,
    chs_error **err);

/*
 * chs_block_free: Releases the caller's reference to a block. Freeing NULL does nothing.
 *
 * Class: api. Thread: handle_serial.
 *
 * - `block`: may be NULL.
 */
CHS_API void chs_block_free(chs_block *block);

/*
 * chs_filter_eval_block: Evaluates the filter over a parsed block. Over a body a server would
 * accept, it gives the same answers `chs_filter_eval_body` gives for that body. Over one it would
 * not (the verdict `chs_block_create` recorded is not `accepted`), the outcome mirrors that verdict
 * as for `chs_filter_eval_body`, and every verdict from the first refused row on is `d`. The first
 * refused row is the first row of that batch whose outcome is neither `accepted` nor `skipped`.
 * When the refusal belongs to no row (a whole-body step, a poisoned value, the call's own
 * settings), it is the first row of the block. The rows before it keep their evaluated verdicts. A
 * caller treats those as `d` too: any non-`ok` outcome, including `unsupported`, means every
 * verdict is `d`. It takes no settings: the filter brings the settings it was compiled under and
 * the block those it was parsed under. The filter and the block must come from the same schema; a
 * pair from two schemas is `CHS_INVALID_ARGUMENT`.
 *
 * Class: api. Thread: shared. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `filter`: required.
 * - `block`: required.
 * - `out`: receives the JSON document `filter_result`, owned by the caller, freed with
 *   chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_filter_eval_block(
    const chs_filter *filter,
    const chs_block *block,
    chs_buf **out,
    chs_error **err);

/*
 * chs_discover_query: The query a caller runs against a server to read a table's `system.columns`
 * rows, so that no binding holds SQL of its own. It is the connect-time way to rebuild a table's
 * columns from a server; whether a server's `SHOW CREATE TABLE` output compiles under
 * `chs_schema_create` instead is not yet measured. It takes no input. The SQL names the table
 * through the query parameters in `discover_query_param` (`{database:String}` and
 * `{table:String}`), which the caller binds when it runs the query; it selects exactly the
 * `system.columns` fields `chs_discover_columns` reads, `FORMAT JSONEachRow`.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `out`: receives SQL text (a statement, an expression, a type, a quoted name or literal): may
 *   carry any byte, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_discover_query(chs_buf **out, chs_error **err);

/*
 * chs_discover_columns: Reads a server's `system.columns` rows (the JSONEachRow answer to
 * `chs_discover_query`'s query) with ClickHouse's own reader and returns the column declarations,
 * formatted by ClickHouse's own formatter.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `rows`, `rows_len`: arbitrary bytes: a body, a string value, an export; length 0 is none, and
 *   the pointer may then be NULL.
 * - `out`: receives the JSON document `discovery`, owned by the caller, freed with chs_buf_free;
 *   required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_discover_columns(
    const uint8_t *rows,
    size_t rows_len,
    chs_buf **out,
    chs_error **err);

#ifdef __cplusplus
}
#endif

#endif /* CHTYPES_V2_H */
