/* GENERATED by scripts/abi-v1/gen.py from spec/abi-v1/abi.json (CHS_ABI_FINGERPRINT sha256:856e5cb7543db291b4db716662bf6e487b2258973b959bbf5d58b4bd46d73285) — DO NOT EDIT */
/*
 * One typed, copy-then-free method per described call, named without the `chs_` prefix.
 * Each marshals through the generic `rawCall`, throws the error class sdk.json's status
 * table gives for a non-OK status, returns every owned buffer as a Buffer (already copied
 * and freed) and every new handle wrapped. No raw buffer or error handle ever escapes.
 * The accessors and frees of those two kinds, and the handshake, tombstone and tooling
 * exports, get no method: the generic engine and the loader own them.
 */

import { SYMBOL } from './decls.gen.js';
import { type Abi1Handle, wrapHandle } from './handles.js';
import { asBuffer, checkStatus, type HandleRef, NULL_EXTERNAL, type RawApi, rawCall } from './raw.js';

export type SchemaHandle = Abi1Handle & { readonly kind: "chs_schema" };
export type FilterHandle = Abi1Handle & { readonly kind: "chs_filter" };
export type BlockHandle = Abi1Handle & { readonly kind: "chs_block" };

export class Calls {
  readonly raw: RawApi;

  constructor(raw: RawApi) {
    this.raw = raw;
  }

  /** The generated call wrapper for chs_live_handles. */
  liveHandles(): Buffer {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.LIVE_HANDLES, []));
    return outs["out"] as Buffer;
  }

  /** The generated call wrapper for chs_error_codes. */
  errorCodes(): Buffer {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.ERROR_CODES, []));
    return outs["out"] as Buffer;
  }

  /** The generated call wrapper for chs_initialize. */
  initialize(timezone: Uint8Array): void {
    checkStatus(rawCall(this.raw, SYMBOL.INITIALIZE, [asBuffer(timezone)]));
  }

  /** The generated call wrapper for chs_set_defaults. */
  setDefaults(settings: Uint8Array): void {
    checkStatus(rawCall(this.raw, SYMBOL.SET_DEFAULTS, [asBuffer(settings)]));
  }

  /** The generated call wrapper for chs_type_validate. */
  typeValidate(typeExpr: Uint8Array): Buffer {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.TYPE_VALIDATE, [asBuffer(typeExpr)]));
    return outs["out"] as Buffer;
  }

  /** The generated call wrapper for chs_back_quote. */
  backQuote(name: Uint8Array): Buffer {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.BACK_QUOTE, [asBuffer(name)]));
    return outs["out"] as Buffer;
  }

  /** The generated call wrapper for chs_back_quote_if_needed. */
  backQuoteIfNeeded(name: Uint8Array): Buffer {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.BACK_QUOTE_IF_NEEDED, [asBuffer(name)]));
    return outs["out"] as Buffer;
  }

  /** The generated call wrapper for chs_quote_string. */
  quoteString(text: Uint8Array): Buffer {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.QUOTE_STRING, [asBuffer(text)]));
    return outs["out"] as Buffer;
  }

  /** The generated call wrapper for chs_schema_create. */
  schemaCreate(createTable: Uint8Array, settings: Uint8Array): SchemaHandle {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.SCHEMA_CREATE, [asBuffer(createTable), asBuffer(settings)]));
    return wrapHandle(this.raw, outs["out"] as HandleRef) as SchemaHandle;
  }

  /** The generated call wrapper for chs_schema_describe. */
  schemaDescribe(schema: SchemaHandle): Buffer {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.SCHEMA_DESCRIBE, [schema.ptr]));
    return outs["out"] as Buffer;
  }

  /** The generated call wrapper for chs_preview_row. */
  previewRow(schema: SchemaHandle, format: number, body: Uint8Array, settings: Uint8Array, columns: Uint8Array): Buffer {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.PREVIEW_ROW, [schema.ptr, format, asBuffer(body), asBuffer(settings), asBuffer(columns)]));
    return outs["out"] as Buffer;
  }

  /** The generated call wrapper for chs_preview_batch. */
  previewBatch(schema: SchemaHandle, format: number, body: Uint8Array, settings: Uint8Array, columns: Uint8Array, filter: FilterHandle | null, exportFormat: number, docFlags: number): { readonly out: Buffer; readonly outExport: Buffer } {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.PREVIEW_BATCH, [schema.ptr, format, asBuffer(body), asBuffer(settings), asBuffer(columns), filter === null ? NULL_EXTERNAL : filter.ptr, exportFormat, docFlags]));
    return {
      out: outs["out"] as Buffer,
      outExport: outs["out_export"] as Buffer,
    };
  }

  /** The generated call wrapper for chs_filter_create. */
  filterCreate(schema: SchemaHandle, expr: Uint8Array, queryParams: Uint8Array, settings: Uint8Array): FilterHandle {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.FILTER_CREATE, [schema.ptr, asBuffer(expr), asBuffer(queryParams), asBuffer(settings)]));
    return wrapHandle(this.raw, outs["out"] as HandleRef) as FilterHandle;
  }

  /** The generated call wrapper for chs_filter_eval_body. */
  filterEvalBody(filter: FilterHandle, format: number, body: Uint8Array, settings: Uint8Array): Buffer {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.FILTER_EVAL_BODY, [filter.ptr, format, asBuffer(body), asBuffer(settings)]));
    return outs["out"] as Buffer;
  }

  /** The generated call wrapper for chs_block_create. */
  blockCreate(schema: SchemaHandle, format: number, body: Uint8Array, settings: Uint8Array, columns: Uint8Array): BlockHandle {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.BLOCK_CREATE, [schema.ptr, format, asBuffer(body), asBuffer(settings), asBuffer(columns)]));
    return wrapHandle(this.raw, outs["out"] as HandleRef) as BlockHandle;
  }

  /** The generated call wrapper for chs_filter_eval_block. */
  filterEvalBlock(filter: FilterHandle, block: BlockHandle): Buffer {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.FILTER_EVAL_BLOCK, [filter.ptr, block.ptr]));
    return outs["out"] as Buffer;
  }

  /** The generated call wrapper for chs_discover_query. */
  discoverQuery(): Buffer {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.DISCOVER_QUERY, []));
    return outs["out"] as Buffer;
  }

  /** The generated call wrapper for chs_discover_columns. */
  discoverColumns(rows: Uint8Array): Buffer {
    const outs = checkStatus(rawCall(this.raw, SYMBOL.DISCOVER_COLUMNS, [asBuffer(rows)]));
    return outs["out"] as Buffer;
  }

}
