/* GENERATED by scripts/abi-v1/gen.py from spec/abi-v1/abi.json (CHS_ABI_FINGERPRINT sha256:d6b9a42bc2fbb97273122a098ce09ee980d4ef31c0ceb6cb1b5c99e1465e0431) — DO NOT EDIT */
/*
 * spec/abi-v1/sdk.json's two error tables, as code: a CALL's chs_status -> one of
 * SchemaError/UnsupportedError/UsageError/InternalError (errors.status), and a LOADER
 * refusal's reason -> artifact_incompatible or artifact_corrupt (loader.refusals). Both
 * read spec/abi-v1/sdk.json; regenerate rather than hand-editing either table.
 */

import {
  type CallErrorFields,
  type ChtypesAbi1Error,
  InternalError,
  SchemaError,
  UnsupportedError,
  UsageError,
} from './errors.js';

/**
 * A call's chs_status name -> the mapped error instance (spec/abi-v1/sdk.json's
 * errors.status table). CHS_OK has no entry: a caller checks the status name for
 * 'CHS_OK' before ever calling this. An unrecognized status (impossible under a matching
 * fingerprint; see spec/abi-v1/docs.md's chs_status section) maps to InternalError, naming
 * the raw value, exactly like every other binding's generated table.
 */
export function errorForStatus(statusName: string, fields: CallErrorFields): ChtypesAbi1Error {
  switch (statusName) {
    case 'CHS_DECLINED':
      return new UnsupportedError(fields);
    case 'CHS_INTERNAL':
      return new InternalError(fields);
    case 'CHS_INVALID_ARGUMENT':
      return new UsageError(fields);
    case 'CHS_REJECTED':
      return new SchemaError(fields);
    default:
      return new InternalError({
        ...fields,
        messageBytes: Buffer.from(
          `chtypes: unrecognized chs_status ${statusName}: ${fields.messageBytes.toString('utf8')}`,
          'utf8',
        ),
      });
  }
}

export type LoaderErrorClass = 'artifact_incompatible' | 'artifact_corrupt';

/**
 * A loader refusal reason (spec/abi-v1/sdk.json's loader.refusals vocabulary, a
 * `missing_symbol:<name>` or `build_info_mismatch:<field>` reason included, via its
 * prefix before the first ':') -> which artifact error class the C ABI contract §Loading
 * error map says it is.
 */
export function loaderErrorClassFor(reason: string): LoaderErrorClass {
  const prefix = reason.split(':', 1)[0];
  switch (prefix) {
    case 'glibc_floor':
      return 'artifact_incompatible';
    case 'no_glibc':
      return 'artifact_incompatible';
    case 'predicate_malformed':
      return 'artifact_incompatible';
    case 'dlopen':
      return 'artifact_incompatible';
    case 'not_v1':
      return 'artifact_incompatible';
    case 'abi_version':
      return 'artifact_incompatible';
    case 'build_info_malformed':
      return 'artifact_corrupt';
    case 'fingerprint':
      return 'artifact_incompatible';
    case 'missing_symbol':
      return 'artifact_incompatible';
    case 'build_info_mismatch':
      return 'artifact_corrupt';
    default:
      throw new Error(`chtypes abi1: no sdk.json loader refusal class for reason ${reason}`);
  }
}
