/* GENERATED by scripts/abi-v1/gen.py from spec/abi-v1/abi.json (CHS_ABI_FINGERPRINT sha256:ef51ac764a2714ea7f2ce3689a83c0d2cbc9f2222fe57b10577f7b9de22e711d) — DO NOT EDIT */
/*
 * chtypes.h: the chtypes C ABI, generation 1.
 *
 * This header is generated from `spec/abi-v1/abi.json` by `scripts/abi-v1/gen.py`. Edit the
 * description and regenerate; never edit this file. `docs/reference/abi-v1.md` is the normative
 * reference.
 *
 * Identity. `CHS_ABI_VERSION` is the generation and `CHS_ABI_FINGERPRINT` is sha256 over the
 * canonical form of the description. A loader opens a library with `RTLD_NOW | RTLD_LOCAL`, calls
 * only the handshake set (`chs_abi_version`, `chs_build_info`, `chs_clickhouse_version`) before its
 * checks pass, and refuses any library whose generation or fingerprint differs from the ones it was
 * compiled with. Nothing degrades: every described symbol is mandatory.
 *
 * Ownership. Every input string, statement, document and body is counted bytes, `(const uint8_t *p,
 * size_t n)`: length 0 is none and the pointer may then be NULL, and a NULL pointer with a nonzero
 * length is `CHS_INVALID_ARGUMENT`. Every output is an owned, opaque `chs_buf`, read with
 * `chs_buf_data` and `chs_buf_len` and released with `chs_buf_free`. Bytes pass through unmodified,
 * NUL and invalid UTF-8 included: a column name may contain either (measured on live servers), so
 * no name, statement or message is ever a C string. The only static strings are the handshake's.
 * Handles are opaque, reference-counted and tagged with their kind and the image that made them;
 * every entry point checks both, a child holds a strong reference to what it needs, and each free
 * drops only the caller's reference, so any free order is safe and freeing NULL does nothing.
 *
 * Errors. A fallible call returns a `chs_status` and, through an optional last `chs_error **err`,
 * an owned error carrying the status, ClickHouse's own code and name, the message and the column.
 * The status alone carries the verdict, so `err` may be NULL.
 */
#ifndef CHTYPES_H
#define CHTYPES_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Every chs_* entry point is exported with default visibility; the library exports nothing else. */
#ifndef CHS_API
#define CHS_API __attribute__((visibility("default")))
#endif

/* ------------------------------------------------------------------------------------- identity */

/*
 * The ABI generation: what chs_abi_version() returns. A loader refuses a library whose answer
 * differs.
 */
#define CHS_ABI_VERSION 1

/*
 * `sha256:` and 64 lowercase hex digits: sha256 over the RFC 8785 canonical form of
 * spec/abi-v1/abi.json. chs_build_info()'s `abi_fingerprint` is this macro, copied; a loader
 * compares the two byte for byte and refuses any difference.
 */
#define CHS_ABI_FINGERPRINT "sha256:ef51ac764a2714ea7f2ce3689a83c0d2cbc9f2222fe57b10577f7b9de22e711d"

/* -------------------------------------------------------------------------- provisional markers */

/*
 * A declaration marked PROVISIONAL is in its proposed form and may change before the ABI is
 * confirmed; one with no marker is FIRM. The markers:
 *
 * - A4: the content of build_info capabilities: which formats and document flags a build reports
 * - A5: process initialization and the time-zone contract: whether an init call survives, and where
 *   a zone is set
 * - A6: settings channels and process defaults: whether a context handle exists and which calls
 *   take it
 * - A8: schema construction: one call over a whole CREATE TABLE statement, and its settings input
 * - A9: how filters and blocks bind to a schema
 * - A10: the row, batch and filter result documents: fields, outcomes, vocabularies, and which
 *   refusals are call statuses
 * - A11: derived results computed in the library: the Transformed classifier and the discovery kit
 * - A12: column introspection, and how a column name that is not valid UTF-8 is carried inside a
 *   JSON document
 * - A13: teardown: shutdown, background threads, and unloading the library
 * - Q-c: the form of the error accessors' text results, and the error-code table's buffer format
 * - Q-f: whether the discovery call also returns the query text a caller runs against a server
 * - confirm: outside the decided set: the SDK's proposed form, waiting on the confirmation of the
 *   whole ABI
 */

/* -------------------------------------------------------------------------------------- handles */

/*
 * chs_buf: An owned, immutable byte buffer: every output of the library. Read it with
 * `chs_buf_data` and `chs_buf_len`; the bytes are exactly what the library produced, with no
 * terminator and no encoding promise beyond what the producing parameter's content says.
 *
 * Freed with chs_buf_free.
 */
typedef struct chs_buf chs_buf;

/*
 * chs_error: The error a fallible call reports when its status is not `CHS_OK`: the status,
 * ClickHouse's own error code and name, a message and the column concerned. Created only by the
 * library, through a call's `err` out-parameter.
 *
 * Freed with chs_error_free.
 */
typedef struct chs_error chs_error;

/*
 * chs_schema: A compiled table: the columns, engine, keys and settings of one `CREATE TABLE`
 * statement, immutable once created.
 *
 * Freed with chs_schema_free.
 *
 * PROVISIONAL (A8).
 */
typedef struct chs_schema chs_schema;

/*
 * chs_filter: A compiled boolean SQL expression over a schema's columns, with its query parameters
 * bound.
 *
 * Freed with chs_filter_free. Holds a reference to its chs_schema, so any free order is safe.
 *
 * PROVISIONAL (A9).
 */
typedef struct chs_filter chs_filter;

/*
 * chs_block: A body parsed once under a schema, for evaluating many filters without parsing again.
 *
 * Freed with chs_block_free. Holds a reference to its chs_schema, so any free order is safe.
 *
 * PROVISIONAL (A9).
 */
typedef struct chs_block chs_block;

/* ---------------------------------------------------------------------------------------- enums */

/*
 * chs_status: The verdict of every fallible call, in five values whose numbering is frozen.
 *
 * - `CHS_OK`: the call succeeded and its outputs are set.
 * - `CHS_REJECTED`: ClickHouse's own refusal, with its own code, name and message, which a server
 *   would also give.
 * - `CHS_DECLINED`: this build will not answer; a server might accept. Never scored as agreement.
 * - `CHS_INVALID_ARGUMENT`: caller misuse, such as a NULL pointer with a nonzero length, a
 *   wrong-kind, freed or cross-library handle, or a NULL required out-parameter.
 * - `CHS_INTERNAL`: a guarded exception inside the library, which is a library bug.
 *
 * The set is closed within this generation: any new condition maps onto one of these five. A
 * binding maps each status to one error class (`spec/abi-v1/sdk.json`), and treats a value outside
 * the set as an internal error naming it.
 *
 * Closed and frozen: no value is added within this generation, and none is renumbered or removed.
 */
typedef int32_t chs_status;
#define CHS_OK               0
#define CHS_REJECTED         1
#define CHS_DECLINED         2
#define CHS_INVALID_ARGUMENT 3
#define CHS_INTERNAL         4

/*
 * chs_format: The input and export formats, numbered as they have been since the first release; the
 * numbers are frozen and a binding passes the integer. `ch_name` is ClickHouse's own name for the
 * format, which is how `chs_build_info` lists the formats a build supports. Being in this enum
 * never proves a build supports a format: the build says so in its `capabilities`.
 *
 * Frozen: no value is renumbered or removed.
 */
typedef int32_t chs_format;
#define CHS_JSON_EACH_ROW                                0  /* ch_name: JSONEachRow */
#define CHS_CSV                                          1  /* ch_name: CSV */
#define CHS_TSV                                          2  /* ch_name: TSV */
#define CHS_VALUES                                       3  /* ch_name: Values */
#define CHS_JSON_COMPACT_EACH_ROW                        4  /* ch_name: JSONCompactEachRow */
#define CHS_ROW_BINARY                                   5  /* ch_name: RowBinary */
#define CHS_ROW_BINARY_WITH_DEFAULTS                     6  /* ch_name: RowBinaryWithDefaults */
#define CHS_ROW_BINARY_WITH_NAMES_AND_TYPES_AND_DEFAULTS 7  /* ch_name: RowBinaryWithNamesAndTypesAndDefaults */
#define CHS_NATIVE                                       8  /* ch_name: Native */
#define CHS_BUFFERS                                      9  /* ch_name: Buffers */
#define CHS_CSV_WITH_NAMES                               10 /* ch_name: CSVWithNames */
#define CHS_TSV_WITH_NAMES                               11 /* ch_name: TSVWithNames */

/* ------------------------------------------------------------------------------------ constants */

/*
 * CHS_ABI_REVISION_TOMBSTONE: What `chs_abi_revision` always returns: 1001, outside every revision
 * a released v0 binding speaks.
 */
#define CHS_ABI_REVISION_TOMBSTONE 1001

/*
 * CHS_EXPORT_NONE: The `export_format` of a batch preview that exports nothing.
 *
 * PROVISIONAL (A10).
 */
#define CHS_EXPORT_NONE (-1)

/*
 * CHS_DOC_VALUES: A `doc_flags` bit: the per-row documents carry each column's stored value and
 * provenance.
 *
 * PROVISIONAL (A10).
 */
#define CHS_DOC_VALUES 1u

/*
 * CHS_DOC_TRANSFORMS: A `doc_flags` bit: the per-row documents carry the transformations the
 * library detected.
 *
 * PROVISIONAL (A10).
 */
#define CHS_DOC_TRANSFORMS 2u

/*
 * CHS_DOC_DEFAULTS: A `doc_flags` bit: the per-row documents carry the values the library computed
 * from DEFAULT and MATERIALIZED expressions.
 *
 * PROVISIONAL (A10).
 */
#define CHS_DOC_DEFAULTS 4u

/*
 * CHS_DOC_ALL: Every `doc_flags` bit. A bit outside it is refused.
 *
 * PROVISIONAL (A10).
 */
#define CHS_DOC_ALL 7u

/* ------------------------------------------------------------------------------------ functions */

/*
 * chs_abi_version: The ABI generation this library implements: always 1 for this header. A loader
 * resolves and calls it right after opening the library. A library without the symbol is not an ABI
 * v1 artifact, and any other value is refused, naming both values.
 *
 * Class: handshake. Thread: any.
 */
CHS_API int32_t chs_abi_version(void);

/*
 * chs_build_info: What this library is, as static, NUL-terminated, ASCII-only JSON in the image's
 * read-only data: never NULL, never freed, the same bytes on every call, and callable straight
 * after opening the library. Its fields are listed under `build_info` in the reference, and
 * `abi_fingerprint` is `CHS_ABI_FINGERPRINT` as the library was built, copied, never recomputed.
 *
 * A loader parses it (ASCII only, duplicate keys refused, `schema` equal to 1, every required field
 * of its type), refuses when `abi_fingerprint` differs from its own compiled-in
 * `CHS_ABI_FINGERPRINT` byte for byte, and then compares the fields listed in
 * `spec/abi-v1/sdk.json` (`cross_check`) with the verified signed statement it fetched the library
 * under, refusing on the first mismatch and naming the field. That comparison is mandatory. The
 * file's own size, digest and glibc floor are not in it, because the file cannot carry facts
 * measured on itself; they are in the signed statement.
 *
 * Class: handshake. Thread: any.
 */
CHS_API const char *chs_build_info(void);

/*
 * chs_clickhouse_version: The ClickHouse release this library was built from, spelled as every v0
 * library spelled it (for example `26.8.15.10-lts`): static, never freed. It keeps its v0 signature
 * and spelling so a v0 binding reaches its own refusal. A v1 binding reads `clickhouse_version`
 * from `chs_build_info` instead.
 *
 * Class: handshake. Thread: any.
 */
CHS_API const char *chs_clickhouse_version(void);

/*
 * chs_abi_revision: The v0 tombstone. It always returns `CHS_ABI_REVISION_TOMBSTONE` (1001). It
 * must never be removed, and its name must never be given another meaning.
 *
 * A sweep of every released binding (every minor from 0.1 to 0.5, in all four languages; [the CI
 * run](https://github.com/Wave-RF/chtypes/actions/runs/36939764841)) measured why: each one calls
 * this symbol whenever it exists and refuses cleanly, naming both numbers, when it returns a
 * revision other than its own, but treats a MISSING symbol as "revision 0, predates the probe" and
 * goes on to call `chs_init`. So this tombstone is what turns every v0 binding away before it can
 * reach any other symbol, and `gen.py --check` refuses a description that reuses a v0 name without
 * it. A v1 binding never calls it; the loader resolves it only to prove it is present.
 *
 * Class: tombstone. Thread: any. Always returns CHS_ABI_REVISION_TOMBSTONE (1001).
 */
CHS_API int chs_abi_revision(void);

/*
 * chs_buf_data: The buffer's bytes. The pointer may be NULL when `chs_buf_len` is 0, and a binding
 * never dereferences it then. A NULL, freed, wrong-kind or cross-library buffer gives NULL.
 *
 * Class: api. Thread: any. The pointer is borrowed from `buf` and valid until it is freed; copy
 * before freeing.
 *
 * - `buf`: required.
 */
CHS_API const uint8_t *chs_buf_data(const chs_buf *buf);

/*
 * chs_buf_len: The buffer's length in bytes. A NULL, freed, wrong-kind or cross-library buffer
 * gives 0.
 *
 * Class: api. Thread: any.
 *
 * - `buf`: required.
 */
CHS_API size_t chs_buf_len(const chs_buf *buf);

/*
 * chs_buf_free: Releases the caller's reference to a buffer. Freeing NULL does nothing.
 *
 * Class: api. Thread: handle_serial.
 *
 * - `buf`: may be NULL.
 */
CHS_API void chs_buf_free(chs_buf *buf);

/*
 * chs_error_status: The error's status, never `CHS_OK` for an error a call set. A NULL, freed,
 * wrong-kind or cross-library error gives `CHS_INVALID_ARGUMENT`.
 *
 * Class: api. Thread: any.
 *
 * - `error`: required.
 */
CHS_API chs_status chs_error_status(const chs_error *error);

/*
 * chs_error_ch_code: ClickHouse's own error code, nonzero only when the status is `CHS_REJECTED`,
 * and 0 otherwise or for an invalid error.
 *
 * Class: api. Thread: any.
 *
 * - `error`: required.
 */
CHS_API int32_t chs_error_ch_code(const chs_error *error);

/*
 * chs_error_ch_name: A new buffer holding the name this build's vendored error table gives the
 * code, the name a server prints after the code; empty when the build has none or the status is not
 * `CHS_REJECTED`. The form of the three text accessors (a returned buffer, as here, or an
 * out-parameter) is open.
 *
 * Class: api. Thread: any. Returns a new chs_buf the caller owns and frees with chs_buf_free; its
 * content is guaranteed ASCII; NULL only on allocation failure or an invalid argument.
 *
 * - `error`: required.
 *
 * PROVISIONAL, waiting on Q-c: the form of the error accessors' text results, and the error-code
 * table's buffer format.
 */
CHS_API chs_buf *chs_error_ch_name(const chs_error *error);

/*
 * chs_error_message: A new buffer holding the message: ClickHouse's own text, verbatim, for
 * `CHS_REJECTED`, and the library's explanation otherwise. A message may quote input bytes, so it
 * is a byte string, not text.
 *
 * Class: api. Thread: any. Returns a new chs_buf the caller owns and frees with chs_buf_free; its
 * content is a ClickHouse message: may quote input bytes, so may carry any byte; NULL only on
 * allocation failure or an invalid argument.
 *
 * - `error`: required.
 *
 * PROVISIONAL, waiting on Q-c: the form of the error accessors' text results, and the error-code
 * table's buffer format.
 */
CHS_API chs_buf *chs_error_message(const chs_error *error);

/*
 * chs_error_column: A new buffer holding the name of the column the error concerns, empty when
 * there is none. A column name is a byte string: NUL and invalid UTF-8 are legal in a name.
 *
 * Class: api. Thread: any. Returns a new chs_buf the caller owns and frees with chs_buf_free; its
 * content is a ClickHouse column name: NUL and invalid UTF-8 are legal, so never assume UTF-8; NULL
 * only on allocation failure or an invalid argument.
 *
 * - `error`: required.
 *
 * PROVISIONAL, waiting on Q-c: the form of the error accessors' text results, and the error-code
 * table's buffer format.
 */
CHS_API chs_buf *chs_error_column(const chs_error *error);

/*
 * chs_error_free: Releases the caller's reference to an error. Freeing NULL does nothing.
 *
 * Class: api. Thread: handle_serial.
 *
 * - `error`: may be NULL.
 */
CHS_API void chs_error_free(chs_error *error);

/*
 * chs_live_handles: A JSON document counting the live handles of each kind this image has made,
 * taken before the document's own buffer exists. A test abandons handles, lets its runtime collect
 * them and then asserts every count is zero, which is how all four bindings prove their finalizers
 * release everything.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `out`: receives the JSON document `live_handles`, owned by the caller, freed with chs_buf_free;
 *   required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_live_handles(chs_buf **out, chs_error **err);

/*
 * chs_error_code_table: ClickHouse's own error-code table for this build, as a JSON document: a
 * passthrough over the vendored table, never a copy. The table belongs to the build, and one number
 * can name different errors on two ClickHouse lines, so a caller that needs several lines asks each
 * library. Named for what it returns; the v0 symbol with the nearer name had a different signature.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `out`: receives the JSON document `error_code_table`, owned by the caller, freed with
 *   chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_error_code_table(chs_buf **out, chs_error **err);

/*
 * chs_tool_registered_families: Every type family in this build's own type registry, one per line.
 * A tooling export for the artifact producer's build gates: no binding wraps it, and a loader
 * resolves it only for presence.
 *
 * Class: tooling. Thread: process_serial. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT,
 * CHS_INTERNAL.
 *
 * - `out`: receives guaranteed ASCII, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_tool_registered_families(chs_buf **out, chs_error **err);

/*
 * chs_tool_function_flags: A tab-separated audit of every registered function's volatility flags,
 * one function per line, read off this build's own registry. A tooling export for the artifact
 * producer's build gates, which derive the statelessness evidence from it; no binding wraps it.
 *
 * Class: tooling. Thread: process_serial. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT,
 * CHS_INTERNAL.
 *
 * - `out`: receives guaranteed ASCII, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_tool_function_flags(chs_buf **out, chs_error **err);

/*
 * chs_tool_reference_type: The widened reference type this build pairs with a type expression. A
 * tooling export; no binding wraps it.
 *
 * Class: tooling. Thread: process_serial. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `type_expr`, `type_expr_len`: SQL text (a statement, an expression, a type, a quoted name or
 *   literal): may carry any byte; length 0 is none, and the pointer may then be NULL.
 * - `out`: receives SQL text (a statement, an expression, a type, a quoted name or literal): may
 *   carry any byte, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 */
CHS_API chs_status chs_tool_reference_type(
    const uint8_t *type_expr,
    size_t type_expr_len,
    chs_buf **out,
    chs_error **err);

/*
 * chs_initialize: Process setup for this image. The proposed form takes nothing: the time zone
 * becomes per call rather than per process, and the list of type families the build must refuse is
 * embedded when the library is built. Whether an initialization call survives at all is open;
 * nothing before it in the load sequence needs it.
 *
 * Class: api. Thread: process_once. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on A5: process initialization and the time-zone contract: whether an init
 * call survives, and where a zone is set.
 */
CHS_API chs_status chs_initialize(chs_error **err);

/*
 * chs_set_defaults: Seeds the settings every later call starts from, as a JSON object whose values
 * are JSON strings (a binding never rewrites a value, a boolean included). A setting name the
 * server would refuse is refused here, with ClickHouse's own code and message, and nothing is
 * committed.
 *
 * Class: api. Thread: process_serial. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `settings`, `settings_len`: a JSON object whose values are JSON strings (settings, query
 *   parameters); length 0 is none, and the pointer may then be NULL.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on A6: settings channels and process defaults: whether a context handle
 * exists and which calls take it.
 */
CHS_API chs_status chs_set_defaults(const uint8_t *settings, size_t settings_len, chs_error **err);

/*
 * chs_shutdown: Stops the background work the library started and joins its threads. Safe to call
 * when nothing was started. Whether teardown and unloading are supported at all is open; a loader
 * never unloads a library.
 *
 * Class: api. Thread: process_serial.
 *
 * PROVISIONAL, waiting on A13: teardown: shutdown, background threads, and unloading the library.
 */
CHS_API void chs_shutdown(void);

/*
 * chs_type_validate: Parses one type expression with ClickHouse's own parser and returns its
 * canonical spelling, or ClickHouse's own refusal.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `type_expr`, `type_expr_len`: SQL text (a statement, an expression, a type, a quoted name or
 *   literal): may carry any byte; length 0 is none, and the pointer may then be NULL.
 * - `out`: receives SQL text (a statement, an expression, a type, a quoted name or literal): may
 *   carry any byte, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on A6: settings channels and process defaults: whether a context handle
 * exists and which calls take it.
 */
CHS_API chs_status chs_type_validate(
    const uint8_t *type_expr,
    size_t type_expr_len,
    chs_buf **out,
    chs_error **err);

/*
 * chs_back_quote: A name quoted the way ClickHouse's own `backQuote` quotes it: always quoted,
 * every special byte escaped. A passthrough over the vendored function; the name is a byte string.
 * Named after that function, because the v0 symbol for the same job had a different signature.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `name`, `name_len`: a ClickHouse column name: NUL and invalid UTF-8 are legal, so never assume
 *   UTF-8; length 0 is none, and the pointer may then be NULL.
 * - `out`: receives SQL text (a statement, an expression, a type, a quoted name or literal): may
 *   carry any byte, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on confirm: outside the decided set: the SDK's proposed form, waiting on the
 * confirmation of the whole ABI.
 */
CHS_API chs_status chs_back_quote(
    const uint8_t *name,
    size_t name_len,
    chs_buf **out,
    chs_error **err);

/*
 * chs_back_quote_if_needed: A name quoted only where this build's own `backQuoteIfNeed` says it
 * must be. Which names stay bare is a property of the ClickHouse release, so a caller that needs
 * one answer for several releases asks each library.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `name`, `name_len`: a ClickHouse column name: NUL and invalid UTF-8 are legal, so never assume
 *   UTF-8; length 0 is none, and the pointer may then be NULL.
 * - `out`: receives SQL text (a statement, an expression, a type, a quoted name or literal): may
 *   carry any byte, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on confirm: outside the decided set: the SDK's proposed form, waiting on the
 * confirmation of the whole ABI.
 */
CHS_API chs_status chs_back_quote_if_needed(
    const uint8_t *name,
    size_t name_len,
    chs_buf **out,
    chs_error **err);

/*
 * chs_quote_string: A byte string spelled as a ClickHouse string literal by the vendored
 * `quoteString`. The input may contain NUL; the answer escapes it.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `text`, `text_len`: arbitrary bytes: a body, a string value, an export; length 0 is none, and
 *   the pointer may then be NULL.
 * - `out`: receives SQL text (a statement, an expression, a type, a quoted name or literal): may
 *   carry any byte, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on confirm: outside the decided set: the SDK's proposed form, waiting on the
 * confirmation of the whole ABI.
 */
CHS_API chs_status chs_quote_string(
    const uint8_t *text,
    size_t text_len,
    chs_buf **out,
    chs_error **err);

/*
 * chs_schema_create: Compiles one whole `CREATE TABLE` statement (columns, engine, keys, TTL,
 * settings and constraints) with ClickHouse's own parser and the checks a server's CREATE runs,
 * under a profile of settings given as a JSON object of string values. The result is immutable. The
 * proposed form replaces v0's column-list compile and its engine, TTL and partition-key setters.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `create_table`, `create_table_len`: SQL text (a statement, an expression, a type, a quoted name
 *   or literal): may carry any byte; length 0 is none, and the pointer may then be NULL.
 * - `settings`, `settings_len`: a JSON object whose values are JSON strings (settings, query
 *   parameters); length 0 is none, and the pointer may then be NULL.
 * - `out`: receives a new chs_schema, owned by the caller, freed with chs_schema_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on A6: settings channels and process defaults: whether a context handle
 * exists and which calls take it; A8: schema construction: one call over a whole CREATE TABLE
 * statement, and its settings input.
 */
CHS_API chs_status chs_schema_create(
    const uint8_t *create_table,
    size_t create_table_len,
    const uint8_t *settings,
    size_t settings_len,
    chs_schema **out,
    chs_error **err);

/*
 * chs_schema_free: Releases the caller's reference to a schema. Filters and blocks made from it
 * keep it alive. Freeing NULL does nothing.
 *
 * Class: api. Thread: handle_serial.
 *
 * - `schema`: may be NULL.
 *
 * PROVISIONAL, waiting on A8: schema construction: one call over a whole CREATE TABLE statement,
 * and its settings input.
 */
CHS_API void chs_schema_free(chs_schema *schema);

/*
 * chs_schema_describe: A JSON document describing the schema's columns, owned by the caller; it
 * replaces v0's borrowed column accessors.
 *
 * Class: api. Thread: handle_serial. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `schema`: required.
 * - `out`: receives the JSON document `schema_description`, owned by the caller, freed with
 *   chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on A8: schema construction: one call over a whole CREATE TABLE statement,
 * and its settings input; A12: column introspection, and how a column name that is not valid UTF-8
 * is carried inside a JSON document.
 */
CHS_API chs_status chs_schema_describe(const chs_schema *schema, chs_buf **out, chs_error **err);

/*
 * chs_preview_row: Validates and coerces one row of `body` under the schema, as a server's INSERT
 * would, and returns the row's document. `columns` is the INSERT column list, empty for none.
 *
 * Class: api. Thread: handle_serial. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `schema`: required.
 * - `body`, `body_len`: arbitrary bytes: a body, a string value, an export; length 0 is none, and
 *   the pointer may then be NULL.
 * - `settings`, `settings_len`: a JSON object whose values are JSON strings (settings, query
 *   parameters); length 0 is none, and the pointer may then be NULL.
 * - `columns`, `columns_len`: a JSON array of column names (the encoding of a non-UTF-8 name is
 *   provisional: A12); length 0 is none, and the pointer may then be NULL.
 * - `out`: receives the JSON document `row`, owned by the caller, freed with chs_buf_free;
 *   required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on A8: schema construction: one call over a whole CREATE TABLE statement,
 * and its settings input; A10: the row, batch and filter result documents: fields, outcomes,
 * vocabularies, and which refusals are call statuses; A11: derived results computed in the library:
 * the Transformed classifier and the discovery kit; A12: column introspection, and how a column
 * name that is not valid UTF-8 is carried inside a JSON document.
 */
CHS_API chs_status chs_preview_row(
    const chs_schema *schema,
    chs_format format,
    const uint8_t *body,
    size_t body_len,
    const uint8_t *settings,
    size_t settings_len,
    const uint8_t *columns,
    size_t columns_len,
    chs_buf **out,
    chs_error **err);

/*
 * chs_preview_batch: Validates and coerces a whole body, which may hold many rows, and returns the
 * batch document. Row separation and the server's error allowance are ClickHouse's own. `filter`,
 * when given, is evaluated over each stored row in the same parse. `export_format` is
 * `CHS_EXPORT_NONE` or a `chs_format` the build can write; with an export, `out_export` receives
 * the accepted rows serialized once, and it may be NULL when no export is asked for. `doc_flags`
 * chooses which groups the per-row documents carry.
 *
 * Class: api. Thread: handle_serial. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `schema`: required.
 * - `body`, `body_len`: arbitrary bytes: a body, a string value, an export; length 0 is none, and
 *   the pointer may then be NULL.
 * - `settings`, `settings_len`: a JSON object whose values are JSON strings (settings, query
 *   parameters); length 0 is none, and the pointer may then be NULL.
 * - `columns`, `columns_len`: a JSON array of column names (the encoding of a non-UTF-8 name is
 *   provisional: A12); length 0 is none, and the pointer may then be NULL.
 * - `filter`: may be NULL.
 * - `out`: receives the JSON document `batch`, owned by the caller, freed with chs_buf_free;
 *   required.
 * - `out_export`: receives arbitrary bytes: a body, a string value, an export, owned by the caller,
 *   freed with chs_buf_free; may be NULL when that output is not wanted.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on A8: schema construction: one call over a whole CREATE TABLE statement,
 * and its settings input; A9: how filters and blocks bind to a schema; A10: the row, batch and
 * filter result documents: fields, outcomes, vocabularies, and which refusals are call statuses;
 * A11: derived results computed in the library: the Transformed classifier and the discovery kit;
 * A12: column introspection, and how a column name that is not valid UTF-8 is carried inside a JSON
 * document.
 */
CHS_API chs_status chs_preview_batch(
    const chs_schema *schema,
    chs_format format,
    const uint8_t *body,
    size_t body_len,
    const uint8_t *settings,
    size_t settings_len,
    const uint8_t *columns,
    size_t columns_len,
    const chs_filter *filter,
    int32_t export_format,
    uint32_t doc_flags,
    chs_buf **out,
    chs_buf **out_export,
    chs_error **err);

/*
 * chs_filter_create: Compiles a boolean SQL expression over the schema's columns, binding its query
 * parameters (a JSON object of string values) by ClickHouse's own substitution, so a value is never
 * SQL text. Non-deterministic expressions are declined.
 *
 * Class: api. Thread: handle_serial. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `schema`: required.
 * - `expr`, `expr_len`: SQL text (a statement, an expression, a type, a quoted name or literal):
 *   may carry any byte; length 0 is none, and the pointer may then be NULL.
 * - `query_params`, `query_params_len`: a JSON object whose values are JSON strings (settings,
 *   query parameters); length 0 is none, and the pointer may then be NULL.
 * - `out`: receives a new chs_filter, owned by the caller, freed with chs_filter_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on A8: schema construction: one call over a whole CREATE TABLE statement,
 * and its settings input; A9: how filters and blocks bind to a schema.
 */
CHS_API chs_status chs_filter_create(
    const chs_schema *schema,
    const uint8_t *expr,
    size_t expr_len,
    const uint8_t *query_params,
    size_t query_params_len,
    chs_filter **out,
    chs_error **err);

/*
 * chs_filter_free: Releases the caller's reference to a filter. Freeing NULL does nothing.
 *
 * Class: api. Thread: handle_serial.
 *
 * - `filter`: may be NULL.
 *
 * PROVISIONAL, waiting on A9: how filters and blocks bind to a schema.
 */
CHS_API void chs_filter_free(chs_filter *filter);

/*
 * chs_filter_eval_body: Evaluates the filter over every row of a body, returning one verdict per
 * row.
 *
 * Class: api. Thread: handle_serial. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `filter`: required.
 * - `body`, `body_len`: arbitrary bytes: a body, a string value, an export; length 0 is none, and
 *   the pointer may then be NULL.
 * - `settings`, `settings_len`: a JSON object whose values are JSON strings (settings, query
 *   parameters); length 0 is none, and the pointer may then be NULL.
 * - `out`: receives the JSON document `filter_result`, owned by the caller, freed with
 *   chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on A9: how filters and blocks bind to a schema; A10: the row, batch and
 * filter result documents: fields, outcomes, vocabularies, and which refusals are call statuses.
 */
CHS_API chs_status chs_filter_eval_body(
    const chs_filter *filter,
    chs_format format,
    const uint8_t *body,
    size_t body_len,
    const uint8_t *settings,
    size_t settings_len,
    chs_buf **out,
    chs_error **err);

/*
 * chs_block_create: Parses a body once under the schema, for evaluating many filters over it.
 *
 * Class: api. Thread: handle_serial. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `schema`: required.
 * - `body`, `body_len`: arbitrary bytes: a body, a string value, an export; length 0 is none, and
 *   the pointer may then be NULL.
 * - `settings`, `settings_len`: a JSON object whose values are JSON strings (settings, query
 *   parameters); length 0 is none, and the pointer may then be NULL.
 * - `columns`, `columns_len`: a JSON array of column names (the encoding of a non-UTF-8 name is
 *   provisional: A12); length 0 is none, and the pointer may then be NULL.
 * - `out`: receives a new chs_block, owned by the caller, freed with chs_block_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on A8: schema construction: one call over a whole CREATE TABLE statement,
 * and its settings input; A9: how filters and blocks bind to a schema; A10: the row, batch and
 * filter result documents: fields, outcomes, vocabularies, and which refusals are call statuses;
 * A12: column introspection, and how a column name that is not valid UTF-8 is carried inside a JSON
 * document.
 */
CHS_API chs_status chs_block_create(
    const chs_schema *schema,
    chs_format format,
    const uint8_t *body,
    size_t body_len,
    const uint8_t *settings,
    size_t settings_len,
    const uint8_t *columns,
    size_t columns_len,
    chs_block **out,
    chs_error **err);

/*
 * chs_block_free: Releases the caller's reference to a block. Freeing NULL does nothing.
 *
 * Class: api. Thread: handle_serial.
 *
 * - `block`: may be NULL.
 *
 * PROVISIONAL, waiting on A9: how filters and blocks bind to a schema.
 */
CHS_API void chs_block_free(chs_block *block);

/*
 * chs_filter_eval_block: Evaluates the filter over a parsed block, with the same answers
 * `chs_filter_eval_body` gives for the same body. The filter and the block must come from the same
 * schema.
 *
 * Class: api. Thread: handle_serial. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `filter`: required.
 * - `block`: required.
 * - `out`: receives the JSON document `filter_result`, owned by the caller, freed with
 *   chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on A9: how filters and blocks bind to a schema; A10: the row, batch and
 * filter result documents: fields, outcomes, vocabularies, and which refusals are call statuses.
 */
CHS_API chs_status chs_filter_eval_block(
    const chs_filter *filter,
    const chs_block *block,
    chs_buf **out,
    chs_error **err);

/*
 * chs_discover_query: The query a caller runs against a server to read a table's `system.columns`
 * rows, so that no binding holds SQL of its own.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `out`: receives SQL text (a statement, an expression, a type, a quoted name or literal): may
 *   carry any byte, owned by the caller, freed with chs_buf_free; required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on A6: settings channels and process defaults: whether a context handle
 * exists and which calls take it; A11: derived results computed in the library: the Transformed
 * classifier and the discovery kit; Q-f: whether the discovery call also returns the query text a
 * caller runs against a server.
 */
CHS_API chs_status chs_discover_query(chs_buf **out, chs_error **err);

/*
 * chs_discover_columns: Reads a server's `system.columns` rows (the JSONEachRow answer to
 * `chs_discover_query`'s query) with ClickHouse's own reader and returns the column declarations,
 * formatted by ClickHouse's own formatter.
 *
 * Class: api. Thread: any. Returns one of: CHS_OK, CHS_REJECTED, CHS_DECLINED,
 * CHS_INVALID_ARGUMENT, CHS_INTERNAL.
 *
 * - `rows`, `rows_len`: arbitrary bytes: a body, a string value, an export; length 0 is none, and
 *   the pointer may then be NULL.
 * - `out`: receives the JSON document `discovery`, owned by the caller, freed with chs_buf_free;
 *   required.
 * - `err`: may be NULL; set only when the status is not CHS_OK.
 *
 * PROVISIONAL, waiting on A6: settings channels and process defaults: whether a context handle
 * exists and which calls take it; A11: derived results computed in the library: the Transformed
 * classifier and the discovery kit; A12: column introspection, and how a column name that is not
 * valid UTF-8 is carried inside a JSON document.
 */
CHS_API chs_status chs_discover_columns(
    const uint8_t *rows,
    size_t rows_len,
    chs_buf **out,
    chs_error **err);

#ifdef __cplusplus
}
#endif

#endif /* CHTYPES_H */
