# GENERATED by scripts/abi-v1/gen.py from spec/abi-v1/abi.json (CHS_ABI_FINGERPRINT sha256:d6b9a42bc2fbb97273122a098ce09ee980d4ef31c0ceb6cb1b5c99e1465e0431) — DO NOT EDIT  # noqa: E501
"""The Python binding's generated ABI v1 layer: ctypes signatures, the handle
classes, the two-phase resolve functions and invoke_by_name(), the test-only
dispatcher the conformance suite drives from tests/fixtures/abi-v1/cases.json.
See scripts/abi-v1/emit/python.py's module docstring for the design this file
implements and why. This is the ONLY python/src/chtypes/_abi1 file that reads
a chs_* attribute (scripts/abi-v1/check-no-hand-decls.py exempts it by its
banner, above); every other file in this package calls the non-chs_-prefixed
names this module exposes instead.
"""

from __future__ import annotations

import ctypes
from collections.abc import Callable, Iterable
from dataclasses import dataclass, field

CHS_ABI_VERSION = 1
CHS_ABI_FINGERPRINT = "sha256:d6b9a42bc2fbb97273122a098ce09ee980d4ef31c0ceb6cb1b5c99e1465e0431"

# sdk.json's loader.cross_check: (build_info field, predicate field, how to
# compare), read by _loader.py's step 5 without it ever touching sdk.json
# itself (not part of the installed package).
CROSS_CHECK_FIELDS: tuple[tuple[str, str, str], ...] = (
    ("abi", "abi", "int"),
    ("abi_fingerprint", "abi_fingerprint", "bytes"),
    ("clickhouse_version", "clickhouse_version", "bytes"),
    ("channel", "channel", "bytes"),
    ("build", "build", "bytes"),
    ("os", "os", "bytes"),
    ("arch", "arch", "bytes"),
    ("core_commit", "core_commit", "bytes"),
    ("inputs_sha256", "inputs_sha256", "bytes"),
)

# chs_status's values, both directions. Frozen by D3, but still generated
# from the description rather than hand-copied, so a future enum change is a
# regeneration, never a drift.
STATUS_BY_VALUE: dict[int, str] = {
    0: "CHS_OK",
    1: "CHS_REJECTED",
    2: "CHS_DECLINED",
    3: "CHS_INVALID_ARGUMENT",
    4: "CHS_INTERNAL",
}
STATUS_BY_NAME: dict[str, int] = {v: k for k, v in STATUS_BY_VALUE.items()}

# handle type name -> its free function's name (never called directly outside
# this file: Handle.close() holds the bound method, resolved once in
# resolve_all()).
HANDLE_FREE: dict[str, str] = {
    "chs_buf": "chs_buf_free",
    "chs_error": "chs_error_free",
    "chs_schema": "chs_schema_free",
    "chs_filter": "chs_filter_free",
    "chs_block": "chs_block_free",
}

ALL_SYMBOLS: tuple[str, ...] = (
    "chs_abi_revision",
    "chs_abi_version",
    "chs_back_quote",
    "chs_back_quote_if_needed",
    "chs_block_create",
    "chs_block_free",
    "chs_buf_data",
    "chs_buf_free",
    "chs_buf_len",
    "chs_build_info",
    "chs_clickhouse_version",
    "chs_discover_columns",
    "chs_discover_query",
    "chs_error_ch_code",
    "chs_error_ch_name",
    "chs_error_codes",
    "chs_error_column",
    "chs_error_free",
    "chs_error_message",
    "chs_error_status",
    "chs_filter_create",
    "chs_filter_eval_block",
    "chs_filter_eval_body",
    "chs_filter_free",
    "chs_function_flags",
    "chs_initialize",
    "chs_live_handles",
    "chs_preview_batch",
    "chs_preview_row",
    "chs_quote_string",
    "chs_reference_type",
    "chs_registered_families",
    "chs_schema_create",
    "chs_schema_describe",
    "chs_schema_free",
    "chs_set_defaults",
    "chs_shutdown",
    "chs_type_validate",
)
HANDSHAKE_NAMES: tuple[str, ...] = (
    "chs_abi_version",
    "chs_build_info",
    "chs_clickhouse_version",
)

_CTYPES_NUMERIC: dict[str, type] = {
    "int": ctypes.c_int,
    "int32": ctypes.c_int32,
    "uint32": ctypes.c_uint32,
    "int64": ctypes.c_int64,
    "uint64": ctypes.c_uint64,
    "size": ctypes.c_size_t,
}


class MissingSymbol(Exception):
    """Step 3 or step 6 (plan section 3.2) could not resolve `name` in the
    opened library -- ctypes' own getattr-is-dlsym behavior raised
    AttributeError, which this file turns into a named exception so
    _loader.py never has to spell a chs_ name to report which one."""

    def __init__(self, name: str) -> None:
        super().__init__(name)
        self.name = name


class Handle:
    """A reference-counted, kind- and image-tagged C handle (D2): closing it
    releases this binding's own reference, any number of times, from any
    thread, in any order relative to other handles -- never from a __del__
    racing a live reference elsewhere, since CPython only runs a finalizer
    once nothing refers to the object. `value` is the raw pointer (an int,
    for echo/identity comparisons in the conformance suite) or None once
    closed."""

    __slots__ = ("_closed", "_free", "_ptr")

    def __init__(self, ptr: int, free: Callable[..., object]) -> None:
        self._ptr = ptr
        self._free = free
        self._closed = ptr is None or ptr == 0

    @property
    def value(self) -> int | None:
        return None if self._closed else self._ptr

    def close(self) -> None:
        if not self._closed:
            self._free(self._ptr)
            self._closed = True
            self._ptr = None

    def __del__(self) -> None:
        try:
            self.close()
        except Exception:  # noqa: BLE001 - a finalizer must never raise
            pass


class BufHandle(Handle):
    """A `chs_buf` the library owns the free function for."""


class ErrorHandle(Handle):
    """A `chs_error` the library owns the free function for."""


class SchemaHandle(Handle):
    """A `chs_schema` the library owns the free function for."""


class FilterHandle(Handle):
    """A `chs_filter` the library owns the free function for."""


class BlockHandle(Handle):
    """A `chs_block` the library owns the free function for."""


_HANDLE_CLASS: dict[str, type[Handle]] = {
    "chs_buf": BufHandle,
    "chs_error": ErrorHandle,
    "chs_schema": SchemaHandle,
    "chs_filter": FilterHandle,
    "chs_block": BlockHandle,
}


@dataclass(frozen=True)
class _P:
    """One function parameter, as the description's closed param-kind
    vocabulary (model.py's PARAM_KINDS) names it: scalar | enum | bytes_in |
    handle | out_handle | out_error | out_scalar. `type` is a scalar name, a
    handle type name, or None (bytes_in, out_error)."""

    name: str
    kind: str
    type: str | None
    nullable: bool = False


@dataclass(frozen=True)
class _F:
    """One described function: its return shape and its parameters, in
    declaration order -- everything invoke_by_name() and the signature
    setters need, read generically rather than unrolled per function, so a
    regeneration changes only FUNCTIONS, never this interpreter."""

    name: str
    returns_kind: str
    returns_type: str | None
    params: tuple[_P, ...] = ()


FUNCTIONS: dict[str, _F] = {}


def _add(name: str, returns_kind: str, returns_type: str | None, *params: _P) -> None:
    FUNCTIONS[name] = _F(name, returns_kind, returns_type, params)


_add("chs_abi_version", "scalar", "int32")
_add("chs_build_info", "scalar", "cstr_static")
_add("chs_clickhouse_version", "scalar", "cstr_static")
_add("chs_abi_revision", "scalar", "int")
_add("chs_buf_data", "scalar", "u8ptr_const", _P("buf", "handle", "chs_buf"))
_add("chs_buf_len", "scalar", "size", _P("buf", "handle", "chs_buf"))
_add("chs_buf_free", "void", None, _P("buf", "handle", "chs_buf", nullable=True))
_add("chs_error_status", "enum", "chs_status", _P("error", "handle", "chs_error"))
_add("chs_error_ch_code", "scalar", "int32", _P("error", "handle", "chs_error"))
_add("chs_error_ch_name", "handle", "chs_buf", _P("error", "handle", "chs_error"))
_add("chs_error_message", "handle", "chs_buf", _P("error", "handle", "chs_error"))
_add("chs_error_column", "handle", "chs_buf", _P("error", "handle", "chs_error"))
_add("chs_error_free", "void", None, _P("error", "handle", "chs_error", nullable=True))
_add(
    "chs_live_handles",
    "status",
    "chs_status",
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_error_codes",
    "status",
    "chs_status",
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_registered_families",
    "status",
    "chs_status",
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_function_flags",
    "status",
    "chs_status",
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_reference_type",
    "status",
    "chs_status",
    _P("type_expr", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_initialize",
    "status",
    "chs_status",
    _P("timezone", "bytes_in", None),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_set_defaults",
    "status",
    "chs_status",
    _P("settings", "bytes_in", None),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add("chs_shutdown", "void", None)
_add(
    "chs_type_validate",
    "status",
    "chs_status",
    _P("type_expr", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_back_quote",
    "status",
    "chs_status",
    _P("name", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_back_quote_if_needed",
    "status",
    "chs_status",
    _P("name", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_quote_string",
    "status",
    "chs_status",
    _P("text", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_schema_create",
    "status",
    "chs_status",
    _P("create_table", "bytes_in", None),
    _P("settings", "bytes_in", None),
    _P("out", "out_handle", "chs_schema"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add("chs_schema_free", "void", None, _P("schema", "handle", "chs_schema", nullable=True))
_add(
    "chs_schema_describe",
    "status",
    "chs_status",
    _P("schema", "handle", "chs_schema"),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_preview_row",
    "status",
    "chs_status",
    _P("schema", "handle", "chs_schema"),
    _P("format", "enum", "chs_format"),
    _P("body", "bytes_in", None),
    _P("settings", "bytes_in", None),
    _P("columns", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_preview_batch",
    "status",
    "chs_status",
    _P("schema", "handle", "chs_schema"),
    _P("format", "enum", "chs_format"),
    _P("body", "bytes_in", None),
    _P("settings", "bytes_in", None),
    _P("columns", "bytes_in", None),
    _P("filter", "handle", "chs_filter", nullable=True),
    _P("export_format", "scalar", "int32"),
    _P("doc_flags", "scalar", "uint32"),
    _P("out", "out_handle", "chs_buf"),
    _P("out_export", "out_handle", "chs_buf", nullable=True),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_filter_create",
    "status",
    "chs_status",
    _P("schema", "handle", "chs_schema"),
    _P("expr", "bytes_in", None),
    _P("query_params", "bytes_in", None),
    _P("settings", "bytes_in", None),
    _P("out", "out_handle", "chs_filter"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add("chs_filter_free", "void", None, _P("filter", "handle", "chs_filter", nullable=True))
_add(
    "chs_filter_eval_body",
    "status",
    "chs_status",
    _P("filter", "handle", "chs_filter"),
    _P("format", "enum", "chs_format"),
    _P("body", "bytes_in", None),
    _P("settings", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_block_create",
    "status",
    "chs_status",
    _P("schema", "handle", "chs_schema"),
    _P("format", "enum", "chs_format"),
    _P("body", "bytes_in", None),
    _P("settings", "bytes_in", None),
    _P("columns", "bytes_in", None),
    _P("out", "out_handle", "chs_block"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add("chs_block_free", "void", None, _P("block", "handle", "chs_block", nullable=True))
_add(
    "chs_filter_eval_block",
    "status",
    "chs_status",
    _P("filter", "handle", "chs_filter"),
    _P("block", "handle", "chs_block"),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_discover_query",
    "status",
    "chs_status",
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_discover_columns",
    "status",
    "chs_status",
    _P("rows", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)


def _argtypes(spec: _F) -> list[type]:
    out: list[type] = []
    for p in spec.params:
        if p.kind == "scalar":
            out.append(_CTYPES_NUMERIC[p.type])
        elif p.kind == "enum":
            out.append(ctypes.c_int32)
        elif p.kind == "bytes_in":
            out += [ctypes.c_char_p, ctypes.c_size_t]
        elif p.kind == "handle":
            out.append(ctypes.c_void_p)
        elif p.kind in ("out_handle", "out_error"):
            out.append(ctypes.POINTER(ctypes.c_void_p))
        else:  # out_scalar
            out.append(ctypes.POINTER(_CTYPES_NUMERIC[p.type]))
    return out


def _restype(spec: _F) -> type | None:
    if spec.returns_kind == "status":
        return ctypes.c_int32
    if spec.returns_kind == "void":
        return None
    if spec.returns_kind == "enum":
        return ctypes.c_int32
    if spec.returns_kind == "handle":
        return ctypes.c_void_p
    # scalar
    if spec.returns_type == "cstr_static":
        return ctypes.c_char_p
    if spec.returns_type == "u8ptr_const":
        return ctypes.c_void_p
    return _CTYPES_NUMERIC[spec.returns_type]


def _set_signature(fn: Callable[..., object], spec: _F) -> None:
    fn.argtypes = _argtypes(spec)
    restype = _restype(spec)
    if restype is not None:
        fn.restype = restype


def resolve_abi_version(lib: ctypes.CDLL) -> Callable[..., object]:
    """Loader step 3's dlsym: ctypes resolves a CDLL attribute lazily (a
    dlsym, not a call), so a plain getattr IS the resolution; AttributeError
    is "not present"."""
    try:
        fn = lib.chs_abi_version
    except AttributeError:
        raise MissingSymbol("chs_abi_version") from None
    _set_signature(fn, FUNCTIONS["chs_abi_version"])
    return fn


class Api:
    """Every described symbol, resolved and signature-typed, step 6
    (plan section 3.2). Constructed ONLY by resolve_all(): the constructor
    checks a private key, so a loader that skipped resolution -- and so
    might hold a partially-typed or entirely absent symbol table -- cannot
    silently produce one (the "two-phase table" rule, plan section 2.2)."""

    def __init__(self, lib: ctypes.CDLL, raw: dict, key: object) -> None:
        if key is not _API_KEY:
            raise TypeError("Api is constructed only by resolve_all()")
        self._lib = lib
        self._raw = raw

    def build_info(self) -> bytes | None:
        return self._raw["chs_build_info"]()

    def clickhouse_version(self) -> bytes | None:
        return self._raw["chs_clickhouse_version"]()

    def abi_revision(self) -> int:
        return self._raw["chs_abi_revision"]()

    def initialize(self, timezone: bytes = b"") -> InvokeResult:
        """Loader step 7: the once-per-process image zone (length 0 = UTC).
        process_once: the same spelling again is CHS_OK, a different one is
        CHS_INVALID_ARGUMENT. Returns the generic result so _loader.py never
        spells a chs_ name."""
        return invoke_by_name(self, "chs_initialize", [timezone])


_API_KEY = object()


def resolve_all(lib: ctypes.CDLL) -> Api:
    """Every described symbol, in sorted, deterministic order -- chs_abi_version
    INCLUDED, even though _loader.py's step 3 (resolve_abi_version) already
    resolved it before this runs: the test-only invoke_by_name() dispatcher
    below needs every symbol reachable through ONE Api, handshake class
    included, and re-resolving an already-present symbol is harmless (by the
    time step 6 runs, step 3 has already proven it exists). The first symbol
    ctypes cannot dlsym raises MissingSymbol(name); _loader.py's step 6 turns
    that into "missing_symbol:<name>", matching every missing-<sym> stub
    variant (tests/fixtures/abi-v1/cases.json), chs_build_info and
    chs_clickhouse_version included -- loader step 4 needs chs_build_info
    already resolved, which is exactly why this sweep must run before it."""
    raw: dict = {}
    for name in ALL_SYMBOLS:
        try:
            fn = getattr(lib, name)
        except AttributeError:
            raise MissingSymbol(name) from None
        _set_signature(fn, FUNCTIONS[name])
        raw[name] = fn
    return Api(lib, raw, _API_KEY)


@dataclass
class ErrorInfo:
    status: str
    ch_code: int
    ch_name: bytes
    message: bytes
    column: bytes


@dataclass
class InvokeResult:
    status: str | None = None
    int_value: int | None = None
    bytes_value: bytes | None = None
    error: ErrorInfo | None = None
    outputs: dict[str, bytes] = field(default_factory=dict)
    out_handles: dict[str, Handle] = field(default_factory=dict)
    out_scalars: dict[str, int] = field(default_factory=dict)


def _read_buf(api: Api, ptr: int | None) -> bytes:
    """Read and free an owned chs_buf (an out_handle of that type, or a
    handle-kind return of that type): string_at(data, len) then
    chs_buf_free, matching every caller's "copy then free" contract (plan
    section 2.2's Python row)."""
    if not ptr:
        return b""
    data_ptr = api._raw["chs_buf_data"](ptr)
    n = api._raw["chs_buf_len"](ptr)
    data = b"" if not data_ptr else ctypes.string_at(data_ptr, n)
    api._raw["chs_buf_free"](ptr)
    return data


def _wrap_or_read(
    api: Api, handle_type: str, ptr: int | None
) -> tuple[bytes | None, Handle | None]:
    """A handle-kind value of type chs_buf is read to bytes and freed
    immediately (nothing in this dispatcher holds a chs_buf past the call
    that produced it); any other handle kind is wrapped, alive, for a later
    call to use as an input."""
    if ptr is None or not ptr:
        return (None, None)
    if handle_type == "chs_buf":
        return (_read_buf(api, ptr), None)
    cls = _HANDLE_CLASS[handle_type]
    free = api._raw[HANDLE_FREE[handle_type]]
    return (None, cls(ptr, free))


def _decode_error(api: Api, err_ptr: int) -> ErrorInfo:
    status_val = api._raw["chs_error_status"](err_ptr)
    ch_code = api._raw["chs_error_ch_code"](err_ptr)
    ch_name = _read_buf(api, api._raw["chs_error_ch_name"](err_ptr))
    message = _read_buf(api, api._raw["chs_error_message"](err_ptr))
    column = _read_buf(api, api._raw["chs_error_column"](err_ptr))
    api._raw["chs_error_free"](err_ptr)
    return ErrorInfo(
        status=STATUS_BY_VALUE.get(status_val, f"UNKNOWN:{status_val}"),
        ch_code=ch_code,
        ch_name=ch_name,
        message=message,
        column=column,
    )


def invoke_by_name(api: Api, name: str, args: Iterable[object] = ()) -> InvokeResult:
    """Call the described function `name` generically, from its FUNCTIONS
    entry alone: `args` holds exactly the INPUT parameters (every kind but
    out_handle/out_error/out_scalar), in declaration order, already built as
    Python values -- an int for scalar/enum, bytes for bytes_in (None and 0
    both mean "no bytes"; this dispatcher passes None for either), a Handle
    (or None, where nullable) for handle. Output parameters are never
    supplied by the caller: this dispatcher allocates them, and decodes them
    into the returned InvokeResult. Test-only: every chs_ spelling below is
    why this file, alone in python/src/chtypes/_abi1, carries the generated
    banner check-no-hand-decls.py exempts."""
    spec = FUNCTIONS[name]
    fn = api._raw[name]
    call_args: list[object] = []
    out_handle_params: list[_P] = []
    out_error_present = False
    out_scalar_params: list[_P] = []
    it = iter(args)
    for p in spec.params:
        if p.kind in ("scalar", "enum"):
            call_args.append(int(next(it)))
        elif p.kind == "bytes_in":
            data = next(it)
            if not data:
                call_args += [None, 0]
            else:
                call_args += [data, len(data)]
        elif p.kind == "handle":
            h = next(it)
            call_args.append(None if h is None else h.value)
        elif p.kind == "out_handle":
            var = ctypes.c_void_p()
            out_handle_params.append((p, var))
            call_args.append(ctypes.byref(var))
        elif p.kind == "out_error":
            out_error_present = True
            err_var = ctypes.c_void_p()
            call_args.append(ctypes.byref(err_var))
        else:  # out_scalar
            ctype = _CTYPES_NUMERIC[p.type]
            var = ctype()
            out_scalar_params.append((p, var))
            call_args.append(ctypes.byref(var))

    raw_result = fn(*call_args)
    result = InvokeResult()

    if spec.returns_kind == "status":
        result.status = STATUS_BY_VALUE.get(raw_result, f"UNKNOWN:{raw_result}")
        if result.status != "CHS_OK" and out_error_present and err_var.value:
            result.error = _decode_error(api, err_var.value)
    elif spec.returns_kind == "scalar":
        if spec.returns_type == "cstr_static":
            result.bytes_value = raw_result
        else:
            result.int_value = raw_result
    elif spec.returns_kind == "enum":
        result.int_value = raw_result
    elif spec.returns_kind == "handle":
        data, handle = _wrap_or_read(api, spec.returns_type, raw_result)
        if data is not None:
            result.bytes_value = data
        elif handle is not None:
            result.out_handles["__return__"] = handle

    for p, var in out_handle_params:
        if not var.value:
            continue
        data, handle = _wrap_or_read(api, p.type, var.value)
        if data is not None:
            result.outputs[p.name] = data
        elif handle is not None:
            result.out_handles[p.name] = handle
    for p, var in out_scalar_params:
        result.out_scalars[p.name] = var.value
    return result
