# GENERATED by scripts/abi-v1/gen.py from spec/abi-v1/abi.json (CHS_ABI_FINGERPRINT sha256:b691663f42fb9ca2a872909e73a06fb61836abf92ce552a95b21baf4e006c4ed) — DO NOT EDIT  # noqa: E501
"""spec/abi-v1/sdk.json's error-mapping tables, as references to the
hand-written classes in python/src/chtypes/_abi1/_errors.py. Only the
MAPPING is generated: the classes themselves are stable across a
regeneration (plan section 3.4), so a status renumbering or a new loader
refusal reason changes this file, never _errors.py.
"""

from __future__ import annotations

from . import _errors

# chs_status name -> the sdk.json error-class KEY (an index into CLASS_BY_KEY,
# below); "unknown" covers a status value outside the closed set, which
# cannot happen under a matching fingerprint but is handled rather than
# trusted away (plan section 3.4).
STATUS_CLASS_KEY: dict[str, str | None] = {
    "CHS_OK": None,
    "CHS_REJECTED": "schema",
    "CHS_DECLINED": "unsupported",
    "CHS_INVALID_ARGUMENT": "usage",
    "CHS_INTERNAL": "internal",
}
UNKNOWN_STATUS_CLASS_KEY: str = "internal"

# a loader refusal's BASE reason (before any ":<suffix>") -> the sdk.json
# error-class key.
LOADER_REFUSAL_CLASS_KEY: dict[str, str] = {
    "glibc_floor": "artifact_incompatible",
    "no_glibc": "artifact_incompatible",
    "predicate_malformed": "artifact_incompatible",
    "dlopen": "artifact_incompatible",
    "not_v1": "artifact_incompatible",
    "abi_version": "artifact_incompatible",
    "build_info_malformed": "artifact_corrupt",
    "fingerprint": "artifact_incompatible",
    "build_info_mismatch": "artifact_corrupt",
    "missing_symbol": "artifact_incompatible",
}

# sdk.json error-class key -> the actual exception class.
CLASS_BY_KEY: dict[str, type[_errors.Abi1Error]] = {
    "schema": _errors.SchemaError,
    "unsupported": _errors.UnsupportedError,
    "usage": _errors.UsageError,
    "internal": _errors.InternalError,
    "artifact_incompatible": _errors.ArtifactIncompatibleError,
    "artifact_corrupt": _errors.ArtifactCorruptError,
}

# sdk.json's error codes (reserved exit-status names; plan section 3.4, Q-m).
ERROR_CODES: dict[str, str] = {
    "artifact_incompatible": "CHTYPES_ARTIFACT_INCOMPATIBLE",
    "artifact_corrupt": "CHTYPES_ARTIFACT_CORRUPT",
}


def call_error_class(status: str) -> type[_errors.Abi1Error] | None:
    """The exception class a `status` other than CHS_OK maps to, or None for
    CHS_OK itself."""
    key = STATUS_CLASS_KEY.get(status, UNKNOWN_STATUS_CLASS_KEY)
    return None if key is None else CLASS_BY_KEY[key]


def loader_error_class(reason: str) -> type[_errors.Abi1Error]:
    """The exception class a loader refusal `reason` (its base, before any
    ":<suffix>") maps to."""
    base = reason.split(":", 1)[0]
    return CLASS_BY_KEY[LOADER_REFUSAL_CLASS_KEY[base]]
