// GENERATED by scripts/abi-v1/gen.py --major 2 from spec/abi-v2/abi.json (CHS_ABI_FINGERPRINT sha256:8ec0c6941f000aa07bfb9fbfef20205d3ee0a588833856bd12270ba42912bfb3) — DO NOT EDIT

package abi2

// StatusClass maps a chs_status NAME to spec/abi-v2/sdk.json's errors.classes
// key ("" for CHS_OK, which never becomes an error). An unrecognized name --
// never possible under a matching fingerprint -- reads as sdk.json's own
// "unknown" fallback, so a caller still fails closed instead of panicking.
func StatusClass(status string) string {
	switch status {
	case "CHS_OK":
		return ""
	case "CHS_REJECTED":
		return "schema"
	case "CHS_DECLINED":
		return "unsupported"
	case "CHS_INVALID_ARGUMENT":
		return "usage"
	case "CHS_INTERNAL":
		return "internal"
	default:
		return "internal"
	}
}
