// GENERATED by scripts/abi-v1/gen.py --major 2 from spec/abi-v2/abi.json (CHS_ABI_FINGERPRINT sha256:4129dccc3f4e698dedb0e99cae413f5240085f633c5a1244e2c55bf7a7bb6c3a) — DO NOT EDIT

//go:build chtypes_linked

package abi2

/*
// The header is this repository's own include/v2/chtypes.h -- the SDK owns the
// contract. A full LINK (never needed by scripts/abi-v1/check-linked.sh's
// type-check alone) additionally needs CGO_LDFLAGS naming where libchtypes
// lives.
#cgo CFLAGS: -I${SRCDIR}/../../../include/v2
#cgo LDFLAGS: -lchtypes
#include "abi2_table.h"
#include "chtypes.h"
#if !defined(CHS_ABI_VERSION) || CHS_ABI_VERSION != 2
#error "go/internal/abi2 is ABI v2: its -I must reach include/v2/chtypes.h"
#endif

// Every address below is resolved by the LINKER, at build time: a described
// symbol chtypes.h does not declare is a link error here, not a runtime one, so
// this fill can never report a missing symbol the way the dlopen path's step 6
// can -- linked mode runs steps 3, 4 and 6, and 6 is trivially satisfied.
static void chtypes_abi2_linked_fill(struct chtypes_abi2_table *t) {
    t->chs_abi_version = (chtypes_abi2_fn_chs_abi_version) &chs_abi_version;
    t->chs_build_info = (chtypes_abi2_fn_chs_build_info) &chs_build_info;
    t->chs_clickhouse_version = (chtypes_abi2_fn_chs_clickhouse_version) &chs_clickhouse_version;
    t->chs_abi_revision = (chtypes_abi2_fn_chs_abi_revision) &chs_abi_revision;
    t->chs_buf_data = (chtypes_abi2_fn_chs_buf_data) &chs_buf_data;
    t->chs_buf_len = (chtypes_abi2_fn_chs_buf_len) &chs_buf_len;
    t->chs_buf_free = (chtypes_abi2_fn_chs_buf_free) &chs_buf_free;
    t->chs_error_status = (chtypes_abi2_fn_chs_error_status) &chs_error_status;
    t->chs_error_ch_code = (chtypes_abi2_fn_chs_error_ch_code) &chs_error_ch_code;
    t->chs_error_ch_name = (chtypes_abi2_fn_chs_error_ch_name) &chs_error_ch_name;
    t->chs_error_message = (chtypes_abi2_fn_chs_error_message) &chs_error_message;
    t->chs_error_column = (chtypes_abi2_fn_chs_error_column) &chs_error_column;
    t->chs_error_free = (chtypes_abi2_fn_chs_error_free) &chs_error_free;
    t->chs_live_handles = (chtypes_abi2_fn_chs_live_handles) &chs_live_handles;
    t->chs_error_codes = (chtypes_abi2_fn_chs_error_codes) &chs_error_codes;
    t->chs_registered_families = (chtypes_abi2_fn_chs_registered_families) &chs_registered_families;
    t->chs_function_flags = (chtypes_abi2_fn_chs_function_flags) &chs_function_flags;
    t->chs_reference_type = (chtypes_abi2_fn_chs_reference_type) &chs_reference_type;
    t->chs_initialize = (chtypes_abi2_fn_chs_initialize) &chs_initialize;
    t->chs_set_defaults = (chtypes_abi2_fn_chs_set_defaults) &chs_set_defaults;
    t->chs_shutdown = (chtypes_abi2_fn_chs_shutdown) &chs_shutdown;
    t->chs_type_validate = (chtypes_abi2_fn_chs_type_validate) &chs_type_validate;
    t->chs_back_quote = (chtypes_abi2_fn_chs_back_quote) &chs_back_quote;
    t->chs_back_quote_if_needed = (chtypes_abi2_fn_chs_back_quote_if_needed) &chs_back_quote_if_needed;
    t->chs_quote_string = (chtypes_abi2_fn_chs_quote_string) &chs_quote_string;
    t->chs_server_create = (chtypes_abi2_fn_chs_server_create) &chs_server_create;
    t->chs_server_free = (chtypes_abi2_fn_chs_server_free) &chs_server_free;
    t->chs_schema_create = (chtypes_abi2_fn_chs_schema_create) &chs_schema_create;
    t->chs_schema_free = (chtypes_abi2_fn_chs_schema_free) &chs_schema_free;
    t->chs_schema_describe = (chtypes_abi2_fn_chs_schema_describe) &chs_schema_describe;
    t->chs_preview_row = (chtypes_abi2_fn_chs_preview_row) &chs_preview_row;
    t->chs_preview_batch = (chtypes_abi2_fn_chs_preview_batch) &chs_preview_batch;
    t->chs_filter_create = (chtypes_abi2_fn_chs_filter_create) &chs_filter_create;
    t->chs_filter_free = (chtypes_abi2_fn_chs_filter_free) &chs_filter_free;
    t->chs_filter_eval_body = (chtypes_abi2_fn_chs_filter_eval_body) &chs_filter_eval_body;
    t->chs_block_create = (chtypes_abi2_fn_chs_block_create) &chs_block_create;
    t->chs_block_free = (chtypes_abi2_fn_chs_block_free) &chs_block_free;
    t->chs_filter_eval_block = (chtypes_abi2_fn_chs_filter_eval_block) &chs_filter_eval_block;
    t->chs_discover_query = (chtypes_abi2_fn_chs_discover_query) &chs_discover_query;
    t->chs_discover_columns = (chtypes_abi2_fn_chs_discover_columns) &chs_discover_columns;
}
*/
import "C"

// OpenLinked fills a Table from the statically linked library: no dlopen, no
// dlsym, nothing to ever dlclose (there is no separate image to close).
func OpenLinked() *Table {
	t := &Table{}
	C.chtypes_abi2_linked_fill(&t.tbl)
	return t
}
