# GENERATED by scripts/abi-v1/gen.py --major 2 from spec/abi-v2/abi.json (CHS_ABI_FINGERPRINT sha256:8ec0c6941f000aa07bfb9fbfef20205d3ee0a588833856bd12270ba42912bfb3) — DO NOT EDIT  # noqa: E501
"""The Python binding's generated ABI v2 layer: ctypes signatures, the handle
classes, the two-phase resolve functions and invoke_by_name(), the test-only
dispatcher the conformance suite drives from tests/fixtures/abi-v2/cases.json.
See scripts/abi-v1/emit/python.py's module docstring for the design this file
implements and why. This is the ONLY python/src/chtypes/_abi2 file that reads
a chs_* attribute (scripts/abi-v1/check-no-hand-decls.py exempts it by its
banner, above); every other file in this package calls the non-chs_-prefixed
names this module exposes instead.
"""

from __future__ import annotations

import ctypes
import threading
from collections.abc import Callable, Iterable
from dataclasses import dataclass, field

from . import _errmap

CHS_ABI_VERSION = 2
CHS_ABI_FINGERPRINT = "sha256:8ec0c6941f000aa07bfb9fbfef20205d3ee0a588833856bd12270ba42912bfb3"

# The description's stability: "unstable" while this generation is being
# designed, so CHS_ABI_FINGERPRINT moves with every change, and "locked" after
# (spec/abi-v2/docs.md, rule r6). A dev SDK refuses any other fingerprint with
# the dev message (_loader.py).
CHS_ABI_STABILITY = "unstable"

# sdk.json's loader.cross_check: (build_info field, predicate field, how to
# compare), read by _loader.py's step 5 without it ever touching sdk.json
# itself (not part of the installed package).
CROSS_CHECK_FIELDS: tuple[tuple[str, str, str], ...] = (
    ("abi", "abi", "int"),
    ("abi_fingerprint", "abi_fingerprint", "bytes"),
    ("clickhouse_version", "clickhouse_version", "bytes"),
    ("channel", "channel", "bytes"),
    ("build", "build", "bytes"),
    ("os", "os", "bytes"),
    ("arch", "arch", "bytes"),
    ("core_commit", "core_commit", "bytes"),
    ("inputs_sha256", "inputs_sha256", "bytes"),
)

# chs_status's values, both directions. Frozen by D3, but still generated
# from the description rather than hand-copied, so a future enum change is a
# regeneration, never a drift.
STATUS_BY_VALUE: dict[int, str] = {
    0: "CHS_OK",
    1: "CHS_REJECTED",
    2: "CHS_DECLINED",
    3: "CHS_INVALID_ARGUMENT",
    4: "CHS_INTERNAL",
}
STATUS_BY_NAME: dict[str, int] = {v: k for k, v in STATUS_BY_VALUE.items()}
_STATUS_OK = 0

# handle type name -> its free function's name (never called directly outside
# this file: Handle.close() holds the bound method, resolved once in
# resolve_all()).
HANDLE_FREE: dict[str, str] = {
    "chs_buf": "chs_buf_free",
    "chs_error": "chs_error_free",
    "chs_schema": "chs_schema_free",
    "chs_filter": "chs_filter_free",
    "chs_block": "chs_block_free",
}

ALL_SYMBOLS: tuple[str, ...] = (
    "chs_abi_revision",
    "chs_abi_version",
    "chs_back_quote",
    "chs_back_quote_if_needed",
    "chs_block_create",
    "chs_block_free",
    "chs_buf_data",
    "chs_buf_free",
    "chs_buf_len",
    "chs_build_info",
    "chs_clickhouse_version",
    "chs_discover_columns",
    "chs_discover_query",
    "chs_error_ch_code",
    "chs_error_ch_name",
    "chs_error_codes",
    "chs_error_column",
    "chs_error_free",
    "chs_error_message",
    "chs_error_status",
    "chs_filter_create",
    "chs_filter_eval_block",
    "chs_filter_eval_body",
    "chs_filter_free",
    "chs_function_flags",
    "chs_initialize",
    "chs_live_handles",
    "chs_preview_batch",
    "chs_preview_row",
    "chs_quote_string",
    "chs_reference_type",
    "chs_registered_families",
    "chs_schema_create",
    "chs_schema_describe",
    "chs_schema_free",
    "chs_set_defaults",
    "chs_shutdown",
    "chs_type_validate",
)
HANDSHAKE_NAMES: tuple[str, ...] = (
    "chs_abi_version",
    "chs_build_info",
    "chs_clickhouse_version",
)

_CTYPES_NUMERIC: dict[str, type] = {
    "int": ctypes.c_int,
    "int32": ctypes.c_int32,
    "uint32": ctypes.c_uint32,
    "int64": ctypes.c_int64,
    "uint64": ctypes.c_uint64,
    "size": ctypes.c_size_t,
}


class MissingSymbol(Exception):
    """Step 3 or step 6 (plan section 3.2) could not resolve `name` in the
    opened library -- ctypes' own getattr-is-dlsym behavior raised
    AttributeError, which this file turns into a named exception so
    _loader.py never has to spell a chs_ name to report which one."""

    def __init__(self, name: str) -> None:
        super().__init__(name)
        self.name = name


class Handle:
    """A reference-counted, kind- and image-tagged C handle (D2): closing it
    releases this binding's own reference, any number of times, from any
    thread, in any order relative to other handles -- never from a __del__
    racing a live reference elsewhere, since CPython only runs a finalizer
    once nothing refers to the object. `value` is the raw pointer (an int,
    for echo/identity comparisons in the conformance suite) or None once
    closed."""

    __slots__ = ("_closed", "_free", "_ptr")

    def __init__(self, ptr: int, free: Callable[..., object]) -> None:
        self._ptr = ptr
        self._free = free
        self._closed = ptr is None or ptr == 0

    @property
    def value(self) -> int | None:
        return None if self._closed else self._ptr

    def close(self) -> None:
        if not self._closed:
            self._free(self._ptr)
            self._closed = True
            self._ptr = None

    def __del__(self) -> None:
        try:
            self.close()
        except Exception:  # noqa: BLE001 - a finalizer must never raise
            pass


class BufHandle(Handle):
    """A `chs_buf` the library owns the free function for."""


class ErrorHandle(Handle):
    """A `chs_error` the library owns the free function for."""


class SchemaHandle(Handle):
    """A `chs_schema` the library owns the free function for."""


class FilterHandle(Handle):
    """A `chs_filter` the library owns the free function for."""


class BlockHandle(Handle):
    """A `chs_block` the library owns the free function for."""


_HANDLE_CLASS: dict[str, type[Handle]] = {
    "chs_buf": BufHandle,
    "chs_error": ErrorHandle,
    "chs_schema": SchemaHandle,
    "chs_filter": FilterHandle,
    "chs_block": BlockHandle,
}


@dataclass(frozen=True)
class _P:
    """One function parameter, as the description's closed param-kind
    vocabulary (model.py's PARAM_KINDS) names it: scalar | enum | bytes_in |
    handle | out_handle | out_error | out_scalar. `type` is a scalar name, a
    handle type name, or None (bytes_in, out_error)."""

    name: str
    kind: str
    type: str | None
    nullable: bool = False


@dataclass(frozen=True)
class _F:
    """One described function: its return shape and its parameters, in
    declaration order -- everything invoke_by_name() and the signature
    setters need, read generically rather than unrolled per function, so a
    regeneration changes only FUNCTIONS, never this interpreter."""

    name: str
    returns_kind: str
    returns_type: str | None
    params: tuple[_P, ...] = ()


FUNCTIONS: dict[str, _F] = {}


def _add(name: str, returns_kind: str, returns_type: str | None, *params: _P) -> None:
    FUNCTIONS[name] = _F(name, returns_kind, returns_type, params)


_add("chs_abi_version", "scalar", "int32")
_add("chs_build_info", "scalar", "cstr_static")
_add("chs_clickhouse_version", "scalar", "cstr_static")
_add("chs_abi_revision", "scalar", "int")
_add("chs_buf_data", "scalar", "u8ptr_const", _P("buf", "handle", "chs_buf"))
_add("chs_buf_len", "scalar", "size", _P("buf", "handle", "chs_buf"))
_add("chs_buf_free", "void", None, _P("buf", "handle", "chs_buf", nullable=True))
_add("chs_error_status", "enum", "chs_status", _P("error", "handle", "chs_error"))
_add("chs_error_ch_code", "scalar", "int32", _P("error", "handle", "chs_error"))
_add("chs_error_ch_name", "handle", "chs_buf", _P("error", "handle", "chs_error"))
_add("chs_error_message", "handle", "chs_buf", _P("error", "handle", "chs_error"))
_add("chs_error_column", "handle", "chs_buf", _P("error", "handle", "chs_error"))
_add("chs_error_free", "void", None, _P("error", "handle", "chs_error", nullable=True))
_add(
    "chs_live_handles",
    "status",
    "chs_status",
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_error_codes",
    "status",
    "chs_status",
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_registered_families",
    "status",
    "chs_status",
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_function_flags",
    "status",
    "chs_status",
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_reference_type",
    "status",
    "chs_status",
    _P("type_expr", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_initialize",
    "status",
    "chs_status",
    _P("timezone", "bytes_in", None),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_set_defaults",
    "status",
    "chs_status",
    _P("settings", "bytes_in", None),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add("chs_shutdown", "void", None)
_add(
    "chs_type_validate",
    "status",
    "chs_status",
    _P("type_expr", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_back_quote",
    "status",
    "chs_status",
    _P("name", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_back_quote_if_needed",
    "status",
    "chs_status",
    _P("name", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_quote_string",
    "status",
    "chs_status",
    _P("text", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_schema_create",
    "status",
    "chs_status",
    _P("create_table", "bytes_in", None),
    _P("settings", "bytes_in", None),
    _P("out", "out_handle", "chs_schema"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add("chs_schema_free", "void", None, _P("schema", "handle", "chs_schema", nullable=True))
_add(
    "chs_schema_describe",
    "status",
    "chs_status",
    _P("schema", "handle", "chs_schema"),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_preview_row",
    "status",
    "chs_status",
    _P("schema", "handle", "chs_schema"),
    _P("format", "enum", "chs_format"),
    _P("body", "bytes_in", None),
    _P("settings", "bytes_in", None),
    _P("columns", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_preview_batch",
    "status",
    "chs_status",
    _P("schema", "handle", "chs_schema"),
    _P("format", "enum", "chs_format"),
    _P("body", "bytes_in", None),
    _P("settings", "bytes_in", None),
    _P("columns", "bytes_in", None),
    _P("filter", "handle", "chs_filter", nullable=True),
    _P("export_format", "scalar", "int32"),
    _P("doc_flags", "scalar", "uint32"),
    _P("out", "out_handle", "chs_buf"),
    _P("out_export", "out_handle", "chs_buf", nullable=True),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_filter_create",
    "status",
    "chs_status",
    _P("schema", "handle", "chs_schema"),
    _P("expr", "bytes_in", None),
    _P("query_params", "bytes_in", None),
    _P("settings", "bytes_in", None),
    _P("out", "out_handle", "chs_filter"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add("chs_filter_free", "void", None, _P("filter", "handle", "chs_filter", nullable=True))
_add(
    "chs_filter_eval_body",
    "status",
    "chs_status",
    _P("filter", "handle", "chs_filter"),
    _P("format", "enum", "chs_format"),
    _P("body", "bytes_in", None),
    _P("settings", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_block_create",
    "status",
    "chs_status",
    _P("schema", "handle", "chs_schema"),
    _P("format", "enum", "chs_format"),
    _P("body", "bytes_in", None),
    _P("settings", "bytes_in", None),
    _P("columns", "bytes_in", None),
    _P("out", "out_handle", "chs_block"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add("chs_block_free", "void", None, _P("block", "handle", "chs_block", nullable=True))
_add(
    "chs_filter_eval_block",
    "status",
    "chs_status",
    _P("filter", "handle", "chs_filter"),
    _P("block", "handle", "chs_block"),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_discover_query",
    "status",
    "chs_status",
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)
_add(
    "chs_discover_columns",
    "status",
    "chs_status",
    _P("rows", "bytes_in", None),
    _P("out", "out_handle", "chs_buf"),
    _P("err", "out_error", "chs_error", nullable=True),
)


def _argtypes(spec: _F) -> list[type]:
    out: list[type] = []
    for p in spec.params:
        if p.kind == "scalar":
            out.append(_CTYPES_NUMERIC[p.type])
        elif p.kind == "enum":
            out.append(ctypes.c_int32)
        elif p.kind == "bytes_in":
            out += [ctypes.c_char_p, ctypes.c_size_t]
        elif p.kind == "handle":
            out.append(ctypes.c_void_p)
        elif p.kind in ("out_handle", "out_error"):
            out.append(ctypes.POINTER(ctypes.c_void_p))
        else:  # out_scalar
            out.append(ctypes.POINTER(_CTYPES_NUMERIC[p.type]))
    return out


def _restype(spec: _F) -> type | None:
    if spec.returns_kind == "status":
        return ctypes.c_int32
    if spec.returns_kind == "void":
        return None
    if spec.returns_kind == "enum":
        return ctypes.c_int32
    if spec.returns_kind == "handle":
        return ctypes.c_void_p
    # scalar
    if spec.returns_type == "cstr_static":
        return ctypes.c_char_p
    if spec.returns_type == "u8ptr_const":
        return ctypes.c_void_p
    return _CTYPES_NUMERIC[spec.returns_type]


def _set_signature(fn: Callable[..., object], spec: _F) -> None:
    fn.argtypes = _argtypes(spec)
    restype = _restype(spec)
    if restype is not None:
        fn.restype = restype


def resolve_abi_version(lib: ctypes.CDLL) -> Callable[..., object]:
    """Loader step 3's dlsym: ctypes resolves a CDLL attribute lazily (a
    dlsym, not a call), so a plain getattr IS the resolution; AttributeError
    is "not present"."""
    try:
        fn = lib.chs_abi_version
    except AttributeError:
        raise MissingSymbol("chs_abi_version") from None
    _set_signature(fn, FUNCTIONS["chs_abi_version"])
    return fn


def resolve_build_info(lib: ctypes.CDLL) -> Callable[..., object]:
    """Loader step 4's dlsym: `chs_build_info` ALONE, so the fingerprint can be
    compared before step 6's full sweep (rule r6 beats a missing symbol,
    public issue #537). Absent is MissingSymbol, the step 4 refusal."""
    try:
        fn = lib.chs_build_info
    except AttributeError:
        raise MissingSymbol("chs_build_info") from None
    _set_signature(fn, FUNCTIONS["chs_build_info"])
    return fn


class Api:
    """Every described symbol, resolved and signature-typed, step 6
    (plan section 3.2). Constructed ONLY by resolve_all(): the constructor
    checks a private key, so a loader that skipped resolution -- and so
    might hold a partially-typed or entirely absent symbol table -- cannot
    silently produce one (the "two-phase table" rule, plan section 2.2)."""

    def __init__(self, lib: ctypes.CDLL, raw: dict, key: object) -> None:
        if key is not _API_KEY:
            raise TypeError("Api is constructed only by resolve_all()")
        self._lib = lib
        self._raw = raw
        self._process_lock = threading.RLock()

    def build_info(self) -> bytes | None:
        return self._raw["chs_build_info"]()

    def clickhouse_version(self) -> bytes | None:
        return self._raw["chs_clickhouse_version"]()

    def abi_revision(self) -> int:
        return self._raw["chs_abi_revision"]()

    def _check(self, status: int, err: ctypes.c_void_p | None) -> None:
        """Turn a non-OK `status` into the class the description maps it to,
        carrying the `chs_error` fields read verbatim (and freed) -- or, for a
        status outside the closed set, an InternalError naming its value."""
        if status == _STATUS_OK:
            return
        info = None
        if err is not None and err.value:
            info = _decode_error(self, err.value)
        name = STATUS_BY_VALUE.get(status, f"UNKNOWN:{status}")
        cls = _errmap.call_error_class(name)
        message = info.message if info else b""
        if name not in STATUS_BY_NAME:
            message = f"call status unknown({status}) is outside the closed set".encode() + (
                b": " + message if message else b""
            )
        raise cls(
            status,
            info.ch_code if info else 0,
            info.ch_name.decode("ascii", "replace") if info else "",
            message,
            info.column if info else b"",
        )

    def live_handles(self) -> bytes:
        """The generated call wrapper for chs_live_handles (thread class any).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_live_handles"](
            ctypes.byref(out),
            ctypes.byref(err),
        )
        self._check(status, err)
        return _read_buf(self, out.value)

    def error_codes(self) -> bytes:
        """The generated call wrapper for chs_error_codes (thread class any).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_error_codes"](
            ctypes.byref(out),
            ctypes.byref(err),
        )
        self._check(status, err)
        return _read_buf(self, out.value)

    def registered_families(self) -> bytes:
        """The generated call wrapper for chs_registered_families (thread class process_serial).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        with self._process_lock:
            status = self._raw["chs_registered_families"](
                ctypes.byref(out),
                ctypes.byref(err),
            )
        self._check(status, err)
        return _read_buf(self, out.value)

    def function_flags(self) -> bytes:
        """The generated call wrapper for chs_function_flags (thread class process_serial).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        with self._process_lock:
            status = self._raw["chs_function_flags"](
                ctypes.byref(out),
                ctypes.byref(err),
            )
        self._check(status, err)
        return _read_buf(self, out.value)

    def reference_type(
        self,
        type_expr: bytes | None,
    ) -> bytes:
        """The generated call wrapper for chs_reference_type (thread class process_serial).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        with self._process_lock:
            status = self._raw["chs_reference_type"](
                *_bytes_in(type_expr),
                ctypes.byref(out),
                ctypes.byref(err),
            )
        self._check(status, err)
        return _read_buf(self, out.value)

    def initialize(
        self,
        timezone: bytes | None,
    ) -> None:
        """The generated call wrapper for chs_initialize (thread class process_once).

        Raises the class the status maps to on a non-OK status."""
        err = ctypes.c_void_p()
        with self._process_lock:
            status = self._raw["chs_initialize"](
                *_bytes_in(timezone),
                ctypes.byref(err),
            )
        self._check(status, err)

    def set_defaults(
        self,
        settings: bytes | None,
    ) -> None:
        """The generated call wrapper for chs_set_defaults (thread class process_serial).

        Raises the class the status maps to on a non-OK status."""
        err = ctypes.c_void_p()
        with self._process_lock:
            status = self._raw["chs_set_defaults"](
                *_bytes_in(settings),
                ctypes.byref(err),
            )
        self._check(status, err)

    def type_validate(
        self,
        type_expr: bytes | None,
    ) -> bytes:
        """The generated call wrapper for chs_type_validate (thread class any).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_type_validate"](
            *_bytes_in(type_expr),
            ctypes.byref(out),
            ctypes.byref(err),
        )
        self._check(status, err)
        return _read_buf(self, out.value)

    def back_quote(
        self,
        name: bytes | None,
    ) -> bytes:
        """The generated call wrapper for chs_back_quote (thread class any).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_back_quote"](
            *_bytes_in(name),
            ctypes.byref(out),
            ctypes.byref(err),
        )
        self._check(status, err)
        return _read_buf(self, out.value)

    def back_quote_if_needed(
        self,
        name: bytes | None,
    ) -> bytes:
        """The generated call wrapper for chs_back_quote_if_needed (thread class any).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_back_quote_if_needed"](
            *_bytes_in(name),
            ctypes.byref(out),
            ctypes.byref(err),
        )
        self._check(status, err)
        return _read_buf(self, out.value)

    def quote_string(
        self,
        text: bytes | None,
    ) -> bytes:
        """The generated call wrapper for chs_quote_string (thread class any).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_quote_string"](
            *_bytes_in(text),
            ctypes.byref(out),
            ctypes.byref(err),
        )
        self._check(status, err)
        return _read_buf(self, out.value)

    def schema_create(
        self,
        create_table: bytes | None,
        settings: bytes | None,
    ) -> SchemaHandle:
        """The generated call wrapper for chs_schema_create (thread class any).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_schema_create"](
            *_bytes_in(create_table),
            *_bytes_in(settings),
            ctypes.byref(out),
            ctypes.byref(err),
        )
        self._check(status, err)
        return SchemaHandle(out.value, self._raw["chs_schema_free"])

    def schema_describe(
        self,
        schema: SchemaHandle,
    ) -> bytes:
        """The generated call wrapper for chs_schema_describe (thread class shared).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_schema_describe"](
            schema.value,
            ctypes.byref(out),
            ctypes.byref(err),
        )
        self._check(status, err)
        return _read_buf(self, out.value)

    def preview_row(
        self,
        schema: SchemaHandle,
        format: int,
        body: bytes | None,
        settings: bytes | None,
        columns: bytes | None,
    ) -> bytes:
        """The generated call wrapper for chs_preview_row (thread class shared).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_preview_row"](
            schema.value,
            int(format),
            *_bytes_in(body),
            *_bytes_in(settings),
            *_bytes_in(columns),
            ctypes.byref(out),
            ctypes.byref(err),
        )
        self._check(status, err)
        return _read_buf(self, out.value)

    def preview_batch(
        self,
        schema: SchemaHandle,
        format: int,
        body: bytes | None,
        settings: bytes | None,
        columns: bytes | None,
        filter: FilterHandle | None,
        export_format: int,
        doc_flags: int,
    ) -> tuple[bytes, bytes | None]:
        """The generated call wrapper for chs_preview_batch (thread class shared).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        out_export = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_preview_batch"](
            schema.value,
            int(format),
            *_bytes_in(body),
            *_bytes_in(settings),
            *_bytes_in(columns),
            None if filter is None else filter.value,
            int(export_format),
            int(doc_flags),
            ctypes.byref(out),
            ctypes.byref(out_export),
            ctypes.byref(err),
        )
        self._check(status, err)
        return (
            _read_buf(self, out.value),
            None if not out_export.value else _read_buf(self, out_export.value),
        )

    def filter_create(
        self,
        schema: SchemaHandle,
        expr: bytes | None,
        query_params: bytes | None,
        settings: bytes | None,
    ) -> FilterHandle:
        """The generated call wrapper for chs_filter_create (thread class shared).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_filter_create"](
            schema.value,
            *_bytes_in(expr),
            *_bytes_in(query_params),
            *_bytes_in(settings),
            ctypes.byref(out),
            ctypes.byref(err),
        )
        self._check(status, err)
        return FilterHandle(out.value, self._raw["chs_filter_free"])

    def filter_eval_body(
        self,
        filter: FilterHandle,
        format: int,
        body: bytes | None,
        settings: bytes | None,
    ) -> bytes:
        """The generated call wrapper for chs_filter_eval_body (thread class shared).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_filter_eval_body"](
            filter.value,
            int(format),
            *_bytes_in(body),
            *_bytes_in(settings),
            ctypes.byref(out),
            ctypes.byref(err),
        )
        self._check(status, err)
        return _read_buf(self, out.value)

    def block_create(
        self,
        schema: SchemaHandle,
        format: int,
        body: bytes | None,
        settings: bytes | None,
        columns: bytes | None,
    ) -> BlockHandle:
        """The generated call wrapper for chs_block_create (thread class shared).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_block_create"](
            schema.value,
            int(format),
            *_bytes_in(body),
            *_bytes_in(settings),
            *_bytes_in(columns),
            ctypes.byref(out),
            ctypes.byref(err),
        )
        self._check(status, err)
        return BlockHandle(out.value, self._raw["chs_block_free"])

    def filter_eval_block(
        self,
        filter: FilterHandle,
        block: BlockHandle,
    ) -> bytes:
        """The generated call wrapper for chs_filter_eval_block (thread class shared).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_filter_eval_block"](
            filter.value,
            block.value,
            ctypes.byref(out),
            ctypes.byref(err),
        )
        self._check(status, err)
        return _read_buf(self, out.value)

    def discover_query(self) -> bytes:
        """The generated call wrapper for chs_discover_query (thread class any).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_discover_query"](
            ctypes.byref(out),
            ctypes.byref(err),
        )
        self._check(status, err)
        return _read_buf(self, out.value)

    def discover_columns(
        self,
        rows: bytes | None,
    ) -> bytes:
        """The generated call wrapper for chs_discover_columns (thread class any).

        Raises the class the status maps to on a non-OK status."""
        out = ctypes.c_void_p()
        err = ctypes.c_void_p()
        status = self._raw["chs_discover_columns"](
            *_bytes_in(rows),
            ctypes.byref(out),
            ctypes.byref(err),
        )
        self._check(status, err)
        return _read_buf(self, out.value)


_API_KEY = object()


def resolve_all(lib: ctypes.CDLL) -> Api:
    """Every described symbol, in sorted, deterministic order -- the handshake
    symbols INCLUDED, even though _loader.py's steps 3 and 4 (resolve_abi_version,
    resolve_build_info) already resolved theirs before this runs: the test-only
    invoke_by_name() dispatcher below needs every symbol reachable through ONE
    Api, and re-resolving an already-present symbol is harmless. The first
    symbol ctypes cannot dlsym raises MissingSymbol(name); _loader.py's step 6
    turns that into "missing_symbol:<name>", matching every missing-<sym> stub
    variant. Step 6 runs AFTER step 4's fingerprint comparison, so a library
    with another fingerprint is refused with rule r6's message first."""
    raw: dict = {}
    for name in ALL_SYMBOLS:
        try:
            fn = getattr(lib, name)
        except AttributeError:
            raise MissingSymbol(name) from None
        _set_signature(fn, FUNCTIONS[name])
        raw[name] = fn
    return Api(lib, raw, _API_KEY)


@dataclass
class ErrorInfo:
    status: str
    ch_code: int
    ch_name: bytes
    message: bytes
    column: bytes


@dataclass
class InvokeResult:
    status: str | None = None
    int_value: int | None = None
    bytes_value: bytes | None = None
    error: ErrorInfo | None = None
    outputs: dict[str, bytes] = field(default_factory=dict)
    out_handles: dict[str, Handle] = field(default_factory=dict)
    out_scalars: dict[str, int] = field(default_factory=dict)


def _bytes_in(data: bytes | None) -> tuple[bytes | None, int]:
    """A `bytes_in` parameter's two C arguments: (NULL, 0) for empty or
    absent, else the bytes and their own length. ctypes hands a `bytes`
    object's buffer over without scanning for a NUL, so NUL and invalid UTF-8
    cross intact; any other bytes-like object is copied to `bytes` first."""
    if not data:
        return None, 0
    if not isinstance(data, bytes):
        data = bytes(data)
    return data, len(data)


def _read_buf(api: Api, ptr: int | None) -> bytes:
    """Read and free an owned chs_buf (an out_handle of that type, or a
    handle-kind return of that type): string_at(data, len) then
    chs_buf_free, matching every caller's "copy then free" contract (plan
    section 2.2's Python row)."""
    if not ptr:
        return b""
    data_ptr = api._raw["chs_buf_data"](ptr)
    n = api._raw["chs_buf_len"](ptr)
    data = b"" if not data_ptr else ctypes.string_at(data_ptr, n)
    api._raw["chs_buf_free"](ptr)
    return data


def _wrap_or_read(
    api: Api, handle_type: str, ptr: int | None
) -> tuple[bytes | None, Handle | None]:
    """A handle-kind value of type chs_buf is read to bytes and freed
    immediately (nothing in this dispatcher holds a chs_buf past the call
    that produced it); any other handle kind is wrapped, alive, for a later
    call to use as an input."""
    if ptr is None or not ptr:
        return (None, None)
    if handle_type == "chs_buf":
        return (_read_buf(api, ptr), None)
    cls = _HANDLE_CLASS[handle_type]
    free = api._raw[HANDLE_FREE[handle_type]]
    return (None, cls(ptr, free))


def _decode_error(api: Api, err_ptr: int) -> ErrorInfo:
    status_val = api._raw["chs_error_status"](err_ptr)
    ch_code = api._raw["chs_error_ch_code"](err_ptr)
    ch_name = _read_buf(api, api._raw["chs_error_ch_name"](err_ptr))
    message = _read_buf(api, api._raw["chs_error_message"](err_ptr))
    column = _read_buf(api, api._raw["chs_error_column"](err_ptr))
    api._raw["chs_error_free"](err_ptr)
    return ErrorInfo(
        status=STATUS_BY_VALUE.get(status_val, f"UNKNOWN:{status_val}"),
        ch_code=ch_code,
        ch_name=ch_name,
        message=message,
        column=column,
    )


def invoke_by_name(api: Api, name: str, args: Iterable[object] = ()) -> InvokeResult:
    """Call the described function `name` generically, from its FUNCTIONS
    entry alone: `args` holds exactly the INPUT parameters (every kind but
    out_handle/out_error/out_scalar), in declaration order, already built as
    Python values -- an int for scalar/enum, bytes for bytes_in (None and 0
    both mean "no bytes"; this dispatcher passes None for either), a Handle
    (or None, where nullable) for handle. Output parameters are never
    supplied by the caller: this dispatcher allocates them, and decodes them
    into the returned InvokeResult. Test-only: every chs_ spelling below is
    why this file, alone in python/src/chtypes/_abi2, carries the generated
    banner check-no-hand-decls.py exempts."""
    spec = FUNCTIONS[name]
    fn = api._raw[name]
    call_args: list[object] = []
    out_handle_params: list[_P] = []
    out_error_present = False
    out_scalar_params: list[_P] = []
    it = iter(args)
    for p in spec.params:
        if p.kind in ("scalar", "enum"):
            call_args.append(int(next(it)))
        elif p.kind == "bytes_in":
            data = next(it)
            if not data:
                call_args += [None, 0]
            else:
                call_args += [data, len(data)]
        elif p.kind == "handle":
            h = next(it)
            call_args.append(None if h is None else h.value)
        elif p.kind == "out_handle":
            var = ctypes.c_void_p()
            out_handle_params.append((p, var))
            call_args.append(ctypes.byref(var))
        elif p.kind == "out_error":
            out_error_present = True
            err_var = ctypes.c_void_p()
            call_args.append(ctypes.byref(err_var))
        else:  # out_scalar
            ctype = _CTYPES_NUMERIC[p.type]
            var = ctype()
            out_scalar_params.append((p, var))
            call_args.append(ctypes.byref(var))

    raw_result = fn(*call_args)
    result = InvokeResult()

    if spec.returns_kind == "status":
        result.status = STATUS_BY_VALUE.get(raw_result, f"UNKNOWN:{raw_result}")
        if result.status != "CHS_OK" and out_error_present and err_var.value:
            result.error = _decode_error(api, err_var.value)
    elif spec.returns_kind == "scalar":
        if spec.returns_type == "cstr_static":
            result.bytes_value = raw_result
        else:
            result.int_value = raw_result
    elif spec.returns_kind == "enum":
        result.int_value = raw_result
    elif spec.returns_kind == "handle":
        data, handle = _wrap_or_read(api, spec.returns_type, raw_result)
        if data is not None:
            result.bytes_value = data
        elif handle is not None:
            result.out_handles["__return__"] = handle

    for p, var in out_handle_params:
        if not var.value:
            continue
        data, handle = _wrap_or_read(api, p.type, var.value)
        if data is not None:
            result.outputs[p.name] = data
        elif handle is not None:
            result.out_handles[p.name] = handle
    for p, var in out_scalar_params:
        result.out_scalars[p.name] = var.value
    return result
