"""The process setup's shared public-API cases (tests/fixtures/abi-v1/setup-cases.json,
generated by scripts/abi-v1/emit/setup_cases.py and read by all four bindings), run
through the public API over a fresh copy of a stub library.

Each case gets a fresh image (`stub_copy`) and starts with no setup recorded
(`clean_process`). Without `$CHTYPES_ABI1_STUBS` every case skips loudly by name.
"""

from __future__ import annotations

import contextlib
import json
import shutil

import pytest

from chtypes import (
    InternalError,
    SchemaError,
    Status,
    UnsupportedError,
    UsageError,
    open_unverified,
    setup,
)

from .conftest import REPO_ROOT, stub_path

SETUP_CASES_PATH = REPO_ROOT / "tests" / "fixtures" / "abi-v1" / "setup-cases.json"
_SETUP_CASES: list[dict] = json.loads(SETUP_CASES_PATH.read_text(encoding="utf-8"))["cases"]

CLASSES = {
    "schema": SchemaError,
    "unsupported": UnsupportedError,
    "usage": UsageError,
    "internal": InternalError,
}


def test_the_setup_cases_file_is_not_empty() -> None:
    assert _SETUP_CASES, f"{SETUP_CASES_PATH}: zero cases; a suite that ran nothing must not pass"


def _outcome(want: dict, error: BaseException | None) -> str:
    """What differs between a step's outcome and its expectation; "" when none."""
    if want.get("ok"):
        return "" if error is None else f"want success, got {error!r}"
    cls = CLASSES.get(want["class"])
    if cls is None:
        return f"the case names an error class this runner does not know: {want['class']!r}"
    if not isinstance(error, cls):
        return f"want {cls.__name__}, got {error!r}"
    if "status" in want and error.status != Status[want["status"].removeprefix("CHS_")]:
        return f"status {error.status}, want {want['status']}"
    if "ch_code" in want and error.ch_code != want["ch_code"]:
        return f"ch_code {error.ch_code}, want {want['ch_code']}"
    if "ch_name" in want and error.ch_name != want["ch_name"]:
        return f"ch_name {error.ch_name!r}, want {want['ch_name']!r}"
    return ""


@pytest.mark.parametrize("setup_case", _SETUP_CASES, ids=[c["id"] for c in _SETUP_CASES])
def test_setup_case(
    setup_case: dict, stubs_dir, stubs_manifest, tmp_path, clean_process, monkeypatch
) -> None:
    image = tmp_path / f"{setup_case['variant']}-image.so"
    shutil.copyfile(stub_path(stubs_dir, stubs_manifest["variants"][setup_case["variant"]]), image)
    image.chmod(0o755)
    monkeypatch.setenv("CHTYPES_ALLOW_UNVERIFIED_LIBRARY", "1")
    steps = setup_case["steps"]
    assert steps, "a case with no steps"
    warned = False
    for i, step in enumerate(steps):
        error: BaseException | None = None
        try:
            if step["op"] == "setup":
                setup(timezone=step["timezone"])
            elif step["op"] == "open":
                # An unverified open warns once per path: on this copy's first open.
                expect_warning = not warned
                warned = True
                with (
                    pytest.warns(UserWarning, match="UNVERIFIED")
                    if expect_warning
                    else contextlib.nullcontext()
                ):
                    open_unverified(str(image), allow=True)
            else:
                pytest.fail(f"step {i}: an op this runner does not know: {step['op']!r}")
        except (SchemaError, UnsupportedError, UsageError, InternalError) as exc:
            error = exc
        diff = _outcome(step["expect"], error)
        assert not diff, f"step {i} ({step['op']} {step.get('timezone', '')!r}): {diff}"
