//! The process setup's shared public-API cases
//! (`tests/fixtures/abi-v1/setup-cases.json`, generated by
//! `scripts/abi-v1/emit/setup_cases.py` and read by all four bindings), run
//! through the public API over a fresh copy of a stub library.
//!
//! `setup` is process-wide and nothing public forgets it, so every case runs in
//! a process of its own: the parent re-executes this test binary once per case,
//! naming the case in `CHTYPES_SETUP_CASE`, and the child runs exactly that
//! case on its own copy of the stub, then prints a line the parent requires.
//!
//! `CHTYPES_ABI1_STUBS` unset: this suite skips LOUDLY by name and passes.

use std::path::{Path, PathBuf};
use std::process::Command;

use chtypes::{Error, Library, SetupOptions, status};
use serde_json::Value;

const ENV_STUBS: &str = "CHTYPES_ABI1_STUBS";
const ENV_UNVERIFIED: &str = "CHTYPES_ALLOW_UNVERIFIED_LIBRARY";
const ENV_CASE: &str = "CHTYPES_SETUP_CASE";
const TEST_NAME: &str = "setup_cases";

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("rust/ has a parent")
        .to_path_buf()
}

fn load_cases() -> Vec<Value> {
    let path = repo_root().join("tests/fixtures/abi-v1/setup-cases.json");
    let doc: Value = serde_json::from_slice(&std::fs::read(&path).expect("read setup-cases.json"))
        .expect("parse setup-cases.json");
    let cases = doc["cases"]
        .as_array()
        .expect("setup-cases.json has a cases array")
        .clone();
    assert!(
        !cases.is_empty(),
        "{}: zero cases; a suite that ran nothing must not pass",
        path.display()
    );
    cases
}

/// A status name (`CHS_REJECTED`) as the generated constant's value.
fn status_of(name: &str) -> Option<i32> {
    match name {
        "CHS_OK" => Some(status::OK),
        "CHS_REJECTED" => Some(status::REJECTED),
        "CHS_DECLINED" => Some(status::DECLINED),
        "CHS_INVALID_ARGUMENT" => Some(status::INVALID_ARGUMENT),
        "CHS_INTERNAL" => Some(status::INTERNAL),
        _ => None,
    }
}

/// What differs between a step's outcome and its expectation.
fn outcome(want: &Value, got: &Result<(), Error>) -> Result<(), String> {
    if want.get("ok").and_then(Value::as_bool) == Some(true) {
        return match got {
            Ok(()) => Ok(()),
            Err(e) => Err(format!("want success, got {e:?}")),
        };
    }
    let class = want
        .get("class")
        .and_then(Value::as_str)
        .ok_or("the expectation names no class")?;
    let err = match got {
        Ok(()) => return Err(format!("want a {class} error, got success")),
        Err(e) => e,
    };
    let call = match (class, err) {
        ("schema", Error::Schema(c))
        | ("unsupported", Error::Unsupported(c))
        | ("usage", Error::Usage(c))
        | ("internal", Error::Internal(c)) => c,
        ("schema" | "unsupported" | "usage" | "internal", other) => {
            return Err(format!("want a {class} error, got {other:?}"));
        }
        (unknown, _) => {
            return Err(format!(
                "the case names an error class this runner does not know: {unknown:?}"
            ));
        }
    };
    if let Some(name) = want.get("status").and_then(Value::as_str) {
        let want_status = status_of(name)
            .ok_or_else(|| format!("a status this binding does not know: {name}"))?;
        if call.status != want_status {
            return Err(format!("status {}, want {name}", call.status));
        }
    }
    // No let-chains: the MSRV predates them.
    if let Some(code) = want.get("ch_code").and_then(Value::as_i64) {
        if i64::from(call.ch_code) != code {
            return Err(format!("ch_code {}, want {code}", call.ch_code));
        }
    }
    if let Some(name) = want.get("ch_name").and_then(Value::as_str) {
        if call.ch_name != name {
            return Err(format!("ch_name {:?}, want {name:?}", call.ch_name));
        }
    }
    Ok(())
}

/// The child: one case, on a fresh copy of its stub, from a process with no
/// setup recorded.
fn run_case(stubs: &Path, case: &Value) {
    let id = case["id"].as_str().expect("case id");
    let variant = case["variant"].as_str().expect("case variant");
    let manifest: Value =
        serde_json::from_slice(&std::fs::read(stubs.join("stubs.json")).expect("read stubs.json"))
            .expect("parse stubs.json");
    let source = stubs.join(
        Path::new(
            manifest["variants"][variant]["path"]
                .as_str()
                .expect("variant path"),
        )
        .file_name()
        .expect("file name"),
    );
    let dir = std::env::temp_dir().join(format!("chtypes_setup_case_{}", std::process::id()));
    std::fs::create_dir_all(&dir).expect("create the case directory");
    let image = dir.join(format!("{variant}-image.so"));
    std::fs::copy(&source, &image).expect("copy the stub");
    // SAFETY: the child runs this one test on one thread (--test-threads=1),
    // so nothing reads or writes the environment concurrently.
    unsafe { std::env::set_var(ENV_UNVERIFIED, "1") };

    let steps = case["steps"].as_array().expect("case steps");
    assert!(!steps.is_empty(), "case {id}: a case with no steps");
    for (i, step) in steps.iter().enumerate() {
        let op = step["op"].as_str().expect("step op");
        let zone = step.get("timezone").and_then(Value::as_str).unwrap_or("");
        let got: Result<(), Error> = match op {
            "setup" => chtypes::setup(SetupOptions {
                timezone: Some(zone.to_string()),
                defaults: Vec::new(),
            }),
            "open" => Library::open_unverified(&image, true).map(|_| ()),
            other => panic!("case {id} step {i}: an op this runner does not know: {other:?}"),
        };
        if let Err(diff) = outcome(&step["expect"], &got) {
            panic!("case {id} step {i} ({op} {zone:?}): {diff}");
        }
    }
    let _ = std::fs::remove_dir_all(&dir);
    println!("setup case {id}: ran {} steps", steps.len());
}

#[test]
fn setup_cases() {
    let Some(stubs) = std::env::var_os(ENV_STUBS).map(PathBuf::from) else {
        eprintln!(
            "SKIPPED (loudly): api_v1_setup_cases needs {ENV_STUBS} (the v1-abi-stubs directory); nothing was exercised"
        );
        return;
    };
    let cases = load_cases();

    if let Some(id) = std::env::var_os(ENV_CASE) {
        let id = id.to_string_lossy().into_owned();
        let case = cases
            .iter()
            .find(|c| c["id"].as_str() == Some(id.as_str()))
            .unwrap_or_else(|| panic!("no setup case {id:?}"));
        run_case(&stubs, case);
        return;
    }

    let exe = std::env::current_exe().expect("this test binary's path");
    for case in &cases {
        let id = case["id"].as_str().expect("case id");
        let out = Command::new(&exe)
            .args([TEST_NAME, "--exact", "--nocapture", "--test-threads=1"])
            .env(ENV_CASE, id)
            .output()
            .expect("re-run this test binary for one case");
        let stdout = String::from_utf8_lossy(&out.stdout);
        let stderr = String::from_utf8_lossy(&out.stderr);
        assert!(
            out.status.success(),
            "setup case {id} failed:\n{stdout}\n{stderr}"
        );
        let ran = format!("setup case {id}: ran ");
        assert!(
            stdout.contains(&ran),
            "setup case {id}: the child did not run it (no {ran:?} line):\n{stdout}\n{stderr}"
        );
        println!("setup case {id}: passed in its own process");
    }
}
