//! The process setup's shared public-API cases
//! (`tests/fixtures/abi-v2/setup-cases.json`, generated by
//! `scripts/abi-v1/emit/setup_cases.py` and read by all four bindings), run
//! through the public API over a fresh copy of a stub library.
//!
//! `setup` is process-wide and nothing public forgets it, so every case runs in
//! a process of its own: the parent re-executes this test binary once per case,
//! naming the case in `CHTYPES_SETUP_CASE`, and the child runs exactly that
//! case on its own copy of the stub, then prints a line the parent requires.
//!
//! `CHTYPES_ABI2_STUBS` unset: this suite skips LOUDLY by name and passes.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Arc;

use chtypes::{
    CompileOptions, Error, FetchOptions, FilterOptions, Library, Registry, RegistryOptions, Schema,
    SchemaDescription, Server, ServerProfile, SetupOptions, status,
};
use serde_json::Value;

const ENV_STUBS: &str = "CHTYPES_ABI2_STUBS";
const ENV_UNVERIFIED: &str = "CHTYPES_ALLOW_UNVERIFIED_LIBRARY";
const ENV_CASE: &str = "CHTYPES_SETUP_CASE";
const TEST_NAME: &str = "setup_cases";

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("rust/ has a parent")
        .to_path_buf()
}

/// The document's image zone probe, and its cases.
fn load_cases() -> (String, Vec<Value>) {
    let path = repo_root().join("tests/fixtures/abi-v2/setup-cases.json");
    let doc: Value = serde_json::from_slice(&std::fs::read(&path).expect("read setup-cases.json"))
        .expect("parse setup-cases.json");
    let probe = doc["image_zone_probe"]
        .as_str()
        .expect("setup-cases.json has an image_zone_probe")
        .to_string();
    let cases = doc["cases"]
        .as_array()
        .expect("setup-cases.json has a cases array")
        .clone();
    assert!(
        !cases.is_empty(),
        "{}: zero cases; a suite that ran nothing must not pass",
        path.display()
    );
    (probe, cases)
}

/// A status name (`CHS_REJECTED`) as the generated constant's value.
fn status_of(name: &str) -> Option<i32> {
    match name {
        "CHS_OK" => Some(status::OK),
        "CHS_REJECTED" => Some(status::REJECTED),
        "CHS_DECLINED" => Some(status::DECLINED),
        "CHS_INVALID_ARGUMENT" => Some(status::INVALID_ARGUMENT),
        "CHS_INTERNAL" => Some(status::INTERNAL),
        _ => None,
    }
}

/// What differs between a step's outcome and its expectation.
fn outcome(want: &Value, got: &Result<(), Error>) -> Result<(), String> {
    if want.get("ok").and_then(Value::as_bool) == Some(true) {
        return match got {
            Ok(()) => Ok(()),
            Err(e) => Err(format!("want success, got {e:?}")),
        };
    }
    let class = want
        .get("class")
        .and_then(Value::as_str)
        .ok_or("the expectation names no class")?;
    let err = match got {
        Ok(()) => return Err(format!("want a {class} error, got success")),
        Err(e) => e,
    };
    // A loader refusal: its class, and the reason word it carries.
    if class == "artifact_incompatible" || class == "artifact_corrupt" {
        let refusal = match (class, err) {
            ("artifact_incompatible", Error::ArtifactIncompatible(r))
            | ("artifact_corrupt", Error::ArtifactCorrupt(r)) => r,
            (_, other) => return Err(format!("want a {class} error, got {other:?}")),
        };
        if let Some(reason) = want.get("reason").and_then(Value::as_str) {
            if refusal.reason != reason {
                return Err(format!("reason {:?}, want {reason:?}", refusal.reason));
            }
        }
        return Ok(());
    }
    let call = match (class, err) {
        ("schema", Error::Schema(c))
        | ("unsupported", Error::Unsupported(c))
        | ("usage", Error::Usage(c))
        | ("internal", Error::Internal(c)) => c,
        ("schema" | "unsupported" | "usage" | "internal", other) => {
            return Err(format!("want a {class} error, got {other:?}"));
        }
        (unknown, _) => {
            return Err(format!(
                "the case names an error class this runner does not know: {unknown:?}"
            ));
        }
    };
    if let Some(name) = want.get("status").and_then(Value::as_str) {
        let want_status = status_of(name)
            .ok_or_else(|| format!("a status this binding does not know: {name}"))?;
        if call.status != want_status {
            return Err(format!("status {}, want {name}", call.status));
        }
    }
    // No let-chains: the MSRV predates them.
    if let Some(code) = want.get("ch_code").and_then(Value::as_i64) {
        if i64::from(call.ch_code) != code {
            return Err(format!("ch_code {}, want {code}", call.ch_code));
        }
    }
    if let Some(name) = want.get("ch_name").and_then(Value::as_str) {
        if call.ch_name != name {
            return Err(format!("ch_name {:?}, want {name:?}", call.ch_name));
        }
    }
    if let Some(message) = want.get("message").and_then(Value::as_str) {
        if call.message.as_bytes() != message.as_bytes() {
            return Err(format!(
                "message {:?}, want {message:?}",
                call.message.to_lossy()
            ));
        }
    }
    Ok(())
}

/// What differs between a description's server `filter_declined_settings` and
/// a describe step's expectation: each entry's name as hex of its bytes, its
/// tier's raw spelling, and whether the description lists that tier (rule r3).
fn declined(described: Option<&SchemaDescription>, want: &Value) -> Result<(), String> {
    let want = want
        .as_array()
        .ok_or("a describe step names no declined list")?;
    let server = described
        .and_then(|d| d.server.as_ref())
        .ok_or("the description carries no server")?;
    let got = &server.filter_declined_settings;
    if got.len() != want.len() {
        return Err(format!(
            "filter_declined_settings has {} entries, want {}: {got:?}",
            got.len(),
            want.len()
        ));
    }
    for (i, (g, w)) in got.iter().zip(want).enumerate() {
        let hex: String = g
            .name
            .as_bytes()
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect();
        if Some(hex.as_str()) != w["name_hex"].as_str() {
            return Err(format!("entry {i}: name {hex}, want hex {}", w["name_hex"]));
        }
        if Some(g.tier.as_str()) != w["tier"].as_str()
            || Some(g.tier.is_known()) != w["known"].as_bool()
        {
            return Err(format!(
                "entry {i}: tier {:?} (known {}), want {} (known {})",
                g.tier.as_str(),
                g.tier.is_known(),
                w["tier"],
                w["known"]
            ));
        }
    }
    Ok(())
}

/// The child: one case, on a fresh copy of each stub it opens, from a process
/// with no setup recorded.
fn run_case(stubs: &Path, probe: &str, case: &Value) {
    let id = case["id"].as_str().expect("case id");
    let case_variant = case["variant"].as_str().expect("case variant");
    let manifest: Value =
        serde_json::from_slice(&std::fs::read(stubs.join("stubs.json")).expect("read stubs.json"))
            .expect("parse stubs.json");
    let dir = std::env::temp_dir().join(format!("chtypes_setup_case_{}", std::process::id()));
    std::fs::create_dir_all(&dir).expect("create the case directory");
    // The case's one fresh copy of each variant, made on its first open.
    let mut images: BTreeMap<String, PathBuf> = BTreeMap::new();
    let mut image = |variant: &str| -> PathBuf {
        images
            .entry(variant.to_string())
            .or_insert_with(|| {
                let source = stubs.join(
                    Path::new(
                        manifest["variants"][variant]["path"]
                            .as_str()
                            .expect("variant path"),
                    )
                    .file_name()
                    .expect("file name"),
                );
                let copy = dir.join(format!("{variant}-image.so"));
                std::fs::copy(&source, &copy).expect("copy the stub");
                copy
            })
            .clone()
    };
    // SAFETY: the child runs this one test on one thread (--test-threads=1),
    // so nothing reads or writes the environment concurrently.
    unsafe { std::env::set_var(ENV_UNVERIFIED, "1") };

    let steps = case["steps"].as_array().expect("case steps");
    assert!(!steps.is_empty(), "case {id}: a case with no steps");
    // The case's open library, and the servers and schemas its steps name.
    let mut current: Option<Arc<Library>> = None;
    let mut servers: BTreeMap<String, Server> = BTreeMap::new();
    let mut schemas: BTreeMap<String, Schema> = BTreeMap::new();
    let name = |step: &Value, key: &str| -> String {
        step[key]
            .as_str()
            .unwrap_or_else(|| panic!("case {id}: a step names no {key}"))
            .to_string()
    };
    for (i, step) in steps.iter().enumerate() {
        let op = step["op"].as_str().expect("step op");
        let zone = step.get("timezone").and_then(Value::as_str).unwrap_or("");
        let variant = step
            .get("variant")
            .and_then(Value::as_str)
            .unwrap_or(case_variant);
        let request = step.get("request").and_then(Value::as_str);
        let allow = step.get("allow").and_then(Value::as_bool).unwrap_or(true);
        let mut opened: Option<Arc<Library>> = None;
        let mut described: Option<SchemaDescription> = None;
        let library = || current.clone().expect("a step that needs an open library");
        let got: Result<(), Error> = match (op, request) {
            ("setup", _) => chtypes::setup(SetupOptions {
                timezone: Some(zone.to_string()),
                defaults: Vec::new(),
            }),
            ("open", Some(request)) => {
                // A registry over an empty cache, offline, autofetch off.
                let cache = dir.join(format!("cache-{i}"));
                std::fs::create_dir_all(&cache).expect("create an empty cache");
                let registry = Registry::new(RegistryOptions {
                    fetch: FetchOptions {
                        cache_dir: Some(cache.to_string_lossy().into_owned()),
                        system_dirs: Some(Vec::new()),
                        offline: true,
                        ..Default::default()
                    },
                    autofetch: Some(false),
                    ..Default::default()
                })
                .expect("constructing a registry opens nothing");
                registry.for_version(request).map(|l| opened = Some(l))
            }
            ("open", None) => {
                Library::open_unverified(image(variant), allow).map(|l| opened = Some(l))
            }
            ("server_new", _) => library()
                .new_server(&ServerProfile {
                    timezone: Some("UTC".to_string()),
                    ..Default::default()
                })
                .map(|s| {
                    servers.insert(name(step, "as"), s);
                }),
            ("compile", _) => {
                let options = CompileOptions {
                    server: step
                        .get("server")
                        .and_then(Value::as_str)
                        .map(|s| servers[s].clone()),
                    ..Default::default()
                };
                library()
                    .compile_table(name(step, "statement"), &options)
                    .map(|schema| {
                        if let Some(as_name) = step.get("as").and_then(Value::as_str) {
                            schemas.insert(as_name.to_string(), schema);
                        }
                    })
            }
            ("describe", _) => schemas[&name(step, "schema")]
                .describe()
                .map(|d| described = Some(d)),
            ("filter_new", _) => schemas[&name(step, "schema")]
                .compile_filter(name(step, "expression"), &FilterOptions::default())
                .map(|_| ()),
            (other, _) => {
                panic!("case {id} step {i}: an op this runner does not know: {other:?}")
            }
        };
        if let Some(library) = &opened {
            current = Some(Arc::clone(library));
        }
        let mut checked = outcome(&step["expect"], &got);
        if checked.is_ok() && op == "describe" {
            // The list as this binding decoded it from the document the stub
            // answered, never a value the case sets by hand.
            checked = declined(described.as_ref(), &step["declined"]);
        }
        if let (Ok(()), Some(want)) = (&checked, step["expect"].get("image_zone")) {
            let want = want.as_str().expect("image_zone is a string");
            let library = opened
                .as_ref()
                .expect("a successful open returns its library");
            checked = match library.validate_type(probe) {
                Err(e) => Err(format!("reading the image zone back: {e:?}")),
                Ok(zone) if zone.as_bytes() != want.as_bytes() => Err(format!(
                    "the image was set up with zone {:?}, want {want:?}",
                    String::from_utf8_lossy(zone.as_bytes())
                )),
                Ok(_) => Ok(()),
            };
        }
        if let Err(diff) = checked {
            panic!(
                "case {id} step {i} ({op} {zone:?} {variant} {}): {diff}",
                request.unwrap_or("")
            );
        }
    }
    let _ = std::fs::remove_dir_all(&dir);
    println!("setup case {id}: ran {} steps", steps.len());
}

#[test]
fn setup_cases() {
    let Some(stubs) = std::env::var_os(ENV_STUBS).map(PathBuf::from) else {
        eprintln!(
            "SKIPPED (loudly): api_v1_setup_cases needs {ENV_STUBS} (the v1-abi-stubs directory); nothing was exercised"
        );
        return;
    };
    let (probe, cases) = load_cases();

    if let Some(id) = std::env::var_os(ENV_CASE) {
        let id = id.to_string_lossy().into_owned();
        let case = cases
            .iter()
            .find(|c| c["id"].as_str() == Some(id.as_str()))
            .unwrap_or_else(|| panic!("no setup case {id:?}"));
        run_case(&stubs, &probe, case);
        return;
    }

    // Every case runs, and every failure is reported, before the verdict.
    let exe = std::env::current_exe().expect("this test binary's path");
    let mut failures = Vec::new();
    for case in &cases {
        let id = case["id"].as_str().expect("case id");
        // A case this binding cannot express is SKIPPED loudly, with the
        // case's own reason, never passed silently (rule r7: a freed handle
        // is unreachable in Rust, so there is nothing to refuse).
        if let Some(why) = case["not_expressible"]["rust"].as_str() {
            eprintln!("setup case {id}: SKIPPED (loudly), not expressible in Rust: {why}");
            continue;
        }
        let out = Command::new(&exe)
            .args([TEST_NAME, "--exact", "--nocapture", "--test-threads=1"])
            .env(ENV_CASE, id)
            .output()
            .expect("re-run this test binary for one case");
        let stdout = String::from_utf8_lossy(&out.stdout);
        let stderr = String::from_utf8_lossy(&out.stderr);
        let ran = format!("setup case {id}: ran ");
        if !out.status.success() {
            eprintln!("setup case {id}: FAILED in its own process");
            failures.push(format!("setup case {id} failed:\n{stdout}\n{stderr}"));
        } else if !stdout.contains(&ran) {
            failures.push(format!(
                "setup case {id}: the child did not run it (no {ran:?} line):\n{stdout}\n{stderr}"
            ));
        } else {
            println!("setup case {id}: passed in its own process");
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
