/**
 * The process setup's shared public-API cases
 * (`tests/fixtures/abi-v1/setup-cases.json`, generated by
 * `scripts/abi-v1/emit/setup_cases.py` and read by all four bindings), run
 * through the public API over a fresh copy of a stub library.
 *
 * Each case gets a fresh image (its own copy of the stub) and starts with no
 * setup recorded. Without `$CHTYPES_ABI1_STUBS` every case SKIPS LOUDLY by
 * name; it never passes silently.
 */

import { chmodSync, copyFileSync, mkdtempSync, readFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it, vi } from 'vitest';
import { InternalError, openUnverified, SchemaError, Status, setup, UnsupportedError, UsageError } from '../../src/index.js';
import { resetSetupForTests } from '../../src/setup.js';

const STUBS_DIR = process.env.CHTYPES_ABI1_STUBS;
const stubsAvailable = typeof STUBS_DIR === 'string' && STUBS_DIR.length > 0;

const SETUP_CASES_PATH = path.resolve(import.meta.dirname, '../../../tests/fixtures/abi-v1/setup-cases.json');

interface Expect {
  readonly ok?: boolean;
  readonly class?: string;
  readonly status?: string;
  readonly ch_code?: number;
  readonly ch_name?: string;
}

interface Step {
  readonly op: string;
  readonly timezone?: string;
  readonly expect: Expect;
}

interface SetupCase {
  readonly id: string;
  readonly variant: string;
  readonly steps: readonly Step[];
}

const setupCases: readonly SetupCase[] = (JSON.parse(readFileSync(SETUP_CASES_PATH, 'utf8')) as { cases: SetupCase[] }).cases;

const CLASSES: Readonly<Record<string, abstract new (...args: never[]) => Error>> = {
  schema: SchemaError,
  unsupported: UnsupportedError,
  usage: UsageError,
  internal: InternalError,
};

/** `CHS_INVALID_ARGUMENT` -> `Status.InvalidArgument`: the generated vocabulary's own spelling of a status name. */
function statusOf(name: string): number | undefined {
  const key = name
    .replace(/^CHS_/, '')
    .toLowerCase()
    .replace(/(^|_)([a-z])/g, (_m: string, _sep: string, c: string) => c.toUpperCase());
  return (Status as Readonly<Record<string, number>>)[key];
}

/** What differs between a step's outcome and its expectation; '' when none. */
function outcome(want: Expect, error: unknown): string {
  if (want.ok === true) return error === undefined ? '' : `want success, got ${String(error)}`;
  const cls = want.class === undefined ? undefined : CLASSES[want.class];
  if (cls === undefined) return `the case names an error class this runner does not know: ${String(want.class)}`;
  if (!(error instanceof cls)) return `want ${cls.name}, got ${error === undefined ? 'success' : String(error)}`;
  const e = error as unknown as { status: number; chCode: number; chName: string };
  if (want.status !== undefined) {
    const status = statusOf(want.status);
    if (status === undefined) return `the case names a status this binding does not know: ${want.status}`;
    if (e.status !== status) return `status ${e.status}, want ${want.status}`;
  }
  if (want.ch_code !== undefined && e.chCode !== want.ch_code) return `ch_code ${e.chCode}, want ${want.ch_code}`;
  if (want.ch_name !== undefined && e.chName !== want.ch_name) return `ch_name ${e.chName}, want ${want.ch_name}`;
  return '';
}

describe('the setup cases file', () => {
  it('is not empty: a suite that ran nothing must not pass', () => {
    expect(setupCases.length).toBeGreaterThan(0);
  });
});

describe.skipIf(!stubsAvailable)('the shared setup cases, through the public API', () => {
  it.each(setupCases.map((c) => [c.id, c] as const))('%s', (_id, c) => {
    expect(c.steps.length).toBeGreaterThan(0);
    const dir = mkdtempSync(path.join(os.tmpdir(), 'setup-case-'));
    const image = path.join(dir, `${c.variant}-image.so`);
    copyFileSync(path.join(STUBS_DIR as string, `${c.variant}.so`), image);
    chmodSync(image, 0o755);
    resetSetupForTests();
    const saved = process.env.CHTYPES_ALLOW_UNVERIFIED_LIBRARY;
    const warn = vi.spyOn(console, 'warn').mockImplementation(() => {});
    process.env.CHTYPES_ALLOW_UNVERIFIED_LIBRARY = '1';
    try {
      c.steps.forEach((step, i) => {
        let error: unknown;
        try {
          if (step.op === 'setup') setup({ timezone: step.timezone ?? '' });
          else if (step.op === 'open') openUnverified(image, { allow: true });
          else throw new Error(`step ${i}: an op this runner does not know: ${step.op}`);
        } catch (err) {
          if (!(err instanceof SchemaError || err instanceof UnsupportedError || err instanceof UsageError || err instanceof InternalError)) throw err;
          error = err;
        }
        const diff = outcome(step.expect, error);
        expect(diff, `step ${i} (${step.op} ${JSON.stringify(step.timezone ?? '')})`).toBe('');
      });
    } finally {
      warn.mockRestore();
      resetSetupForTests();
      if (saved === undefined) delete process.env.CHTYPES_ALLOW_UNVERIFIED_LIBRARY;
      else process.env.CHTYPES_ALLOW_UNVERIFIED_LIBRARY = saved;
    }
  });
});
