// Code generated by scripts/fetch-v1/gen-constants.py from
// spec/fetch-v1/constants.json (sha256:82afa8d6cba96c10b5945c6f7c1c8360a504cc8ac6231e74017cc6c20b908df6). DO NOT EDIT.

package chtypes

// ErrorCode is one of the shared artifact codes (docs/guides/fetch-v1.md
// section 8): the Code every *ArtifactError carries.
type ErrorCode string

// The shared artifact codes, one per entry of the fetch constants' errors, in
// their order (docs/reference/bindings-v1.md section 4, the codes).
const (
	CodeArtifactMissing      ErrorCode = `CHTYPES_ARTIFACT_MISSING`
	CodeArtifactUntrusted    ErrorCode = `CHTYPES_ARTIFACT_UNTRUSTED`
	CodeArtifactCorrupt      ErrorCode = `CHTYPES_ARTIFACT_CORRUPT`
	CodeArtifactPinned       ErrorCode = `CHTYPES_ARTIFACT_PINNED`
	CodeArtifactUnpublished  ErrorCode = `CHTYPES_ARTIFACT_UNPUBLISHED`
	CodeSourceUnreachable    ErrorCode = `CHTYPES_SOURCE_UNREACHABLE`
	CodeSourceUnauthorized   ErrorCode = `CHTYPES_SOURCE_UNAUTHORIZED`
	CodeSourceForbidden      ErrorCode = `CHTYPES_SOURCE_FORBIDDEN`
	CodeSourceIncompatible   ErrorCode = `CHTYPES_SOURCE_INCOMPATIBLE`
	CodeArtifactIncompatible ErrorCode = `CHTYPES_ARTIFACT_INCOMPATIBLE`
	CodeCacheUnusable        ErrorCode = `CHTYPES_CACHE_UNUSABLE`
	CodeSourceRetired        ErrorCode = `CHTYPES_SOURCE_RETIRED`
)
