package chtypes

// setup_cases_test.go — the process setup's shared public-API cases
// (tests/fixtures/abi-v1/setup-cases.json, generated by
// scripts/abi-v1/emit/setup_cases.py and read by all four bindings), run
// through the public API over a fresh copy of a stub library. Without
// CHTYPES_ABI1_STUBS it skips LOUDLY by name.

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

type setupCaseExpect struct {
	OK     bool    `json:"ok"`
	Class  string  `json:"class"`
	Status string  `json:"status"`
	ChCode *int32  `json:"ch_code"`
	ChName *string `json:"ch_name"`
	Reason string  `json:"reason"`
	// ImageZone, on a successful open, is the zone the image was set up
	// with, read back with the document's image_zone_probe.
	ImageZone *string `json:"image_zone"`
}

type setupCaseStep struct {
	Op       string          `json:"op"`
	Timezone string          `json:"timezone"`
	Variant  string          `json:"variant"`
	Request  string          `json:"request"`
	Allow    *bool           `json:"allow"`
	Expect   setupCaseExpect `json:"expect"`
	// The compile and filter ops (rule r7): the statement to compile and the
	// schema, filter and expression the steps name, the body (CSV), and the
	// rows_passed a batch result must report.
	As         string `json:"as"`
	Schema     string `json:"schema"`
	Statement  string `json:"statement"`
	Filter     string `json:"filter"`
	Expression string `json:"expression"`
	Body       string `json:"body"`
	RowsPassed *int   `json:"rows_passed"`
}

type setupCasesDoc struct {
	ImageZoneProbe string      `json:"image_zone_probe"`
	Cases          []setupCase `json:"cases"`
}

type setupCase struct {
	ID      string          `json:"id"`
	Variant string          `json:"variant"`
	Steps   []setupCaseStep `json:"steps"`
	// NotExpressible names the bindings that cannot express the case, and why.
	NotExpressible map[string]string `json:"not_expressible"`
}

func loadSetupCases(t *testing.T) setupCasesDoc {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller(0) failed")
	}
	path := filepath.Join(filepath.Dir(file), "..", "..", "tests", "fixtures", "abi-v1", "setup-cases.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var doc setupCasesDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("%s: %v", path, err)
	}
	if len(doc.Cases) == 0 {
		t.Fatalf("%s: zero cases; a suite that ran nothing must not pass", path)
	}
	if doc.ImageZoneProbe == "" {
		t.Fatalf("%s: no image_zone_probe", path)
	}
	return doc
}

// setupStepOutcome compares one step's outcome with its expectation, and
// returns what differs, or "" when they agree.
func setupStepOutcome(want setupCaseExpect, err error) string {
	if want.OK {
		if err != nil {
			return fmt.Sprintf("want success, got %T: %v", err, err)
		}
		return ""
	}
	if err == nil {
		return fmt.Sprintf("want a %s error, got success", want.Class)
	}
	switch want.Class {
	case "artifact_incompatible", "artifact_corrupt":
		sentinel := ErrArtifactIncompatible
		if want.Class == "artifact_corrupt" {
			sentinel = ErrArtifactCorrupt
		}
		var ae *ArtifactError
		if !errors.Is(err, sentinel) || !errors.As(err, &ae) {
			return fmt.Sprintf("want a %s error, got %T: %v", want.Class, err, err)
		}
		if want.Reason != "" && ae.Reason != want.Reason {
			return fmt.Sprintf("reason %q, want %q", ae.Reason, want.Reason)
		}
		return ""
	}
	var matched bool
	switch want.Class {
	case "schema":
		var e *SchemaError
		matched = errors.As(err, &e)
	case "unsupported":
		var e *UnsupportedError
		matched = errors.As(err, &e)
	case "usage":
		var e *UsageError
		matched = errors.As(err, &e)
	case "internal":
		var e *InternalError
		matched = errors.As(err, &e)
	default:
		return fmt.Sprintf("the case names an error class this runner does not know: %q", want.Class)
	}
	if !matched {
		return fmt.Sprintf("want a %s error, got %T: %v", want.Class, err, err)
	}
	if want.Status == "" && want.ChCode == nil && want.ChName == nil {
		return "" // a binding's own usage error, raised before any call, carries no call fields
	}
	ce, ok := AsCallError(err)
	if !ok {
		return fmt.Sprintf("%T carries no call error fields", err)
	}
	if want.Status != "" && ce.Status.String() != want.Status {
		return fmt.Sprintf("status %s, want %s", ce.Status, want.Status)
	}
	if want.ChCode != nil && ce.ChCode != *want.ChCode {
		return fmt.Sprintf("ch_code %d, want %d", ce.ChCode, *want.ChCode)
	}
	if want.ChName != nil && ce.ChName != *want.ChName {
		return fmt.Sprintf("ch_name %q, want %q", ce.ChName, *want.ChName)
	}
	return ""
}

// TestSetupCases runs every shared setup case: one fresh image per variant the
// case opens, no setup recorded at its start, and each step through the public
// API.
func TestSetupCases(t *testing.T) {
	stubDir(t) // skips loudly without the stubs
	doc := loadSetupCases(t)
	for _, c := range doc.Cases {
		t.Run(c.ID, func(t *testing.T) {
			if why, skip := c.NotExpressible["go"]; skip {
				t.Skipf("not expressible in Go: %s", why)
			}
			resetSetup(t)
			t.Setenv("CHTYPES_ALLOW_UNVERIFIED_LIBRARY", "1")
			images := map[string]string{}
			image := func(variant string) string {
				if variant == "" {
					variant = c.Variant
				}
				if images[variant] == "" {
					images[variant] = stubFile(t, variant)
				}
				return images[variant]
			}
			if len(c.Steps) == 0 {
				t.Fatal("a case with no steps")
			}
			// The case's open library, and the schemas and filters its steps
			// (rule r7) name.
			var current *Library
			schemas := map[string]*Schema{}
			filters := map[string]*Filter{}
			var rowsPassed *uint64
			for i, s := range c.Steps {
				var err error
				var lib *Library
				switch {
				case s.Op == "filter_close":
					if err := filters[s.Filter].Close(); err != nil {
						t.Fatalf("step %d: closing filter %q: %v", i, s.Filter, err)
					}
					continue
				case s.Op == "filter_new":
					var f *Filter
					f, err = schemas[s.Schema].CompileFilter(s.Expression)
					filters[s.As] = f
				case s.Op == "rows":
					var opts []RowsOption
					if s.Filter != "" {
						opts = append(opts, WithRowFilter(filters[s.Filter]))
					}
					var res BatchResult
					res, err = schemas[s.Schema].Rows(CSV, []byte(s.Body), opts...)
					rowsPassed = nil
					if err == nil {
						rowsPassed = &res.RowsPassed
					}
				case s.Op == "compile":
					var schema *Schema
					schema, err = current.CompileTable(s.Statement)
					schemas[s.As] = schema
				case s.Op == "setup":
					err = Setup(SetupOptions{Timezone: s.Timezone})
				case s.Op == "open" && s.Request != "":
					// A registry over an empty cache, offline, autofetch off.
					var reg *Registry
					reg, err = NewRegistry(WithFetchOptions(FetchOptions{
						CacheDir: t.TempDir(), SystemDirs: []string{t.TempDir()}, Offline: true,
					}), WithAutoFetch(false))
					if err != nil {
						t.Fatalf("step %d: constructing a registry: %v", i, err)
					}
					lib, err = reg.For(s.Request)
				case s.Op == "open":
					lib, err = OpenUnverified(image(s.Variant), s.Allow == nil || *s.Allow)
				default:
					t.Fatalf("step %d: an op this runner does not know: %q", i, s.Op)
				}
				if lib != nil {
					current = lib
				}
				diff := setupStepOutcome(s.Expect, err)
				if diff == "" && s.RowsPassed != nil && (rowsPassed == nil || *rowsPassed != uint64(*s.RowsPassed)) {
					diff = fmt.Sprintf("rows_passed differs from %d (or the call failed): the stub says whether the filter reached the library", *s.RowsPassed)
				}
				if diff == "" && s.Expect.ImageZone != nil {
					zone, perr := lib.ValidateType(doc.ImageZoneProbe)
					switch {
					case perr != nil:
						diff = fmt.Sprintf("reading the image zone back: %v", perr)
					case zone != *s.Expect.ImageZone:
						diff = fmt.Sprintf("the image was set up with zone %q, want %q", zone, *s.Expect.ImageZone)
					}
				}
				if diff != "" {
					t.Fatalf("step %d (%s %q %s%s): %s", i, s.Op, s.Timezone, s.Variant, s.Request, diff)
				}
			}
		})
	}
}
