// GENERATED by scripts/abi-v1/gen.py from spec/abi-v1/abi.json (CHS_ABI_FINGERPRINT sha256:b691663f42fb9ca2a872909e73a06fb61836abf92ce552a95b21baf4e006c4ed) — DO NOT EDIT
//
// The opaque handle types, the `extern "C"` function-pointer type for
// every described function, the resolved symbol tables (`Handshake`, the
// two symbols loader steps 3-4 need; `Api`, every symbol, step 6), and the
// small facts (`CHS_ABI_VERSION`, `CHS_ABI_FINGERPRINT`, the build_info
// cross-check field map, the chs_status name table) the hand-written
// loader and conformance runner read by name. See scripts/abi-v1/emit/rust.py.
#![allow(non_camel_case_types, dead_code)]

use std::os::raw::c_char;

use libloading::os::unix::{Library as UnixLibrary, Symbol};

// --------------------------------------------------------------- identity

/// `CHS_ABI_VERSION`: what a v1 artifact's `chs_abi_version()` must answer.
pub(crate) const CHS_ABI_VERSION: i32 = 1;

/// `CHS_ABI_FINGERPRINT`: `sha256:` + the sha256 of the RFC 8785 canonical
/// form of spec/abi-v1/abi.json (D1.1). Compared byte for byte against
/// `chs_build_info()`'s `abi_fingerprint` field at loader step 4.
pub(crate) const CHS_ABI_FINGERPRINT: &str =
    "sha256:b691663f42fb9ca2a872909e73a06fb61836abf92ce552a95b21baf4e006c4ed";

/// `build_info`'s required top-level fields (spec/abi-v1/abi.json's own
/// `build_info.schema.required`), so the loader's step 4 refuses a
/// `chs_build_info()` answer missing any of them, by name.
pub(crate) const BUILD_INFO_REQUIRED: &[&str] = &[
    "schema",
    "abi",
    "abi_fingerprint",
    "clickhouse_version",
    "channel",
    "clickhouse_minor",
    "clickhouse_commit",
    "core_commit",
    "build",
    "inputs_sha256",
    "os",
    "arch",
    "toolchain",
    "capabilities",
];

/// sdk.json's `cross_check`: loader step 5 compares each `build_info`
/// field against the matching predicate field, either as an exact integer
/// or as exact bytes (never through a float or a lossy string coercion).
pub(crate) enum CrossCheckKind {
    Int,
    Bytes,
}

pub(crate) const CROSS_CHECK_FIELDS: &[(&str, &str, CrossCheckKind)] = &[
    ("abi", "abi", CrossCheckKind::Int),
    ("abi_fingerprint", "abi_fingerprint", CrossCheckKind::Bytes),
    (
        "clickhouse_version",
        "clickhouse_version",
        CrossCheckKind::Bytes,
    ),
    ("channel", "channel", CrossCheckKind::Bytes),
    ("build", "build", CrossCheckKind::Bytes),
    ("os", "os", CrossCheckKind::Bytes),
    ("arch", "arch", CrossCheckKind::Bytes),
    ("core_commit", "core_commit", CrossCheckKind::Bytes),
    ("inputs_sha256", "inputs_sha256", CrossCheckKind::Bytes),
];

/// The `chs_status` enum's C name for each integer value this ABI
/// generation defines (D3, frozen numbering). `None` for a value this
/// generation never defines, which the loader treats as `sdk.json`'s
/// `errors.status.unknown` class rather than a parse failure.
pub(crate) fn status_name(value: i32) -> Option<&'static str> {
    match value {
        0 => Some("CHS_OK"),
        1 => Some("CHS_REJECTED"),
        2 => Some("CHS_DECLINED"),
        3 => Some("CHS_INVALID_ARGUMENT"),
        4 => Some("CHS_INTERNAL"),
        _ => None,
    }
}

// ---------------------------------------------------------------- handles

/// Opaque `chs_buf`, mirroring the C ABI's opaque handle type. Never
/// constructed in Rust; only ever a pointer this module receives from, or
/// hands to, the loaded library.
#[repr(C)]
pub(crate) struct ChsBuf {
    _opaque: [u8; 0],
}

/// Opaque `chs_error`, mirroring the C ABI's opaque handle type. Never
/// constructed in Rust; only ever a pointer this module receives from, or
/// hands to, the loaded library.
#[repr(C)]
pub(crate) struct ChsError {
    _opaque: [u8; 0],
}

/// Opaque `chs_schema`, mirroring the C ABI's opaque handle type. Never
/// constructed in Rust; only ever a pointer this module receives from, or
/// hands to, the loaded library.
#[repr(C)]
pub(crate) struct ChsSchema {
    _opaque: [u8; 0],
}

/// Opaque `chs_filter`, mirroring the C ABI's opaque handle type. Never
/// constructed in Rust; only ever a pointer this module receives from, or
/// hands to, the loaded library.
#[repr(C)]
pub(crate) struct ChsFilter {
    _opaque: [u8; 0],
}

/// Opaque `chs_block`, mirroring the C ABI's opaque handle type. Never
/// constructed in Rust; only ever a pointer this module receives from, or
/// hands to, the loaded library.
#[repr(C)]
pub(crate) struct ChsBlock {
    _opaque: [u8; 0],
}

/// One utility type alias `decls.rs` needs that the ABI description does
/// not describe: `gnu_get_libc_version`, resolved from the process image
/// itself (`UnixLibrary::this()`), never from a loaded artifact. Declared
/// here, not in `loader.rs`, so every `extern "C"` declaration in `abi1/`
/// stays inside a file `check-no-hand-decls.py` exempts.
pub(crate) type FnGlibcVersion = unsafe extern "C" fn() -> *const c_char;

// ------------------------------------------------------- function pointers

pub(crate) type FnChsAbiVersion = unsafe extern "C" fn() -> i32;
pub(crate) type FnChsBuildInfo = unsafe extern "C" fn() -> *const std::os::raw::c_char;
pub(crate) type FnChsClickhouseVersion = unsafe extern "C" fn() -> *const std::os::raw::c_char;
pub(crate) type FnChsAbiRevision = unsafe extern "C" fn() -> std::os::raw::c_int;
pub(crate) type FnChsBufData = unsafe extern "C" fn(*const ChsBuf) -> *const u8;
pub(crate) type FnChsBufLen = unsafe extern "C" fn(*const ChsBuf) -> usize;
pub(crate) type FnChsBufFree = unsafe extern "C" fn(*mut ChsBuf);
pub(crate) type FnChsErrorStatus = unsafe extern "C" fn(*const ChsError) -> i32;
pub(crate) type FnChsErrorChCode = unsafe extern "C" fn(*const ChsError) -> i32;
pub(crate) type FnChsErrorChName = unsafe extern "C" fn(*const ChsError) -> *mut ChsBuf;
pub(crate) type FnChsErrorMessage = unsafe extern "C" fn(*const ChsError) -> *mut ChsBuf;
pub(crate) type FnChsErrorColumn = unsafe extern "C" fn(*const ChsError) -> *mut ChsBuf;
pub(crate) type FnChsErrorFree = unsafe extern "C" fn(*mut ChsError);
pub(crate) type FnChsLiveHandles =
    unsafe extern "C" fn(*mut *mut ChsBuf, *mut *mut ChsError) -> i32;
pub(crate) type FnChsErrorCodes = unsafe extern "C" fn(*mut *mut ChsBuf, *mut *mut ChsError) -> i32;
pub(crate) type FnChsRegisteredFamilies =
    unsafe extern "C" fn(*mut *mut ChsBuf, *mut *mut ChsError) -> i32;
pub(crate) type FnChsFunctionFlags =
    unsafe extern "C" fn(*mut *mut ChsBuf, *mut *mut ChsError) -> i32;
pub(crate) type FnChsReferenceType =
    unsafe extern "C" fn(*const u8, usize, *mut *mut ChsBuf, *mut *mut ChsError) -> i32;
pub(crate) type FnChsInitialize = unsafe extern "C" fn(*mut *mut ChsError) -> i32;
pub(crate) type FnChsSetDefaults =
    unsafe extern "C" fn(*const u8, usize, *mut *mut ChsError) -> i32;
pub(crate) type FnChsShutdown = unsafe extern "C" fn();
pub(crate) type FnChsTypeValidate =
    unsafe extern "C" fn(*const u8, usize, *mut *mut ChsBuf, *mut *mut ChsError) -> i32;
pub(crate) type FnChsBackQuote =
    unsafe extern "C" fn(*const u8, usize, *mut *mut ChsBuf, *mut *mut ChsError) -> i32;
pub(crate) type FnChsBackQuoteIfNeeded =
    unsafe extern "C" fn(*const u8, usize, *mut *mut ChsBuf, *mut *mut ChsError) -> i32;
pub(crate) type FnChsQuoteString =
    unsafe extern "C" fn(*const u8, usize, *mut *mut ChsBuf, *mut *mut ChsError) -> i32;
pub(crate) type FnChsSchemaCreate = unsafe extern "C" fn(
    *const u8,
    usize,
    *const u8,
    usize,
    *mut *mut ChsSchema,
    *mut *mut ChsError,
) -> i32;
pub(crate) type FnChsSchemaFree = unsafe extern "C" fn(*mut ChsSchema);
pub(crate) type FnChsSchemaDescribe =
    unsafe extern "C" fn(*const ChsSchema, *mut *mut ChsBuf, *mut *mut ChsError) -> i32;
pub(crate) type FnChsPreviewRow = unsafe extern "C" fn(
    *const ChsSchema,
    i32,
    *const u8,
    usize,
    *const u8,
    usize,
    *const u8,
    usize,
    *mut *mut ChsBuf,
    *mut *mut ChsError,
) -> i32;
pub(crate) type FnChsPreviewBatch = unsafe extern "C" fn(
    *const ChsSchema,
    i32,
    *const u8,
    usize,
    *const u8,
    usize,
    *const u8,
    usize,
    *const ChsFilter,
    i32,
    u32,
    *mut *mut ChsBuf,
    *mut *mut ChsBuf,
    *mut *mut ChsError,
) -> i32;
pub(crate) type FnChsFilterCreate = unsafe extern "C" fn(
    *const ChsSchema,
    *const u8,
    usize,
    *const u8,
    usize,
    *mut *mut ChsFilter,
    *mut *mut ChsError,
) -> i32;
pub(crate) type FnChsFilterFree = unsafe extern "C" fn(*mut ChsFilter);
pub(crate) type FnChsFilterEvalBody = unsafe extern "C" fn(
    *const ChsFilter,
    i32,
    *const u8,
    usize,
    *const u8,
    usize,
    *mut *mut ChsBuf,
    *mut *mut ChsError,
) -> i32;
pub(crate) type FnChsBlockCreate = unsafe extern "C" fn(
    *const ChsSchema,
    i32,
    *const u8,
    usize,
    *const u8,
    usize,
    *const u8,
    usize,
    *mut *mut ChsBlock,
    *mut *mut ChsError,
) -> i32;
pub(crate) type FnChsBlockFree = unsafe extern "C" fn(*mut ChsBlock);
pub(crate) type FnChsFilterEvalBlock = unsafe extern "C" fn(
    *const ChsFilter,
    *const ChsBlock,
    *mut *mut ChsBuf,
    *mut *mut ChsError,
) -> i32;
pub(crate) type FnChsDiscoverQuery =
    unsafe extern "C" fn(*mut *mut ChsBuf, *mut *mut ChsError) -> i32;
pub(crate) type FnChsDiscoverColumns =
    unsafe extern "C" fn(*const u8, usize, *mut *mut ChsBuf, *mut *mut ChsError) -> i32;

// -------------------------------------------------------------- handshake

/// The two symbols loader steps 3 and 4 need before the full table is safe
/// to resolve (D1.2: "nothing before the checks"). `Api` is constructible
/// only through `Api::resolve_all`, after those checks and the step-5
/// cross-check pass, so a hand-written caller cannot reach a non-handshake
/// symbol early by construction.
pub(crate) struct Handshake {
    pub(crate) chs_abi_version: Symbol<FnChsAbiVersion>,
    pub(crate) chs_build_info: Symbol<FnChsBuildInfo>,
}

impl Handshake {
    /// # Safety
    /// `lib` must be a library this process just `dlopen`'d and will never
    /// `dlclose` (D2's no-`dlclose`-ever rule): the returned symbols outlive
    /// this call only because the image itself is never unloaded.
    pub(crate) unsafe fn resolve(lib: &UnixLibrary) -> Result<Handshake, &'static str> {
        // SAFETY: the caller's `# Safety` clause is exactly what `Symbol`'s own
        // safety contract needs: the library stays loaded for the process's life.
        unsafe {
            Ok(Handshake {
                chs_abi_version: lib
                    .get(concat!("chs_abi_version", "\0").as_bytes())
                    .map_err(|_| "chs_abi_version")?,
                chs_build_info: lib
                    .get(concat!("chs_build_info", "\0").as_bytes())
                    .map_err(|_| "chs_build_info")?,
            })
        }
    }
}

// ------------------------------------------------------------------- api

/// Every described symbol, resolved once (loader step 6: `api`, `tooling`
/// and the tombstone, all for presence). Built only by `Api::resolve_all`.
pub(crate) struct Api {
    /// Held so the mapping outlives every symbol; never dropped (D2: no
    /// `dlclose`, ever — see `rust/src/ffi.rs`'s identical v0 rule).
    _lib: std::mem::ManuallyDrop<UnixLibrary>,
    pub(crate) chs_abi_version: Symbol<FnChsAbiVersion>,
    pub(crate) chs_build_info: Symbol<FnChsBuildInfo>,
    pub(crate) chs_clickhouse_version: Symbol<FnChsClickhouseVersion>,
    pub(crate) chs_abi_revision: Symbol<FnChsAbiRevision>,
    pub(crate) chs_buf_data: Symbol<FnChsBufData>,
    pub(crate) chs_buf_len: Symbol<FnChsBufLen>,
    pub(crate) chs_buf_free: Symbol<FnChsBufFree>,
    pub(crate) chs_error_status: Symbol<FnChsErrorStatus>,
    pub(crate) chs_error_ch_code: Symbol<FnChsErrorChCode>,
    pub(crate) chs_error_ch_name: Symbol<FnChsErrorChName>,
    pub(crate) chs_error_message: Symbol<FnChsErrorMessage>,
    pub(crate) chs_error_column: Symbol<FnChsErrorColumn>,
    pub(crate) chs_error_free: Symbol<FnChsErrorFree>,
    pub(crate) chs_live_handles: Symbol<FnChsLiveHandles>,
    pub(crate) chs_error_codes: Symbol<FnChsErrorCodes>,
    pub(crate) chs_registered_families: Symbol<FnChsRegisteredFamilies>,
    pub(crate) chs_function_flags: Symbol<FnChsFunctionFlags>,
    pub(crate) chs_reference_type: Symbol<FnChsReferenceType>,
    pub(crate) chs_initialize: Symbol<FnChsInitialize>,
    pub(crate) chs_set_defaults: Symbol<FnChsSetDefaults>,
    pub(crate) chs_shutdown: Symbol<FnChsShutdown>,
    pub(crate) chs_type_validate: Symbol<FnChsTypeValidate>,
    pub(crate) chs_back_quote: Symbol<FnChsBackQuote>,
    pub(crate) chs_back_quote_if_needed: Symbol<FnChsBackQuoteIfNeeded>,
    pub(crate) chs_quote_string: Symbol<FnChsQuoteString>,
    pub(crate) chs_schema_create: Symbol<FnChsSchemaCreate>,
    pub(crate) chs_schema_free: Symbol<FnChsSchemaFree>,
    pub(crate) chs_schema_describe: Symbol<FnChsSchemaDescribe>,
    pub(crate) chs_preview_row: Symbol<FnChsPreviewRow>,
    pub(crate) chs_preview_batch: Symbol<FnChsPreviewBatch>,
    pub(crate) chs_filter_create: Symbol<FnChsFilterCreate>,
    pub(crate) chs_filter_free: Symbol<FnChsFilterFree>,
    pub(crate) chs_filter_eval_body: Symbol<FnChsFilterEvalBody>,
    pub(crate) chs_block_create: Symbol<FnChsBlockCreate>,
    pub(crate) chs_block_free: Symbol<FnChsBlockFree>,
    pub(crate) chs_filter_eval_block: Symbol<FnChsFilterEvalBlock>,
    pub(crate) chs_discover_query: Symbol<FnChsDiscoverQuery>,
    pub(crate) chs_discover_columns: Symbol<FnChsDiscoverColumns>,
}

impl Api {
    /// Resolve every described symbol by name, naming the FIRST one that is
    /// missing (`sdk.json`'s `missing_symbol:<name>` loader refusal, step 6).
    ///
    /// # Safety
    /// `lib` must be a library this process just `dlopen`'d, past steps 1-5,
    /// and will never `dlclose` (D2).
    pub(crate) unsafe fn resolve_all(lib: UnixLibrary) -> Result<Api, &'static str> {
        // SAFETY: the caller's `# Safety` clause is `Symbol`'s own contract.
        unsafe {
            Ok(Api {
                chs_abi_version: lib
                    .get(concat!("chs_abi_version", "\0").as_bytes())
                    .map_err(|_| "chs_abi_version")?,
                chs_build_info: lib
                    .get(concat!("chs_build_info", "\0").as_bytes())
                    .map_err(|_| "chs_build_info")?,
                chs_clickhouse_version: lib
                    .get(concat!("chs_clickhouse_version", "\0").as_bytes())
                    .map_err(|_| "chs_clickhouse_version")?,
                chs_abi_revision: lib
                    .get(concat!("chs_abi_revision", "\0").as_bytes())
                    .map_err(|_| "chs_abi_revision")?,
                chs_buf_data: lib
                    .get(concat!("chs_buf_data", "\0").as_bytes())
                    .map_err(|_| "chs_buf_data")?,
                chs_buf_len: lib
                    .get(concat!("chs_buf_len", "\0").as_bytes())
                    .map_err(|_| "chs_buf_len")?,
                chs_buf_free: lib
                    .get(concat!("chs_buf_free", "\0").as_bytes())
                    .map_err(|_| "chs_buf_free")?,
                chs_error_status: lib
                    .get(concat!("chs_error_status", "\0").as_bytes())
                    .map_err(|_| "chs_error_status")?,
                chs_error_ch_code: lib
                    .get(concat!("chs_error_ch_code", "\0").as_bytes())
                    .map_err(|_| "chs_error_ch_code")?,
                chs_error_ch_name: lib
                    .get(concat!("chs_error_ch_name", "\0").as_bytes())
                    .map_err(|_| "chs_error_ch_name")?,
                chs_error_message: lib
                    .get(concat!("chs_error_message", "\0").as_bytes())
                    .map_err(|_| "chs_error_message")?,
                chs_error_column: lib
                    .get(concat!("chs_error_column", "\0").as_bytes())
                    .map_err(|_| "chs_error_column")?,
                chs_error_free: lib
                    .get(concat!("chs_error_free", "\0").as_bytes())
                    .map_err(|_| "chs_error_free")?,
                chs_live_handles: lib
                    .get(concat!("chs_live_handles", "\0").as_bytes())
                    .map_err(|_| "chs_live_handles")?,
                chs_error_codes: lib
                    .get(concat!("chs_error_codes", "\0").as_bytes())
                    .map_err(|_| "chs_error_codes")?,
                chs_registered_families: lib
                    .get(concat!("chs_registered_families", "\0").as_bytes())
                    .map_err(|_| "chs_registered_families")?,
                chs_function_flags: lib
                    .get(concat!("chs_function_flags", "\0").as_bytes())
                    .map_err(|_| "chs_function_flags")?,
                chs_reference_type: lib
                    .get(concat!("chs_reference_type", "\0").as_bytes())
                    .map_err(|_| "chs_reference_type")?,
                chs_initialize: lib
                    .get(concat!("chs_initialize", "\0").as_bytes())
                    .map_err(|_| "chs_initialize")?,
                chs_set_defaults: lib
                    .get(concat!("chs_set_defaults", "\0").as_bytes())
                    .map_err(|_| "chs_set_defaults")?,
                chs_shutdown: lib
                    .get(concat!("chs_shutdown", "\0").as_bytes())
                    .map_err(|_| "chs_shutdown")?,
                chs_type_validate: lib
                    .get(concat!("chs_type_validate", "\0").as_bytes())
                    .map_err(|_| "chs_type_validate")?,
                chs_back_quote: lib
                    .get(concat!("chs_back_quote", "\0").as_bytes())
                    .map_err(|_| "chs_back_quote")?,
                chs_back_quote_if_needed: lib
                    .get(concat!("chs_back_quote_if_needed", "\0").as_bytes())
                    .map_err(|_| "chs_back_quote_if_needed")?,
                chs_quote_string: lib
                    .get(concat!("chs_quote_string", "\0").as_bytes())
                    .map_err(|_| "chs_quote_string")?,
                chs_schema_create: lib
                    .get(concat!("chs_schema_create", "\0").as_bytes())
                    .map_err(|_| "chs_schema_create")?,
                chs_schema_free: lib
                    .get(concat!("chs_schema_free", "\0").as_bytes())
                    .map_err(|_| "chs_schema_free")?,
                chs_schema_describe: lib
                    .get(concat!("chs_schema_describe", "\0").as_bytes())
                    .map_err(|_| "chs_schema_describe")?,
                chs_preview_row: lib
                    .get(concat!("chs_preview_row", "\0").as_bytes())
                    .map_err(|_| "chs_preview_row")?,
                chs_preview_batch: lib
                    .get(concat!("chs_preview_batch", "\0").as_bytes())
                    .map_err(|_| "chs_preview_batch")?,
                chs_filter_create: lib
                    .get(concat!("chs_filter_create", "\0").as_bytes())
                    .map_err(|_| "chs_filter_create")?,
                chs_filter_free: lib
                    .get(concat!("chs_filter_free", "\0").as_bytes())
                    .map_err(|_| "chs_filter_free")?,
                chs_filter_eval_body: lib
                    .get(concat!("chs_filter_eval_body", "\0").as_bytes())
                    .map_err(|_| "chs_filter_eval_body")?,
                chs_block_create: lib
                    .get(concat!("chs_block_create", "\0").as_bytes())
                    .map_err(|_| "chs_block_create")?,
                chs_block_free: lib
                    .get(concat!("chs_block_free", "\0").as_bytes())
                    .map_err(|_| "chs_block_free")?,
                chs_filter_eval_block: lib
                    .get(concat!("chs_filter_eval_block", "\0").as_bytes())
                    .map_err(|_| "chs_filter_eval_block")?,
                chs_discover_query: lib
                    .get(concat!("chs_discover_query", "\0").as_bytes())
                    .map_err(|_| "chs_discover_query")?,
                chs_discover_columns: lib
                    .get(concat!("chs_discover_columns", "\0").as_bytes())
                    .map_err(|_| "chs_discover_columns")?,
                _lib: std::mem::ManuallyDrop::new(lib),
            })
        }
    }
}
