// GENERATED by scripts/abi-v1/gen.py from spec/abi-v1/abi.json (CHS_ABI_FINGERPRINT sha256:d6b9a42bc2fbb97273122a098ce09ee980d4ef31c0ceb6cb1b5c99e1465e0431) — DO NOT EDIT
//
// Every vocabulary of the description, as Rust: the `chs_format` and
// `chs_status` numbers, the document vocabularies (outcomes, verdicts,
// reasons with their `lossy` fact, sources with their `is_stored` fact,
// default kinds), and the document-group flags. No binding keeps a copy
// of its own. See scripts/abi-v1/emit/rust.py.

// ----------------------------------------------------------------- format

/// The input (and export) encoding of a body, as the `chs_format` integer.
/// **The numbers are part of the ABI** (frozen) and are never renumbered.
/// Each carries `ch_name`, ClickHouse's own name for the format, which is how
/// a build's `capabilities` lists it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum Format {
    /// `JSONEachRow` (`CHS_JSON_EACH_ROW`).
    JsonEachRow = 0,
    /// `CSV` (`CHS_CSV`).
    Csv = 1,
    /// `TSV` (`CHS_TSV`).
    Tsv = 2,
    /// `Values` (`CHS_VALUES`).
    Values = 3,
    /// `JSONCompactEachRow` (`CHS_JSON_COMPACT_EACH_ROW`).
    JsonCompactEachRow = 4,
    /// `RowBinary` (`CHS_ROW_BINARY`).
    RowBinary = 5,
    /// `RowBinaryWithDefaults` (`CHS_ROW_BINARY_WITH_DEFAULTS`).
    RowBinaryWithDefaults = 6,
    /// `RowBinaryWithNamesAndTypesAndDefaults` (`CHS_ROW_BINARY_WITH_NAMES_AND_TYPES_AND_DEFAULTS`).
    RowBinaryWithNamesAndTypesAndDefaults = 7,
    /// `Native` (`CHS_NATIVE`).
    Native = 8,
    /// `Buffers` (`CHS_BUFFERS`).
    Buffers = 9,
    /// `CSVWithNames` (`CHS_CSV_WITH_NAMES`).
    CsvWithNames = 10,
    /// `TSVWithNames` (`CHS_TSV_WITH_NAMES`).
    TsvWithNames = 11,
}

impl Format {
    /// Every format, in numeric order.
    pub const ALL: [Format; 12] = [
        Format::JsonEachRow,
        Format::Csv,
        Format::Tsv,
        Format::Values,
        Format::JsonCompactEachRow,
        Format::RowBinary,
        Format::RowBinaryWithDefaults,
        Format::RowBinaryWithNamesAndTypesAndDefaults,
        Format::Native,
        Format::Buffers,
        Format::CsvWithNames,
        Format::TsvWithNames,
    ];

    /// ClickHouse's own name for this format, as `capabilities` lists it.
    pub fn ch_name(self) -> &'static str {
        match self {
            Format::JsonEachRow => "JSONEachRow",
            Format::Csv => "CSV",
            Format::Tsv => "TSV",
            Format::Values => "Values",
            Format::JsonCompactEachRow => "JSONCompactEachRow",
            Format::RowBinary => "RowBinary",
            Format::RowBinaryWithDefaults => "RowBinaryWithDefaults",
            Format::RowBinaryWithNamesAndTypesAndDefaults => {
                "RowBinaryWithNamesAndTypesAndDefaults"
            }
            Format::Native => "Native",
            Format::Buffers => "Buffers",
            Format::CsvWithNames => "CSVWithNames",
            Format::TsvWithNames => "TSVWithNames",
        }
    }

    /// The `chs_format` value that crosses the C boundary.
    pub(crate) fn code(self) -> i32 {
        self as i32
    }
}

/// The call statuses, as the `chs_status` integers (D3, frozen). A call error
/// carries the raw status; compare it with these.
pub mod status {
    /// `CHS_OK`.
    pub const OK: i32 = 0;
    /// `CHS_REJECTED`.
    pub const REJECTED: i32 = 1;
    /// `CHS_DECLINED`.
    pub const DECLINED: i32 = 2;
    /// `CHS_INVALID_ARGUMENT`.
    pub const INVALID_ARGUMENT: i32 = 3;
    /// `CHS_INTERNAL`.
    pub const INTERNAL: i32 = 4;
}

/// A row's or a batch's outcome, as the library's document states it (already final: the library applies every promotion).
/// An unknown value reads as the description's fallback, `unsupported`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[non_exhaustive]
pub enum Outcome {
    /// The wire value `accepted`.
    Accepted,
    /// The wire value `accepted_poisoned`.
    AcceptedPoisoned,
    /// The wire value `rejected`.
    Rejected,
    /// The wire value `skipped`.
    Skipped,
    #[default]
    /// The wire value `unsupported`.
    Unsupported,
}

impl Outcome {
    /// The wire spelling.
    pub fn as_str(self) -> &'static str {
        match self {
            Outcome::Accepted => "accepted",
            Outcome::AcceptedPoisoned => "accepted_poisoned",
            Outcome::Rejected => "rejected",
            Outcome::Skipped => "skipped",
            Outcome::Unsupported => "unsupported",
        }
    }

    /// Read one wire value; an unknown value reads as the description's fallback
    pub(crate) fn from_wire(s: &str) -> Self {
        match s {
            "accepted" => Outcome::Accepted,
            "accepted_poisoned" => Outcome::AcceptedPoisoned,
            "rejected" => Outcome::Rejected,
            "skipped" => Outcome::Skipped,
            "unsupported" => Outcome::Unsupported,
            _ => Self::Unsupported,
        }
    }
}

impl std::fmt::Display for Outcome {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A filter evaluation's outcome. An unknown value reads as the description's fallback, `unsupported`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[non_exhaustive]
pub enum FilterOutcome {
    /// The wire value `ok`.
    Ok,
    /// The wire value `rejected`.
    Rejected,
    #[default]
    /// The wire value `unsupported`.
    Unsupported,
}

impl FilterOutcome {
    /// The wire spelling.
    pub fn as_str(self) -> &'static str {
        match self {
            FilterOutcome::Ok => "ok",
            FilterOutcome::Rejected => "rejected",
            FilterOutcome::Unsupported => "unsupported",
        }
    }

    /// Read one wire value; an unknown value reads as the description's fallback
    pub(crate) fn from_wire(s: &str) -> Self {
        match s {
            "ok" => FilterOutcome::Ok,
            "rejected" => FilterOutcome::Rejected,
            "unsupported" => FilterOutcome::Unsupported,
            _ => Self::Unsupported,
        }
    }
}

impl std::fmt::Display for FilterOutcome {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// One row's filter verdict. `answered` says which are answers; `Error` and `Decline` are never answers, and a caller enforcing visibility fails closed on both.
/// An unknown value reads as the description's fallback, `d`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[non_exhaustive]
pub enum Verdict {
    /// The wire value `t`.
    True,
    /// The wire value `f`.
    False,
    /// The wire value `e`.
    Error,
    #[default]
    /// The wire value `d`.
    Decline,
}

impl Verdict {
    /// The wire spelling.
    pub fn as_str(self) -> &'static str {
        match self {
            Verdict::True => "t",
            Verdict::False => "f",
            Verdict::Error => "e",
            Verdict::Decline => "d",
        }
    }

    /// Read one wire value; an unknown value reads as the description's fallback
    pub(crate) fn from_wire(s: &str) -> Self {
        match s {
            "t" => Verdict::True,
            "f" => Verdict::False,
            "e" => Verdict::Error,
            "d" => Verdict::Decline,
            _ => Self::Decline,
        }
    }

    /// The description's `answered` fact for this value.
    pub fn answered(self) -> bool {
        match self {
            Verdict::True => true,
            Verdict::False => true,
            Verdict::Error => false,
            Verdict::Decline => false,
        }
    }
}

impl std::fmt::Display for Verdict {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Verdict {
    /// The document character: `t`, `f`, `e` or `d`.
    pub fn as_char(self) -> char {
        match self {
            Verdict::True => 't',
            Verdict::False => 'f',
            Verdict::Error => 'e',
            Verdict::Decline => 'd',
        }
    }
}

/// What a column's DEFAULT clause is. The empty wire value is `None`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum DefaultKind {
    /// The wire value ``.
    None,
    /// The wire value `DEFAULT`.
    Default,
    /// The wire value `MATERIALIZED`.
    Materialized,
    /// The wire value `ALIAS`.
    Alias,
    /// The wire value `EPHEMERAL`.
    Ephemeral,
}

impl DefaultKind {
    /// The wire spelling.
    pub fn as_str(self) -> &'static str {
        match self {
            DefaultKind::None => "",
            DefaultKind::Default => "DEFAULT",
            DefaultKind::Materialized => "MATERIALIZED",
            DefaultKind::Alias => "ALIAS",
            DefaultKind::Ephemeral => "EPHEMERAL",
        }
    }

    /// Read one wire value; `None` for a value the description does not list.
    pub(crate) fn from_wire(s: &str) -> Option<Self> {
        match s {
            "" => Some(DefaultKind::None),
            "DEFAULT" => Some(DefaultKind::Default),
            "MATERIALIZED" => Some(DefaultKind::Materialized),
            "ALIAS" => Some(DefaultKind::Alias),
            "EPHEMERAL" => Some(DefaultKind::Ephemeral),
            _ => None,
        }
    }
}

impl std::fmt::Display for DefaultKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// The `transform_reason` vocabulary: the reason spellings a transformation
/// carries, and the `lossy` fact the description gives each.
pub mod reason {
    /// `overflow_wrap`.
    pub const OVERFLOW_WRAP: &str = "overflow_wrap";
    /// `null_to_default`.
    pub const NULL_TO_DEFAULT: &str = "null_to_default";
    /// `null_loss`.
    pub const NULL_LOSS: &str = "null_loss";
    /// `decimal_truncate`.
    pub const DECIMAL_TRUNCATE: &str = "decimal_truncate";
    /// `date_clamp`.
    pub const DATE_CLAMP: &str = "date_clamp";
    /// `datetime_wrap`.
    pub const DATETIME_WRAP: &str = "datetime_wrap";
    /// `date_shift`.
    pub const DATE_SHIFT: &str = "date_shift";
    /// `uuid_mangle`.
    pub const UUID_MANGLE: &str = "uuid_mangle";
    /// `ip_mangle`.
    pub const IP_MANGLE: &str = "ip_mangle";
    /// `float_precision`.
    pub const FLOAT_PRECISION: &str = "float_precision";
    /// `lossy_numeric`.
    pub const LOSSY_NUMERIC: &str = "lossy_numeric";
    /// `fixedstring_pad`.
    pub const FIXEDSTRING_PAD: &str = "fixedstring_pad";
    /// `emptied`.
    pub const EMPTIED: &str = "emptied";
    /// `element_changed`.
    pub const ELEMENT_CHANGED: &str = "element_changed";
    /// `enum_coerce`.
    pub const ENUM_COERCE: &str = "enum_coerce";
    /// `value_changed`.
    pub const VALUE_CHANGED: &str = "value_changed";
    /// `poisoned`.
    pub const POISONED: &str = "poisoned";
    /// `duplicate_key_dropped`.
    pub const DUPLICATE_KEY_DROPPED: &str = "duplicate_key_dropped";
    /// `reformat`.
    pub const REFORMAT: &str = "reformat";
    /// `default_filled`.
    pub const DEFAULT_FILLED: &str = "default_filled";
    /// `zero_filled`.
    pub const ZERO_FILLED: &str = "zero_filled";
    /// `default_materialized`.
    pub const DEFAULT_MATERIALIZED: &str = "default_materialized";
    /// `ttl_expired`.
    pub const TTL_EXPIRED: &str = "ttl_expired";
    /// `ttl_column_expired`.
    pub const TTL_COLUMN_EXPIRED: &str = "ttl_column_expired";

    /// The description's `lossy` fact for a reason; a reason the description does
    /// not list takes the fallback's fact.
    pub fn is_lossy(reason: &str) -> bool {
        match reason {
            "overflow_wrap" => true,
            "null_to_default" => true,
            "null_loss" => true,
            "decimal_truncate" => true,
            "date_clamp" => true,
            "datetime_wrap" => true,
            "date_shift" => true,
            "uuid_mangle" => true,
            "ip_mangle" => true,
            "float_precision" => true,
            "lossy_numeric" => true,
            "fixedstring_pad" => true,
            "emptied" => true,
            "element_changed" => true,
            "enum_coerce" => true,
            "value_changed" => true,
            "poisoned" => true,
            "duplicate_key_dropped" => true,
            "reformat" => false,
            "default_filled" => false,
            "zero_filled" => false,
            "default_materialized" => false,
            "ttl_expired" => true,
            "ttl_column_expired" => true,
            _ => true,
        }
    }
}

/// The `value_src` vocabulary: where a column's value came from, and whether
/// the description says it is stored.
pub mod source {
    /// `input`.
    pub const INPUT: &str = "input";
    /// `default`.
    pub const DEFAULT: &str = "default";
    /// `default_substituted`.
    pub const DEFAULT_SUBSTITUTED: &str = "default_substituted";
    /// `default_generated`.
    pub const DEFAULT_GENERATED: &str = "default_generated";
    /// `absent`.
    pub const ABSENT: &str = "absent";
    /// `materialized_input`.
    pub const MATERIALIZED_INPUT: &str = "materialized_input";
    /// `skipped`.
    pub const SKIPPED: &str = "skipped";
    /// `ephemeral_input`.
    pub const EPHEMERAL_INPUT: &str = "ephemeral_input";
    /// `default_expr_unsupported`.
    pub const DEFAULT_EXPR_UNSUPPORTED: &str = "default_expr_unsupported";
    /// `default_volatile_unresolved`.
    pub const DEFAULT_VOLATILE_UNRESOLVED: &str = "default_volatile_unresolved";
    /// `default_pending`.
    pub const DEFAULT_PENDING: &str = "default_pending";

    /// The description's `is_stored` fact for a source, or `None` for a value the
    /// description does not list (the vocabulary has no fallback).
    pub fn is_stored(src: &str) -> Option<bool> {
        match src {
            "input" => Some(true),
            "default" => Some(true),
            "default_substituted" => Some(true),
            "default_generated" => Some(true),
            "absent" => Some(true),
            "materialized_input" => Some(true),
            "skipped" => Some(false),
            "ephemeral_input" => Some(false),
            "default_expr_unsupported" => Some(false),
            "default_volatile_unresolved" => Some(false),
            "default_pending" => Some(false),
            _ => None,
        }
    }
}

/// Which groups a `rows` document carries: values (`cols`), transformations
/// and defaults. Combine with `|`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct DocFlags(u32);

impl DocFlags {
    /// `CHS_DOC_VALUES`.
    pub const VALUES: DocFlags = DocFlags(1);
    /// `CHS_DOC_TRANSFORMS`.
    pub const TRANSFORMS: DocFlags = DocFlags(2);
    /// `CHS_DOC_DEFAULTS`.
    pub const DEFAULTS: DocFlags = DocFlags(4);
    /// `CHS_DOC_ALL`.
    pub const ALL: DocFlags = DocFlags(7);

    /// The raw bitmask, as it crosses the C boundary.
    pub fn bits(self) -> u32 {
        self.0
    }

    /// A mask from raw bits, unvalidated on purpose: an unknown bit reaches the
    /// library, which refuses it loudly.
    pub fn from_bits(bits: u32) -> DocFlags {
        DocFlags(bits)
    }
}

impl std::ops::BitOr for DocFlags {
    type Output = DocFlags;
    fn bitor(self, rhs: DocFlags) -> DocFlags {
        DocFlags(self.0 | rhs.0)
    }
}

impl std::ops::BitOrAssign for DocFlags {
    fn bitor_assign(&mut self, rhs: DocFlags) {
        self.0 |= rhs.0;
    }
}

/// `export_format` when no export is asked for.
pub(crate) const EXPORT_NONE: i32 = -1;

/// The JSON member suffix that carries a name's raw bytes in base64, when the
/// plain member would not be valid UTF-8.
pub(crate) const BYTES_SUFFIX: &str = "_b64";

/// The text member of a name.
pub(crate) const NAME_TEXT: &str = "name";
