# Code generated by scripts/fetch-v1/gen-constants.py from
# spec/fetch-v1/constants.json. DO NOT EDIT.
# Source sha256: 82afa8d6cba96c10b5945c6f7c1c8360a504cc8ac6231e74017cc6c20b908df6
"""The v1 fetch constants, generated: see docs/guides/fetch-v1.md."""

from __future__ import annotations

from typing import Final

SCHEMA_VERSION: Final[int] = 1
ABI_GENERATION: Final[int] = 1

ENV_BASES_NAME: Final[str] = "CHTYPES_ARTIFACTS_URL"
BASE_SEPARATOR: Final[str] = ","
FIXTURES_REPO_SUFFIX: Final[str] = "/sdk-fetch-fixtures"
DEFAULT_BASES: Final[tuple[str, ...]] = ("https://registry.wavehouse.dev/chtypes/v1",)
ALLOWED_SCHEMES: Final[tuple[str, ...]] = ("https", "http", "file")

ENV_CACHE_NAME: Final[str] = "CHTYPES_CACHE"
ENV_TOKEN_NAME: Final[str] = "CHTYPES_DOWNLOAD_TOKEN"
ENV_TRUSTED_KEYS_NAME: Final[str] = "CHTYPES_TRUSTED_KEYS"
ENV_ALLOW_UNSIGNED_NAME: Final[str] = "CHTYPES_ALLOW_UNSIGNED"
ENV_AUTOFETCH_NAME: Final[str] = "CHTYPES_AUTOFETCH"
ENV_TARGET_NAME: Final[str] = "CHTYPES_TARGET"
ENV_CACHE_STRICT_NAME: Final[str] = "CHTYPES_CACHE_STRICT"
ENV_RETIRED: Final[tuple[str, ...]] = ("CHTYPES_REGISTRY",)

SPELLING_REGEX: Final[str] = (
    "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(\\.(0|[1-9][0-9]*)(\\.(0|[1-9][0-9]*))?)?$"
)
SPELLING_REFUSE_HINT_REGEX: Final[str] = "^v|-(lts|stable)$"

PLATFORMS: Final[tuple[dict[str, str], ...]] = (
    {"key": "linux-amd64", "os": "linux", "architecture": "amd64"},
    {"key": "linux-arm64", "os": "linux", "architecture": "arm64"},
    {"key": "darwin-arm64", "os": "darwin", "architecture": "arm64"},
)

MEDIA_TYPE_INDEX: Final[str] = "application/vnd.oci.image.index.v1+json"
MEDIA_TYPE_MANIFEST: Final[str] = "application/vnd.oci.image.manifest.v1+json"
MEDIA_TYPE_EMPTY_CONFIG: Final[str] = "application/vnd.oci.empty.v1+json"
MEDIA_TYPE_CONFIG: Final[str] = "application/vnd.wavehouse.chtypes.config.v1+json"
MEDIA_TYPE_LAYER: Final[str] = "application/vnd.oci.image.layer.v1.tar+zstd"
MEDIA_TYPE_BUNDLE: Final[str] = "application/vnd.dev.sigstore.bundle.v0.3+json"
ARTIFACT_TYPE: Final[str] = "application/vnd.wavehouse.chtypes.artifact.v1"
GOLDENS_ARTIFACT_TYPE: Final[str] = "application/vnd.wavehouse.chtypes.goldens.v1"
FIXTURES_ARTIFACT_TYPE: Final[str] = "application/vnd.wavehouse.chtypes.sdk-fetch-fixtures.v1"
CHANNEL_ARTIFACT_TYPE: Final[str] = "application/vnd.wavehouse.chtypes.channel.v1"

DSSE_PAYLOAD_TYPE: Final[str] = "application/vnd.in-toto+json"
DSSE_MAX_SIGNATURES: Final[int] = 4

STATEMENT_TYPE: Final[str] = "https://in-toto.io/Statement/v1"

PREDICATE_TYPE_ARTIFACT: Final[str] = "https://artifacts.wavehouse.dev/spec/artifact/v1"
PREDICATE_TYPE_GOLDENS: Final[str] = "https://artifacts.wavehouse.dev/spec/goldens/v1"
PREDICATE_TYPE_FIXTURES: Final[str] = "https://artifacts.wavehouse.dev/spec/sdk-fetch-fixtures/v1"
PREDICATE_TYPE_CHANNEL: Final[str] = "https://artifacts.wavehouse.dev/spec/channel/v1"

KEYID_ALGORITHM: Final[str] = "sha256-first16hex"
RELEASE_KEYS: Final[tuple[dict[str, str], ...]] = (
    {
        "keyid": "deb275922dbff76e",
        "ed25519_hex": "fdb5f06a8d4c9918d049a5f1748fa2e3b3238c3f2000986d5bb9e31beff778fc",
    },
)

# Fixture-only keys. A conformance case trusts one only by explicitly naming
# it; TRUSTED_BY_DEFAULT is always False and never consulted for real trust.
TEST_KEYS: Final[tuple[dict[str, object], ...]] = (
    {
        "keyid": "6c3468e4ec653ac0",
        "ed25519_hex": "b9b314491f92f6c4b93fc69f932164739a619965ed79dbbcea7a4ae2da611ce2",
        "trusted_by_default": False,
    },
)

RETRY_ATTEMPTS: Final[int] = 5
RETRY_FIRST_WAIT_S: Final[float] = 4.0
RETRY_MULTIPLIER: Final[float] = 2.0
RETRY_STATUSES: Final[tuple[int, ...]] = (408, 429, 500, 502, 503, 504)
RETRY_AFTER_STATUSES: Final[tuple[int, ...]] = (429, 503)
RETRY_AFTER_OVER_BUDGET: Final[str] = "refuse"
DIGEST_404_POLICY: Final[str] = "next_base_then_retry_on_last"
TAG_404_POLICY: Final[str] = "next_base_then_unpublished"
RETIRED_STATUSES: Final[tuple[int, ...]] = (410,)

CONNECT_TIMEOUT_S: Final[float] = 30.0
IDLE_READ_TIMEOUT_S: Final[float] = 60.0

MANIFEST_MAX_BYTES: Final[int] = 4194304
BUNDLE_MAX_BYTES: Final[int] = 1048576
TAGS_LIST_MAX_BYTES: Final[int] = 8388608
LAYOUT_INDEX_MAX_BYTES: Final[int] = 8388608
MAX_REFERRERS: Final[int] = 16
MAX_REDIRECTS: Final[int] = 5
MAX_UNPACKED_BYTES: Final[int] = 4294967296
ZSTD_WINDOW_LOG_MAX: Final[int] = 27
RETIRED_BODY_MAX_BYTES: Final[int] = 65536
RETIRED_MESSAGE_MAX_CODE_POINTS: Final[int] = 256

CACHE_ROOT_TEMPLATE: Final[str] = "${XDG_CACHE_HOME:-$HOME/.cache}/chtypes/v1"
SYSTEM_CACHE_DIRS: Final[tuple[str, ...]] = ("/usr/local/share/chtypes/v1", "/opt/chtypes/v1")
PROD_V2_NAME: Final[str] = "v2"
PROD_V2_ABI_GENERATION: Final[int] = 2
PROD_V2_RECORD_SCHEMA: Final[int] = 2
PROD_V2_CACHE_DIR: Final[str] = "v2"
PROD_V2_BASES: Final[tuple[str, ...]] = ("https://registry.wavehouse.dev/chtypes/v2",)
PROD_V2_SYSTEM_DIRS: Final[tuple[str, ...]] = ("/usr/local/share/chtypes/v2", "/opt/chtypes/v2")
CACHE_UNPACKED_DIR: Final[str] = "unpacked/sha256"
CACHE_VERIFIED_RECORD: Final[str] = "verified.json"
CACHE_ANNOTATION_PREFIX: Final[str] = "dev.wavehouse.chtypes."

LOCK_SCHEMA: Final[int] = 3
LOCK_DEFAULT_FILE: Final[str] = "chtypes.lock"

AUTOFETCH_UNPUBLISHED_MEMO_S: Final[float] = 300.0

# docs/guides/fetch-v1.md §8: the six v0 codes carry v0's own real, measured
# mapping (python/src/chtypes/__main__.py _EXIT_FOR_CODE; Go, TypeScript and
# Rust agree); the four new v1-only codes are assigned here, not inherited.
ERROR_EXIT_CODES: Final[dict[str, int]] = {
    "CHTYPES_ARTIFACT_MISSING": 1,
    "CHTYPES_ARTIFACT_UNTRUSTED": 1,
    "CHTYPES_ARTIFACT_CORRUPT": 1,
    "CHTYPES_ARTIFACT_PINNED": 1,
    "CHTYPES_ARTIFACT_UNPUBLISHED": 4,
    "CHTYPES_SOURCE_UNREACHABLE": 3,
    "CHTYPES_SOURCE_UNAUTHORIZED": 5,
    "CHTYPES_SOURCE_FORBIDDEN": 6,
    "CHTYPES_SOURCE_INCOMPATIBLE": 7,
    "CHTYPES_ARTIFACT_INCOMPATIBLE": 8,
    "CHTYPES_CACHE_UNUSABLE": 9,
    "CHTYPES_SOURCE_RETIRED": 10,
}
