"""The emitters: one module per output family, discovered, never listed.

Every module in this package except this one is an emitter. `discover()`
imports them in sorted file-name order, so adding a binding's emitter is
adding one file: no list here or in gen.py to edit, and no two lanes ever
edit the same file.

THE CONTRACT. An emitter module defines

    def outputs(model: model.Model) -> list[Output]

and nothing it returns may depend on anything but the model: no clock, no
environment, no network, no randomness, no dict or set iteration order that
the model does not fix. `gen.py --selftest` runs `--write` twice and requires
byte-identical trees, so a nondeterministic emitter fails CI.

An `Output` is either a WHOLE FILE (`content`), which must carry the banner
from `banner()` within its first 512 bytes (first line where the language
allows it; a JSON output carries it as the value of a leading "_generated"
key), or a BLOCK inside a hand-written file (`block`), which `gen.py` splices
between the two marker lines `<!-- BEGIN GENERATED: <name> -->` and
`<!-- END GENERATED: <name> -->`, leaving the rest of the file alone.

Paths are repository-relative, POSIX-separated. Two emitters producing one
path is an error. A whole-file output under a binding's source tree must not
match the security carve-out's verification needles
(scripts/policy-merge-check.py), which `gen.py --check` asserts.

BUILD-TIME FILES. An emitter may also define

    def render_files(model: model.Model) -> dict[str, str]

for files that are generated at build time and never committed (the test
stub's C source is the case it exists for). `gen.py --render <module> --out
DIR` writes them under DIR, keyed by DIR-relative path; `--check` never sees
them. An emitter with only build-time files returns [] from outputs().
"""

from __future__ import annotations

import importlib
import pkgutil
import re
from dataclasses import dataclass
from types import ModuleType

BANNER_PREFIX = "GENERATED by scripts/abi-v1/gen.py from spec/abi-v1/abi.json"
# What `gen.py` (stale-file detection) and check-no-hand-decls.py (the
# generated-file exemption) recognize as a generated file. A real 64-hex
# fingerprint is required, so prose that merely QUOTES the banner's shape
# with an ellipsis is never mistaken for a generated file.
BANNER_RE = re.compile(re.escape(BANNER_PREFIX) + r" \(CHS_ABI_FINGERPRINT sha256:[0-9a-f]{64}\) \S+ DO NOT EDIT")


@dataclass(frozen=True)
class Output:
    path: str
    content: str | None = None
    block: str | None = None  # the generated block's name, for a spliced output
    body: str | None = None  # the block's text, without its marker lines

    def __post_init__(self) -> None:
        if (self.content is None) == (self.block is None):
            raise ValueError(f"{self.path}: an Output is a whole file or a block, exactly one")
        if self.block is not None and self.body is None:
            raise ValueError(f"{self.path}: a block output needs a body")


def banner(model) -> str:
    """The one-line banner, without comment syntax."""
    return f"{BANNER_PREFIX} (CHS_ABI_FINGERPRINT {model.fingerprint}) — DO NOT EDIT"


def marker_key(marker: str) -> tuple[int, int, str]:
    """A provisional marker's display order: A4 before A10, then Q-x, then
    confirm."""
    if marker[:1] == "A" and marker[1:].isdigit():
        return (0, int(marker[1:]), marker)
    return (1 if marker.startswith("Q-") else 2, 0, marker)


def block_markers(name: str) -> tuple[str, str]:
    return f"<!-- BEGIN GENERATED: {name} -->", f"<!-- END GENERATED: {name} -->"


def discover() -> list[ModuleType]:
    mods = []
    for info in sorted(pkgutil.iter_modules(__path__), key=lambda i: i.name):
        if info.name.startswith("_"):
            continue
        mod = importlib.import_module(f"{__name__}.{info.name}")
        if not callable(getattr(mod, "outputs", None)):
            raise TypeError(f"emit/{info.name}.py defines no outputs(model)")
        mods.append(mod)
    return mods
