// GENERATED by scripts/abi-v1/gen.py from spec/abi-v1/abi.json (CHS_ABI_FINGERPRINT sha256:856e5cb7543db291b4db716662bf6e487b2258973b959bbf5d58b4bd46d73285) — DO NOT EDIT

package abi1

/*
#cgo LDFLAGS: -ldl
// glibc's dlfcn.h only declares RTLD_DEFAULT under _GNU_SOURCE; darwin's does not
// need it, but defining it there too is harmless. Must precede every #include.
#define _GNU_SOURCE
#include "abi1_table.h"
#include <dlfcn.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// Resolve glibc's own version string from the CURRENT process (never from the
// candidate artifact, which has not been dlopen'd yet): RTLD_DEFAULT searches only
// images already loaded into this process, so this never touches the artifact path
// at all -- D3's loader step 1 runs "before dlopen". Absence (NULL) means a non-glibc
// libc (musl); loader.go reports that as the sdk.json "no_glibc" reason.
static int chtypes_abi1_glibc_version(char *buf, size_t buflen) {
    const char *(*fn)(void) = (const char *(*)(void)) dlsym(RTLD_DEFAULT, "gnu_get_libc_version");
    if (!fn) return 0;
    const char *v = fn();
    if (!v) return 0;
    size_t n = strlen(v);
    if (n >= buflen) n = buflen - 1;
    memcpy(buf, v, n);
    buf[n] = 0;
    return 1;
}

// RTLD_NOW|RTLD_LOCAL (sdk.json loader.dlopen_flags, D-step 2): every relocation
// is bound at open time (a missing symbol in a transitively linked library fails
// HERE, not on first call), and LOCAL keeps this image's symbols out of the global
// namespace the way every vendored ClickHouse build has always required.
static void *chtypes_abi1_dlopen(const char *path, const char **errmsg) {
    dlerror();
    void *h = dlopen(path, RTLD_NOW | RTLD_LOCAL);
    if (!h) *errmsg = dlerror();
    return h;
}

// Resolves chs_abi_version alone (D1.2 handshake class: callable before any
// check). Returns NULL on success, else the symbol's own name.
static const char *chtypes_abi1_resolve_chs_abi_version(void *h, struct chtypes_abi1_table *t) {
    t->chs_abi_version = (chtypes_abi1_fn_chs_abi_version) dlsym(h, "chs_abi_version");
    if (!t->chs_abi_version) return "chs_abi_version";
    return NULL;
}

// Resolves chs_build_info alone (D1.2 handshake class: callable before any
// check). Returns NULL on success, else the symbol's own name.
static const char *chtypes_abi1_resolve_chs_build_info(void *h, struct chtypes_abi1_table *t) {
    t->chs_build_info = (chtypes_abi1_fn_chs_build_info) dlsym(h, "chs_build_info");
    if (!t->chs_build_info) return "chs_build_info";
    return NULL;
}

// Resolves chs_clickhouse_version alone (D1.2 handshake class: callable before any
// check). Returns NULL on success, else the symbol's own name.
static const char *chtypes_abi1_resolve_chs_clickhouse_version(void *h, struct chtypes_abi1_table *t) {
    t->chs_clickhouse_version = (chtypes_abi1_fn_chs_clickhouse_version) dlsym(h, "chs_clickhouse_version");
    if (!t->chs_clickhouse_version) return "chs_clickhouse_version";
    return NULL;
}

// Step 6: every described symbol -- api, tooling and the chs_abi_revision
// tombstone included, for presence -- resolved only after steps 1-5 pass.
// Returns the first missing symbol's name, or NULL.
static const char *chtypes_abi1_resolve_all(void *h, struct chtypes_abi1_table *t) {
    t->chs_abi_version = (chtypes_abi1_fn_chs_abi_version) dlsym(h, "chs_abi_version");
    if (!t->chs_abi_version) return "chs_abi_version";
    t->chs_build_info = (chtypes_abi1_fn_chs_build_info) dlsym(h, "chs_build_info");
    if (!t->chs_build_info) return "chs_build_info";
    t->chs_clickhouse_version = (chtypes_abi1_fn_chs_clickhouse_version) dlsym(h, "chs_clickhouse_version");
    if (!t->chs_clickhouse_version) return "chs_clickhouse_version";
    t->chs_abi_revision = (chtypes_abi1_fn_chs_abi_revision) dlsym(h, "chs_abi_revision");
    if (!t->chs_abi_revision) return "chs_abi_revision";
    t->chs_buf_data = (chtypes_abi1_fn_chs_buf_data) dlsym(h, "chs_buf_data");
    if (!t->chs_buf_data) return "chs_buf_data";
    t->chs_buf_len = (chtypes_abi1_fn_chs_buf_len) dlsym(h, "chs_buf_len");
    if (!t->chs_buf_len) return "chs_buf_len";
    t->chs_buf_free = (chtypes_abi1_fn_chs_buf_free) dlsym(h, "chs_buf_free");
    if (!t->chs_buf_free) return "chs_buf_free";
    t->chs_error_status = (chtypes_abi1_fn_chs_error_status) dlsym(h, "chs_error_status");
    if (!t->chs_error_status) return "chs_error_status";
    t->chs_error_ch_code = (chtypes_abi1_fn_chs_error_ch_code) dlsym(h, "chs_error_ch_code");
    if (!t->chs_error_ch_code) return "chs_error_ch_code";
    t->chs_error_ch_name = (chtypes_abi1_fn_chs_error_ch_name) dlsym(h, "chs_error_ch_name");
    if (!t->chs_error_ch_name) return "chs_error_ch_name";
    t->chs_error_message = (chtypes_abi1_fn_chs_error_message) dlsym(h, "chs_error_message");
    if (!t->chs_error_message) return "chs_error_message";
    t->chs_error_column = (chtypes_abi1_fn_chs_error_column) dlsym(h, "chs_error_column");
    if (!t->chs_error_column) return "chs_error_column";
    t->chs_error_free = (chtypes_abi1_fn_chs_error_free) dlsym(h, "chs_error_free");
    if (!t->chs_error_free) return "chs_error_free";
    t->chs_live_handles = (chtypes_abi1_fn_chs_live_handles) dlsym(h, "chs_live_handles");
    if (!t->chs_live_handles) return "chs_live_handles";
    t->chs_error_codes = (chtypes_abi1_fn_chs_error_codes) dlsym(h, "chs_error_codes");
    if (!t->chs_error_codes) return "chs_error_codes";
    t->chs_registered_families = (chtypes_abi1_fn_chs_registered_families) dlsym(h, "chs_registered_families");
    if (!t->chs_registered_families) return "chs_registered_families";
    t->chs_function_flags = (chtypes_abi1_fn_chs_function_flags) dlsym(h, "chs_function_flags");
    if (!t->chs_function_flags) return "chs_function_flags";
    t->chs_reference_type = (chtypes_abi1_fn_chs_reference_type) dlsym(h, "chs_reference_type");
    if (!t->chs_reference_type) return "chs_reference_type";
    t->chs_initialize = (chtypes_abi1_fn_chs_initialize) dlsym(h, "chs_initialize");
    if (!t->chs_initialize) return "chs_initialize";
    t->chs_set_defaults = (chtypes_abi1_fn_chs_set_defaults) dlsym(h, "chs_set_defaults");
    if (!t->chs_set_defaults) return "chs_set_defaults";
    t->chs_shutdown = (chtypes_abi1_fn_chs_shutdown) dlsym(h, "chs_shutdown");
    if (!t->chs_shutdown) return "chs_shutdown";
    t->chs_type_validate = (chtypes_abi1_fn_chs_type_validate) dlsym(h, "chs_type_validate");
    if (!t->chs_type_validate) return "chs_type_validate";
    t->chs_back_quote = (chtypes_abi1_fn_chs_back_quote) dlsym(h, "chs_back_quote");
    if (!t->chs_back_quote) return "chs_back_quote";
    t->chs_back_quote_if_needed = (chtypes_abi1_fn_chs_back_quote_if_needed) dlsym(h, "chs_back_quote_if_needed");
    if (!t->chs_back_quote_if_needed) return "chs_back_quote_if_needed";
    t->chs_quote_string = (chtypes_abi1_fn_chs_quote_string) dlsym(h, "chs_quote_string");
    if (!t->chs_quote_string) return "chs_quote_string";
    t->chs_schema_create = (chtypes_abi1_fn_chs_schema_create) dlsym(h, "chs_schema_create");
    if (!t->chs_schema_create) return "chs_schema_create";
    t->chs_schema_free = (chtypes_abi1_fn_chs_schema_free) dlsym(h, "chs_schema_free");
    if (!t->chs_schema_free) return "chs_schema_free";
    t->chs_schema_describe = (chtypes_abi1_fn_chs_schema_describe) dlsym(h, "chs_schema_describe");
    if (!t->chs_schema_describe) return "chs_schema_describe";
    t->chs_preview_row = (chtypes_abi1_fn_chs_preview_row) dlsym(h, "chs_preview_row");
    if (!t->chs_preview_row) return "chs_preview_row";
    t->chs_preview_batch = (chtypes_abi1_fn_chs_preview_batch) dlsym(h, "chs_preview_batch");
    if (!t->chs_preview_batch) return "chs_preview_batch";
    t->chs_filter_create = (chtypes_abi1_fn_chs_filter_create) dlsym(h, "chs_filter_create");
    if (!t->chs_filter_create) return "chs_filter_create";
    t->chs_filter_free = (chtypes_abi1_fn_chs_filter_free) dlsym(h, "chs_filter_free");
    if (!t->chs_filter_free) return "chs_filter_free";
    t->chs_filter_eval_body = (chtypes_abi1_fn_chs_filter_eval_body) dlsym(h, "chs_filter_eval_body");
    if (!t->chs_filter_eval_body) return "chs_filter_eval_body";
    t->chs_block_create = (chtypes_abi1_fn_chs_block_create) dlsym(h, "chs_block_create");
    if (!t->chs_block_create) return "chs_block_create";
    t->chs_block_free = (chtypes_abi1_fn_chs_block_free) dlsym(h, "chs_block_free");
    if (!t->chs_block_free) return "chs_block_free";
    t->chs_filter_eval_block = (chtypes_abi1_fn_chs_filter_eval_block) dlsym(h, "chs_filter_eval_block");
    if (!t->chs_filter_eval_block) return "chs_filter_eval_block";
    t->chs_discover_query = (chtypes_abi1_fn_chs_discover_query) dlsym(h, "chs_discover_query");
    if (!t->chs_discover_query) return "chs_discover_query";
    t->chs_discover_columns = (chtypes_abi1_fn_chs_discover_columns) dlsym(h, "chs_discover_columns");
    if (!t->chs_discover_columns) return "chs_discover_columns";
    return NULL;
}

static int32_t chtypes_abi1_call_chs_abi_version(struct chtypes_abi1_table *t) { return t->chs_abi_version(); }
static const char * chtypes_abi1_call_chs_build_info(struct chtypes_abi1_table *t) { return t->chs_build_info(); }
static const char * chtypes_abi1_call_chs_clickhouse_version(struct chtypes_abi1_table *t) { return t->chs_clickhouse_version(); }
static int chtypes_abi1_call_chs_abi_revision(struct chtypes_abi1_table *t) { return t->chs_abi_revision(); }
static const uint8_t * chtypes_abi1_call_chs_buf_data(struct chtypes_abi1_table *t, const void * buf) { return t->chs_buf_data(buf); }
static size_t chtypes_abi1_call_chs_buf_len(struct chtypes_abi1_table *t, const void * buf) { return t->chs_buf_len(buf); }
static void chtypes_abi1_call_chs_buf_free(struct chtypes_abi1_table *t, void * buf) { t->chs_buf_free(buf); }
static int32_t chtypes_abi1_call_chs_error_status(struct chtypes_abi1_table *t, const void * error) { return t->chs_error_status(error); }
static int32_t chtypes_abi1_call_chs_error_ch_code(struct chtypes_abi1_table *t, const void * error) { return t->chs_error_ch_code(error); }
static void * chtypes_abi1_call_chs_error_ch_name(struct chtypes_abi1_table *t, const void * error) { return t->chs_error_ch_name(error); }
static void * chtypes_abi1_call_chs_error_message(struct chtypes_abi1_table *t, const void * error) { return t->chs_error_message(error); }
static void * chtypes_abi1_call_chs_error_column(struct chtypes_abi1_table *t, const void * error) { return t->chs_error_column(error); }
static void chtypes_abi1_call_chs_error_free(struct chtypes_abi1_table *t, void * error) { t->chs_error_free(error); }
static int32_t chtypes_abi1_call_chs_live_handles(struct chtypes_abi1_table *t, void ** out, void ** err) { return t->chs_live_handles(out, err); }
static int32_t chtypes_abi1_call_chs_error_codes(struct chtypes_abi1_table *t, void ** out, void ** err) { return t->chs_error_codes(out, err); }
static int32_t chtypes_abi1_call_chs_registered_families(struct chtypes_abi1_table *t, void ** out, void ** err) { return t->chs_registered_families(out, err); }
static int32_t chtypes_abi1_call_chs_function_flags(struct chtypes_abi1_table *t, void ** out, void ** err) { return t->chs_function_flags(out, err); }
static int32_t chtypes_abi1_call_chs_reference_type(struct chtypes_abi1_table *t, const uint8_t * type_expr, size_t type_expr_len, void ** out, void ** err) { return t->chs_reference_type(type_expr, type_expr_len, out, err); }
static int32_t chtypes_abi1_call_chs_initialize(struct chtypes_abi1_table *t, const uint8_t * timezone, size_t timezone_len, void ** err) { return t->chs_initialize(timezone, timezone_len, err); }
static int32_t chtypes_abi1_call_chs_set_defaults(struct chtypes_abi1_table *t, const uint8_t * settings, size_t settings_len, void ** err) { return t->chs_set_defaults(settings, settings_len, err); }
static void chtypes_abi1_call_chs_shutdown(struct chtypes_abi1_table *t) { t->chs_shutdown(); }
static int32_t chtypes_abi1_call_chs_type_validate(struct chtypes_abi1_table *t, const uint8_t * type_expr, size_t type_expr_len, void ** out, void ** err) { return t->chs_type_validate(type_expr, type_expr_len, out, err); }
static int32_t chtypes_abi1_call_chs_back_quote(struct chtypes_abi1_table *t, const uint8_t * name, size_t name_len, void ** out, void ** err) { return t->chs_back_quote(name, name_len, out, err); }
static int32_t chtypes_abi1_call_chs_back_quote_if_needed(struct chtypes_abi1_table *t, const uint8_t * name, size_t name_len, void ** out, void ** err) { return t->chs_back_quote_if_needed(name, name_len, out, err); }
static int32_t chtypes_abi1_call_chs_quote_string(struct chtypes_abi1_table *t, const uint8_t * text, size_t text_len, void ** out, void ** err) { return t->chs_quote_string(text, text_len, out, err); }
static int32_t chtypes_abi1_call_chs_schema_create(struct chtypes_abi1_table *t, const uint8_t * create_table, size_t create_table_len, const uint8_t * settings, size_t settings_len, void ** out, void ** err) { return t->chs_schema_create(create_table, create_table_len, settings, settings_len, out, err); }
static void chtypes_abi1_call_chs_schema_free(struct chtypes_abi1_table *t, void * schema) { t->chs_schema_free(schema); }
static int32_t chtypes_abi1_call_chs_schema_describe(struct chtypes_abi1_table *t, const void * schema, void ** out, void ** err) { return t->chs_schema_describe(schema, out, err); }
static int32_t chtypes_abi1_call_chs_preview_row(struct chtypes_abi1_table *t, const void * schema, int32_t format, const uint8_t * body, size_t body_len, const uint8_t * settings, size_t settings_len, const uint8_t * columns, size_t columns_len, void ** out, void ** err) { return t->chs_preview_row(schema, format, body, body_len, settings, settings_len, columns, columns_len, out, err); }
static int32_t chtypes_abi1_call_chs_preview_batch(struct chtypes_abi1_table *t, const void * schema, int32_t format, const uint8_t * body, size_t body_len, const uint8_t * settings, size_t settings_len, const uint8_t * columns, size_t columns_len, const void * filter, int32_t export_format, uint32_t doc_flags, void ** out, void ** out_export, void ** err) { return t->chs_preview_batch(schema, format, body, body_len, settings, settings_len, columns, columns_len, filter, export_format, doc_flags, out, out_export, err); }
static int32_t chtypes_abi1_call_chs_filter_create(struct chtypes_abi1_table *t, const void * schema, const uint8_t * expr, size_t expr_len, const uint8_t * query_params, size_t query_params_len, const uint8_t * settings, size_t settings_len, void ** out, void ** err) { return t->chs_filter_create(schema, expr, expr_len, query_params, query_params_len, settings, settings_len, out, err); }
static void chtypes_abi1_call_chs_filter_free(struct chtypes_abi1_table *t, void * filter) { t->chs_filter_free(filter); }
static int32_t chtypes_abi1_call_chs_filter_eval_body(struct chtypes_abi1_table *t, const void * filter, int32_t format, const uint8_t * body, size_t body_len, const uint8_t * settings, size_t settings_len, void ** out, void ** err) { return t->chs_filter_eval_body(filter, format, body, body_len, settings, settings_len, out, err); }
static int32_t chtypes_abi1_call_chs_block_create(struct chtypes_abi1_table *t, const void * schema, int32_t format, const uint8_t * body, size_t body_len, const uint8_t * settings, size_t settings_len, const uint8_t * columns, size_t columns_len, void ** out, void ** err) { return t->chs_block_create(schema, format, body, body_len, settings, settings_len, columns, columns_len, out, err); }
static void chtypes_abi1_call_chs_block_free(struct chtypes_abi1_table *t, void * block) { t->chs_block_free(block); }
static int32_t chtypes_abi1_call_chs_filter_eval_block(struct chtypes_abi1_table *t, const void * filter, const void * block, void ** out, void ** err) { return t->chs_filter_eval_block(filter, block, out, err); }
static int32_t chtypes_abi1_call_chs_discover_query(struct chtypes_abi1_table *t, void ** out, void ** err) { return t->chs_discover_query(out, err); }
static int32_t chtypes_abi1_call_chs_discover_columns(struct chtypes_abi1_table *t, const uint8_t * rows, size_t rows_len, void ** out, void ** err) { return t->chs_discover_columns(rows, rows_len, out, err); }
*/
import "C"

import (
	"fmt"
	"runtime"
	"unsafe"
)

// ChsAbiVersion is CHS_ABI_VERSION (D1.2): what chs_abi_version() must return.
const ChsAbiVersion = 1

// ChsAbiFingerprint is CHS_ABI_FINGERPRINT: sha256 over the RFC 8785 canonical
// form of spec/abi-v1/abi.json. chs_build_info()'s abi_fingerprint field is
// this value, copied from the compiled-in macro, never recomputed.
const ChsAbiFingerprint = "sha256:856e5cb7543db291b4db716662bf6e487b2258973b959bbf5d58b4bd46d73285"

// Table is one dlopen'd (or, under -tags chtypes_linked, statically linked)
// ABI v1 image: the resolved function-pointer table plus, in dlopen mode, the
// dlopen handle itself (nil in linked mode, where there is nothing to dlclose --
// D3: no dlclose, ever).
type Table struct {
	h   unsafe.Pointer
	tbl C.struct_chtypes_abi1_table
}

// GlibcVersion reads gnu_get_libc_version() from THIS process (loader step 1).
// The second return is false when the symbol is absent (a non-glibc libc).
func GlibcVersion() (string, bool) {
	var buf [64]C.char
	ok := C.chtypes_abi1_glibc_version(&buf[0], C.size_t(len(buf)))
	if ok == 0 {
		return "", false
	}
	return C.GoString(&buf[0]), true
}

// OpenLibrary dlopen's path (RTLD_NOW|RTLD_LOCAL) with an otherwise empty table.
// The second return is the dlerror() text on failure, else "".
func OpenLibrary(path string) (*Table, string) {
	cpath := C.CString(path)
	defer C.free(unsafe.Pointer(cpath))
	var errmsg *C.char
	h := C.chtypes_abi1_dlopen(cpath, &errmsg)
	if h == nil {
		if errmsg != nil {
			return nil, C.GoString(errmsg)
		}
		return nil, "dlopen: unknown error"
	}
	return &Table{h: h}, ""
}

// ResolveAbiVersion resolves chs_abi_version alone (D1.2). The return is "" once it
// resolved, else "chs_abi_version".
func (t *Table) ResolveAbiVersion() string {
	if m := C.chtypes_abi1_resolve_chs_abi_version(t.h, &t.tbl); m != nil {
		return C.GoString(m)
	}
	return ""
}

// ResolveBuildInfo resolves chs_build_info alone (D1.2). The return is "" once it
// resolved, else "chs_build_info".
func (t *Table) ResolveBuildInfo() string {
	if m := C.chtypes_abi1_resolve_chs_build_info(t.h, &t.tbl); m != nil {
		return C.GoString(m)
	}
	return ""
}

// ResolveClickhouseVersion resolves chs_clickhouse_version alone (D1.2). The return is "" once it
// resolved, else "chs_clickhouse_version".
func (t *Table) ResolveClickhouseVersion() string {
	if m := C.chtypes_abi1_resolve_chs_clickhouse_version(t.h, &t.tbl); m != nil {
		return C.GoString(m)
	}
	return ""
}

// ResolveAll resolves every described symbol (step 6). The return is the first
// missing symbol's name, or "" once every one of them resolved.
func (t *Table) ResolveAll() string {
	if m := C.chtypes_abi1_resolve_all(t.h, &t.tbl); m != nil {
		return C.GoString(m)
	}
	return ""
}

// CallError is D3's per-call error shape, read verbatim off a non-OK status:
// the chs_status NAME (never the bare int), ch_code, ch_name, message and column.
// It carries no class of its own -- StatusClass(e.Status) is sdk.json's table,
// generated into errmap_gen.go, and the public API (wave C) is what turns this
// into an idiomatic *SchemaError/*UsageError/...
type CallError struct {
	Status  string
	ChCode  int32
	ChName  string
	Message string
	Column  string
}

func (e *CallError) Error() string {
	if e.ChName != "" {
		return fmt.Sprintf("%s: %s (%s)", e.Status, e.Message, e.ChName)
	}
	return fmt.Sprintf("%s: %s", e.Status, e.Message)
}

// statusName maps a raw chs_status value to its chs_status.h NAME. Every value
// the description does not list reads as "CHS_STATUS_<n>" -- it cannot happen
// under a matching fingerprint (D3's closed, frozen enum), and the binding still
// fails closed rather than panicking on it.
func statusName(v int32) string {
	switch v {
	case 0:
		return "CHS_OK"
	case 1:
		return "CHS_REJECTED"
	case 2:
		return "CHS_DECLINED"
	case 3:
		return "CHS_INVALID_ARGUMENT"
	case 4:
		return "CHS_INTERNAL"
	default:
		return fmt.Sprintf("CHS_STATUS_%d", v)
	}
}

// bytesPtr returns (NULL, 0) for an empty slice, so a bytes_in parameter's
// "length 0 means none" rule (model.py's Param docs) always holds, and a
// pointer into b's backing array plus its length otherwise. The pointer is
// only read synchronously by the trampoline call that follows it in the same
// statement, which is what cgo's pointer-passing rules require.
func bytesPtr(b []byte) (*C.uint8_t, C.size_t) {
	if len(b) == 0 {
		return nil, 0
	}
	return (*C.uint8_t)(unsafe.Pointer(&b[0])), C.size_t(len(b))
}

// copyBytes copies n bytes out of a BORROWED C pointer (never retained).
func copyBytes(p unsafe.Pointer, n int) []byte {
	out := make([]byte, n)
	if n > 0 {
		copy(out, unsafe.Slice((*byte)(p), n))
	}
	return out
}

// readAndFreeBuf copies b's bytes (nil for a nil b, an absent optional buf)
// then frees it -- D3's copy-then-free rule every status-returning call's
// chs_buf output follows, instead of handing a live chs_buf to a caller.
func readAndFreeBuf(t *Table, b *Buf) []byte {
	if b == nil {
		return nil
	}
	out := copyBytes(t.BufData(b), int(t.BufLen(b)))
	b.Close()
	return out
}

// makeCallError is D3's status/error marshaling, shared by every generated
// call wrapper: nil on CHS_OK, else a *CallError read verbatim off err (if
// any) and copy-then-freed, matching the chs_error accessors' owned-buffer
// form (Q-c's current default).
func makeCallError(t *Table, status int32, err *ErrorHandle) *CallError {
	if status == 0 {
		return nil
	}
	ce := &CallError{Status: statusName(status)}
	if err != nil {
		ce.ChCode = t.ErrorChCode(err)
		ce.ChName = string(readAndFreeBuf(t, t.ErrorChName(err)))
		ce.Message = string(readAndFreeBuf(t, t.ErrorMessage(err)))
		ce.Column = string(readAndFreeBuf(t, t.ErrorColumn(err)))
		err.Close()
	}
	return ce
}

// Buf wraps a live chs_buf. Close() (and the finalizer backing it)
// call BufFree; D2 makes any free order safe.
type Buf struct {
	ptr unsafe.Pointer
	tbl *Table
}

func newBuf(t *Table, ptr unsafe.Pointer) *Buf {
	if ptr == nil {
		return nil
	}
	h := &Buf{ptr: ptr, tbl: t}
	runtime.SetFinalizer(h, (*Buf).Close)
	return h
}

// rawPtr is nil-receiver-safe: a nil *Buf (an absent optional handle)
// marshals to a C NULL, never a panic.
func (h *Buf) rawPtr() unsafe.Pointer {
	if h == nil {
		return nil
	}
	return h.ptr
}

// Close frees this chs_buf (a no-op if already closed or nil); any free order
// is safe (D2). It never returns a non-nil error; the signature matches io.Closer
// for callers that want to defer it.
func (h *Buf) Close() error {
	if h == nil || h.ptr == nil {
		return nil
	}
	runtime.SetFinalizer(h, nil)
	C.chtypes_abi1_call_chs_buf_free(&h.tbl.tbl, h.ptr)
	h.ptr = nil
	return nil
}

// ErrorHandle wraps a live chs_error. Close() (and the finalizer backing it)
// call ErrorFree; D2 makes any free order safe.
type ErrorHandle struct {
	ptr unsafe.Pointer
	tbl *Table
}

func newErrorHandle(t *Table, ptr unsafe.Pointer) *ErrorHandle {
	if ptr == nil {
		return nil
	}
	h := &ErrorHandle{ptr: ptr, tbl: t}
	runtime.SetFinalizer(h, (*ErrorHandle).Close)
	return h
}

// rawPtr is nil-receiver-safe: a nil *ErrorHandle (an absent optional handle)
// marshals to a C NULL, never a panic.
func (h *ErrorHandle) rawPtr() unsafe.Pointer {
	if h == nil {
		return nil
	}
	return h.ptr
}

// Close frees this chs_error (a no-op if already closed or nil); any free order
// is safe (D2). It never returns a non-nil error; the signature matches io.Closer
// for callers that want to defer it.
func (h *ErrorHandle) Close() error {
	if h == nil || h.ptr == nil {
		return nil
	}
	runtime.SetFinalizer(h, nil)
	C.chtypes_abi1_call_chs_error_free(&h.tbl.tbl, h.ptr)
	h.ptr = nil
	return nil
}

// Schema is a live chs_schema: a copy-then-free chs_buf and a copy-then-free
// chs_error never reach a caller as one of these (the generated wrapper layer
// reads their content and frees them immediately), so in practice only a type
// this ABI generation marks provisional lives this long -- Close() (and the
// finalizer backing it) call the SAME free function every free order is safe
// under (D2: a child holds its parents alive, so freeing a live parent first
// is not a use-after-free).
type Schema struct {
	ptr unsafe.Pointer
	tbl *Table
}

func newSchema(t *Table, ptr unsafe.Pointer) *Schema {
	if ptr == nil {
		return nil
	}
	h := &Schema{ptr: ptr, tbl: t}
	runtime.SetFinalizer(h, (*Schema).Close)
	return h
}

// rawPtr is nil-receiver-safe: a nil *Schema (an absent optional handle)
// marshals to a C NULL, never a panic.
func (h *Schema) rawPtr() unsafe.Pointer {
	if h == nil {
		return nil
	}
	return h.ptr
}

// Close frees this chs_schema (a no-op if already closed or nil); any free order
// is safe (D2). It never returns a non-nil error; the signature matches io.Closer
// for callers that want to defer it.
func (h *Schema) Close() error {
	if h == nil || h.ptr == nil {
		return nil
	}
	runtime.SetFinalizer(h, nil)
	C.chtypes_abi1_call_chs_schema_free(&h.tbl.tbl, h.ptr)
	h.ptr = nil
	return nil
}

// Filter is a live chs_filter: a copy-then-free chs_buf and a copy-then-free
// chs_error never reach a caller as one of these (the generated wrapper layer
// reads their content and frees them immediately), so in practice only a type
// this ABI generation marks provisional lives this long -- Close() (and the
// finalizer backing it) call the SAME free function every free order is safe
// under (D2: a child holds its parents alive, so freeing a live parent first
// is not a use-after-free).
type Filter struct {
	ptr unsafe.Pointer
	tbl *Table
}

func newFilter(t *Table, ptr unsafe.Pointer) *Filter {
	if ptr == nil {
		return nil
	}
	h := &Filter{ptr: ptr, tbl: t}
	runtime.SetFinalizer(h, (*Filter).Close)
	return h
}

// rawPtr is nil-receiver-safe: a nil *Filter (an absent optional handle)
// marshals to a C NULL, never a panic.
func (h *Filter) rawPtr() unsafe.Pointer {
	if h == nil {
		return nil
	}
	return h.ptr
}

// Close frees this chs_filter (a no-op if already closed or nil); any free order
// is safe (D2). It never returns a non-nil error; the signature matches io.Closer
// for callers that want to defer it.
func (h *Filter) Close() error {
	if h == nil || h.ptr == nil {
		return nil
	}
	runtime.SetFinalizer(h, nil)
	C.chtypes_abi1_call_chs_filter_free(&h.tbl.tbl, h.ptr)
	h.ptr = nil
	return nil
}

// Block is a live chs_block: a copy-then-free chs_buf and a copy-then-free
// chs_error never reach a caller as one of these (the generated wrapper layer
// reads their content and frees them immediately), so in practice only a type
// this ABI generation marks provisional lives this long -- Close() (and the
// finalizer backing it) call the SAME free function every free order is safe
// under (D2: a child holds its parents alive, so freeing a live parent first
// is not a use-after-free).
type Block struct {
	ptr unsafe.Pointer
	tbl *Table
}

func newBlock(t *Table, ptr unsafe.Pointer) *Block {
	if ptr == nil {
		return nil
	}
	h := &Block{ptr: ptr, tbl: t}
	runtime.SetFinalizer(h, (*Block).Close)
	return h
}

// rawPtr is nil-receiver-safe: a nil *Block (an absent optional handle)
// marshals to a C NULL, never a panic.
func (h *Block) rawPtr() unsafe.Pointer {
	if h == nil {
		return nil
	}
	return h.ptr
}

// Close frees this chs_block (a no-op if already closed or nil); any free order
// is safe (D2). It never returns a non-nil error; the signature matches io.Closer
// for callers that want to defer it.
func (h *Block) Close() error {
	if h == nil || h.ptr == nil {
		return nil
	}
	runtime.SetFinalizer(h, nil)
	C.chtypes_abi1_call_chs_block_free(&h.tbl.tbl, h.ptr)
	h.ptr = nil
	return nil
}

// AbiVersion is the generated call wrapper for chs_abi_version.
func (t *Table) AbiVersion() int32 {
	return int32(C.chtypes_abi1_call_chs_abi_version(&t.tbl))
}

// BuildInfo is the generated call wrapper for chs_build_info.
func (t *Table) BuildInfo() string {
	return C.GoString(C.chtypes_abi1_call_chs_build_info(&t.tbl))
}

// ClickhouseVersion is the generated call wrapper for chs_clickhouse_version.
func (t *Table) ClickhouseVersion() string {
	return C.GoString(C.chtypes_abi1_call_chs_clickhouse_version(&t.tbl))
}

// AbiRevision is the generated call wrapper for chs_abi_revision.
func (t *Table) AbiRevision() int32 {
	return int32(C.chtypes_abi1_call_chs_abi_revision(&t.tbl))
}

// BufData is the generated call wrapper for chs_buf_data.
func (t *Table) BufData(buf *Buf) unsafe.Pointer {
	return unsafe.Pointer(C.chtypes_abi1_call_chs_buf_data(&t.tbl, buf.rawPtr()))
}

// BufLen is the generated call wrapper for chs_buf_len.
func (t *Table) BufLen(buf *Buf) uint64 {
	return uint64(C.chtypes_abi1_call_chs_buf_len(&t.tbl, buf.rawPtr()))
}

// BufFree is the generated call wrapper for chs_buf_free.
func (t *Table) BufFree(buf *Buf) {
	C.chtypes_abi1_call_chs_buf_free(&t.tbl, buf.rawPtr())
}

// ErrorStatus is the generated call wrapper for chs_error_status.
func (t *Table) ErrorStatus(errorArg *ErrorHandle) int32 {
	return int32(C.chtypes_abi1_call_chs_error_status(&t.tbl, errorArg.rawPtr()))
}

// ErrorChCode is the generated call wrapper for chs_error_ch_code.
func (t *Table) ErrorChCode(errorArg *ErrorHandle) int32 {
	return int32(C.chtypes_abi1_call_chs_error_ch_code(&t.tbl, errorArg.rawPtr()))
}

// ErrorChName is the generated call wrapper for chs_error_ch_name.
func (t *Table) ErrorChName(errorArg *ErrorHandle) *Buf {
	return newBuf(t, C.chtypes_abi1_call_chs_error_ch_name(&t.tbl, errorArg.rawPtr()))
}

// ErrorMessage is the generated call wrapper for chs_error_message.
func (t *Table) ErrorMessage(errorArg *ErrorHandle) *Buf {
	return newBuf(t, C.chtypes_abi1_call_chs_error_message(&t.tbl, errorArg.rawPtr()))
}

// ErrorColumn is the generated call wrapper for chs_error_column.
func (t *Table) ErrorColumn(errorArg *ErrorHandle) *Buf {
	return newBuf(t, C.chtypes_abi1_call_chs_error_column(&t.tbl, errorArg.rawPtr()))
}

// ErrorFree is the generated call wrapper for chs_error_free.
func (t *Table) ErrorFree(errorArg *ErrorHandle) {
	C.chtypes_abi1_call_chs_error_free(&t.tbl, errorArg.rawPtr())
}

// LiveHandles is the generated call wrapper for chs_live_handles.
func (t *Table) LiveHandles() (*Buf, *CallError) {
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_live_handles(&t.tbl, &outOut, &errOut)
	return newBuf(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// ErrorCodes is the generated call wrapper for chs_error_codes.
func (t *Table) ErrorCodes() (*Buf, *CallError) {
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_error_codes(&t.tbl, &outOut, &errOut)
	return newBuf(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// RegisteredFamilies is the generated call wrapper for chs_registered_families.
func (t *Table) RegisteredFamilies() (*Buf, *CallError) {
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_registered_families(&t.tbl, &outOut, &errOut)
	return newBuf(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// FunctionFlags is the generated call wrapper for chs_function_flags.
func (t *Table) FunctionFlags() (*Buf, *CallError) {
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_function_flags(&t.tbl, &outOut, &errOut)
	return newBuf(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// ReferenceType is the generated call wrapper for chs_reference_type.
func (t *Table) ReferenceType(typeExpr []byte) (*Buf, *CallError) {
	typeExprPtr, typeExprLen := bytesPtr(typeExpr)
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_reference_type(&t.tbl, typeExprPtr, typeExprLen, &outOut, &errOut)
	return newBuf(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// Initialize is the generated call wrapper for chs_initialize.
func (t *Table) Initialize(timezone []byte) *CallError {
	timezonePtr, timezoneLen := bytesPtr(timezone)
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_initialize(&t.tbl, timezonePtr, timezoneLen, &errOut)
	return makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// SetDefaults is the generated call wrapper for chs_set_defaults.
func (t *Table) SetDefaults(settings []byte) *CallError {
	settingsPtr, settingsLen := bytesPtr(settings)
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_set_defaults(&t.tbl, settingsPtr, settingsLen, &errOut)
	return makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// Shutdown is the generated call wrapper for chs_shutdown.
func (t *Table) Shutdown() {
	C.chtypes_abi1_call_chs_shutdown(&t.tbl)
}

// TypeValidate is the generated call wrapper for chs_type_validate.
func (t *Table) TypeValidate(typeExpr []byte) (*Buf, *CallError) {
	typeExprPtr, typeExprLen := bytesPtr(typeExpr)
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_type_validate(&t.tbl, typeExprPtr, typeExprLen, &outOut, &errOut)
	return newBuf(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// BackQuote is the generated call wrapper for chs_back_quote.
func (t *Table) BackQuote(name []byte) (*Buf, *CallError) {
	namePtr, nameLen := bytesPtr(name)
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_back_quote(&t.tbl, namePtr, nameLen, &outOut, &errOut)
	return newBuf(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// BackQuoteIfNeeded is the generated call wrapper for chs_back_quote_if_needed.
func (t *Table) BackQuoteIfNeeded(name []byte) (*Buf, *CallError) {
	namePtr, nameLen := bytesPtr(name)
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_back_quote_if_needed(&t.tbl, namePtr, nameLen, &outOut, &errOut)
	return newBuf(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// QuoteString is the generated call wrapper for chs_quote_string.
func (t *Table) QuoteString(text []byte) (*Buf, *CallError) {
	textPtr, textLen := bytesPtr(text)
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_quote_string(&t.tbl, textPtr, textLen, &outOut, &errOut)
	return newBuf(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// SchemaCreate is the generated call wrapper for chs_schema_create.
func (t *Table) SchemaCreate(createTable []byte, settings []byte) (*Schema, *CallError) {
	createTablePtr, createTableLen := bytesPtr(createTable)
	settingsPtr, settingsLen := bytesPtr(settings)
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_schema_create(&t.tbl, createTablePtr, createTableLen, settingsPtr, settingsLen, &outOut, &errOut)
	return newSchema(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// SchemaFree is the generated call wrapper for chs_schema_free.
func (t *Table) SchemaFree(schema *Schema) {
	C.chtypes_abi1_call_chs_schema_free(&t.tbl, schema.rawPtr())
}

// SchemaDescribe is the generated call wrapper for chs_schema_describe.
func (t *Table) SchemaDescribe(schema *Schema) (*Buf, *CallError) {
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_schema_describe(&t.tbl, schema.rawPtr(), &outOut, &errOut)
	return newBuf(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// PreviewRow is the generated call wrapper for chs_preview_row.
func (t *Table) PreviewRow(schema *Schema, format int32, body []byte, settings []byte, columns []byte) (*Buf, *CallError) {
	bodyPtr, bodyLen := bytesPtr(body)
	settingsPtr, settingsLen := bytesPtr(settings)
	columnsPtr, columnsLen := bytesPtr(columns)
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_preview_row(&t.tbl, schema.rawPtr(), C.int32_t(format), bodyPtr, bodyLen, settingsPtr, settingsLen, columnsPtr, columnsLen, &outOut, &errOut)
	return newBuf(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// PreviewBatch is the generated call wrapper for chs_preview_batch.
func (t *Table) PreviewBatch(schema *Schema, format int32, body []byte, settings []byte, columns []byte, filter *Filter, exportFormat int32, docFlags uint32) (*Buf, *Buf, *CallError) {
	bodyPtr, bodyLen := bytesPtr(body)
	settingsPtr, settingsLen := bytesPtr(settings)
	columnsPtr, columnsLen := bytesPtr(columns)
	var outOut unsafe.Pointer
	var outExportOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_preview_batch(&t.tbl, schema.rawPtr(), C.int32_t(format), bodyPtr, bodyLen, settingsPtr, settingsLen, columnsPtr, columnsLen, filter.rawPtr(), C.int32_t(exportFormat), C.uint32_t(docFlags), &outOut, &outExportOut, &errOut)
	return newBuf(t, outOut), newBuf(t, outExportOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// FilterCreate is the generated call wrapper for chs_filter_create.
func (t *Table) FilterCreate(schema *Schema, expr []byte, queryParams []byte, settings []byte) (*Filter, *CallError) {
	exprPtr, exprLen := bytesPtr(expr)
	queryParamsPtr, queryParamsLen := bytesPtr(queryParams)
	settingsPtr, settingsLen := bytesPtr(settings)
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_filter_create(&t.tbl, schema.rawPtr(), exprPtr, exprLen, queryParamsPtr, queryParamsLen, settingsPtr, settingsLen, &outOut, &errOut)
	return newFilter(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// FilterFree is the generated call wrapper for chs_filter_free.
func (t *Table) FilterFree(filter *Filter) {
	C.chtypes_abi1_call_chs_filter_free(&t.tbl, filter.rawPtr())
}

// FilterEvalBody is the generated call wrapper for chs_filter_eval_body.
func (t *Table) FilterEvalBody(filter *Filter, format int32, body []byte, settings []byte) (*Buf, *CallError) {
	bodyPtr, bodyLen := bytesPtr(body)
	settingsPtr, settingsLen := bytesPtr(settings)
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_filter_eval_body(&t.tbl, filter.rawPtr(), C.int32_t(format), bodyPtr, bodyLen, settingsPtr, settingsLen, &outOut, &errOut)
	return newBuf(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// BlockCreate is the generated call wrapper for chs_block_create.
func (t *Table) BlockCreate(schema *Schema, format int32, body []byte, settings []byte, columns []byte) (*Block, *CallError) {
	bodyPtr, bodyLen := bytesPtr(body)
	settingsPtr, settingsLen := bytesPtr(settings)
	columnsPtr, columnsLen := bytesPtr(columns)
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_block_create(&t.tbl, schema.rawPtr(), C.int32_t(format), bodyPtr, bodyLen, settingsPtr, settingsLen, columnsPtr, columnsLen, &outOut, &errOut)
	return newBlock(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// BlockFree is the generated call wrapper for chs_block_free.
func (t *Table) BlockFree(block *Block) {
	C.chtypes_abi1_call_chs_block_free(&t.tbl, block.rawPtr())
}

// FilterEvalBlock is the generated call wrapper for chs_filter_eval_block.
func (t *Table) FilterEvalBlock(filter *Filter, block *Block) (*Buf, *CallError) {
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_filter_eval_block(&t.tbl, filter.rawPtr(), block.rawPtr(), &outOut, &errOut)
	return newBuf(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// DiscoverQuery is the generated call wrapper for chs_discover_query.
func (t *Table) DiscoverQuery() (*Buf, *CallError) {
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_discover_query(&t.tbl, &outOut, &errOut)
	return newBuf(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}

// DiscoverColumns is the generated call wrapper for chs_discover_columns.
func (t *Table) DiscoverColumns(rows []byte) (*Buf, *CallError) {
	rowsPtr, rowsLen := bytesPtr(rows)
	var outOut unsafe.Pointer
	var errOut unsafe.Pointer
	status := C.chtypes_abi1_call_chs_discover_columns(&t.tbl, rowsPtr, rowsLen, &outOut, &errOut)
	return newBuf(t, outOut), makeCallError(t, int32(status), newErrorHandle(t, errOut))
}
