// GENERATED by scripts/abi-v1/gen.py from spec/abi-v1/abi.json (CHS_ABI_FINGERPRINT sha256:b691663f42fb9ca2a872909e73a06fb61836abf92ce552a95b21baf4e006c4ed) — DO NOT EDIT

package abi1

// StatusClass maps a chs_status NAME to spec/abi-v1/sdk.json's errors.classes
// key ("" for CHS_OK, which never becomes an error). An unrecognized name --
// never possible under a matching fingerprint -- reads as sdk.json's own
// "unknown" fallback, so a caller still fails closed instead of panicking.
func StatusClass(status string) string {
	switch status {
	case "CHS_OK":
		return ""
	case "CHS_REJECTED":
		return "schema"
	case "CHS_DECLINED":
		return "unsupported"
	case "CHS_INVALID_ARGUMENT":
		return "usage"
	case "CHS_INTERNAL":
		return "internal"
	default:
		return "internal"
	}
}
