// GENERATED by scripts/abi-v1/gen.py --major 2 from spec/abi-v2/abi.json (CHS_ABI_FINGERPRINT sha256:8ec0c6941f000aa07bfb9fbfef20205d3ee0a588833856bd12270ba42912bfb3) — DO NOT EDIT
//
// The test-only invoke-by-name dispatcher: `invoke(api, name, args)` marshals
// an already-resolved argument list (`ResolvedArg`, rust/src/abi2/conformance.rs)
// into a real call through `Api`'s symbol table and reports back a generic
// `Outcome`. One match arm per handshake/tombstone call and per function
// scripts/abi-v1/emit/stub.py's `classify()` calls "generic" (the
// echo/status-injection shape every case in tests/fixtures/abi-v2/cases.json
// drives); a "free"-classified function is never dispatched by name here
// because no case ever calls one directly (see this module's own docstring,
// scripts/abi-v1/emit/rust.py).
#![allow(dead_code)]

use std::collections::BTreeMap;
use std::ffi::{CStr, c_void};

use super::decls::{self, Api, ChsBlock, ChsBuf, ChsError, ChsFilter, ChsSchema};

/// One already-resolved argument `invoke` consumes positionally. Built from
/// a case's JSON expression tree by rust/src/abi2/conformance.rs, which also
/// recursively mints any nested `{"handle": {...}}` argument first.
#[derive(Clone)]
pub(crate) enum ResolvedArg {
    Int(i64),
    Bytes(Vec<u8>),
    Handle {
        kind: &'static str,
        ptr: *mut c_void,
    },
    Null,
}

/// A handle this call minted through one of its `out_handle` parameters,
/// kept generic over the handle kind so the conformance runner can free it,
/// read it (a `chs_buf`'s bytes), or feed it into a later call as a
/// `ResolvedArg::Handle` without knowing which kind it minted ahead of time.
#[derive(Clone, Copy)]
pub(crate) enum MintedHandle {
    Buf(*mut decls::ChsBuf),
    Schema(*mut decls::ChsSchema),
    Filter(*mut decls::ChsFilter),
    Block(*mut decls::ChsBlock),
}

impl MintedHandle {
    /// The `abi.json` handle name this value was minted as (`"chs_schema"`
    /// and so on) — what `ResolvedArg::Handle`'s own kind check compares
    /// against when this handle is fed into a later call.
    pub(crate) fn kind_name(&self) -> &'static str {
        match self {
            MintedHandle::Buf(_) => "chs_buf",
            MintedHandle::Schema(_) => "chs_schema",
            MintedHandle::Filter(_) => "chs_filter",
            MintedHandle::Block(_) => "chs_block",
        }
    }

    /// Fed back into a later call as a `handle` argument: the raw pointer,
    /// type-erased, tagged with this value's own kind name.
    pub(crate) fn as_resolved_arg(&self) -> ResolvedArg {
        ResolvedArg::Handle {
            kind: self.kind_name(),
            ptr: self.raw_ptr(),
        }
    }

    /// The minted pointer, type-erased — never dereferenced here.
    pub(crate) fn raw_ptr(&self) -> *mut c_void {
        match *self {
            MintedHandle::Buf(p) => p as *mut c_void,
            MintedHandle::Schema(p) => p as *mut c_void,
            MintedHandle::Filter(p) => p as *mut c_void,
            MintedHandle::Block(p) => p as *mut c_void,
        }
    }
}

/// One case error's four fields (D3), read from the error accessors once a
/// call's status is not `CHS_OK`.
pub(crate) struct CaseError {
    pub(crate) ch_code: i32,
    pub(crate) ch_name: String,
    pub(crate) message: String,
    pub(crate) column: String,
}

/// What invoking one function produced, generic across every call shape
/// `invoke` dispatches.
pub(crate) enum Outcome {
    /// A handshake call's int32 (`chs_abi_version`) or the tombstone
    /// (`chs_abi_revision`).
    Int(i64),
    /// A handshake call's borrowed, NUL-terminated string
    /// (`chs_build_info`, `chs_clickhouse_version`).
    Str(String),
    /// A status-returning call: the `chs_status` name, the error (once set,
    /// read and freed) when the status was not `CHS_OK`, and one entry per
    /// `out_handle` parameter this function declares.
    Call {
        status: &'static str,
        error: Option<CaseError>,
        outputs: BTreeMap<String, MintedHandle>,
    },
}

/// A cursor over one call's already-resolved, non-out arguments, consumed
/// positionally exactly as `abi.json` declares them (model.py's own
/// invariant: every input precedes every output).
struct ArgCursor<'a> {
    args: &'a [ResolvedArg],
    pos: usize,
}

impl<'a> ArgCursor<'a> {
    fn new(args: &'a [ResolvedArg]) -> Self {
        ArgCursor { args, pos: 0 }
    }

    fn next(&mut self) -> Result<&'a ResolvedArg, String> {
        let a = self
            .args
            .get(self.pos)
            .ok_or_else(|| format!("expected an argument at position {}, found none", self.pos))?;
        self.pos += 1;
        Ok(a)
    }

    /// A scalar or enum argument, as the integer a case expresses it with.
    fn int(&mut self) -> Result<i64, String> {
        match self.next()? {
            ResolvedArg::Int(v) => Ok(*v),
            other => Err(format!(
                "expected an int argument, found {}",
                describe(other)
            )),
        }
    }

    /// A `bytes_in` argument's bytes.
    fn bytes(&mut self) -> Result<&'a [u8], String> {
        match self.next()? {
            ResolvedArg::Bytes(b) => Ok(b.as_slice()),
            other => Err(format!(
                "expected a bytes argument, found {}",
                describe(other)
            )),
        }
    }

    /// A required `handle` argument of the named kind.
    fn handle(&mut self, kind: &str) -> Result<*mut c_void, String> {
        match self.next()? {
            ResolvedArg::Handle { kind: got, ptr } if *got == kind => Ok(*ptr),
            ResolvedArg::Handle { kind: got, .. } => {
                Err(format!("expected a {kind} handle, found a {got} handle"))
            }
            other => Err(format!(
                "expected a {kind} handle, found {}",
                describe(other)
            )),
        }
    }

    /// A nullable `handle` argument: `None` for `null_handle`, else as
    /// `handle` above.
    fn handle_opt(&mut self, kind: &str) -> Result<Option<*mut c_void>, String> {
        match self.next()? {
            ResolvedArg::Null => Ok(None),
            ResolvedArg::Handle { kind: got, ptr } if *got == kind => Ok(Some(*ptr)),
            ResolvedArg::Handle { kind: got, .. } => Err(format!(
                "expected a {kind} handle or null, found a {got} handle"
            )),
            other => Err(format!(
                "expected a {kind} handle or null, found {}",
                describe(other)
            )),
        }
    }
}

fn describe(a: &ResolvedArg) -> &'static str {
    match a {
        ResolvedArg::Int(_) => "an int",
        ResolvedArg::Bytes(_) => "bytes",
        ResolvedArg::Handle { .. } => "a handle",
        ResolvedArg::Null => "null",
    }
}

/// A borrowed, NUL-terminated C string, copied. `p` NULL reads as empty —
/// every handshake call this generation describes is documented never to
/// return NULL.
///
/// # Safety
/// `p` must be null or a valid NUL-terminated `const char *` whose referent
/// outlives this call (every handshake string here is a compiled-in
/// constant, never freed).
unsafe fn cstr_to_string(p: *const std::os::raw::c_char) -> String {
    if p.is_null() {
        return String::new();
    }
    // SAFETY: the caller's `# Safety` clause.
    unsafe { CStr::from_ptr(p).to_string_lossy().into_owned() }
}

/// Read and free one owned `chs_buf *` text accessor's result (`chs_error_ch_name`,
/// `chs_error_message`, `chs_error_column`: each returns a fresh `chs_buf`, D4,
/// NULL only on allocation failure). Empty string on NULL, never a panic.
///
/// # Safety
/// `buf` must be null or a `chs_buf *` this same `api` minted.
unsafe fn take_buf_text(api: &Api, buf: *mut decls::ChsBuf) -> String {
    if buf.is_null() {
        return String::new();
    }
    // SAFETY: the caller's `# Safety` clause; `chs_buf_data`/`chs_buf_len` read a
    // live buffer this call just received ownership of, and `chs_buf_free` is
    // this same library's own, called exactly once, after the copy.
    unsafe {
        let p = (api.chs_buf_data)(buf as *const decls::ChsBuf);
        let n = (api.chs_buf_len)(buf as *const decls::ChsBuf);
        let text = if p.is_null() || n == 0 {
            String::new()
        } else {
            String::from_utf8_lossy(std::slice::from_raw_parts(p, n)).into_owned()
        };
        (api.chs_buf_free)(buf);
        text
    }
}

/// Build a status call's `Outcome`: the status name, and — once `err` is
/// read and freed — its four fields when the status was not `CHS_OK`.
///
/// # Safety
/// `err` must be null or a `chs_error *` this same `api` minted.
unsafe fn finish_status(
    api: &Api,
    status: i32,
    err: *mut decls::ChsError,
    outputs: BTreeMap<String, MintedHandle>,
) -> Result<Outcome, String> {
    let name = decls::status_name(status)
        .ok_or_else(|| format!("a status of {status}, which this generation does not define"))?;
    let error = if err.is_null() {
        None
    } else {
        // SAFETY: the caller's `# Safety` clause; every accessor reads a live
        // `chs_error *` this call just received ownership of, and `chs_error_free`
        // is this same library's own, called exactly once, after every read.
        unsafe {
            let ch_code = (api.chs_error_ch_code)(err as *const decls::ChsError);
            let ch_name_buf = (api.chs_error_ch_name)(err as *const decls::ChsError);
            let ch_name = take_buf_text(api, ch_name_buf);
            let message_buf = (api.chs_error_message)(err as *const decls::ChsError);
            let message = take_buf_text(api, message_buf);
            let column_buf = (api.chs_error_column)(err as *const decls::ChsError);
            let column = take_buf_text(api, column_buf);
            (api.chs_error_free)(err);
            Some(CaseError {
                ch_code,
                ch_name,
                message,
                column,
            })
        }
    };
    Ok(Outcome::Call {
        status: name,
        error,
        outputs,
    })
}

/// Dispatch one call by name with already-resolved raw arguments: a pure
/// marshal/unmarshal step that never recurses and never frees an `outputs`
/// entry (the caller, rust/src/abi2/conformance.rs, owns that).
///
/// # Safety
/// Every `ResolvedArg::Handle` must carry a live pointer of the kind it
/// claims, minted by this same `api` (or, for a `chs_buf`, read and never
/// otherwise used); `api` must have completed loader step 6.
pub(crate) unsafe fn invoke(
    api: &Api,
    name: &str,
    args: &[ResolvedArg],
) -> Result<Outcome, String> {
    match name {
        "chs_abi_version" => {
            // SAFETY: a handshake call takes no arguments and borrows nothing.
            Ok(Outcome::Int(unsafe { (api.chs_abi_version)() } as i64))
        }
        "chs_abi_revision" => {
            // SAFETY: the tombstone takes no arguments and borrows nothing.
            Ok(Outcome::Int(unsafe { (api.chs_abi_revision)() } as i64))
        }
        "chs_build_info" => {
            // SAFETY: chs_build_info returns a static, NUL-terminated string (D1.2/D4),
            // never freed, valid for the process's life.
            let p = unsafe { (api.chs_build_info)() };
            // SAFETY: see the comment above; cstr_to_string's own contract is the same one.
            Ok(Outcome::Str(unsafe { cstr_to_string(p) }))
        }
        "chs_clickhouse_version" => {
            // SAFETY: same as chs_build_info: a static, NUL-terminated string.
            let p = unsafe { (api.chs_clickhouse_version)() };
            // SAFETY: see the comment above; cstr_to_string's own contract is the same one.
            Ok(Outcome::Str(unsafe { cstr_to_string(p) }))
        }
        "chs_error_codes" => {
            let mut out_out: *mut ChsBuf = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_error_codes's declared shape; every output pointer is this call's own local.
            let status = unsafe { (api.chs_error_codes)(&mut out_out, &mut err) };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Buf(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_registered_families" => {
            let mut out_out: *mut ChsBuf = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_registered_families's declared shape; every output pointer is this call's own local.
            let status = unsafe { (api.chs_registered_families)(&mut out_out, &mut err) };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Buf(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_function_flags" => {
            let mut out_out: *mut ChsBuf = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_function_flags's declared shape; every output pointer is this call's own local.
            let status = unsafe { (api.chs_function_flags)(&mut out_out, &mut err) };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Buf(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_reference_type" => {
            let mut cur = ArgCursor::new(args);
            let a_type_expr = cur.bytes()?;
            let mut out_out: *mut ChsBuf = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_reference_type's declared shape; every output pointer is this call's own local.
            let status = unsafe {
                (api.chs_reference_type)(
                    a_type_expr.as_ptr(),
                    a_type_expr.len(),
                    &mut out_out,
                    &mut err,
                )
            };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Buf(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_initialize" => {
            let mut cur = ArgCursor::new(args);
            let a_timezone = cur.bytes()?;
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_initialize's declared shape; every output pointer is this call's own local.
            let status =
                unsafe { (api.chs_initialize)(a_timezone.as_ptr(), a_timezone.len(), &mut err) };
            let outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_set_defaults" => {
            let mut cur = ArgCursor::new(args);
            let a_settings = cur.bytes()?;
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_set_defaults's declared shape; every output pointer is this call's own local.
            let status =
                unsafe { (api.chs_set_defaults)(a_settings.as_ptr(), a_settings.len(), &mut err) };
            let outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_type_validate" => {
            let mut cur = ArgCursor::new(args);
            let a_type_expr = cur.bytes()?;
            let mut out_out: *mut ChsBuf = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_type_validate's declared shape; every output pointer is this call's own local.
            let status = unsafe {
                (api.chs_type_validate)(
                    a_type_expr.as_ptr(),
                    a_type_expr.len(),
                    &mut out_out,
                    &mut err,
                )
            };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Buf(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_back_quote" => {
            let mut cur = ArgCursor::new(args);
            let a_name = cur.bytes()?;
            let mut out_out: *mut ChsBuf = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_back_quote's declared shape; every output pointer is this call's own local.
            let status = unsafe {
                (api.chs_back_quote)(a_name.as_ptr(), a_name.len(), &mut out_out, &mut err)
            };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Buf(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_back_quote_if_needed" => {
            let mut cur = ArgCursor::new(args);
            let a_name = cur.bytes()?;
            let mut out_out: *mut ChsBuf = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_back_quote_if_needed's declared shape; every output pointer is this call's own local.
            let status = unsafe {
                (api.chs_back_quote_if_needed)(
                    a_name.as_ptr(),
                    a_name.len(),
                    &mut out_out,
                    &mut err,
                )
            };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Buf(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_quote_string" => {
            let mut cur = ArgCursor::new(args);
            let a_text = cur.bytes()?;
            let mut out_out: *mut ChsBuf = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_quote_string's declared shape; every output pointer is this call's own local.
            let status = unsafe {
                (api.chs_quote_string)(a_text.as_ptr(), a_text.len(), &mut out_out, &mut err)
            };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Buf(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_schema_create" => {
            let mut cur = ArgCursor::new(args);
            let a_create_table = cur.bytes()?;
            let a_settings = cur.bytes()?;
            let mut out_out: *mut ChsSchema = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_schema_create's declared shape; every output pointer is this call's own local.
            let status = unsafe {
                (api.chs_schema_create)(
                    a_create_table.as_ptr(),
                    a_create_table.len(),
                    a_settings.as_ptr(),
                    a_settings.len(),
                    &mut out_out,
                    &mut err,
                )
            };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Schema(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_schema_describe" => {
            let mut cur = ArgCursor::new(args);
            let a_schema = cur.handle("chs_schema")? as *const ChsSchema;
            let mut out_out: *mut ChsBuf = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_schema_describe's declared shape; every output pointer is this call's own local.
            let status = unsafe { (api.chs_schema_describe)(a_schema, &mut out_out, &mut err) };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Buf(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_preview_row" => {
            let mut cur = ArgCursor::new(args);
            let a_schema = cur.handle("chs_schema")? as *const ChsSchema;
            let a_format = cur.int()? as i32;
            let a_body = cur.bytes()?;
            let a_settings = cur.bytes()?;
            let a_columns = cur.bytes()?;
            let mut out_out: *mut ChsBuf = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_preview_row's declared shape; every output pointer is this call's own local.
            let status = unsafe {
                (api.chs_preview_row)(
                    a_schema,
                    a_format,
                    a_body.as_ptr(),
                    a_body.len(),
                    a_settings.as_ptr(),
                    a_settings.len(),
                    a_columns.as_ptr(),
                    a_columns.len(),
                    &mut out_out,
                    &mut err,
                )
            };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Buf(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_preview_batch" => {
            let mut cur = ArgCursor::new(args);
            let a_schema = cur.handle("chs_schema")? as *const ChsSchema;
            let a_format = cur.int()? as i32;
            let a_body = cur.bytes()?;
            let a_settings = cur.bytes()?;
            let a_columns = cur.bytes()?;
            let a_filter = cur.handle_opt("chs_filter")?;
            let a_filter =
                a_filter.map_or(std::ptr::null_mut(), |p| p as *mut ChsFilter) as *const ChsFilter;
            let a_export_format = cur.int()? as i32;
            let a_doc_flags = cur.int()? as u32;
            let mut out_out: *mut ChsBuf = std::ptr::null_mut();
            let mut out_out_export: *mut ChsBuf = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_preview_batch's declared shape; every output pointer is this call's own local.
            let status = unsafe {
                (api.chs_preview_batch)(
                    a_schema,
                    a_format,
                    a_body.as_ptr(),
                    a_body.len(),
                    a_settings.as_ptr(),
                    a_settings.len(),
                    a_columns.as_ptr(),
                    a_columns.len(),
                    a_filter,
                    a_export_format,
                    a_doc_flags,
                    &mut out_out,
                    &mut out_out_export,
                    &mut err,
                )
            };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Buf(out_out));
            outputs.insert("out_export".to_string(), MintedHandle::Buf(out_out_export));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_filter_create" => {
            let mut cur = ArgCursor::new(args);
            let a_schema = cur.handle("chs_schema")? as *const ChsSchema;
            let a_expr = cur.bytes()?;
            let a_query_params = cur.bytes()?;
            let a_settings = cur.bytes()?;
            let mut out_out: *mut ChsFilter = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_filter_create's declared shape; every output pointer is this call's own local.
            let status = unsafe {
                (api.chs_filter_create)(
                    a_schema,
                    a_expr.as_ptr(),
                    a_expr.len(),
                    a_query_params.as_ptr(),
                    a_query_params.len(),
                    a_settings.as_ptr(),
                    a_settings.len(),
                    &mut out_out,
                    &mut err,
                )
            };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Filter(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_filter_eval_body" => {
            let mut cur = ArgCursor::new(args);
            let a_filter = cur.handle("chs_filter")? as *const ChsFilter;
            let a_format = cur.int()? as i32;
            let a_body = cur.bytes()?;
            let a_settings = cur.bytes()?;
            let mut out_out: *mut ChsBuf = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_filter_eval_body's declared shape; every output pointer is this call's own local.
            let status = unsafe {
                (api.chs_filter_eval_body)(
                    a_filter,
                    a_format,
                    a_body.as_ptr(),
                    a_body.len(),
                    a_settings.as_ptr(),
                    a_settings.len(),
                    &mut out_out,
                    &mut err,
                )
            };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Buf(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_block_create" => {
            let mut cur = ArgCursor::new(args);
            let a_schema = cur.handle("chs_schema")? as *const ChsSchema;
            let a_format = cur.int()? as i32;
            let a_body = cur.bytes()?;
            let a_settings = cur.bytes()?;
            let a_columns = cur.bytes()?;
            let mut out_out: *mut ChsBlock = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_block_create's declared shape; every output pointer is this call's own local.
            let status = unsafe {
                (api.chs_block_create)(
                    a_schema,
                    a_format,
                    a_body.as_ptr(),
                    a_body.len(),
                    a_settings.as_ptr(),
                    a_settings.len(),
                    a_columns.as_ptr(),
                    a_columns.len(),
                    &mut out_out,
                    &mut err,
                )
            };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Block(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_filter_eval_block" => {
            let mut cur = ArgCursor::new(args);
            let a_filter = cur.handle("chs_filter")? as *const ChsFilter;
            let a_block = cur.handle("chs_block")? as *const ChsBlock;
            let mut out_out: *mut ChsBuf = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_filter_eval_block's declared shape; every output pointer is this call's own local.
            let status =
                unsafe { (api.chs_filter_eval_block)(a_filter, a_block, &mut out_out, &mut err) };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Buf(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_discover_query" => {
            let mut out_out: *mut ChsBuf = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_discover_query's declared shape; every output pointer is this call's own local.
            let status = unsafe { (api.chs_discover_query)(&mut out_out, &mut err) };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Buf(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        "chs_discover_columns" => {
            let mut cur = ArgCursor::new(args);
            let a_rows = cur.bytes()?;
            let mut out_out: *mut ChsBuf = std::ptr::null_mut();
            let mut err: *mut ChsError = std::ptr::null_mut();
            // SAFETY: every input is marshaled from the case's own recipe above, matching chs_discover_columns's declared shape; every output pointer is this call's own local.
            let status = unsafe {
                (api.chs_discover_columns)(a_rows.as_ptr(), a_rows.len(), &mut out_out, &mut err)
            };
            let mut outputs: BTreeMap<String, MintedHandle> = BTreeMap::new();
            outputs.insert("out".to_string(), MintedHandle::Buf(out_out));
            // SAFETY: err is null or a chs_error* this same call just received from api above.
            unsafe { finish_status(api, status, err, outputs) }
        }
        other => Err(format!(
            "invoke: {other} is not a function this generation describes, or it is a \"free\"-classified function no case ever calls by name"
        )),
    }
}
