"""The process setup's shared public-API cases (tests/fixtures/abi-v2/setup-cases.json,
generated by scripts/abi-v1/emit/setup_cases.py and read by all four bindings), run
through the public API over fresh copies of the stub libraries.

Each case gets a fresh image per variant it opens and starts with no setup
recorded (`clean_process`). Without `$CHTYPES_ABI2_STUBS` every case skips loudly
by name.
"""

from __future__ import annotations

import contextlib
import json
import shutil

import pytest

from chtypes import (
    ArtifactCorruptError,
    ArtifactIncompatibleError,
    FetchOptions,
    Format,
    InternalError,
    Registry,
    SchemaError,
    ServerProfile,
    Status,
    UnsupportedError,
    UsageError,
    open_unverified,
    setup,
)

from .conftest import REPO_ROOT, stub_path

SETUP_CASES_PATH = REPO_ROOT / "tests" / "fixtures" / "abi-v2" / "setup-cases.json"
_SETUP_DOC: dict = json.loads(SETUP_CASES_PATH.read_text(encoding="utf-8"))
_SETUP_CASES: list[dict] = _SETUP_DOC["cases"]
IMAGE_ZONE_PROBE: bytes = _SETUP_DOC["image_zone_probe"].encode()

CLASSES = {
    "schema": SchemaError,
    "unsupported": UnsupportedError,
    "usage": UsageError,
    "internal": InternalError,
    "artifact_incompatible": ArtifactIncompatibleError,
    "artifact_corrupt": ArtifactCorruptError,
}


def test_the_setup_cases_file_is_not_empty() -> None:
    assert _SETUP_CASES, f"{SETUP_CASES_PATH}: zero cases; a suite that ran nothing must not pass"


def _outcome(want: dict, error: BaseException | None) -> str:
    """What differs between a step's outcome and its expectation; "" when none."""
    if want.get("ok"):
        return "" if error is None else f"want success, got {error!r}"
    cls = CLASSES.get(want["class"])
    if cls is None:
        return f"the case names an error class this runner does not know: {want['class']!r}"
    if not isinstance(error, cls):
        return f"want {cls.__name__}, got {error!r}"
    if "status" in want and error.status != Status[want["status"].removeprefix("CHS_")]:
        return f"status {error.status}, want {want['status']}"
    if "ch_code" in want and error.ch_code != want["ch_code"]:
        return f"ch_code {error.ch_code}, want {want['ch_code']}"
    if "ch_name" in want and error.ch_name != want["ch_name"]:
        return f"ch_name {error.ch_name!r}, want {want['ch_name']!r}"
    if "reason" in want and error.reason != want["reason"]:
        return f"reason {error.reason!r}, want {want['reason']!r}"
    return ""


@pytest.mark.parametrize("setup_case", _SETUP_CASES, ids=[c["id"] for c in _SETUP_CASES])
def test_setup_case(
    setup_case: dict, stubs_dir, stubs_manifest, tmp_path, clean_process, monkeypatch
) -> None:
    if "python" in setup_case.get("not_expressible", {}):
        pytest.skip(f"not expressible in Python: {setup_case['not_expressible']['python']}")
    images: dict[str, str] = {}
    # The case's open library, and the servers and schemas its server ops
    # (rule r7) name.
    current = None
    servers: dict = {}
    schemas: dict = {}
    filters: dict = {}
    batch_rows_passed: int | None = None

    def image(variant: str | None) -> str:
        """The case's one fresh copy of `variant` (the case's own by default)."""
        variant = variant or setup_case["variant"]
        if variant not in images:
            target = tmp_path / f"{variant}-image.so"
            shutil.copyfile(stub_path(stubs_dir, stubs_manifest["variants"][variant]), target)
            target.chmod(0o755)
            images[variant] = str(target)
        return images[variant]

    monkeypatch.setenv("CHTYPES_ALLOW_UNVERIFIED_LIBRARY", "1")
    steps = setup_case["steps"]
    assert steps, "a case with no steps"
    warned: set[str] = set()
    for i, step in enumerate(steps):
        error: BaseException | None = None
        opened = None
        if step["op"] == "server_close":
            servers[step["server"]].close()
            continue
        if step["op"] == "schema_close":
            schemas[step["schema"]].close()
            continue
        if step["op"] == "filter_close":
            filters[step["filter"]].close()
            continue
        if step["op"] == "live":
            # The stub's own live-handle counts, not a value the case sets by hand.
            got = current.live_handles()
            for kind, want in step["live"].items():
                assert got[kind] == want, f"step {i}: live {kind} = {got[kind]}, want {want}: {got}"
            continue
        try:
            if step["op"] == "filter_new":
                filters[step["as"]] = schemas[step["schema"]].compile_filter(step["expression"])
            elif step["op"] == "rows":
                batch_rows_passed = None
                row_filter = filters[step["filter"]] if "filter" in step else None
                batch = schemas[step["schema"]].rows(
                    Format.CSV, step["body"].encode(), row_filter=row_filter
                )
                batch_rows_passed = batch.rows_passed
            elif step["op"] == "server_new":
                servers[step["as"]] = current.new_server(ServerProfile(timezone="UTC"))
            elif step["op"] == "compile":
                kwargs = {"server": servers[step["server"]]} if "server" in step else {}
                made = current.compile_table(step["statement"].encode(), **kwargs)
                if "as" in step:
                    schemas[step["as"]] = made
            elif step["op"] == "setup":
                setup(timezone=step["timezone"])
            elif step["op"] == "open" and "request" in step:
                # A registry over an empty cache, offline, autofetch off.
                cache = tmp_path / f"cache-{i}"
                empty = FetchOptions(cache_dir=cache, system_dirs=[], offline=True)
                registry = Registry(fetch=empty, autofetch=False)
                opened = registry.for_version(step["request"])
            elif step["op"] == "open":
                path = image(step.get("variant"))
                allow = step.get("allow", True)
                # An unverified open with both opt-ins warns once per path: on
                # each copy's first such open. Without them it warns nothing.
                expect_warning = allow and path not in warned
                if allow:
                    warned.add(path)
                with (
                    pytest.warns(UserWarning, match="UNVERIFIED")
                    if expect_warning
                    else contextlib.nullcontext()
                ):
                    opened = open_unverified(path, allow=allow)
            else:
                pytest.fail(f"step {i}: an op this runner does not know: {step['op']!r}")
        except (
            SchemaError,
            UnsupportedError,
            UsageError,
            InternalError,
            ArtifactIncompatibleError,
            ArtifactCorruptError,
        ) as exc:
            error = exc
        if opened is not None:
            current = opened
        diff = _outcome(step["expect"], error)
        if not diff and "rows_passed" in step and step["rows_passed"] != batch_rows_passed:
            diff = (
                f"rows_passed {batch_rows_passed}, want {step['rows_passed']}: "
                "the stub says whether the filter reached the library"
            )
        if not diff and "image_zone" in step["expect"]:
            zone = opened.validate_type(IMAGE_ZONE_PROBE)
            want_zone = step["expect"]["image_zone"]
            if zone != want_zone.encode():
                diff = f"the image was set up with zone {zone!r}, want {want_zone!r}"
        where = (
            f"{step['op']} {step.get('timezone', '')!r} "
            f"{step.get('variant', '')}{step.get('request', '')}"
        )
        assert not diff, f"step {i} ({where}): {diff}"
