/**
 * The fetch/verify/install contract (docs/fetch.md), tested offline.
 *
 * Two kinds of release drive it:
 *
 *  - synthetic ones, built here with a test-only ed25519 key and a hand
 *    ustar writer, so every link of the chain can be broken on purpose
 *    (bad signature, unsigned, tampered tarball, index/sums disagreement,
 *    manifest/index disagreement, path traversal) and the verdict checked;
 *  - the shared vectors under `spec/fixtures/fetch/` (§9), generated by the
 *    core repository's tooling, which every SDK must pass with the same
 *    codes. When they are absent this block SKIPS LOUDLY — never silently.
 *
 * Nothing here asserts on an exit code alone: every verdict is checked by
 * its error class and code, and every install by what is on disk.
 *
 * The fake libraries are random bytes: they hash correctly and can never
 * dlopen, which is exactly the property the autofetch tests need — a fetch
 * that ran is proven by the loader's own "cannot load" on the bytes it
 * installed, at the directory the search path says.
 */

import { generateKeyPairSync, randomBytes, sign as signRaw, createHash, type KeyObject } from 'node:crypto';
import { createReadStream, existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, statSync, symlinkSync, writeFileSync } from 'node:fs';
import { createServer, type Server } from 'node:http';
import type { AddressInfo } from 'node:net';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { gzipSync } from 'node:zlib';
import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from 'vitest';
import { EXIT, runCli, type CliIo } from '../src/cli.js';
import {
  ArtifactCorruptError,
  ArtifactMissingError,
  ArtifactPinnedError,
  ArtifactUnpublishedError,
  ArtifactUntrustedError,
  ChtypesError,
  FetchError,
  Registry,
  RegistryError,
  RELEASE_PUBLIC_KEYS,
  SourceUnreachableError,
  artifactMissingMessage,
  cacheRegistryDir,
  compareVersions,
  ensure,
  ensureAll,
  extractTarGz,
  fetchDestination,
  hostPlatform,
  keyId,
  listArtifacts,
  looksLikeRegistry,
  parseSignatureFile,
  parseVersionSpelling,
  readLock,
  registrySearchPath,
  resolveRegistryDir,
  sha256File,
  trustedKeys,
  verifyEd25519,
  verifyInstalled,
  type EnsureOptions,
  type FetchEvent,
} from '../src/index.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SPEC_FIXTURES = path.resolve(HERE, '..', '..', 'spec', 'fixtures', 'fetch');
const PLATFORM = hostPlatform();
const [HOST_OS, HOST_ARCH] = PLATFORM.split('-') as [string, string];

// The real registry, resolved before any test touches the environment.
const REAL_REGISTRY = resolveRegistryDir();
const HAVE_REGISTRY = REAL_REGISTRY !== null && looksLikeRegistry(REAL_REGISTRY);
if (!HAVE_REGISTRY) {
  console.warn('\n[chtypes] fetch tests that need a real artifact registry are SKIPPED: none found (CHTYPES_REGISTRY / the per-user cache).\n');
}

// ------------------------------------------------------------ helpers

const sha256 = (b: Uint8Array): string => createHash('sha256').update(b).digest('hex');

/** A test-only ed25519 key: raw public key as hex (what CHTYPES_TRUSTED_KEYS takes), private half for signing. */
function testKey(): { hex: string; privateKey: KeyObject } {
  const { publicKey, privateKey } = generateKeyPairSync('ed25519');
  const spki = publicKey.export({ format: 'der', type: 'spki' });
  return { hex: spki.subarray(spki.length - 32).toString('hex'), privateKey };
}

const KEY = testKey();
const OTHER_KEY = testKey();

/** One ustar entry: header block + data + padding to 512. */
function tarEntry(name: string, data: Buffer, flag = '0', opts: { prefix?: string } = {}): Buffer {
  const header = Buffer.alloc(512);
  header.write(name, 0, 100, 'utf8');
  header.write('0000644\0', 100, 8, 'latin1');
  header.write('0000000\0', 108, 8, 'latin1');
  header.write('0000000\0', 116, 8, 'latin1');
  header.write(`${data.length.toString(8).padStart(11, '0')}\0`, 124, 12, 'latin1');
  header.write('00000000000\0', 136, 12, 'latin1');
  header.write('        ', 148, 8, 'latin1');
  header.write(flag, 156, 1, 'latin1');
  header.write('ustar\0', 257, 6, 'latin1');
  header.write('00', 263, 2, 'latin1');
  if (opts.prefix !== undefined) header.write(opts.prefix, 345, 155, 'utf8');
  let sum = 0;
  for (const b of header) sum += b;
  header.write(`${sum.toString(8).padStart(6, '0')}\0 `, 148, 8, 'latin1');
  const pad = (512 - (data.length % 512)) % 512;
  return Buffer.concat([header, data, Buffer.alloc(pad)]);
}

function tarball(entries: Buffer[]): Buffer {
  return gzipSync(Buffer.concat([...entries, Buffer.alloc(1024)]));
}

/** A pax extended header entry (`x`) carrying the given records. */
function paxEntry(records: Record<string, string>): Buffer {
  let payload = '';
  for (const [k, v] of Object.entries(records)) {
    const body = ` ${k}=${v}\n`;
    let len = body.length + 1;
    while (`${len}${body}`.length !== len) len = `${len}${body}`.length;
    payload += `${len}${body}`;
  }
  return tarEntry('PaxHeader/x', Buffer.from(payload, 'utf8'), 'x');
}

interface FakeArtifact {
  minor: string;
  version: string;
  os?: string | undefined;
  arch?: string | undefined;
  library?: string | undefined;
  bytes?: number | undefined;
}

interface ReleaseSpec {
  artifacts: FakeArtifact[];
  /** true: signed by KEY; 'other': signed by a different key; false: no .sig at all. */
  sign?: boolean | 'other';
  /** Break one link on purpose. */
  tamper?: 'tarball' | 'sums' | 'manifest' | 'index-schema';
  seed?: string;
}

interface BuiltRelease {
  dir: string;
  url: string;
  files: Map<string, { file: string; sha256: string; librarySha256: string; library: string }>;
}

/** Build a miniature release directory: tarballs, index.json, SHA256SUMS, SHA256SUMS.sig. */
function makeRelease(spec: ReleaseSpec): BuiltRelease {
  const dir = mkdtempSync(path.join(tmpdir(), 'chtypes-release-'));
  const rows: Record<string, unknown>[] = [];
  const sums: string[] = [];
  const files = new Map<string, { file: string; sha256: string; librarySha256: string; library: string }>();
  for (const a of spec.artifacts) {
    const os = a.os ?? HOST_OS;
    const arch = a.arch ?? HOST_ARCH;
    const library = a.library ?? (os === 'darwin' ? 'libchtypes.dylib' : 'libchtypes.so');
    // Deterministic per (version, seed): re-building "the same" release yields the same bytes.
    const lib = createHash('sha512').update(`${a.version}:${spec.seed ?? ''}`).digest();
    const libBytes = Buffer.concat(Array.from({ length: Math.ceil((a.bytes ?? 4096) / lib.length) }, () => lib)).subarray(0, a.bytes ?? 4096);
    const manifest = {
      arch,
      clickhouse_commit: 'deadbeef',
      clickhouse_minor: a.minor,
      clickhouse_version: a.version,
      library,
      library_bytes: libBytes.length,
      library_sha256: sha256(libBytes),
      os,
      unsafe_families: '',
    };
    const tgz = tarball([
      tarEntry('manifest.json', Buffer.from(JSON.stringify(manifest, null, 1))),
      tarEntry(library, libBytes),
      tarEntry('CH_VERSION', Buffer.from(`${a.version}\n`)),
      tarEntry('unsafe_families.txt', Buffer.alloc(0)),
    ]);
    const file = `chtypes-${a.version}-${os}-${arch}.tar.gz`;
    writeFileSync(path.join(dir, file), tgz);
    const row = {
      arch,
      bytes: tgz.length,
      clickhouse_minor: a.minor,
      clickhouse_version: a.version,
      file,
      library,
      library_sha256: manifest.library_sha256,
      os,
      sha256: sha256(tgz),
    };
    rows.push(row);
    sums.push(`${row.sha256}  ${file}`);
    files.set(a.minor, { file, sha256: row.sha256, librarySha256: manifest.library_sha256, library });
  }
  if (spec.tamper === 'manifest') {
    // index.json claims a different library hash than the manifest inside the tarball.
    (rows[0] as { library_sha256: string }).library_sha256 = sha256(Buffer.from('elsewhere'));
  }
  const index = {
    schema: spec.tamper === 'index-schema' ? 2 : 1,
    generated_at: '2026-09-09T00:00:00Z',
    release_tag: 'test',
    license: 'Elastic License 2.0',
    license_url: 'https://www.elastic.co/licensing/elastic-license',
    artifacts: rows,
  };
  writeFileSync(path.join(dir, 'index.json'), JSON.stringify(index, null, 1));
  if (spec.tamper === 'sums') sums[0] = `${sha256(Buffer.from('not the tarball'))}  ${(rows[0] as { file: string }).file}`;
  const sumsBytes = Buffer.from(`${sums.sort().join('\n')}\n`);
  writeFileSync(path.join(dir, 'SHA256SUMS'), sumsBytes);
  if (spec.tamper === 'tarball') {
    const file = (rows[0] as { file: string }).file;
    const bytes = readFileSync(path.join(dir, file));
    bytes[bytes.length - 1] = bytes[bytes.length - 1]! ^ 0xff;
    writeFileSync(path.join(dir, file), bytes);
  }
  const sign = spec.sign ?? true;
  if (sign !== false) {
    const signer = sign === 'other' ? OTHER_KEY : KEY;
    const sig = signRaw(null, sumsBytes, signer.privateKey);
    writeFileSync(
      path.join(dir, 'SHA256SUMS.sig'),
      `untrusted comment: chtypes test release, ed25519 key ${keyId(signer.hex)}\n${sig.toString('base64')}\n`,
    );
  }
  return { dir, url: pathToFileURL(dir).href, files };
}

/** A static file server over a release directory that counts every request. */
async function serve(dir: string): Promise<{ url: string; hits: Map<string, number>; close: () => Promise<void> }> {
  const hits = new Map<string, number>();
  const server: Server = createServer((req, res) => {
    const name = decodeURIComponent((req.url ?? '/').replace(/^\/+/, '').split('?')[0]!);
    hits.set(name, (hits.get(name) ?? 0) + 1);
    const file = path.join(dir, name);
    if (name === '' || name.includes('..') || !existsSync(file) || !statSync(file).isFile()) {
      res.statusCode = 404;
      res.end('not found');
      return;
    }
    res.setHeader('content-type', 'application/octet-stream');
    createReadStream(file).pipe(res);
  });
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  const { port } = server.address() as AddressInfo;
  return {
    url: `http://127.0.0.1:${port}`,
    hits,
    close: () =>
      new Promise<void>((resolve) => {
        server.closeAllConnections();
        server.close(() => resolve());
      }),
  };
}

const tmpDirs: string[] = [];
const scratch = (label: string): string => {
  const d = mkdtempSync(path.join(tmpdir(), `chtypes-${label}-`));
  tmpDirs.push(d);
  return d;
};
afterAll(() => {
  for (const d of tmpDirs) rmSync(d, { recursive: true, force: true });
});

const ENV_KEYS = ['CHTYPES_REGISTRY', 'XDG_CACHE_HOME', 'CHTYPES_TRUSTED_KEYS', 'CHTYPES_ALLOW_UNSIGNED', 'CHTYPES_AUTOFETCH', 'CHTYPES_TARGET', 'CHTYPES_ARTIFACTS_URL'] as const;
const savedEnv = new Map<string, string | undefined>();
for (const k of ENV_KEYS) savedEnv.set(k, process.env[k]);
afterEach(() => {
  for (const k of ENV_KEYS) {
    const v = savedEnv.get(k);
    if (v === undefined) delete process.env[k];
    else process.env[k] = v;
  }
  vi.restoreAllMocks();
});

/** `ensure` against a synthetic release, trusting the test key, into an explicit destination. */
const opts = (release: BuiltRelease, dest: string, more: Partial<EnsureOptions> = {}): EnsureOptions => ({
  url: release.url,
  dest,
  trustedKeys: [KEY.hex],
  ...more,
});

async function codeOf(p: Promise<unknown>): Promise<string> {
  try {
    await p;
  } catch (err) {
    if (err instanceof FetchError) return err.code;
    throw err;
  }
  throw new Error('expected a FetchError');
}

/** Capture what a CLI run wrote. */
function cliIo(): CliIo & { out: string[]; err: string[] } {
  const out: string[] = [];
  const err: string[] = [];
  return { out, err, stdout: (s) => out.push(s), stderr: (s) => err.push(s), tty: false };
}

/** Everything written to stderr from now until the spy is restored (afterEach), as lines. */
const stderrLines = (): (() => string[]) => {
  const spy = vi.spyOn(process.stderr, 'write').mockImplementation(() => true);
  return () => spy.mock.calls.map((c) => String(c[0]));
};

// ---------------------------------------------------------- signature

describe('the signature (docs/fetch.md §4)', () => {
  it('derives the key id the spec defines from the embedded release key', () => {
    expect(RELEASE_PUBLIC_KEYS).toEqual(['fdb5f06a8d4c9918d049a5f1748fa2e3b3238c3f2000986d5bb9e31beff778fc']);
    expect(keyId(RELEASE_PUBLIC_KEYS[0]!)).toBe('deb275922dbff76e');
  });

  it('verifies the reference vector with the embedded key, and refuses a flipped byte', () => {
    const message = Buffer.from('68656c6c6f0a', 'hex'); // "hello\n"
    const signature = Buffer.from(
      '0fee686f7ed7c64b86a7dce0ffd66b15d1504178153c3b0cc118e2c9456afa6d3e2e55019eca8f75e44ab507d65b0714523e92c7f92452821930691212e76c04',
      'hex',
    );
    expect(verifyEd25519(message, signature, RELEASE_PUBLIC_KEYS[0]!)).toBe(true);
    const flipped = Buffer.from(message);
    flipped[0] = flipped[0]! ^ 0x01;
    expect(verifyEd25519(flipped, signature, RELEASE_PUBLIC_KEYS[0]!)).toBe(false);
    expect(verifyEd25519(message, signature, KEY.hex)).toBe(false);
    expect(verifyEd25519(message, signature.subarray(1), RELEASE_PUBLIC_KEYS[0]!)).toBe(false);
    expect(verifyEd25519(message, signature, 'zz')).toBe(false);
  });

  it('reads the two-line .sig shape and nothing else', () => {
    const sig = randomBytes(64).toString('base64');
    const parsed = parseSignatureFile(Buffer.from(`untrusted comment: chtypes artifacts, ed25519 key deb275922dbff76e\n${sig}\n`));
    expect(parsed?.comment).toBe('chtypes artifacts, ed25519 key deb275922dbff76e');
    expect(parsed?.signature.toString('base64')).toBe(sig);
    expect(parseSignatureFile(Buffer.from(sig))?.signature.length).toBe(64);
    expect(parseSignatureFile(Buffer.from('untrusted comment: x\n'))).toBeNull();
    expect(parseSignatureFile(Buffer.from(`untrusted comment: x\n${randomBytes(32).toString('base64')}\n`))).toBeNull();
    expect(parseSignatureFile(Buffer.from('not base64!!\n'))).toBeNull();
  });

  it('CHTYPES_TRUSTED_KEYS replaces the embedded list; a malformed key is refused loudly', () => {
    expect(trustedKeys()).toEqual(RELEASE_PUBLIC_KEYS);
    process.env['CHTYPES_TRUSTED_KEYS'] = ` ${KEY.hex.toUpperCase()},${OTHER_KEY.hex} `;
    expect(trustedKeys()).toEqual([KEY.hex, OTHER_KEY.hex]);
    expect(trustedKeys([OTHER_KEY.hex])).toEqual([OTHER_KEY.hex]);
    process.env['CHTYPES_TRUSTED_KEYS'] = 'nope';
    expect(() => trustedKeys()).toThrow(/not a raw ed25519 public key/);
    process.env['CHTYPES_TRUSTED_KEYS'] = '';
    expect(trustedKeys()).toEqual(RELEASE_PUBLIC_KEYS);
  });
});

// ----------------------------------------------------------- versions

describe('version spellings and the search path', () => {
  it('tells a line from an exact patch', () => {
    expect(parseVersionSpelling('25.8')).toMatchObject({ line: '25.8', exact: null });
    expect(parseVersionSpelling('25.10')).toMatchObject({ line: '25.10', exact: null });
    expect(parseVersionSpelling('25.8.28.1-lts')).toMatchObject({ line: '25.8', exact: '25.8.28.1-lts', bare: '25.8.28.1' });
    expect(parseVersionSpelling('v25.8.28.1-lts')).toMatchObject({ line: '25.8', exact: '25.8.28.1-lts' });
    expect(parseVersionSpelling('25.8.28.1')).toMatchObject({ line: '25.8', exact: '25.8.28.1', bare: '25.8.28.1' });
    expect(() => parseVersionSpelling('latest')).toThrow(ChtypesError);
    expect(() => parseVersionSpelling('25')).toThrow(/cannot make a ClickHouse version/);
  });

  it('orders versions numerically, channel suffix ignored', () => {
    expect(['25.10', '25.8', '24.8', '26.7'].sort(compareVersions)).toEqual(['24.8', '25.8', '25.10', '26.7']);
    expect(compareVersions('25.8.30.16-lts', '25.8.28.1-lts')).toBeGreaterThan(0);
    expect(compareVersions('25.8.28.1-lts', '25.8.28.1')).toBe(0);
  });

  it('spells the §1 search path in order and dedupes it', () => {
    process.env['XDG_CACHE_HOME'] = '/tmp/xdg';
    process.env['CHTYPES_REGISTRY'] = '/tmp/env-reg';
    expect(registrySearchPath('/tmp/explicit', 'linux-arm64')).toEqual([
      '/tmp/explicit',
      '/tmp/env-reg',
      '/tmp/xdg/chtypes/artifacts/linux-arm64',
      '/usr/local/share/chtypes/artifacts/linux-arm64',
      '/opt/chtypes/artifacts/linux-arm64',
    ]);
    expect(registrySearchPath('/tmp/env-reg', 'linux-arm64')[0]).toBe('/tmp/env-reg');
    expect(registrySearchPath('/tmp/env-reg', 'linux-arm64')).toHaveLength(4);
    delete process.env['CHTYPES_REGISTRY'];
    expect(registrySearchPath(undefined, 'darwin-arm64')[0]).toBe('/tmp/xdg/chtypes/artifacts/darwin-arm64');
    expect(cacheRegistryDir('darwin-amd64')).toBe('/tmp/xdg/chtypes/artifacts/darwin-amd64');
  });

  it('fetch writes to the first of explicit, CHTYPES_REGISTRY, the cache — never a system location', () => {
    process.env['XDG_CACHE_HOME'] = '/tmp/xdg';
    process.env['CHTYPES_REGISTRY'] = '/tmp/env-reg';
    expect(fetchDestination('/tmp/explicit', PLATFORM)).toBe('/tmp/explicit');
    expect(fetchDestination(undefined, PLATFORM)).toBe('/tmp/env-reg');
    // CHTYPES_REGISTRY is this host's registry: a foreign platform goes to the cache keyed by it.
    const foreign = PLATFORM === 'linux-arm64' ? 'darwin-arm64' : 'linux-arm64';
    expect(fetchDestination(undefined, foreign)).toBe(`/tmp/xdg/chtypes/artifacts/${foreign}`);
    delete process.env['CHTYPES_REGISTRY'];
    expect(fetchDestination(undefined, PLATFORM)).toBe(`/tmp/xdg/chtypes/artifacts/${PLATFORM}`);
  });
});

// ---------------------------------------------------------- the chain

describe('the verification chain against a synthetic release (docs/fetch.md §3)', () => {
  const good = makeRelease({ artifacts: [{ minor: '25.8', version: '25.8.28.1-lts' }, { minor: '26.7', version: '26.7.3.19-stable' }] });

  it('installs a line: every link verified, the four files in place, the library hashing what the manifest says', async () => {
    const dest = scratch('dest');
    const events: FetchEvent[] = [];
    const r = await ensure('25.8', opts(good, dest, { onProgress: (e) => events.push(e) }));
    expect(r.installed).toBe(true);
    expect(r.dir).toBe(path.join(dest, '25.8'));
    expect(r.registry).toBe(dest);
    expect(r.line).toBe('25.8');
    expect(r.version).toBe('25.8.28.1-lts');
    expect(r.platform).toBe(PLATFORM);
    expect(r.signed).toBe(true);
    expect(r.keyId).toBe(keyId(KEY.hex));
    const want = good.files.get('25.8')!;
    expect(r.file).toBe(want.file);
    expect(r.sha256).toBe(want.sha256);
    expect(readdirSync(r.dir).sort()).toEqual(['CH_VERSION', 'manifest.json', 'unsafe_families.txt', want.library].sort());
    expect(await sha256File(path.join(r.dir, want.library))).toBe(want.librarySha256);
    expect(readFileSync(path.join(r.dir, 'unsafe_families.txt')).length).toBe(0);
    // No staging leftovers: the hidden siblings are gone, only the line remains.
    expect(readdirSync(dest)).toEqual(['25.8']);
    const downloads = events.filter((e) => e.type === 'download');
    expect(downloads.length).toBeGreaterThan(0);
    expect(downloads[downloads.length - 1]).toMatchObject({ file: want.file, received: statSync(path.join(good.dir, want.file)).size });
    expect(events.some((e) => e.type === 'status' && /signature verified \(key/.test(e.message))).toBe(true);
    expect(events.some((e) => e.type === 'status' && /Elastic License 2.0/.test(e.message))).toBe(true);
  });

  it('is idempotent: installed-and-verified downloads nothing; --force downloads again; a damaged install is replaced', async () => {
    const dest = scratch('dest');
    const server = await serve(good.dir);
    try {
      const web = { ...good, url: server.url };
      const first = await ensure('25.8', opts(web, dest));
      expect(first.installed).toBe(true);
      const want = good.files.get('25.8')!;
      expect(server.hits.get(want.file)).toBe(1);

      const second = await ensure('25.8', opts(web, dest));
      expect(second.installed).toBe(false);
      expect(second.dir).toBe(first.dir);
      expect(server.hits.get(want.file)).toBe(1);
      // The chain's small files were still consulted — "installed" is a verified claim against the release.
      expect(server.hits.get('SHA256SUMS.sig')).toBe(2);

      const forced = await ensure('25.8', opts(web, dest, { force: true }));
      expect(forced.installed).toBe(true);
      expect(server.hits.get(want.file)).toBe(2);

      // A library that no longer hashes what the release says is replaced, not trusted.
      writeFileSync(path.join(dest, '25.8', want.library), 'damaged');
      const repaired = await ensure('25.8', opts(web, dest));
      expect(repaired.installed).toBe(true);
      expect(await sha256File(path.join(dest, '25.8', want.library))).toBe(want.librarySha256);
      expect(server.hits.get(want.file)).toBe(3);
    } finally {
      await server.close();
    }
  });

  it('shares one fetch between concurrent ensures of the same line', async () => {
    const dest = scratch('dest');
    const server = await serve(good.dir);
    try {
      const web = { ...good, url: server.url };
      const [a, b] = await Promise.all([ensure('25.8', opts(web, dest)), ensure('25.8', opts(web, dest))]);
      expect(a).toBe(b);
      expect(server.hits.get(good.files.get('25.8')!.file)).toBe(1);
    } finally {
      await server.close();
    }
  });

  it('CHTYPES_ARTIFACT_UNTRUSTED: a signature by an unknown key stops everything', async () => {
    const dest = scratch('dest');
    const bad = makeRelease({ artifacts: [{ minor: '25.8', version: '25.8.28.1-lts' }], sign: 'other' });
    const err = await ensure('25.8', opts(bad, dest)).catch((e: unknown) => e);
    expect(err).toBeInstanceOf(ArtifactUntrustedError);
    expect((err as FetchError).code).toBe('CHTYPES_ARTIFACT_UNTRUSTED');
    expect((err as Error).message).toContain(keyId(KEY.hex));
    expect(readdirSync(dest)).toEqual([]);
  });

  it('CHTYPES_ARTIFACT_UNTRUSTED: an unsigned release is never downloaded around; CHTYPES_ALLOW_UNSIGNED=1 is loud', async () => {
    const dest = scratch('dest');
    const unsigned = makeRelease({ artifacts: [{ minor: '25.8', version: '25.8.28.1-lts' }], sign: false });
    expect(await codeOf(ensure('25.8', opts(unsigned, dest)))).toBe('CHTYPES_ARTIFACT_UNTRUSTED');
    expect(readdirSync(dest)).toEqual([]);

    const lines = stderrLines();
    process.env['CHTYPES_ALLOW_UNSIGNED'] = '1';
    const r = await ensure('25.8', opts(unsigned, dest));
    expect(r.installed).toBe(true);
    expect(r.signed).toBe(false);
    expect(r.keyId).toBeNull();
    expect(lines().filter((l) => /WARNING/.test(l) && l.includes(unsigned.dir) && /NOT being verified/.test(l))).toHaveLength(1);
  });

  it('the allowUnsigned option skips step 0 with the same warning, and a mis-signed release installs under it', async () => {
    const dest = scratch('dest');
    const bad = makeRelease({ artifacts: [{ minor: '25.8', version: '25.8.28.1-lts' }], sign: 'other' });
    const lines = stderrLines();
    const r = await ensure('25.8', opts(bad, dest, { allowUnsigned: true }));
    expect(r.installed).toBe(true);
    expect(lines().some((l) => /WARNING/.test(l) && /NOT being verified/.test(l))).toBe(true);
  });

  it('CHTYPES_ARTIFACT_CORRUPT: index.json and SHA256SUMS disagreeing is a broken release, not repaired', async () => {
    const dest = scratch('dest');
    const broken = makeRelease({ artifacts: [{ minor: '25.8', version: '25.8.28.1-lts' }], tamper: 'sums' });
    const err = await ensure('25.8', opts(broken, dest)).catch((e: unknown) => e);
    expect(err).toBeInstanceOf(ArtifactCorruptError);
    expect((err as FetchError).code).toBe('CHTYPES_ARTIFACT_CORRUPT');
    expect((err as Error).message).toMatch(/disagrees with itself/);
    expect(readdirSync(dest)).toEqual([]);
  });

  it('CHTYPES_ARTIFACT_CORRUPT: a tampered tarball fails its hash before a byte is unpacked, and leaves nothing behind', async () => {
    const dest = scratch('dest');
    const tampered = makeRelease({ artifacts: [{ minor: '25.8', version: '25.8.28.1-lts' }], tamper: 'tarball' });
    const err = await ensure('25.8', opts(tampered, dest)).catch((e: unknown) => e);
    expect(err).toBeInstanceOf(ArtifactCorruptError);
    expect((err as Error).message).toMatch(/FAILED its sha256/);
    expect(readdirSync(dest)).toEqual([]);
  });

  it('CHTYPES_ARTIFACT_CORRUPT: a manifest that disagrees with index.json is refused after unpacking, nothing installed', async () => {
    const dest = scratch('dest');
    const lying = makeRelease({ artifacts: [{ minor: '25.8', version: '25.8.28.1-lts' }], tamper: 'manifest' });
    const err = await ensure('25.8', opts(lying, dest)).catch((e: unknown) => e);
    expect(err).toBeInstanceOf(ArtifactCorruptError);
    expect((err as Error).message).toMatch(/disagrees with index.json/);
    expect(readdirSync(dest)).toEqual([]);
  });

  it('CHTYPES_ARTIFACT_CORRUPT: an index.json schema this SDK does not know is refused, never guessed', async () => {
    const dest = scratch('dest');
    const future = makeRelease({ artifacts: [{ minor: '25.8', version: '25.8.28.1-lts' }], tamper: 'index-schema' });
    const err = await ensure('25.8', opts(future, dest)).catch((e: unknown) => e);
    expect(err).toBeInstanceOf(ArtifactCorruptError);
    expect((err as Error).message).toMatch(/schema 2 is not 1/);
  });

  it('CHTYPES_ARTIFACT_UNPUBLISHED: a platform, a line, or an exact patch the release does not carry', async () => {
    const dest = scratch('dest');
    const foreign = PLATFORM === 'linux-arm64' ? 'darwin-arm64' : 'linux-arm64';
    const lines = stderrLines();
    const err = await ensure('25.8', opts(good, dest, { platform: foreign })).catch((e: unknown) => e);
    expect(err).toBeInstanceOf(ArtifactUnpublishedError);
    expect((err as FetchError).code).toBe('CHTYPES_ARTIFACT_UNPUBLISHED');
    expect((err as Error).message).toContain(`nothing for ${foreign}`);
    expect(lines().some((l) => /note — fetching/.test(l))).toBe(true);

    expect(await codeOf(ensure('19.1', opts(good, dest)))).toBe('CHTYPES_ARTIFACT_UNPUBLISHED');
    // An exact patch is a hard requirement; the release publishes another one.
    const exact = await ensure('25.8.30.16-lts', opts(good, dest)).catch((e: unknown) => e);
    expect(exact).toBeInstanceOf(ArtifactUnpublishedError);
    expect((exact as Error).message).toMatch(/exactly ClickHouse 25\.8\.30\.16-lts .* Ask for the line \(25\.8\)/);
    // The published patch, typed with or without its channel, is the line.
    expect((await ensure('25.8.28.1-lts', opts(good, dest))).version).toBe('25.8.28.1-lts');
    expect((await ensure('v25.8.28.1', opts(good, dest))).version).toBe('25.8.28.1-lts');
    expect(readdirSync(dest)).toEqual(['25.8']);
  });

  it('CHTYPES_SOURCE_UNREACHABLE: a source that cannot be reached, or does not serve the release', async () => {
    const dest = scratch('dest');
    const dead = await ensure('25.8', opts(good, dest, { url: 'http://127.0.0.1:1' })).catch((e: unknown) => e);
    expect(dead).toBeInstanceOf(SourceUnreachableError);
    expect((dead as FetchError).code).toBe('CHTYPES_SOURCE_UNREACHABLE');
    const empty = scratch('empty-release');
    const nothing = await ensure('25.8', opts(good, dest, { url: empty })).catch((e: unknown) => e);
    expect(nothing).toBeInstanceOf(SourceUnreachableError);
    expect((nothing as Error).message).toMatch(/no SHA256SUMS at/);
    const server = await serve(empty);
    try {
      expect(await codeOf(ensure('25.8', opts(good, dest, { url: server.url })))).toBe('CHTYPES_SOURCE_UNREACHABLE');
    } finally {
      await server.close();
    }
    expect(readdirSync(dest)).toEqual([]);
  });

  it('a plain directory and a file:// URL are the same source', async () => {
    const dest = scratch('dest');
    const a = await ensure('25.8', opts(good, dest, { url: good.dir }));
    expect(a.installed).toBe(true);
    expect(a.source).toBe(good.dir);
    const b = await ensure('25.8', opts(good, dest));
    expect(b.installed).toBe(false);
    expect(b.source).toBe(good.dir);
  });

  it('--all installs every line the release publishes for the platform, oldest first', async () => {
    const dest = scratch('dest');
    const all = await ensureAll(opts(good, dest));
    expect(all.map((r) => r.line)).toEqual(['25.8', '26.7']);
    expect(readdirSync(dest).sort()).toEqual(['25.8', '26.7']);
    expect(all.every((r) => r.installed)).toBe(true);
  });

  it('offline: installed-and-verified is fine without touching any source; anything else is CHTYPES_SOURCE_UNREACHABLE', async () => {
    const dest = scratch('dest');
    const err = await ensure('25.8', opts(good, dest, { offline: true, url: 'http://127.0.0.1:1' })).catch((e: unknown) => e);
    expect(err).toBeInstanceOf(SourceUnreachableError);
    expect((err as Error).message).toMatch(/offline/);
    await ensure('25.8', opts(good, dest));
    const r = await ensure('25.8', opts(good, dest, { offline: true, url: 'http://127.0.0.1:1' }));
    expect(r.installed).toBe(false);
    expect(r.source).toBe('offline');
    expect(r.dir).toBe(path.join(dest, '25.8'));
    // Damaged on disk: offline cannot repair it, and says so.
    writeFileSync(path.join(dest, '25.8', good.files.get('25.8')!.library), 'damaged');
    const bad = await ensure('25.8', opts(good, dest, { offline: true })).catch((e: unknown) => e);
    expect(bad).toBeInstanceOf(SourceUnreachableError);
    expect((bad as Error).message).toMatch(/hashes/);
  });

  it('the lock file (§5): records what was installed, and --frozen refuses anything else with CHTYPES_ARTIFACT_PINNED', async () => {
    const dest = scratch('dest');
    const lock = path.join(scratch('lock'), 'chtypes.lock');
    const r = await ensure('25.8', opts(good, dest, { lock }));
    const want = good.files.get('25.8')!;
    expect(readLock(lock)).toEqual({ schema: 1, artifacts: { [`${PLATFORM}/25.8`]: { file: want.file, sha256: want.sha256 } } });
    expect(JSON.parse(readFileSync(lock, 'utf8'))).toMatchObject({ schema: 1 });
    // Frozen against the same release: fine, and still a no-op download.
    expect((await ensure('25.8', opts(good, dest, { lock, frozen: true }))).installed).toBe(false);
    expect(r.sha256).toBe(want.sha256);

    // A line the lock does not pin.
    const unpinned = await ensure('26.7', opts(good, dest, { lock, frozen: true })).catch((e: unknown) => e);
    expect(unpinned).toBeInstanceOf(ArtifactPinnedError);
    expect((unpinned as FetchError).code).toBe('CHTYPES_ARTIFACT_PINNED');
    expect(existsSync(path.join(dest, '26.7'))).toBe(false);

    // The same line, rebuilt: different bytes, different sha256 — drift, refused.
    const drifted = makeRelease({ artifacts: [{ minor: '25.8', version: '25.8.28.1-lts' }], seed: 'rebuilt' });
    const drift = await ensure('25.8', opts(drifted, dest, { lock, frozen: true })).catch((e: unknown) => e);
    expect(drift).toBeInstanceOf(ArtifactPinnedError);
    expect((drift as Error).message).toMatch(/pins .* but the release offers/);
    // Without --frozen the lock follows the fetch (trust on first fetch, re-pinned on change).
    await ensure('25.8', opts(drifted, dest, { lock }));
    expect(readLock(lock)!.artifacts[`${PLATFORM}/25.8`]!.sha256).toBe(drifted.files.get('25.8')!.sha256);

    // No lock file at all under --frozen: nothing is pinned, so everything is refused.
    const missing = await ensure('25.8', opts(good, dest, { lock: path.join(dest, 'absent.lock'), frozen: true })).catch((e: unknown) => e);
    expect(missing).toBeInstanceOf(ArtifactPinnedError);
    // frozen without a lock path reads ./chtypes.lock; none here pins nothing.
    expect(existsSync(path.resolve('chtypes.lock'))).toBe(false);
    const defaulted = await ensure('25.8', opts(good, dest, { frozen: true })).catch((e: unknown) => e);
    expect(defaulted).toBeInstanceOf(ArtifactPinnedError);
    expect((defaulted as Error).message).toMatch(/chtypes\.lock does not exist/);
  });

  it('url and tag are exclusive; a bad platform key and a bad spelling are usage errors, not verdicts', async () => {
    const dest = scratch('dest');
    await expect(ensure('25.8', opts(good, dest, { tag: 'v1' }))).rejects.toThrow(/pass one/);
    await expect(ensure('25.8', opts(good, dest, { platform: 'win-x64' }))).rejects.toThrow(/not a known platform key/);
    await expect(ensure('nope', opts(good, dest))).rejects.toThrow(ChtypesError);
    expect(readdirSync(dest)).toEqual([]);
  });

  it('verifyInstalled re-hashes every installed line and names the damaged one', async () => {
    const dest = scratch('dest');
    await ensureAll(opts(good, dest));
    mkdirSync(path.join(dest, '.26.7.incoming.stale'));
    mkdirSync(path.join(dest, 'scratch'));
    const ok = await verifyInstalled(dest, PLATFORM);
    expect(ok.map((r) => [r.line, r.ok])).toEqual([['25.8', true], ['26.7', true]]);
    writeFileSync(path.join(dest, '26.7', good.files.get('26.7')!.library), 'damaged');
    const bad = await verifyInstalled(dest, PLATFORM);
    expect(bad.map((r) => [r.line, r.ok])).toEqual([['25.8', true], ['26.7', false]]);
    expect(bad[1]!.problem).toMatch(/hashes .* manifest says/);
    expect(await verifyInstalled(scratch('nothing'), PLATFORM)).toEqual([]);
  });

  it('listArtifacts shows what is installed and what the release offers', async () => {
    const dest = scratch('dest');
    await ensure('25.8', opts(good, dest));
    const listing = await listArtifacts(opts(good, dest));
    expect(listing.installed.map((a) => a.line)).toEqual(['25.8']);
    expect(listing.offered!.map((a) => a.clickhouse_minor)).toEqual(['25.8', '26.7']);
    const offline = await listArtifacts(opts(good, dest, { offline: true }));
    expect(offline.offered).toBeNull();
    expect(offline.installed).toHaveLength(1);
  });
});

// ---------------------------------------------------------------- tar

describe('the tar reader: files only, confined to the destination', () => {
  const write = (name: string, tgz: Buffer): string => {
    const file = path.join(scratch('tgz'), name);
    writeFileSync(file, tgz);
    return file;
  };

  it('refuses path traversal and absolute names as corrupt, writing nothing outside', async () => {
    const out = scratch('out');
    const outside = path.join(path.dirname(out), `escaped-${path.basename(out)}`);
    const evil = write('evil.tgz', tarball([tarEntry(`../${path.basename(outside)}`, Buffer.from('x'))]));
    await expect(extractTarGz(evil, out)).rejects.toThrow(ArtifactCorruptError);
    expect(existsSync(outside)).toBe(false);
    const abs = write('abs.tgz', tarball([tarEntry('/etc/passwd', Buffer.from('x'))]));
    await expect(extractTarGz(abs, out)).rejects.toThrow(/absolute path/);
    const prefixed = write('prefix.tgz', tarball([tarEntry('x', Buffer.from('x'), '0', { prefix: '..' })]));
    await expect(extractTarGz(prefixed, out)).rejects.toThrow(/path traversal/);
  });

  it('skips links and devices without following them, creates directories and empty files, reads pax and GNU long names', async () => {
    const out = scratch('out');
    const longName = `${'d'.repeat(120)}/file.txt`;
    const tgz = write(
      'mixed.tgz',
      tarball([
        tarEntry('link', Buffer.alloc(0), '2'),
        tarEntry('dir/', Buffer.alloc(0), '5'),
        tarEntry('dir/empty', Buffer.alloc(0)),
        tarEntry('./plain', Buffer.from('plain')),
        paxEntry({ path: longName }),
        tarEntry('truncated-name', Buffer.from('via pax')),
        tarEntry('././@LongLink', Buffer.from(`gnu/${'g'.repeat(110)}\0`), 'L'),
        tarEntry('ignored', Buffer.from('via gnu')),
        tarEntry('split', Buffer.from('prefixed'), '0', { prefix: 'pre/fix' }),
      ]),
    );
    const entries = await extractTarGz(tgz, out);
    expect(entries.map((e) => e.name)).toEqual(['dir/empty', 'plain', longName, `gnu/${'g'.repeat(110)}`, 'pre/fix/split']);
    expect(existsSync(path.join(out, 'link'))).toBe(false);
    expect(statSync(path.join(out, 'dir/empty')).size).toBe(0);
    expect(readFileSync(path.join(out, 'plain'), 'utf8')).toBe('plain');
    expect(readFileSync(path.join(out, longName), 'utf8')).toBe('via pax');
    expect(readFileSync(path.join(out, 'pre/fix/split'), 'utf8')).toBe('prefixed');
  });

  it('refuses a truncated archive, a bad header checksum, and bytes that are not gzip', async () => {
    const out = scratch('out');
    const whole = tarEntry('big', randomBytes(3000));
    const truncated = write('trunc.tgz', gzipSync(whole.subarray(0, 1500)));
    await expect(extractTarGz(truncated, out)).rejects.toThrow(/truncated/);
    const badSum = tarEntry('x', Buffer.from('x'));
    badSum[148] = 0x37;
    const corrupt = write('sum.tgz', tarball([badSum]));
    await expect(extractTarGz(corrupt, out)).rejects.toThrow(/checksum/);
    const notGzip = write('plain.tgz', Buffer.from('not a gzip stream'));
    await expect(extractTarGz(notGzip, out)).rejects.toThrow(ArtifactCorruptError);
  });
});

// ------------------------------------------------------------ registry

describe('the registry: the search path, the §7 error and autofetch', () => {
  it('spells the one error verbatim', () => {
    expect(artifactMissingMessage('25.8', 'linux-arm64', ['/a', '/b'])).toBe(
      'chtypes: no artifact for ClickHouse 25.8 (linux-arm64). Looked in: /a, /b.\n' +
        'Install it:  npx @wavehouse/chtypes fetch 25.8\n' +
        'or set CHTYPES_AUTOFETCH=1 to fetch on first use.',
    );
    const err = new ArtifactMissingError('25.8', 'linux-arm64', ['/a']);
    expect(err.code).toBe('CHTYPES_ARTIFACT_MISSING');
    expect(err).toBeInstanceOf(RegistryError);
    expect(err.name).toBe('ArtifactMissingError');
    expect(err.line).toBe('25.8');
    expect(err.lookedIn).toEqual(['/a']);
  });

  it('a named directory that does not exist is an error naming it; with autofetch it is the destination-to-be', () => {
    process.env['XDG_CACHE_HOME'] = scratch('xdg');
    delete process.env['CHTYPES_REGISTRY'];
    const missing = path.join(scratch('reg'), 'absent');
    expect(() => new Registry(missing)).toThrow(new RegExp(`cannot read registry ${missing.replaceAll('.', '\\.')}`));
    const lazy = new Registry(missing, { autofetch: true });
    expect(lazy.dir).toBe(missing);
    expect(lazy.versions()).toEqual([]);
    expect(lazy.searchPath[0]).toBe(missing);
    expect(() => lazy.for('25.8')).toThrow(ArtifactMissingError);
    // Nothing anywhere and autofetch off: an error listing every directory looked in.
    const empty = scratch('empty');
    expect(() => new Registry(empty)).toThrow(/no artifacts in any registry directory\. Looked in: .*Install one:  npx @wavehouse\/chtypes fetch <line>/s);
  });

  it.skipIf(!HAVE_REGISTRY)('a line the primary lacks is taken from the first later directory that has it, on request', () => {
    const real = new Registry(REAL_REGISTRY!);
    try {
      const lines = real.versions();
      if (lines.length < 2) {
        console.warn('[chtypes] search-path layering needs two installed lines; only one found — SKIPPED');
        return;
      }
      const [first, second] = [lines[0]!, lines[1]!];
      const primary = scratch('primary');
      const secondary = scratch('secondary');
      symlinkSync(path.join(real.dir, first), path.join(primary, first), 'dir');
      symlinkSync(path.join(real.dir, second), path.join(secondary, second), 'dir');
      process.env['CHTYPES_REGISTRY'] = secondary;
      process.env['XDG_CACHE_HOME'] = scratch('xdg');
      const layered = new Registry(primary);
      try {
        expect(layered.dir).toBe(primary);
        expect(layered.searchPath.slice(0, 2)).toEqual([primary, secondary]);
        expect(layered.versions()).toEqual([first]);
        expect(layered.has(second)).toBe(true);
        expect(layered.has('19.1')).toBe(false);
        expect(layered.for(second).minor).toBe(second);
        expect(layered.versions()).toEqual([first, second].sort(compareVersions));
        try {
          layered.for('19.1');
          throw new Error('unreachable');
        } catch (err) {
          expect(err).toBeInstanceOf(ArtifactMissingError);
          expect((err as ArtifactMissingError).message).toBe(artifactMissingMessage('19.1', PLATFORM, layered.searchPath));
        }
      } finally {
        layered.close();
      }
      // An explicit directory that exists but holds nothing falls through to the next that does.
      const hollow = scratch('hollow');
      const fell = new Registry(hollow);
      try {
        expect(fell.dir).toBe(secondary);
        expect(fell.versions()).toEqual([second]);
      } finally {
        fell.close();
      }
    } finally {
      real.close();
    }
  });

  it.skipIf(!HAVE_REGISTRY)('open(): a missing line rejects with the §7 error unless autofetch is on, which fetches once and then loads', async () => {
    const release = makeRelease({ artifacts: [{ minor: '19.1', version: '19.1.16.79' }] });
    const server = await serve(release.dir);
    const dest = scratch('autofetch-dest');
    try {
      const off = new Registry(REAL_REGISTRY!, { fetch: { url: server.url, dest, trustedKeys: [KEY.hex] } });
      try {
        await expect(off.open('19.1')).rejects.toBeInstanceOf(ArtifactMissingError);
        expect(server.hits.size).toBe(0);
        expect(off.open(off.versions()[0]!)).resolves.toBe(off.for(off.versions()[0]!));
      } finally {
        off.close();
      }

      process.env['CHTYPES_AUTOFETCH'] = '1';
      const on = new Registry(REAL_REGISTRY!, { fetch: { url: server.url, dest, trustedKeys: [KEY.hex] } });
      try {
        // Two concurrent opens: one download. The fake library then fails to
        // dlopen — loudly, from the directory the fetch installed into — which
        // is the proof that ensure ran and landed where the search path says.
        const settled = await Promise.allSettled([on.open('19.1'), on.open('19.1')]);
        for (const s of settled) {
          expect(s.status).toBe('rejected');
          const err = (s as PromiseRejectedResult).reason as Error;
          expect(err).toBeInstanceOf(RegistryError);
          expect(err).not.toBeInstanceOf(ArtifactMissingError);
          expect(err.message).toMatch(new RegExp(`cannot load ${path.join(dest, '19.1').replaceAll('.', '\\.')}`));
        }
        expect(server.hits.get(release.files.get('19.1')!.file)).toBe(1);
        expect(existsSync(path.join(dest, '19.1', 'manifest.json'))).toBe(true);
        // A fetch verdict comes through open() as itself.
        const bad = makeRelease({ artifacts: [{ minor: '19.2', version: '19.2.1.1' }], sign: 'other' });
        const strict = new Registry(REAL_REGISTRY!, { autofetch: true, fetch: { url: bad.url, dest, trustedKeys: [KEY.hex] } });
        try {
          await expect(strict.open('19.2')).rejects.toBeInstanceOf(ArtifactUntrustedError);
        } finally {
          strict.close();
        }
      } finally {
        on.close();
      }
    } finally {
      await server.close();
    }
  });
});

// ----------------------------------------------------------------- CLI

describe('the CLI (docs/fetch.md §6)', () => {
  const good = makeRelease({ artifacts: [{ minor: '25.8', version: '25.8.28.1-lts' }, { minor: '26.7', version: '26.7.3.19-stable' }] });
  const run = (args: string[]): Promise<{ code: number; out: string; err: string }> => {
    const io = cliIo();
    return runCli(args, io).then((code) => ({ code, out: io.out.join(''), err: io.err.join('') }));
  };

  it('where prints the directory fetch would write to', async () => {
    process.env['XDG_CACHE_HOME'] = '/tmp/xdg';
    delete process.env['CHTYPES_REGISTRY'];
    expect(await run(['where'])).toEqual({ code: 0, out: `/tmp/xdg/chtypes/artifacts/${PLATFORM}\n`, err: '' });
    expect((await run(['where', '--dest', '/somewhere'])).out).toBe('/somewhere\n');
    process.env['CHTYPES_REGISTRY'] = '/tmp/env-reg';
    expect((await run(['where'])).out).toBe('/tmp/env-reg\n');
  });

  it('fetch prints the installed directory alone on stdout, progress on stderr, exit 0', async () => {
    const dest = scratch('cli-dest');
    process.env['CHTYPES_TRUSTED_KEYS'] = KEY.hex;
    const r = await run(['fetch', '25.8', '--url', good.url, '--dest', dest]);
    expect(r.code).toBe(EXIT.ok);
    expect(r.out).toBe(`${path.join(dest, '25.8')}\n`);
    expect(r.err).toMatch(/==> .*signature verified/);
    expect(r.err).toMatch(/==> installed and verified/);
    expect(existsSync(path.join(dest, '25.8', 'manifest.json'))).toBe(true);
    // Twice: idempotent, quiet.
    const again = await run(['fetch', '25.8', '--url', good.url, '--dest', dest, '--quiet']);
    expect(again).toEqual({ code: 0, out: `${path.join(dest, '25.8')}\n`, err: '' });
    // Several lines, and --all.
    const both = await run(['fetch', '25.8', '26.7', '--url', good.url, '--dest', dest, '-q']);
    expect(both.out).toBe(`${path.join(dest, '25.8')}\n${path.join(dest, '26.7')}\n`);
    const all = await run(['fetch', '--all', '--url', good.url, '--dest', scratch('cli-all'), '-q']);
    expect(all.code).toBe(0);
    expect(all.out.split('\n').filter(Boolean)).toHaveLength(2);
  });

  it('maps every verdict to its exit code and prints the code', async () => {
    process.env['CHTYPES_TRUSTED_KEYS'] = KEY.hex;
    const dest = scratch('cli-dest');
    const bad = makeRelease({ artifacts: [{ minor: '25.8', version: '25.8.28.1-lts' }], sign: 'other' });
    const untrusted = await run(['fetch', '25.8', '--url', bad.url, '--dest', dest, '-q']);
    expect(untrusted.code).toBe(EXIT.verificationFailed);
    expect(untrusted.err).toMatch(/\[CHTYPES_ARTIFACT_UNTRUSTED\]/);
    expect(untrusted.out).toBe('');

    const tampered = makeRelease({ artifacts: [{ minor: '25.8', version: '25.8.28.1-lts' }], tamper: 'tarball' });
    expect((await run(['fetch', '25.8', '--url', tampered.url, '--dest', dest, '-q'])).code).toBe(EXIT.verificationFailed);

    const unreachable = await run(['fetch', '25.8', '--url', 'http://127.0.0.1:1', '--dest', dest, '-q']);
    expect(unreachable.code).toBe(EXIT.sourceUnreachable);
    expect(unreachable.err).toMatch(/\[CHTYPES_SOURCE_UNREACHABLE\]/);

    const unpublished = await run(['fetch', '19.1', '--url', good.url, '--dest', dest, '-q']);
    expect(unpublished.code).toBe(EXIT.unpublished);
    expect(unpublished.err).toMatch(/\[CHTYPES_ARTIFACT_UNPUBLISHED\]/);

    const lock = path.join(scratch('cli-lock'), 'chtypes.lock');
    expect((await run(['fetch', '25.8', '--url', good.url, '--dest', dest, '--lock', lock, '-q'])).code).toBe(0);
    expect(readLock(lock)!.artifacts[`${PLATFORM}/25.8`]).toBeDefined();
    const pinned = await run(['fetch', '26.7', '--url', good.url, '--dest', dest, '--lock', lock, '--frozen', '-q']);
    expect(pinned.code).toBe(EXIT.verificationFailed);
    expect(pinned.err).toMatch(/\[CHTYPES_ARTIFACT_PINNED\]/);

    const offline = await run(['fetch', '26.7', '--offline', '--dest', dest, '-q']);
    expect(offline.code).toBe(EXIT.sourceUnreachable);
    expect((await run(['fetch', '25.8', '--offline', '--dest', dest, '-q'])).code).toBe(0);
  });

  it('usage errors exit 2 with the usage text', async () => {
    expect((await run([])).code).toBe(EXIT.usage);
    expect((await run(['bogus'])).code).toBe(EXIT.usage);
    expect((await run(['fetch'])).code).toBe(EXIT.usage);
    const unknownFlag = await run(['fetch', '25.8', '--nope']);
    expect(unknownFlag.code).toBe(EXIT.usage);
    expect(unknownFlag.err).toMatch(/usage: chtypes/);
    expect((await run(['fetch', '25.8', '--url', good.url, '--tag', 'v1'])).code).toBe(EXIT.usage);
    expect((await run(['fetch', '25.8', '--all', '--url', good.url])).code).toBe(EXIT.usage);
    expect((await run(['fetch', 'latest', '--url', good.url])).code).toBe(EXIT.usage);
    expect((await run(['fetch', '25.8', '--platform', 'win-x64', '--url', good.url])).code).toBe(EXIT.usage);
    expect((await run(['where', 'extra'])).code).toBe(EXIT.usage);
    const help = await run(['--help']);
    expect(help.code).toBe(0);
    expect(help.out).toMatch(/chtypes fetch <line>/);
    expect((await run(['--version'])).out).toMatch(/^\d+\.\d+\.\d+/);
  });

  it('verify and list report on the registry directory', async () => {
    process.env['CHTYPES_TRUSTED_KEYS'] = KEY.hex;
    const dest = scratch('cli-dest');
    expect((await run(['verify', '--dest', dest])).err).toMatch(/nothing installed/);
    await run(['fetch', '--all', '--url', good.url, '--dest', dest, '-q']);
    const ok = await run(['verify', '--dest', dest]);
    expect(ok.code).toBe(0);
    expect(ok.out.split('\n').filter((l) => l.startsWith('ok '))).toHaveLength(2);
    writeFileSync(path.join(dest, '26.7', good.files.get('26.7')!.library), 'damaged');
    const bad = await run(['verify', '--dest', dest]);
    expect(bad.code).toBe(EXIT.verificationFailed);
    expect(bad.out).toMatch(/^BAD  26\.7/m);

    const listed = await run(['list', '--dest', dest, '--url', good.url]);
    expect(listed.code).toBe(0);
    expect(listed.out).toMatch(/installed in .*:\n  25\.8 /);
    expect(listed.out).toMatch(/offers for .*:\n  25\.8 .*\(installed\)/);
    expect(listed.out).toMatch(/26\.7 .*tar\.gz {2}\d+ bytes/);
    const offline = await run(['list', '--dest', dest, '--offline']);
    expect(offline.out).not.toMatch(/offers/);
  });

  it('the built bin runs as a subprocess: `node dist/cli.js where`', async () => {
    const bin = path.resolve(HERE, '..', 'dist', 'cli.js');
    if (!existsSync(bin)) {
      console.warn('[chtypes] dist/cli.js is not built (pnpm build) — the subprocess check is SKIPPED');
      return;
    }
    const { execFile } = await import('node:child_process');
    const result = await new Promise<{ code: number | null; stdout: string }>((resolve) => {
      execFile(process.execPath, [bin, 'where', '--dest', '/somewhere'], (error, stdout) => {
        resolve({ code: error === null ? 0 : (error as { code?: number }).code ?? 1, stdout });
      });
    });
    expect(result).toEqual({ code: 0, stdout: '/somewhere\n' });
    const usage = await new Promise<number | null>((resolve) => {
      execFile(process.execPath, [bin], (error) => resolve(error === null ? 0 : ((error as { code?: number }).code ?? null)));
    });
    expect(usage).toBe(EXIT.usage);
  });
});

// ------------------------------------------------------- spec fixtures

const HAVE_FIXTURES = existsSync(path.join(SPEC_FIXTURES, 'signed', 'index.json'));
if (!HAVE_FIXTURES) {
  console.warn(`\n[chtypes] spec/fixtures/fetch is ABSENT (${SPEC_FIXTURES}): the shared fetch vectors (docs/fetch.md §9) are SKIPPED.\n`);
}

/** The test key the fixtures are signed with, however its directory spells it. */
function fixtureKey(): string {
  const dir = path.join(SPEC_FIXTURES, 'test-key');
  const candidates = existsSync(dir) ? readdirSync(dir).map((f) => path.join(dir, f)) : [];
  for (const file of candidates) {
    if (!statSync(file).isFile()) continue;
    const text = readFileSync(file, 'utf8');
    const hex = /\b([0-9a-fA-F]{64})\b/.exec(text)?.[1];
    if (hex !== undefined && /pub/i.test(path.basename(file))) return hex;
  }
  for (const file of candidates) {
    if (!statSync(file).isFile()) continue;
    const bytes = readFileSync(file);
    if (bytes.length === 32) return bytes.toString('hex');
    const hex = /\b([0-9a-fA-F]{64})\b/.exec(bytes.toString('utf8'))?.[1];
    if (hex !== undefined) return hex;
  }
  throw new Error(`no public key found under ${dir}: ${candidates.join(', ')}`);
}

describe.skipIf(!HAVE_FIXTURES)('the shared vectors under spec/fixtures/fetch (docs/fetch.md §9)', () => {
  let key: string;
  let fixturePlatform: string;
  let fixtureLine: string;
  beforeAll(() => {
    key = fixtureKey();
    const index = JSON.parse(readFileSync(path.join(SPEC_FIXTURES, 'signed', 'index.json'), 'utf8')) as {
      artifacts: { os: string; arch: string; clickhouse_minor: string }[];
    };
    const row = index.artifacts.find((a) => `${a.os}-${a.arch}` === PLATFORM) ?? index.artifacts[0]!;
    fixturePlatform = `${row.os}-${row.arch}`;
    fixtureLine = row.clickhouse_minor;
  });

  const fixture = (name: string, dest: string, more: Partial<EnsureOptions> = {}): EnsureOptions => ({
    url: pathToFileURL(path.join(SPEC_FIXTURES, name)).href,
    dest,
    platform: fixturePlatform,
    ...more,
  });

  it('signed/ installs and verifies, with CHTYPES_TRUSTED_KEYS set to the test key', async () => {
    process.env['CHTYPES_TRUSTED_KEYS'] = key;
    const dest = scratch('fixture-dest');
    const lines = stderrLines();
    const r = await ensure(fixtureLine, fixture('signed', dest));
    expect(r.installed).toBe(true);
    expect(r.signed).toBe(true);
    expect(r.keyId).toBe(keyId(key));
    expect(await sha256File(path.join(r.dir, r.library))).toBe(r.librarySha256);
    expect((await ensure(fixtureLine, fixture('signed', dest))).installed).toBe(false);
    expect(lines().filter((l) => /WARNING/.test(l))).toHaveLength(0);
    // The embedded release key must NOT verify a test-key fixture.
    delete process.env['CHTYPES_TRUSTED_KEYS'];
    expect(await codeOf(ensure(fixtureLine, fixture('signed', scratch('fixture-dest2'))))).toBe('CHTYPES_ARTIFACT_UNTRUSTED');
  });

  it('expected.json: the unpublished platform, line and patch are CHTYPES_ARTIFACT_UNPUBLISHED against signed/', async () => {
    process.env['CHTYPES_TRUSTED_KEYS'] = key;
    const expected = JSON.parse(readFileSync(path.join(SPEC_FIXTURES, 'expected.json'), 'utf8')) as {
      key_id: string;
      trusted_keys: string[];
      lines: Record<string, string>;
      unpublished: { code: string; exit: number; line: string; patch: string; platform: string };
    };
    expect(expected.trusted_keys).toContain(key);
    expect(keyId(key)).toBe(expected.key_id);
    const dest = scratch('fixture-dest');
    stderrLines(); // the foreign-platform note is expected here; keep it out of the test log
    const { line, patch, platform, code } = expected.unpublished;
    expect(await codeOf(ensure(line, fixture('signed', dest)))).toBe(code);
    expect(await codeOf(ensure(patch, fixture('signed', dest)))).toBe(code);
    expect(await codeOf(ensure(fixtureLine, fixture('signed', dest, { platform })))).toBe(code);
    expect(readdirSync(dest)).toEqual([]);
    // And the published rows resolve to exactly the patches expected.json names.
    for (const [minor, version] of Object.entries(expected.lines)) {
      expect((await ensure(minor, fixture('signed', dest))).version).toBe(version);
    }
    expect(readdirSync(dest).sort()).toEqual(Object.keys(expected.lines).sort());
  });

  it('unsigned/ installs under CHTYPES_ALLOW_UNSIGNED=1, with one loud warning naming the source', async () => {
    process.env['CHTYPES_TRUSTED_KEYS'] = key;
    process.env['CHTYPES_ALLOW_UNSIGNED'] = '1';
    const dest = scratch('fixture-dest');
    const lines = stderrLines();
    const r = await ensure(fixtureLine, fixture('unsigned', dest));
    expect(r.installed).toBe(true);
    expect(r.signed).toBe(false);
    const warnings = lines().filter((l) => /WARNING/.test(l));
    expect(warnings).toHaveLength(1);
    expect(warnings[0]).toContain(path.join(SPEC_FIXTURES, 'unsigned'));
  });

  it.each([
    ['bad-signature', 'CHTYPES_ARTIFACT_UNTRUSTED'],
    ['unsigned', 'CHTYPES_ARTIFACT_UNTRUSTED'],
    ['tampered-tarball', 'CHTYPES_ARTIFACT_CORRUPT'],
    ['sums-index-mismatch', 'CHTYPES_ARTIFACT_CORRUPT'],
  ])('%s/ is refused with %s and installs nothing', async (name, code) => {
    process.env['CHTYPES_TRUSTED_KEYS'] = key;
    const dest = scratch('fixture-dest');
    expect(await codeOf(ensure(fixtureLine, fixture(name, dest)))).toBe(code);
    expect(readdirSync(dest)).toEqual([]);
  });

  it('chtypes.lock pins signed/: --frozen accepts it, and refuses a release that differs', async () => {
    process.env['CHTYPES_TRUSTED_KEYS'] = key;
    const lockFile = path.join(SPEC_FIXTURES, 'chtypes.lock');
    const lock = readLock(lockFile)!;
    expect(lock.schema).toBe(1);
    const pinKey = Object.keys(lock.artifacts).find((k) => k.startsWith(`${fixturePlatform}/`));
    expect(pinKey).toBeDefined();
    const line = pinKey!.split('/')[1]!;
    const dest = scratch('fixture-dest');
    // The lock is a shared fixture: never written to. Copy it beside the destination.
    const copy = path.join(dest, 'chtypes.lock');
    writeFileSync(copy, readFileSync(lockFile));
    const r = await ensure(line, fixture('signed', dest, { lock: copy, frozen: true }));
    expect(r.file).toBe(lock.artifacts[pinKey!]!.file);
    expect(r.sha256).toBe(lock.artifacts[pinKey!]!.sha256);
    expect(readLock(copy)).toEqual(lock);
    // Any release whose bytes differ from the pin is refused under --frozen.
    const other = makeRelease({ artifacts: [{ minor: line, version: r.version, os: fixturePlatform.split('-')[0], arch: fixturePlatform.split('-')[1] }], seed: 'not the pinned one' });
    const pinned = await ensure(line, fixture('signed', scratch('fixture-dest2'), { url: other.url, lock: copy, frozen: true, trustedKeys: [KEY.hex] })).catch((e: unknown) => e);
    expect(pinned).toBeInstanceOf(ArtifactPinnedError);
  });
});
