#!/usr/bin/env bash
# lint-public.sh — this repository is public; nothing tracked here may hand a
# reader a pointer into the private core repository, into the private
# working notes that sit next to it, or into a developer's own filesystem.
#
# WHY THIS EXISTS. A sweep in 2026-09 removed 27 links and paths into that
# repository and reported the job done. It had replaced each path literal with
# the PROSE "the core repository's C ABI specification" — so the pointers did
# not go away, they changed shape, and 148 of them survived in source comments
# that ship inside the crate, the sdist and the Go module. Nothing noticed,
# because the only thing asserting they were gone was a sentence in a
# changelog. A check that exists only as intention is indistinguishable from a
# check that passes.
#
# WIDENED 2026-09-18 (issue #96), after an independent audit judged the check
# too narrow: two case-sensitive literal strings is what it does, no more.
# Zero leaks does not mean the rules are wide enough to have found one. This
# revision (a) makes every rule case-insensitive, (b) adds needles for the
# private repository's characteristic top-level paths (a path that does not
# even contain the private repository's name was going uncaught), for the
# private working-note filenames that live in the housing folder one level
# above both repositories, and for a local absolute path (a developer's own
# home directory leaking into public prose), and (c) keeps every needle
# structural — a path SHAPE — over one that spells out private content,
# because the needles below are themselves public.
#
# The rules are deliberately narrow, so they have no false positives and need
# no allowlist. Describing the two-repository split in prose ("the other half
# is the core repository", "the arbiter", "the acceptance rig") is honest and
# stays legal; naming or citing something a reader cannot open does not. Every
# rule below has a selftest case proving it fires, and the negative cases
# prove the legal prose above still passes — see --selftest.
#
#   scripts/lint-public.sh               check every tracked file
#   scripts/lint-public.sh --selftest    prove every rule fires, and that
#                                         legitimate prose does not
#   scripts/lint-public.sh --print-rules dump the needles this script uses,
#                                         one per line, so a second tool (the
#                                         issue/PR body sweep this script
#                                         cannot itself run as a CI gate —
#                                         see scripts/sweep-public-mentions.py)
#                                         applies exactly the same rules
#                                         instead of a hand-copied drift risk
#
# tests/fixtures/fetch/ is excluded: those bytes are generated by the release
# pipeline and are verified byte-identical to it, so a hand edit here would
# only break that check. Defects in them are reported upstream instead.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$HERE"

# ---------------------------------------------------------------------------
# Literal needles — case-insensitive substrings. Each rule is paired by index
# with what to write instead. `-Fin`: fixed string, case-insensitive, print
# line numbers. `Chtypes-Core` and `CHTYPES-CORE` must be caught exactly like
# `chtypes-core` — a leak does not stop being one for how it was capitalized.
RULES=(
  'chtypes-core'
  "core repository's C ABI specification"
  'lib/csrc/'
  'tests/arbiter/'
  'tests/acceptance/'
  'ci/steps/'
  'docs/proposals/'
)
WHYS=(
  'the private repository by name. A reader cannot open it; say what the thing IS, not where it lives.'
  'the exact prose pointer a 2026-09 sweep left behind 148 times. Write "the C ABI contract"; include/chtypes.h is the public authority for it.'
  "the private repository's C++ source tree. A reader cannot open it; say \"the C++ wrapper\", not its path."
  "one of the private repository's two scoring rigs. A reader cannot open it; say \"the arbiter\" (this repository already does, in docs/reference/bindings.md) — never its path."
  "the private repository's other scoring rig. Same reasoning: say \"the acceptance rig\" in words, never its path."
  "the private repository's CI step directory. A reader cannot open it; describe the step, not where it lives."
  "the private repository's design-proposal directory. A reader cannot open it; describe the proposal, not where it lives."
)

# Private working-note filenames — the housing folder that sits one directory
# above this repository (and above the private one) keeps notes named
# PREFIX-title.md. These five prefixes are the actual folder listing as of
# 2026-09-18 (issue #96); case-insensitive, since a lower-cased or
# URL-slugged citation is still a citation of a file a public reader cannot
# open. A citation of one is exactly as dead an end as a path into the
# private repository itself, and lint-paths.sh will not catch it, because the
# file is not IN this repository for that script to check for existence.
NOTE_FILE_PATTERN='\b(?:AUDIT|HANDOFF|NOTE|PROMPT|REVIEW)-[A-Za-z0-9-]+\.md\b'
NOTE_FILE_WHY='a private working note filename from the housing folder one level above this repository. A reader cannot open it; say what it concluded, not its filename.'

# Local absolute path — /Users/<name>/… or /home/<name>/… is a real leak of a
# developer's own filesystem layout, and has appeared in this project's prose
# before (the finding behind issue #96). This repository already uses the
# generic placeholder spellings "/Users/me/…" (docs/guides/artifacts.md) and
# "/home/u/…" (rust/src/error.rs) to keep a path example machine-agnostic,
# and those stay legal; a segment naming an actual account does not. Scoped
# to a full path (a trailing "/" — more segments follow), not a bare mention
# of the word "Users" or "home".
LOCAL_PATH_PATTERN='(?<![A-Za-z0-9_])/(?:Users|home)/([A-Za-z0-9_.-]+)/'
LOCAL_PATH_PLACEHOLDERS='me,you,user,username,u'
LOCAL_PATH_WHY='a local absolute path — a developer machine home directory. It tells a public reader nothing useful and leaks a filesystem layout; use a relative path, $HOME or ~.'

tracked() {
  git ls-files -z \
    | tr '\0' '\n' \
    | grep -v '^tests/fixtures/fetch/' \
    | grep -v '^scripts/lint-public\.sh$'
}

scan() {
  local root="$1" rc=0 n i

  for i in "${!RULES[@]}"; do
    local rule="${RULES[$i]}" why="${WHYS[$i]}"
    # -F: these are literal strings, not patterns. -i: case-insensitive. A
    # file list on stdin so the exclusions above are the single definition
    # of scope.
    local hits
    hits="$( (cd "$root" && tracked | tr '\n' '\0' | xargs -0 grep -Fin -- "$rule" 2>/dev/null) || true)"
    if [ -n "$hits" ]; then
      n=$(printf '%s\n' "$hits" | wc -l | tr -d ' ')
      printf 'lint-public: %s occurrence(s) of %s\n' "$n" "$(printf '%q' "$rule")" >&2
      printf '  %s\n' "$why" >&2
      printf '%s\n' "$hits" | sed 's/^/    /' >&2
      rc=1
    fi
  done

  # These two need actual pattern matching and (for the path rule) a
  # contextual exclusion list, not a fixed string — so python3 rather than
  # grep -F, the same reason scripts/lint-paths.sh reaches for it. The
  # patterns and placeholder list live in the bash variables above and are
  # handed over by environment so nothing is duplicated between the check
  # itself and --print-rules below.
  local note_hits
  note_hits="$( (cd "$root" && tracked | tr '\n' '\0' | LINT_NOTE_PATTERN="$NOTE_FILE_PATTERN" python3 -c '
import os, re, sys

pat = re.compile(os.environ["LINT_NOTE_PATTERN"], re.IGNORECASE)
bad = []
for f in sys.stdin.read().split("\0"):
    if not f:
        continue
    try:
        text = open(f, encoding="utf-8", errors="ignore").read()
    except OSError:
        continue
    for i, line in enumerate(text.splitlines(), 1):
        for m in pat.finditer(line):
            bad.append((f, i, m.group(0)))
for f, i, name in bad:
    print(f"{f}:{i}:{name}")
if bad:
    sys.exit(1)
' 2>/dev/null) || true)"
  if [ -n "$note_hits" ]; then
    n=$(printf '%s\n' "$note_hits" | wc -l | tr -d ' ')
    printf 'lint-public: %s occurrence(s) of %s\n' "$n" 'a housing-folder private note filename' >&2
    printf '  %s\n' "$NOTE_FILE_WHY" >&2
    printf '%s\n' "$note_hits" | sed 's/^/    /' >&2
    rc=1
  fi

  local path_hits
  path_hits="$( (cd "$root" && tracked | tr '\n' '\0' | LINT_PATH_PATTERN="$LOCAL_PATH_PATTERN" LINT_PATH_PLACEHOLDERS="$LOCAL_PATH_PLACEHOLDERS" python3 -c '
import os, re, sys

pat = re.compile(os.environ["LINT_PATH_PATTERN"])
placeholders = {p for p in os.environ["LINT_PATH_PLACEHOLDERS"].split(",") if p}
bad = []
for f in sys.stdin.read().split("\0"):
    if not f:
        continue
    try:
        text = open(f, encoding="utf-8", errors="ignore").read()
    except OSError:
        continue
    for i, line in enumerate(text.splitlines(), 1):
        for m in pat.finditer(line):
            if m.group(1).lower() in placeholders:
                continue
            bad.append((f, i, line.strip()))
for f, i, line in bad:
    print(f"{f}:{i}:{line}")
if bad:
    sys.exit(1)
' 2>/dev/null) || true)"
  if [ -n "$path_hits" ]; then
    n=$(printf '%s\n' "$path_hits" | wc -l | tr -d ' ')
    printf 'lint-public: %s occurrence(s) of %s\n' "$n" 'a local absolute path' >&2
    printf '  %s\n' "$LOCAL_PATH_WHY" >&2
    printf '%s\n' "$path_hits" | sed 's/^/    /' >&2
    rc=1
  fi

  return $rc
}

if [ "${1:-}" = "--print-rules" ]; then
  # Machine-readable needle dump for scripts/sweep-public-mentions.py, so the
  # body sweep applies exactly these rules rather than a hand-copied second
  # definition that can drift from this one the way the 2026-09 sweep drifted
  # from "gone".
  for i in "${!RULES[@]}"; do
    printf 'LITERAL\t%s\n' "${RULES[$i]}"
  done
  printf 'REGEX\t%s\n' "$NOTE_FILE_PATTERN"
  printf 'LOCALPATH\t%s\t%s\n' "$LOCAL_PATH_PATTERN" "$LOCAL_PATH_PLACEHOLDERS"
  exit 0
fi

if [ "${1:-}" = "--selftest" ]; then
  # Every rule must FIRE on planted text, case-insensitively for the literal
  # ones. A rule that silently matches nothing is the failure this script was
  # written to prevent, so prove it — in a throwaway git repo so
  # `git ls-files` has something to list. Every rule must also stay SILENT on
  # legitimate prose: describing the split in words, citing an in-repo path,
  # or the generic placeholder path spellings this repository's own tree
  # already uses. The first false positive is how a check gets disabled.
  tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
  git init -q "$tmp"

  # --- original two rules, unchanged spelling ---
  printf 'see chtypes-core/tests/conformance for the rest\n' > "$tmp/planted-1.md"
  printf "per the core repository's C ABI specification, the sign decides\n" > "$tmp/planted-2.md"

  # --- case-insensitivity: same two rules, different capitalization ---
  printf 'vendored from Chtypes-Core a year ago\n' > "$tmp/planted-case-1.md"
  printf "matches the CORE REPOSITORY'S C ABI SPECIFICATION exactly\n" > "$tmp/planted-case-2.md"

  # --- new literal path needles: the private repository's top-level shapes ---
  printf 'the wrapper lives in lib/csrc/chtypes_wrapper.cc\n' > "$tmp/planted-csrc.md"
  printf 'rescore under tests/arbiter/ after any change\n' > "$tmp/planted-arbiter.md"
  printf 'report first from tests/acceptance/ before anything else\n' > "$tmp/planted-acceptance.md"
  printf 'the fetch step is ci/steps/header-sync.sh\n' > "$tmp/planted-cisteps.md"
  printf 'recorded under docs/proposals/ in the private tree\n' > "$tmp/planted-proposals.md"

  # --- new needle: a housing-folder private note filename ---
  printf 'see REVIEW-wavehouse-asks-evidence.md for the detail\n' > "$tmp/planted-note.md"

  # --- new needle: a local absolute path naming an actual account ---
  printf 'backup restored from /Users/quinn/Downloads/chtypes-dump\n' > "$tmp/planted-path.md"

  # --- legal: describing the split in words, an in-repo path, and the
  #     generic placeholder path spellings this repository already ships ---
  printf 'the other half is the core repository, under its own license\n' > "$tmp/legal.md"
  printf "mirrors the arbiter's \`_same_value\`, per docs/reference/bindings.md\n" > "$tmp/legal-arbiter-word.md"
  printf "also how the acceptance rig's ground truth is captured\n" > "$tmp/legal-acceptance-word.md"
  printf 'see docs/reference/artifact.md for the loader contract\n' > "$tmp/legal-inrepo-path.md"
  printf 'chtypes: no artifact found. Looked in /Users/me/.cache/chtypes/artifacts/darwin-arm64\n' > "$tmp/legal-path-placeholder.md"
  printf 'PathBuf::from("/home/u/.cache/chtypes/artifacts/linux-arm64")\n' > "$tmp/legal-home-placeholder.md"
  printf 'CLAUDE.md and README.md explain the split; so does NOTICE\n' > "$tmp/legal-allcaps-filenames.md"

  git -C "$tmp" add -A
  out="$(scan "$tmp" 2>&1)" && { echo "SELFTEST FAILED: planted violations were not caught" >&2; exit 1; }

  for want in planted-1.md planted-2.md planted-case-1.md planted-case-2.md \
              planted-csrc.md planted-arbiter.md planted-acceptance.md \
              planted-cisteps.md planted-proposals.md planted-note.md planted-path.md; do
    printf '%s\n' "$out" | grep -q "$want" || { echo "SELFTEST FAILED: rule did not fire on $want" >&2; exit 1; }
  done

  for clean in legal.md legal-arbiter-word.md legal-acceptance-word.md \
               legal-inrepo-path.md legal-path-placeholder.md \
               legal-home-placeholder.md legal-allcaps-filenames.md; do
    printf '%s\n' "$out" | grep -q "$clean" && { echo "SELFTEST FAILED: a legal prose mention was flagged ($clean)" >&2; exit 1; }
  done

  echo "lint-public: selftest ok — every rule fires (case-insensitively), legitimate prose stays legal"
  exit 0
fi

if scan "$HERE"; then
  echo "lint-public: ok — no pointers into the private repository, its private notes, or a local filesystem"
else
  exit 1
fi
