#!/usr/bin/env bash
# lint-public.sh — this repository is public; nothing tracked here may hand a
# reader a pointer into the private core repository.
#
# WHY THIS EXISTS. A sweep in 2026-09 removed 27 links and paths into that
# repository and reported the job done. It had replaced each path literal with
# the PROSE "the core repository's C ABI specification" — so the pointers did
# not go away, they changed shape, and 148 of them survived in source comments
# that ship inside the crate, the sdist and the Go module. Nothing noticed,
# because the only thing asserting they were gone was a sentence in a
# changelog. A check that exists only as intention is indistinguishable from a
# check that passes.
#
# The rules are deliberately narrow, so they have no false positives and need
# no allowlist. Describing the two-repository split in prose ("the other half
# is the core repository") is honest and stays legal; naming something a
# reader cannot open does not.
#
#   scripts/lint-public.sh             check every tracked file
#   scripts/lint-public.sh --selftest  prove both rules actually fire
#
# tests/fixtures/fetch/ is excluded: those bytes are generated by the release
# pipeline and are verified byte-identical to it, so a hand edit here would
# only break that check. Defects in them are reported upstream instead.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$HERE"

# Each rule is a literal string, paired by index with what to write instead.
RULES=(
  'chtypes-core'
  "core repository's C ABI specification"
)
WHYS=(
  'the private repository by name. A reader cannot open it; say what the thing IS, not where it lives.'
  'the exact prose pointer a 2026-09 sweep left behind 148 times. Write "the C ABI contract"; include/chtypes.h is the public authority for it.'
)

tracked() {
  git ls-files -z \
    | tr '\0' '\n' \
    | grep -v '^tests/fixtures/fetch/' \
    | grep -v '^scripts/lint-public\.sh$'
}

scan() {
  local root="$1" rc=0 n i
  for i in "${!RULES[@]}"; do
    local rule="${RULES[$i]}" why="${WHYS[$i]}"
    # -F: these are literal strings, not patterns. A file list on stdin so the
    # exclusions above are the single definition of scope.
    local hits
    hits="$( (cd "$root" && tracked | tr '\n' '\0' | xargs -0 grep -Fn -- "$rule" 2>/dev/null) || true)"
    if [ -n "$hits" ]; then
      n=$(printf '%s\n' "$hits" | wc -l | tr -d ' ')
      printf 'lint-public: %s occurrence(s) of %s\n' "$n" "$(printf '%q' "$rule")" >&2
      printf '  %s\n' "$why" >&2
      printf '%s\n' "$hits" | sed 's/^/    /' >&2
      rc=1
    fi
  done
  return $rc
}

if [ "${1:-}" = "--selftest" ]; then
  # Both rules must FIRE on planted text. A rule that silently matches nothing
  # is the failure this script was written to prevent, so prove it, in a throw
  # away git repo so `git ls-files` has something to list.
  tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
  git init -q "$tmp"
  printf 'see chtypes-core/tests/conformance for the rest\n' > "$tmp/planted-1.md"
  printf "per the core repository's C ABI specification, the sign decides\n" > "$tmp/planted-2.md"
  printf 'the other half is the core repository, under its own license\n' > "$tmp/legal.md"
  git -C "$tmp" add -A
  out="$(scan "$tmp" 2>&1)" && { echo "SELFTEST FAILED: planted violations were not caught" >&2; exit 1; }
  for want in 'planted-1.md' 'planted-2.md'; do
    printf '%s\n' "$out" | grep -q "$want" || { echo "SELFTEST FAILED: rule did not fire on $want" >&2; exit 1; }
  done
  printf '%s\n' "$out" | grep -q 'legal.md' && { echo "SELFTEST FAILED: a legal prose mention was flagged" >&2; exit 1; }
  echo "lint-public: selftest ok — both rules fire, prose mentions stay legal"
  exit 0
fi

if scan "$HERE"; then
  echo "lint-public: ok — no pointers into the private repository"
else
  exit 1
fi
