#!/usr/bin/env bash
# lint-public.sh — this repository is public; nothing tracked here may hand a
# reader a pointer into the private core repository, into the private
# working notes that sit next to it, or into a developer's own filesystem.
#
# WHY THIS EXISTS. A sweep in 2026-09 removed 27 links and paths into that
# repository and reported the job done. It had replaced each path literal with
# the PROSE "the core repository's C ABI specification" — so the pointers did
# not go away, they changed shape, and 148 of them survived in source comments
# that ship inside the crate, the sdist and the Go module. Nothing noticed,
# because the only thing asserting they were gone was a sentence in a
# changelog. A check that exists only as intention is indistinguishable from a
# check that passes.
#
# WIDENED 2026-09-18 (issue #96), after an independent audit judged the check
# too narrow: two case-sensitive literal strings is what it does, no more.
# Zero leaks does not mean the rules are wide enough to have found one. This
# revision (a) makes every rule case-insensitive, (b) adds needles for the
# private repository's characteristic top-level paths (a path that does not
# even contain the private repository's name was going uncaught), for the
# private working-note filenames that live in the housing folder one level
# above both repositories, and for a local absolute path (a developer's own
# home directory leaking into public prose), and (c) keeps every needle
# structural — a path SHAPE — over one that spells out private content,
# because the needles below are themselves public.
#
# The rules are deliberately narrow, so they have no false positives and need
# no allowlist. Describing the two-repository split in prose ("the other half
# is the core repository", "the arbiter", "the acceptance rig") is honest and
# stays legal; naming or citing something a reader cannot open does not. Every
# rule below has a selftest case proving it fires, and the negative cases
# prove the legal prose above still passes — see --selftest.
#
# WIDENED AGAIN 2026-09-23 (issue #171). The private repository's top-level
# layout has more directories than the seven path literals above knew about;
# the artifact producer enumerated their actual tree, and the chtypes lead
# ruled that a directory PREFIX may be encoded here in the open — a detector
# cannot hide what it detects, five prefixes were already sitting in this
# file, and a bare prefix is the accepted cost of catching the full paths
# that matter (a comment pasted with the file appended, a stack trace, a
# copied shell transcript). Added: the private repository's remaining
# `tests/*`, `lib/*`, `dist/*` and `docs/*` top-level directories, plus one
# STRUCTURAL needle, `Wave-RF/software/chtypes/` — the housing path under
# which every private build worktree lives. Worktree names are chosen fresh
# daily and cannot be enumerated without going stale; the housing path they
# all sit under does not change, so it is the one thing worth matching
# structurally rather than by name.
#
# ⚠️ `tests/sdk/` is a KNOWN, ACCEPTED false-positive risk, not an oversight.
# It names the private repository's per-language server-truth suites — but a
# legitimate public sentence about THIS repository's own SDKs can contain the
# same four characters in the same order ("the go/python/ts/rust tests for
# the SDK"), and nothing about the substring match can tell the two apart.
# It stays in the needle set anyway: a needle that fires on a legitimate
# string costs one triage pass to dismiss; a needle that is missing costs a
# leak nobody ever sees. Do not "fix" this by narrowing or dropping the rule
# — that was tried mentally and rejected in #171 for exactly this reason.
#
#   scripts/lint-public.sh               check every tracked file
#   scripts/lint-public.sh --selftest    prove every rule fires, and that
#                                         legitimate prose does not
#   scripts/lint-public.sh --print-rules dump the needles this script uses,
#                                         one per line, so a second tool (the
#                                         issue/PR body sweep this script
#                                         cannot itself run as a CI gate —
#                                         see scripts/sweep-public-mentions.py)
#                                         applies exactly the same rules
#                                         instead of a hand-copied drift risk
#
# WIDENED AGAIN 2026-09-26 (issue #224). tests/fixtures/fetch/ used to be
# excluded outright — reasoned as "those bytes are generated by the release
# pipeline and verified byte-identical to it, so a hand edit here would only
# break that check" — and because of that exemption, nobody had ever pointed
# either this script or lint-cited-paths.sh at it. A cross-repository audit
# found what had accumulated there: the private repository's name, its issue
# numbers and the literal path of the generator that produces the fixtures,
# sitting in prose files (READMEs, a JSON field) that nothing hashes or signs
# — only the tarballs and SHA256SUMS inside each miniature release are, and
# this scan does not touch those. The exemption is gone; this directory is
# tracked text like any other now. Also widened: `ci/steps/` above caught one
# specific file under the private repository's `ci/` directory and missed a
# different one (`ci/resolve-version.py`, cited from scripts/fetch.sh) purely
# because it was a different filename under the same directory. CI_INFRA_PATH
# below replaces reliance on enumerating every filename with a shape match on
# the directory itself, and does the same for `infra/` (the former
# chtypes-infra repository, folded into the private repository's own tree on
# 2026-09-10).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$HERE"

# ---------------------------------------------------------------------------
# Literal needles — case-insensitive substrings. Each rule is paired by index
# with what to write instead. `-Fin`: fixed string, case-insensitive, print
# line numbers. `Chtypes-Core` and `CHTYPES-CORE` must be caught exactly like
# `chtypes-core` — a leak does not stop being one for how it was capitalized.
RULES=(
  'chtypes-core'
  "core repository's C ABI specification"
  'lib/csrc/'
  'tests/arbiter/'
  'tests/acceptance/'
  'docs/proposals/'
  'tests/wherefilter/'
  'tests/conformance/'
  'tests/fuzz/'
  'tests/harness/'
  'tests/perf/'
  'tests/tsan/'
  'tests/sdk/'
  'lib/tools/'
  'lib/harness/'
  'dist/docker/'
  'dist/integration/'
  'dist/linux-verify/'
  'docs/measurements/'
  'Wave-RF/software/chtypes/'
)
WHYS=(
  'the private repository by name. A reader cannot open it; say what the thing IS, not where it lives.'
  'the exact prose pointer a 2026-09 sweep left behind 148 times. Write "the C ABI contract"; include/chtypes.h is the public authority for it.'
  "the private repository's C++ source tree. A reader cannot open it; say \"the C++ wrapper\", not its path."
  "one of the private repository's two scoring rigs. A reader cannot open it; say \"the arbiter\" (this repository already does, in docs/reference/bindings.md) — never its path."
  "the private repository's other scoring rig. Same reasoning: say \"the acceptance rig\" in words, never its path."
  "the private repository's design-proposal directory. A reader cannot open it; describe the proposal, not where it lives."
  "the private repository's wherefilter scoring rig. A reader cannot open it; describe what it scores, not its path."
  "the private repository's conformance suite. A reader cannot open it; say what it conforms to, not its path."
  "the private repository's fuzzing harness. A reader cannot open it; describe the coverage, not its path."
  "the private repository's test harness. A reader cannot open it; say \"the harness\" in words, not its path."
  "the private repository's performance-test suite. A reader cannot open it; cite the result, not its path."
  "the private repository's thread-sanitizer suite. A reader cannot open it; say \"a SANITIZE=thread build\", not its path."
  "the private repository's per-language SDK server-truth suites. A reader cannot open it — KNOWINGLY AMBIGUOUS, see the header note above: kept anyway because a missed leak costs more than a triage pass."
  "the private repository's internal tooling directory. A reader cannot open it; name the tool by what it does, not its path."
  "the private repository's harness library. A reader cannot open it; describe it, not its path."
  "the private repository's Docker build output. A reader cannot open it; describe the image, not its path."
  "the private repository's integration-build output. A reader cannot open it; describe it, not its path."
  "the private repository's Linux verification output. A reader cannot open it; describe the check, not its path."
  "the private repository's internal measurements directory. A reader cannot open it; cite the number, not its path."
  "the housing path under which every private build worktree lives. Worktree names change daily and cannot be enumerated; this structural prefix does not go stale the way a name list would."
)

# Private working-note filenames — the housing folder that sits one directory
# above this repository (and above the private one) keeps notes named
# PREFIX-title.md. These five prefixes are the actual folder listing as of
# 2026-09-18 (issue #96); case-insensitive, since a lower-cased or
# URL-slugged citation is still a citation of a file a public reader cannot
# open. A citation of one is exactly as dead an end as a path into the
# private repository itself, and lint-cited-paths.sh will not catch it, because the
# file is not IN this repository for that script to check for existence.
NOTE_FILE_PATTERN='\b(?:AUDIT|HANDOFF|NOTE|PROMPT|REVIEW)-[A-Za-z0-9-]+\.md\b'
NOTE_FILE_WHY='a private working note filename from the housing folder one level above this repository. A reader cannot open it; say what it concluded, not its filename.'

# Local absolute path — /Users/<name>/… or /home/<name>/… is a real leak of a
# developer's own filesystem layout, and has appeared in this project's prose
# before (the finding behind issue #96). This repository already uses the
# generic placeholder spellings "/Users/me/…" (docs/guides/artifacts.md) and
# "/home/u/…" (rust/src/error.rs) to keep a path example machine-agnostic,
# and those stay legal; a segment naming an actual account does not. Scoped
# to a full path (a trailing "/" — more segments follow), not a bare mention
# of the word "Users" or "home".
#
# `runner` (issue #168) is not a placeholder stand-in like the others — it is
# GitHub Actions' actual, fixed account name on every hosted Ubuntu runner,
# so /home/runner/… is platform boilerplate, not a person's machine. It names
# no one and nothing private, and it is unavoidable: any pasted Actions log
# or CI step output brings it along. It stays narrow the same way the rest of
# this allowlist does — only the exact segment "runner" is exempt; any other
# /home/<name>/… still fires, selftest proves both directions below.
LOCAL_PATH_PATTERN='(?<![A-Za-z0-9_])/(?:Users|home)/([A-Za-z0-9_.-]+)/'
LOCAL_PATH_PLACEHOLDERS='me,you,user,username,u,runner'
LOCAL_PATH_WHY='a local absolute path — a developer machine home directory. It tells a public reader nothing useful and leaks a filesystem layout; use a relative path, $HOME or ~.'

# The private repository's `ci/` and `infra/` top-level directories — its CI
# step scripts, and (since 2026-09-10, when the former chtypes-infra
# repository was folded into it) its infrastructure tree. `ci/steps/` used to
# be one literal entry in RULES above; a citation of a DIFFERENT file under
# the same top-level directory (`ci/resolve-version.py`, cited from
# scripts/fetch.sh) sailed straight past it, because RULES is exact-string
# matching and that was a different string. This is a shape match instead,
# for the same reason NOTE_FILE_PATTERN and LOCAL_PATH_PATTERN are regexes:
# it has to catch the directory, not one filename inside it.
#
# `ci` and `infra` are common enough as substrings that a bare match would
# misfire — `github.com/golangci/misspell` (scripts/lint-spelling.sh's own
# tooling dependency) contains the four characters "ci/" — so the pattern
# requires "ci" or "infra" to START a path segment: not preceded by a letter,
# digit or underscore. This repository has no `ci/` or `infra/` directory of
# its own (its own CI lives under `.github/workflows/`), so every genuine
# match is a citation of the private repository's tree; selftest proves both
# the catch and the golangci/ non-match below.
CI_INFRA_PATH_PATTERN='(?<![A-Za-z0-9_])(?:ci|infra)/'
CI_INFRA_PATH_WHY="a path inside the private repository's CI or infrastructure tree. A reader cannot open it; describe the step or the change, not its path."

tracked() {
  git ls-files -z \
    | tr '\0' '\n' \
    | grep -v '^scripts/lint-public\.sh$'
}

scan() {
  local root="$1" rc=0 n i

  for i in "${!RULES[@]}"; do
    local rule="${RULES[$i]}" why="${WHYS[$i]}"
    # -F: these are literal strings, not patterns. -i: case-insensitive. A
    # file list on stdin so the exclusions above are the single definition
    # of scope.
    local hits
    hits="$( (cd "$root" && tracked | tr '\n' '\0' | xargs -0 grep -Fin -- "$rule" 2>/dev/null) || true)"
    if [ -n "$hits" ]; then
      n=$(printf '%s\n' "$hits" | wc -l | tr -d ' ')
      printf 'lint-public: %s occurrence(s) of %s\n' "$n" "$(printf '%q' "$rule")" >&2
      printf '  %s\n' "$why" >&2
      printf '%s\n' "$hits" | sed 's/^/    /' >&2
      rc=1
    fi
  done

  # These two need actual pattern matching and (for the path rule) a
  # contextual exclusion list, not a fixed string — so python3 rather than
  # grep -F, the same reason scripts/lint-cited-paths.sh reaches for it. The
  # patterns and placeholder list live in the bash variables above and are
  # handed over by environment so nothing is duplicated between the check
  # itself and --print-rules below.
  local note_hits
  note_hits="$( (cd "$root" && tracked | tr '\n' '\0' | LINT_NOTE_PATTERN="$NOTE_FILE_PATTERN" python3 -c '
import os, re, sys

pat = re.compile(os.environ["LINT_NOTE_PATTERN"], re.IGNORECASE)
bad = []
for f in sys.stdin.read().split("\0"):
    if not f:
        continue
    try:
        text = open(f, encoding="utf-8", errors="ignore").read()
    except OSError:
        continue
    for i, line in enumerate(text.splitlines(), 1):
        for m in pat.finditer(line):
            bad.append((f, i, m.group(0)))
for f, i, name in bad:
    print(f"{f}:{i}:{name}")
if bad:
    sys.exit(1)
' 2>/dev/null) || true)"
  if [ -n "$note_hits" ]; then
    n=$(printf '%s\n' "$note_hits" | wc -l | tr -d ' ')
    printf 'lint-public: %s occurrence(s) of %s\n' "$n" 'a housing-folder private note filename' >&2
    printf '  %s\n' "$NOTE_FILE_WHY" >&2
    printf '%s\n' "$note_hits" | sed 's/^/    /' >&2
    rc=1
  fi

  local path_hits
  path_hits="$( (cd "$root" && tracked | tr '\n' '\0' | LINT_PATH_PATTERN="$LOCAL_PATH_PATTERN" LINT_PATH_PLACEHOLDERS="$LOCAL_PATH_PLACEHOLDERS" python3 -c '
import os, re, sys

pat = re.compile(os.environ["LINT_PATH_PATTERN"])
placeholders = {p for p in os.environ["LINT_PATH_PLACEHOLDERS"].split(",") if p}
bad = []
for f in sys.stdin.read().split("\0"):
    if not f:
        continue
    try:
        text = open(f, encoding="utf-8", errors="ignore").read()
    except OSError:
        continue
    for i, line in enumerate(text.splitlines(), 1):
        for m in pat.finditer(line):
            if m.group(1).lower() in placeholders:
                continue
            bad.append((f, i, line.strip()))
for f, i, line in bad:
    print(f"{f}:{i}:{line}")
if bad:
    sys.exit(1)
' 2>/dev/null) || true)"
  if [ -n "$path_hits" ]; then
    n=$(printf '%s\n' "$path_hits" | wc -l | tr -d ' ')
    printf 'lint-public: %s occurrence(s) of %s\n' "$n" 'a local absolute path' >&2
    printf '  %s\n' "$LOCAL_PATH_WHY" >&2
    printf '%s\n' "$path_hits" | sed 's/^/    /' >&2
    rc=1
  fi

  local ci_infra_hits
  ci_infra_hits="$( (cd "$root" && tracked | tr '\n' '\0' | LINT_CI_INFRA_PATTERN="$CI_INFRA_PATH_PATTERN" python3 -c '
import os, re, sys

pat = re.compile(os.environ["LINT_CI_INFRA_PATTERN"], re.IGNORECASE)
bad = []
for f in sys.stdin.read().split("\0"):
    if not f:
        continue
    try:
        text = open(f, encoding="utf-8", errors="ignore").read()
    except OSError:
        continue
    for i, line in enumerate(text.splitlines(), 1):
        for m in pat.finditer(line):
            bad.append((f, i, line.strip()))
for f, i, line in bad:
    print(f"{f}:{i}:{line}")
if bad:
    sys.exit(1)
' 2>/dev/null) || true)"
  if [ -n "$ci_infra_hits" ]; then
    n=$(printf '%s\n' "$ci_infra_hits" | wc -l | tr -d ' ')
    printf 'lint-public: %s occurrence(s) of %s\n' "$n" "a private repository ci/ or infra/ path" >&2
    printf '  %s\n' "$CI_INFRA_PATH_WHY" >&2
    printf '%s\n' "$ci_infra_hits" | sed 's/^/    /' >&2
    rc=1
  fi

  return $rc
}

if [ "${1:-}" = "--print-rules" ]; then
  # Machine-readable needle dump for scripts/sweep-public-mentions.py, so the
  # body sweep applies exactly these rules rather than a hand-copied second
  # definition that can drift from this one the way the 2026-09 sweep drifted
  # from "gone".
  for i in "${!RULES[@]}"; do
    printf 'LITERAL\t%s\n' "${RULES[$i]}"
  done
  printf 'REGEX\t%s\n' "$NOTE_FILE_PATTERN"
  printf 'REGEX\t%s\n' "$CI_INFRA_PATH_PATTERN"
  printf 'LOCALPATH\t%s\t%s\n' "$LOCAL_PATH_PATTERN" "$LOCAL_PATH_PLACEHOLDERS"
  exit 0
fi

if [ "${1:-}" = "--selftest" ]; then
  # Every rule must FIRE on planted text, case-insensitively for the literal
  # ones. A rule that silently matches nothing is the failure this script was
  # written to prevent, so prove it — in a throwaway git repo so
  # `git ls-files` has something to list. Every rule must also stay SILENT on
  # legitimate prose: describing the split in words, citing an in-repo path,
  # or the generic placeholder path spellings this repository's own tree
  # already uses. The first false positive is how a check gets disabled.
  tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
  git init -q "$tmp"

  # --- original two rules, unchanged spelling ---
  printf 'see chtypes-core/tests/conformance for the rest\n' > "$tmp/planted-1.md"
  printf "per the core repository's C ABI specification, the sign decides\n" > "$tmp/planted-2.md"

  # --- case-insensitivity: same two rules, different capitalization ---
  printf 'vendored from Chtypes-Core a year ago\n' > "$tmp/planted-case-1.md"
  printf "matches the CORE REPOSITORY'S C ABI SPECIFICATION exactly\n" > "$tmp/planted-case-2.md"

  # --- new literal path needles: the private repository's top-level shapes ---
  printf 'the wrapper lives in lib/csrc/chtypes_wrapper.cc\n' > "$tmp/planted-csrc.md"
  printf 'rescore under tests/arbiter/ after any change\n' > "$tmp/planted-arbiter.md"
  printf 'report first from tests/acceptance/ before anything else\n' > "$tmp/planted-acceptance.md"
  printf 'recorded under docs/proposals/ in the private tree\n' > "$tmp/planted-proposals.md"

  # --- new needle: a housing-folder private note filename ---
  printf 'see REVIEW-wavehouse-asks-evidence.md for the detail\n' > "$tmp/planted-note.md"

  # --- new needle: a local absolute path naming an actual account ---
  printf 'backup restored from /Users/quinn/Downloads/chtypes-dump\n' > "$tmp/planted-path.md"

  # --- issue #168: /home/runner/… is GitHub Actions' own fixed account name
  #     on every hosted runner, not a developer's machine — must NOT fire.
  #     Pasted straight from a CI log, the shape this actually recurs in. ---
  printf '==> wrote /home/runner/work/_temp/abi-fixtures: wrong-revision reports 5\n' > "$tmp/legal-runner-path.md"

  # --- issue #168, the half that matters more: allowlisting "runner" must
  #     NOT widen into "any /home/<name>/… passes". A DIFFERENT real account
  #     name under /home/ — not "runner" — must still fire exactly as before.
  printf 'reproduced only on /home/eric/work/_temp/abi-fixtures, nowhere else\n' > "$tmp/planted-home-eric.md"

  # --- issue #171: the private repository's remaining top-level directories,
  #     enumerated by the artifact producer. One planted (must fire) and one
  #     legal, words-only (must not fire) case per needle, same shape as the
  #     #96 pairs above. ---
  # NOTE: every tests/* and docs/* fixture below plants a BARE directory
  # prefix (a trailing slash followed by prose, never a filename with an
  # extension) — same shape as the tests/acceptance/ and docs/proposals/
  # fixtures above. lint-cited-paths.sh (a separate gate; see scripts/lint-cited-paths.sh)
  # flags any tracked citation of a docs|examples|scripts|include|goldens|
  # spec|tests path that ends in a real extension and does not resolve to a
  # file in this repository, and it does not exempt this file the way it
  # exempts itself — a planted filename under one of those top-level
  # directories would trip that check, since no such file exists. A bare
  # prefix proves the needle fires just as well and stays invisible to
  # lint-cited-paths.sh's extension test.
  printf 'baseline scores regenerate under tests/wherefilter/ on every run\n' > "$tmp/planted-wherefilter.md"
  printf 'the wherefilter rig scores predicate pushdown, same idea as the arbiter\n' > "$tmp/legal-wherefilter-word.md"

  printf 'new cases land in tests/conformance/ before anything else\n' > "$tmp/planted-conformance.md"
  printf 'the conformance suite gates every release line\n' > "$tmp/legal-conformance-word.md"

  printf 'crash inputs are archived under tests/fuzz/ from the last run\n' > "$tmp/planted-fuzz.md"
  printf 'the fuzzing harness found the boundary case overnight\n' > "$tmp/legal-fuzz-word.md"

  printf 'wire the new check into tests/harness/ before merging\n' > "$tmp/planted-harness.md"
  printf 'the test harness retries a flaky case twice before failing it\n' > "$tmp/legal-harness-word.md"

  printf 'baseline numbers come from tests/perf/ on every run\n' > "$tmp/planted-perf.md"
  printf 'the performance suite flags a five percent regression\n' > "$tmp/legal-perf-word.md"

  printf 'races only reproduce under tests/tsan/ on the nightly run\n' > "$tmp/planted-tsan.md"
  printf 'a SANITIZE=thread build catches the same race\n' > "$tmp/legal-tsan-word.md"

  printf 'the server-truth suites run from tests/sdk/ against this checkout\n' > "$tmp/planted-sdk.md"
  printf "this repository's own SDK tests live under go/, python/, ts/ and rust/\n" > "$tmp/legal-sdk-word.md"

  printf 'the tunable is passed by lib/tools/oracle-linux.sh for old images\n' > "$tmp/planted-libtools.md"
  printf 'the internal tooling directory carries this environment tunable\n' > "$tmp/legal-libtools-word.md"

  printf 'shared fixtures live in lib/harness/fixtures.py\n' > "$tmp/planted-libharness.md"
  printf 'the harness library shares fixtures across every rig\n' > "$tmp/legal-libharness-word.md"

  printf 'the image build script is dist/docker/build.sh\n' > "$tmp/planted-distdocker.md"
  printf 'the Docker build output ships the same artifact\n' > "$tmp/legal-distdocker-word.md"

  printf 'nightly output lands in dist/integration/report.json\n' > "$tmp/planted-distintegration.md"
  printf 'the integration-build output confirmed the fix\n' > "$tmp/legal-distintegration-word.md"

  printf 'the check reads dist/linux-verify/summary.txt\n' > "$tmp/planted-distlinuxverify.md"
  printf 'the Linux verification output confirmed the checksum\n' > "$tmp/legal-distlinuxverify-word.md"

  printf 'the raw numbers are archived under docs/measurements/ from the last release\n' > "$tmp/planted-docsmeasurements.md"
  printf 'the internal measurements directory tracks throughput over time\n' > "$tmp/legal-docsmeasurements-word.md"

  printf 'the failure only reproduced under Wave-RF/software/chtypes/wt-goblin-3\n' > "$tmp/planted-housing.md"
  printf 'the housing folder holds both repositories side by side\n' > "$tmp/legal-housing-word.md"

  # --- issue #224: CI_INFRA_PATH_PATTERN replaces the old single-file
  #     `ci/steps/` literal with a shape match, so a DIFFERENT file under the
  #     same top-level directory (the actual leak, scripts/fetch.sh citing
  #     ci/resolve-version.py) is caught too, and so is `infra/` (the former
  #     chtypes-infra repository, folded into the private one on 2026-09-10).
  #     Negative control: "ci/" is common enough as a bare substring that a
  #     word simply ending in it must NOT fire — see the header note above. ---
  printf 'the resolver lives at ci/resolve-version.py in that tree\n' > "$tmp/planted-ci-path.md"
  printf 'infra/terraform holds the module for that account\n' > "$tmp/planted-infra-path.md"
  printf 'built with github.com/golangci/misspell, same as everywhere else\n' > "$tmp/legal-golangci-word.md"

  # --- issue #224: tests/fixtures/fetch/ used to be exempt from every rule in
  #     this file outright, which is exactly how the leaks behind this issue
  #     went unseen. A leak planted THERE must now be caught like anywhere
  #     else — this is the actual regression test for the exemption's removal. ---
  mkdir -p "$tmp/tests/fixtures/fetch"
  printf 'generated by chtypes-core, never edit by hand\n' > "$tmp/tests/fixtures/fetch/README.md"

  # --- legal: describing the split in words, an in-repo path, and the
  #     generic placeholder path spellings this repository already ships ---
  printf 'the other half is the core repository, under its own license\n' > "$tmp/legal.md"
  printf "mirrors the arbiter's \`_same_value\`, per docs/reference/bindings.md\n" > "$tmp/legal-arbiter-word.md"
  printf "also how the acceptance rig's ground truth is captured\n" > "$tmp/legal-acceptance-word.md"
  printf 'see docs/reference/artifact.md for the loader contract\n' > "$tmp/legal-inrepo-path.md"
  printf 'chtypes: no artifact found. Looked in /Users/me/.cache/chtypes/artifacts/darwin-arm64\n' > "$tmp/legal-path-placeholder.md"
  printf 'PathBuf::from("/home/u/.cache/chtypes/artifacts/linux-arm64")\n' > "$tmp/legal-home-placeholder.md"
  printf 'CLAUDE.md and README.md explain the split; so does NOTICE\n' > "$tmp/legal-allcaps-filenames.md"

  git -C "$tmp" add -A
  out="$(scan "$tmp" 2>&1)" && { echo "SELFTEST FAILED: planted violations were not caught" >&2; exit 1; }

  for want in planted-1.md planted-2.md planted-case-1.md planted-case-2.md \
              planted-csrc.md planted-arbiter.md planted-acceptance.md \
              planted-proposals.md planted-note.md planted-path.md \
              planted-home-eric.md \
              planted-wherefilter.md planted-conformance.md planted-fuzz.md \
              planted-harness.md planted-perf.md planted-tsan.md planted-sdk.md \
              planted-libtools.md planted-libharness.md planted-distdocker.md \
              planted-distintegration.md planted-distlinuxverify.md \
              planted-docsmeasurements.md planted-housing.md \
              planted-ci-path.md planted-infra-path.md \
              tests/fixtures/fetch/README.md; do
    printf '%s\n' "$out" | grep -q "$want" || { echo "SELFTEST FAILED: rule did not fire on $want" >&2; exit 1; }
  done

  for clean in legal.md legal-arbiter-word.md legal-acceptance-word.md \
               legal-inrepo-path.md legal-path-placeholder.md \
               legal-home-placeholder.md legal-allcaps-filenames.md \
               legal-runner-path.md \
               legal-wherefilter-word.md legal-conformance-word.md legal-fuzz-word.md \
               legal-harness-word.md legal-perf-word.md legal-tsan-word.md legal-sdk-word.md \
               legal-libtools-word.md legal-libharness-word.md legal-distdocker-word.md \
               legal-distintegration-word.md legal-distlinuxverify-word.md \
               legal-docsmeasurements-word.md legal-housing-word.md legal-golangci-word.md; do
    printf '%s\n' "$out" | grep -q "$clean" && { echo "SELFTEST FAILED: a legal prose mention was flagged ($clean)" >&2; exit 1; }
  done

  echo "lint-public: selftest ok — every rule fires (case-insensitively), legitimate prose stays legal"
  exit 0
fi

if scan "$HERE"; then
  echo "lint-public: ok — no pointers into the private repository, its private notes, or a local filesystem"
else
  exit 1
fi
