// GENERATED by scripts/abi-v1/gen.py --major 2 from spec/abi-v2/abi.json (CHS_ABI_FINGERPRINT sha256:d60a681ea0e249ab9e2c83b50640ad9cef040261ddf61805106c93e2c68774e4) — DO NOT EDIT

package ocifetch

// DevABIFingerprint is CHS_ABI_FINGERPRINT of ABI v2, the generation this
// module speaks: the same value as the ABI layer's ChsAbiFingerprint. The dev
// channel names its alias tags with it, as 64 lowercase hex characters
// without the sha256: prefix (docs/guides/fetch-v1.md section 3).
const DevABIFingerprint = "sha256:d60a681ea0e249ab9e2c83b50640ad9cef040261ddf61805106c93e2c68774e4"
