// GENERATED by scripts/abi-v1/gen.py --major 2 from spec/abi-v2/abi.json (CHS_ABI_FINGERPRINT sha256:4129dccc3f4e698dedb0e99cae413f5240085f633c5a1244e2c55bf7a7bb6c3a) — DO NOT EDIT

package ocifetch

// DevABIFingerprint is CHS_ABI_FINGERPRINT of ABI v2, the generation this
// module speaks: the same value as the ABI layer's ChsAbiFingerprint. The dev
// channel names its alias tags with it, as 64 lowercase hex characters
// without the sha256: prefix (docs/guides/fetch-v1.md section 3).
const DevABIFingerprint = "sha256:4129dccc3f4e698dedb0e99cae413f5240085f633c5a1244e2c55bf7a7bb6c3a"
