// GENERATED by scripts/abi-v1/gen.py --major 2 from spec/abi-v2/abi.json (CHS_ABI_FINGERPRINT sha256:d87e91be2bbe75b985c38224268c2f7dc5d8236dab0a4b4d61357c6dfdc1a232) — DO NOT EDIT

package ocifetch

// DevABIFingerprint is CHS_ABI_FINGERPRINT of ABI v2, the generation this
// module speaks: the same value as the ABI layer's ChsAbiFingerprint. The dev
// channel names its alias tags with it, as 64 lowercase hex characters
// without the sha256: prefix (docs/guides/fetch-v1.md section 3).
const DevABIFingerprint = "sha256:d87e91be2bbe75b985c38224268c2f7dc5d8236dab0a4b4d61357c6dfdc1a232"
